### ISSUE TITLE
Display warning in the web interface when downloading the vulnerability sources fails

### ISSUE THREAD

**Issue by MelvinKool** [DependencyTrack/dependency-track#100]
When no connection could be made to the vulnerability sources, the dependency-track.log displays an error.
Would it be nice to display an error in the web interface, so a user knows the statistics may not be up to date?

**Comment by stevespringett** [comment]
Agreed. I created #102 to track the creation of a general purpose notification system. Downloading sources from the NVD/NSP, etc would be one of the types of notifications I envision.

**Comment by stevespringett** [comment]
Closing as this functionality is complete. Web notification will likely be part of #213, but as of now, you can get email, slack, and teams notifications for when this type of event occurs.
