### ISSUE TITLE
Add health-check urls

### ISSUE THREAD

**Issue by davidkarlsen** [DependencyTrack/dependency-track#1001]
### Current Behavior:
No [documented] endpoints for [health checks](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)

### Proposed Behavior:
add health-probes which can be used to monitor the app and it's state.

**Comment by mvanini** [comment]
For liveness and startup probes we are actually using `/api/version`

For readiness it can be similar to #1002

**Comment by davidkarlsen** [comment]
Will that url respond even if DT has trouble connecting to the DB?

**Comment by stevespringett** [comment]
Most health checks will need to be implemented in https://github.com/stevespringett/Alpine/issues/22

**Comment by bodaduk** [comment]
> Will that url respond even if DT has trouble connecting to the DB?

This is the issue I have, `/api/version` still responds despite many logged db connection and other exceptions. This means health checks still pass and self healing/recovery doesn't occur.

**Comment by nscuro** [comment]
I raised a PR for this in Alpine: https://github.com/stevespringett/Alpine/pull/480

This will support all the various `/health`, `/health/live`, `/health/ready`, and `/health/started` endpoints.
The PR includes readiness check for database connections, but nothing else for now.

We'll need to work out other areas of the system that we can add checks for, but at least a foundation is laid.
