### ISSUE TITLE
Allow to use claims in access token or id token for openid user/group mappings

### ISSUE THREAD

**Issue by yohanb** [DependencyTrack/dependency-track#1008]
### Current Behavior:
From what I understand, dependency-track uses the standard `userinfo` endpoint to fetch the user's name and groups.  This is limiting when using certain providers, for example [Microsoft Identity](https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo).

### Proposed Behavior:
Allow to use claims returned either in the access token or id token since these are also openid standards.  
For example:
```
ALPINE_OIDC_USERNAME_CLAIM_SOURCE=userinfo/access_token/id_token
ALPINE_OIDC_TEAMS_CLAIM_SOURCE=userinfo/access_token/id_token
```
This would also solved the issue #979 .
Thanks!

**Comment by nscuro** [comment]
We can't reliably use the access token since it's not guaranteed to be a JWT, or even parseable at all. Considering ID token *and* `/userinfo` when looking for claims sounds OK though. 

If we submit both ID token and access token to the API server, we can *always* validate and decode the ID token first. If it's valid, and we find all the claims we're looking for in there, we don't have to bother requesting `/userinfo`. A valid ID token is already enough as proof of authentication. If we're missing claims, we can then request `/userinfo` with the access token. Meaning we don't need the proposed properties that instruct DT where to look for claims. 

I think I'll give this a go. Will probably introduce the [Nimbus OIDC SDK](https://connect2id.com/products/nimbus-oauth-openid-connect-sdk) as we'll now have to deal with retrieving and selecting the correct signing key from the IdP.

**Comment by yohanb** [comment]
@nscuro awesome!  Thanks for your implication.  Too bad I'm not familiar with Java or else I would have happily helped!

**Comment by nscuro** [comment]
Got it working locally with my Keycloak setup. As explained above, the ID token takes precedence over `/userinfo`, but if both of them are "incomplete", we'll merge them. Will have to do a bit more testing, but overall it seems fairly simple.

**Comment by nscuro** [comment]
PRs are ready for review. Once these are merged, it'd be very helpful if someone using AzureAD or Microsoft Identity could verify that their issue has indeed been resolved using a DT `SNAPSHOT` version.

**Comment by davidkarlsen** [comment]
@nscuro do you have any image builds of snapshots?

**Comment by nscuro** [comment]
@davidkarlsen Sadly not right now. This will end up in `dependencytrack/apiserver:snapshot` and `dependencytrack/frontend:snapshot` once the PRs are merged.

**Comment by davidkarlsen** [comment]
Maybe image builds could be added - that can help user-testing pre-releases.
GitHub offers this out of the box with ghcr.

**Comment by yohanb** [comment]
@nscuro same here, I'll be happy to test once images are available.

**Comment by nscuro** [comment]
Thanks @yohanb, only the [frontend PR](https://github.com/DependencyTrack/frontend/pull/70) is left to be merged, then this'll be ready for testing using the `snapshot` images. :)

**Comment by yohanb** [comment]
@nscuro seems that the latest `snapshot` image for the frontend doesn't contain your latest changes; at least, I cleary see the `id_token` isn't posted to the api server.
Version in the app footer is `v4.3.0-SNAPSHOT`.
But when I have a look at the source code in my browser, the `login.vue` file still has the following content:
![image](https://user-images.githubusercontent.com/812993/118584470-ff229080-b764-11eb-8dc2-ba7c2bf251b4.png)
Made sure my cache was cleared and everything.

**Comment by stevespringett** [comment]
@yohanb Try pulling the frontend snapshot image again. It doesn't look like the push to Docker Hub was successful previously, but it's working now.

**Comment by yohanb** [comment]
Alright so I got everything up to the latest version 🎉
ID token is sent to the backend api.  @nscuro one thing I can't figure out now is how to use my `groups` claim to setup mapped teams.  Not sure if it's a config problem or a problem with the new claim.
Using DEBUG logs, I was able to see that my ID token contains the groups (abridged for clarity): 
```
DEBUG [OidcIdTokenAuthenticator
] ID token claims: {
    "groups": [
        "11111111-1111-1111-1111-111111111111",
        ...
    ],
    "preferred_username": "yohan.belval@gsoft.com",
    "name": "Yohan Belval",
    "email": "yohan.belval@gsoft.com"
}

DEBUG [OidcAuthenticationService
] ID token profile: OidcProfile{username='Yohan Belval', groups=[
    11111111-1111-1111-1111-111111111111
    ], email='yohan.belval@gsoft.com'
}
```
So I expect that when I setup the following:
![image](https://user-images.githubusercontent.com/812993/118656797-dd52f900-b7b8-11eb-906b-100a157ff202.png)

I would get mapped to the Administrators Team but that isn't happening.
Oh and I also have these values configured:
```
            - name: ALPINE_OIDC_USER_PROVISIONING
              value: "true"
            - name: ALPINE_OIDC_TEAMS_CLAIM
              value: "groups"
            - name: ALPINE_OIDC_TEAMS_SYNCHRONIZATION
              value: "true"
            - name: ALPINE_OIDC_CLIENT_ID
              value: "MY_HIDDEN_CLIENT_ID"
```
Any help would be appreciated! :)

**Comment by nscuro** [comment]
@yohanb Hmmm... your config looks fine. Did you configure the mapping *after* you logged in via OIDC? Mapping happens ad-hoc when you authenticate, so you'd have to log out of DT and re-authenticate for the mapping to apply.

In any case, you could search the logs for any of [these](https://github.com/stevespringett/Alpine/blob/master/alpine/src/main/java/alpine/persistence/AlpineQueryManager.java#L252-L272) debug logs, that should tell you what's happening.

**Comment by yohanb** [comment]
@nscuro well I found my error...!
typo in `ALPINE_OIDC_TEAMS_SYNCHRONIZATION` no 'S' on TEAM~~S~~
Tested and it's now working!  🎉

**Comment by nscuro** [comment]
@yohanb Great, thank you very much for verifying 😁👌🏻
