### ISSUE TITLE
Policy violations are not showing

### ISSUE THREAD

**Issue by witchdr** [DependencyTrack/dependency-track#1021]
I'm new to Dependency Track so may have misconfigured. I'm using the Docker image of version 4.2.1.

I have imported the BOM for a project. Dependency Track shows me it has 1465 components. Of those, there are 6 high, 4 medium and 1 low severity vulnerabilities.

I have created two policies. One is called "High Severity Policy" and has a Violation State of "Fail", It has two conditions. The first condition is: Severity is High and the other, Severity is Critical.

The second policy is called "Medium Severity Policy" and has a Violation State of "Warn". It has a single condition, Severity is Medium.

From these policies, I'm expecting to see two policy violations on the Dashboard but it shows none. Have I missed something?

![Dependency Track Policies](https://user-images.githubusercontent.com/6839556/116329597-9e3a1500-a7c3-11eb-9c52-ba4ac9c4ba12.png)

![Dependency Track Dashboard](https://user-images.githubusercontent.com/6839556/116329604-a2663280-a7c3-11eb-8c54-c4bf5f6a9976.png)

![Dependency Track Version](https://user-images.githubusercontent.com/6839556/116329956-5962ae00-a7c4-11eb-97f7-ae9a286499fd.png)

**Comment by stevespringett** [comment]
Policy evaluation happens when BOMs are imported, components are changed, or every 24 hours.

If you created the policy after the BOM was imported and did not reimport the BOM, that might explain why you're not seeing violations.

**Comment by witchdr** [comment]
I re-imported the BOM and now they're showing. Thanks.
