### ISSUE TITLE
[Project] Unable to add PURL attribute containing "@" to project

### ISSUE THREAD

**Issue by mattwongsd** [DependencyTrack/dependency-track#1036]
### Current Behavior:
DT Version : 4.2.2

Upload PURL attribute to a project using the web UI.
Attribute used: `pkg:npm/%40angular/animation@12.3.1`
Server will respond with a status code of 400 and response body: `[{"message":"The Package URL (purl) must be a valid URI and conform to https://github.com/package-url/purl-spec","messageTemplate":"The Package URL (purl) must be a valid URI and conform to https://github.com/package-url/purl-spec","path":"purl","invalidValue":"pkg:npm/%40angular/animation@12.3.1"}]`

### Steps to Reproduce:
See above

### Expected Behavior:
I think the problematic character would be the @ character.
This would be perfectly valid input due to how npm does the scoping of packages. This example is also used in the https://github.com/package-url/purl-spec documentation.

### Environment:
  
  - Dependency-Track Version: 4.2.2
  - Distribution: [ Docker ]
  - BOM Format & Version: NIL
  - Database Server: [ H2 ]
  - Browser: Chrome

**Comment by stevespringett** [comment]
Thanks for reporting. Issue was replicated and corrected. Fix will be available in v4.3
