### ISSUE TITLE
Add 'View Details' to small widgets

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#104]
The 'View Details' bar on the small widgets is being temporarily hidden in preparation for v3.0.0 release #94. This enhancement is to bring that functionality back with working metrics behind the details.

**Comment by msymons** [comment]
This is frontend issue from before Frontend existed as a separate project.  

"View details" are working properly in current version 4.7.0 in many places.  eg project, component, vulnerability screens
