### ISSUE TITLE
Permissions per project

### ISSUE THREAD

**Issue by brvheem** [DependencyTrack/dependency-track#1047]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
Currently it is not possible to set permissions per project, e.g. by setting teams (w/ API keys) to a project

### Proposed Behavior:
Add a possibility for a project to add a team (w/ its API keys) or users to it, so that only that team/user has access to the information (scan results etc.) of that project

**Comment by nscuro** [comment]
Duplicate of #140.
