### ISSUE TITLE
get projoct info api support paging

### ISSUE THREAD

**Issue by nibiwodong** [DependencyTrack/dependency-track#1052]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
swagger api do not support pagesize and pagenum params，so users can only get 100 projects infomation, but not all projects infomation.
`curl -X GET "http://localhost:8080/api/v1/project" -H  "accept: application/json" -H  "X-Api-Key: xxxxxx"`

And also, project numbers is in response header `X-Total-Count`,  but not response body, so swagger python api can not get it.
### Proposed Behavior:
Support pagesize and pagenumber params.
Move X-Total-Count response header to response body.

**Comment by stevespringett** [comment]
We will be migrating to OpenAPI 3 and moving away from autogenerated swagger docs to manually created ones. That will resolve this issue.

Related to #840

**Comment by nscuro** [comment]
Fixed in 4.11 via #3625.
