### ISSUE TITLE
Containerization image improperly resolves DNS

### ISSUE THREAD

**Issue by muteid10t** [DependencyTrack/dependency-track#1054]
### Current Behavior:
Busybox used in container image improperly resolves all dns to wildcard DNS entry in local dns when using wget.
![image](https://user-images.githubusercontent.com/9994583/119671607-e6bb1180-be07-11eb-9c1f-b142356b69f5.png)

This is a common problem with busybox

### Steps to Reproduce:
Create a wildcard DNS entry for a domain in local DNS, *.example.corp
Launch containered Dependency-Track
Run wget https://google.com
See result from above image that DNS resolves to a wildcard entry in local DNS

### Expected Behavior:
DNS resolved properly

### Environment:
  
  - Dependency-Track Version: 4.2.2
  - Distribution: Container (on kubernetes using community helm chart)
  - Database Server: PostgreSQL 
  - Browser: NA

### Additional Details:
https://unix.stackexchange.com/questions/124283/busybox-ping-ip-works-but-hostname-nslookup-fails-with-bad-address

**Comment by stevespringett** [comment]
Perhaps this is an issue with K8s or the Helm chart?

The container itself resolves DNS just fine. Screenshot is a standalone Docker image of v4.2.2 deployed using Swarm - The DT project only supports Docker Compose and Docker Swarm. The community has Helm charts that are not supported by this project.

<img width="682" alt="Screen Shot 2021-05-26 at 12 22 56 PM" src="https://user-images.githubusercontent.com/3878933/119704503-5982b780-be1d-11eb-8b16-813aafe2f3ed.png">

**Comment by davidkarlsen** [comment]
Is the image alpine-based? It is known to have issues with resolving: https://github.com/kubernetes/kubernetes/issues/64924

**Comment by stevespringett** [comment]
Yes. The frontend is built with `nginxinc/nginx-unprivileged:stable-alpine` and the API Server is built with `adoptopenjdk/openjdk11:alpine-jre`. Both are alpine images.

**Comment by muteid10t** [comment]
I found the issues I was having. 
It ended up being a DNS config issue on the k8s hosts. We have multiple internal DNS zones and having them all configured as search suffixes on the k8s hosts resulted in name resolution issues even at the host level. Removing the unneeded search suffixes from the resolution scope eliminated the problem. Still haven't found out why only these hosts had the problem but I suspect it is related to coredns in k8s.

**Comment by davidkarlsen** [comment]
> I found the issues I was having.
> It ended up being a DNS config issue on the k8s hosts. We have multiple internal DNS zones and having them all configured as search suffixes on the k8s hosts resulted in name resolution issues even at the host level. Removing the unneeded search suffixes from the resolution scope eliminated the problem. Still haven't found out why only these hosts had the problem but I suspect it is related to coredns in k8s.

Exactly. It is a alpine /musl issue. I recommend avoiding alpine for base images for this reason
