### ISSUE TITLE
Add create and last used timestamps for API Keys to the /team API response

### ISSUE THREAD

**Issue by 37b** [DependencyTrack/dependency-track#1068]
### Current Behavior:
The `/team` API returns a list of API Keys assigned to a team, but does not provide a timestamp for when each key was created or last accessed. This information is needed to enforce API Key rotation schemas.

```
...
    "apiKeys": [
      {
        "key": "string"
      }
    ]
```

### Proposed Behavior:
```
...
    "apiKeys": [
      {
        "key": "string",
        "createdAt": "2021-06-09T18:18:21.710Z",
        "lastUsed": "2021-06-09T18:18:21.710Z"
      }
    ]
```

**Comment by stevespringett** [comment]
This enhancement would likely need to be made to `alpine.model.ApiKey`

**Comment by 37b** [comment]
@stevespringett should I make an enhancement request on that project?

**Comment by valentijnscholten** [comment]
I suggest to also add a `name` or `description` to help recognize / manage key usage.

**Comment by raboof** [comment]
I see adding the create and last used timestamps has now been reported to the Alpine repo at https://github.com/stevespringett/Alpine/issues/362

I added https://github.com/stevespringett/Alpine/issues/536 for adding a `name`/`description`/`comment` field.

**Comment by nscuro** [comment]
Do we have anyone with experience in implementing something like this?

I don't believe updating the `lastUsed` timestamp for each request is feasible, that'd be *way* too many database transactions. Also, keys can be used by multiple requests concurrently so there's some contention to be expected.

One aspect I've seen being discussed on my surface-level Google search, is what the desired resolution of `lastUsed` is. Are we looking at seconds, minutes, hours? Would "last used today" / "last used 4 days ago" be sufficient?

@37b What's the MVP to fulfill your requirement?

**Comment by 37b** [comment]
> Do we have anyone with experience in implementing something like this?
> 
> 
> 
> I don't believe updating the `lastUsed` timestamp for each request is feasible, that'd be *way* too many database transactions. Also, keys can be used by multiple requests concurrently so there's some contention to be expected.
> 
> 
> 
> One aspect I've seen being discussed on my surface-level Google search, is what the desired resolution of `lastUsed` is. Are we looking at seconds, minutes, hours? Would "last used today" / "last used 4 days ago" be sufficient?
> 
> 
> 
> @37b What's the MVP to fulfill your requirement?

Last used is more of a nice to have to cleanup unused keys as part of general housekeeping. I really need to rotate the keys on a schedule and I can do that based on create time.

**Comment by nscuro** [comment]
Found a practical solution to track `lastUsed` timestamps. Raised a PR here: https://github.com/stevespringett/Alpine/pull/537
