### ISSUE TITLE
How to invoke project key in window server 2019

### ISSUE THREAD

**Issue by rinkucool007** [DependencyTrack/dependency-track#1069]
Hi,
Please let me know how to invoke project key using powershell. As curl is working in UNIX not in window server 2019.

Here is what I am trying :
Invoke-RestMethod -Method Get -Uri "http://dependency-track.com/api/v1/project/lookup?name=Project01&version=1.0.0" -ContentType 'application/json' -Headers @{'X-Api-Key=zzzzzzzzzzzzz'} -OutFile "out.json"

**Comment by stevespringett** [comment]
No idea. You might want to ask in the Slack channel. There are likely a few Windows users there.

**Comment by stevespringett** [comment]
https://dependencytrack.org/slack/invite

**Comment by rinkucool007** [comment]
I solved this :

$URI = "http://dependency.com/api/v1/project/lookup?name=xxxxxxx&version=1.0.0"
$APIKey = "xxxxxxxxxxxxxxxxxxxxxxxxxx"
$response = Invoke-WebRequest -Uri $URI -Method GET -Header @{ "X-Api-Key" = $APIKey } -ContentType 'application/json'
$response.Content > out.json
$responseObject = ConvertFrom-Json –InputObject $response.Content
$responseObject.uuid > uuid
$deptrname = Get-Content .\uuid -Raw 
echo http://dependency.com/projects/$deptrname
