### ISSUE TITLE
Not being able to see the API

### ISSUE THREAD

**Issue by varunsudhakaran** [DependencyTrack/dependency-track#1072]
All questions should be directed to the Dependency-Track Slack channel or to GitHub discussions
Questions submitted through GitHub issues will be closed.

Slack channel
  - https://dependencytrack.org/slack

Slack invite
  - https://dependencytrack.org/slack/invite
  
GitHub discussions
  - https://github.com/DependencyTrack/dependency-track/discussions

Groups.io (mailing list)
  - https://dependencytrack.org/discussion

Providing as much detail as possible, what is your question?
![Screen Shot 2021-06-11 at 4 59 31 PM](https://user-images.githubusercontent.com/43083445/121753500-1e001280-cad8-11eb-93cc-12557f4c2289.png)

Currently I am trying to integrate an SBOM to the Dependency Tracker in order to see some vulnerability scannings. So, I am trying to see the API of the application, and I added this Google Chrome extension by putting local host with the port and the rest of the link. If you have any guidance on how to load these SBOMS over to the app or even how to look at these API's versions, component, bom, etc because I am dead lost on how to get through to this.

**Comment by stevespringett** [comment]
Refer to https://docs.dependencytrack.org/usage/cicd/ for examples on how to use curl. Or use one of the many community integrations which make it easier https://docs.dependencytrack.org/integrations/community-integrations/

**Comment by varunsudhakaran** [comment]
We ,as a team, are refraining from using Jenkins to use as a plug-in, so we are trying to use the curl method instead. We tried the way with the appropriate path name, and API key, and we are still running into issues.

**Comment by stevespringett** [comment]
Refer to the updated documentation, which will be published with v4.3

https://github.com/DependencyTrack/dependency-track/blob/master/docs/_docs/usage/cicd.md
