### ISSUE TITLE
Can't get SBOM to integrate to this application for Dependency Tracker 

### ISSUE THREAD

**Issue by varunsudhakaran** [DependencyTrack/dependency-track#1073]
All questions should be directed to the Dependency-Track Slack channel or to GitHub discussions
Questions submitted through GitHub issues will be closed.

Slack channel
  - https://dependencytrack.org/slack

Slack invite
  - https://dependencytrack.org/slack/invite
  
GitHub discussions
  - https://github.com/DependencyTrack/dependency-track/discussions

Groups.io (mailing list)
  - https://dependencytrack.org/discussion

Providing as much detail as possible, what is your question?

![Screen Shot 2021-06-11 at 5 17 11 PM](https://user-images.githubusercontent.com/43083445/121753887-e6de3100-cad8-11eb-99e0-355701dbaebf.png)

```

curl --location --request POST 'http://0.0.0.0:8080/api/v1/bom' \
--header 'Content-Type: multipart/form-data; charset=utf-8; boundary=__X_CURL_BOUNDARY__' \
--header 'X-API-Key: xxxxxx' \
--form 'project="afecdf5b-508a-43fa-bb5f-ef85fbc833e3"' \
--form 'bom=@"/Users/xxxx/Downloads/bom_new.xml"'


405 Not Allowed
nginx/1.18.0


[11/Jun/2021:21:56:35 +0000] "POST /api/v1/bom HTTP/1.1" 405 157 "-" "PostmanRuntime/7.28.0" "-"
```

I tried to integrate this SBOM into the Dependency Tracker application, and there was no way that I could get the app contain these SBOM with the project. I couldn't get any credentials to pop up, and I get a 405 Not allowed error when I submit this curl command. Please let me know if anyone got this issue.

**Comment by stevespringett** [comment]
Try not including `charset=utf-8; boundary=__X_CURL_BOUNDARY__'`

```bash
curl --location --request POST 'http://0.0.0.0:8080/api/v1/bom' \
--header 'Content-Type: multipart/form-data;' \
--header 'X-API-Key: xxxxxx' \
--form 'project="afecdf5b-508a-43fa-bb5f-ef85fbc833e3"' \
--form 'bom=@"/Users/xxxx/Downloads/bom_new.xml"'
```

**Comment by varunsudhakaran** [comment]
I tried doing this with the appropriate file path, and the API key, and it is still giving me issues. The error was 405 not allowed again.
