### ISSUE TITLE
Migrate Docker image from Alpine to Debian Slim

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#1090]
Alpine images can cause some incompatibility issues due to its use on musl instead of glibc.

This ticket is to track the migration of the Dockerfile from using an Alpine base image to one based on Debian slim.

Related to #1054

Frontend: https://github.com/DependencyTrack/frontend/issues/78

**Comment by sephiroth-j** [comment]
@stevespringett, you might want to take a look at the "distroless" images such as "gcr.io/distroless/java-debian10" from https://github.com/GoogleContainerTools/distroless
