### ISSUE TITLE
Portfolio Access Control shows no project to users

### ISSUE THREAD

**Issue by becelot** [DependencyTrack/dependency-track#1132]
If a user has multiple teams, and portfolio access control is enabled, users do not see any projects in the projects list.

### Current Behavior:

Logging in with a user with Portfolio Access Management enabled, the user sees no projects, although the user belongs to teams that have access to some projects.

### Steps to Reproduce:

* Create two teams 'standard-user' and 'test-portfolio-view'
* Assign VIEW_PORTFOLIO to 'standard-user' team
* Create a new project 'test'
* Enable Portfolio Access Management, and assign project 'test' to 'test-portfolio-view'
* Create a new user that belongs to team 'standard-user' and 'test-portfolio-view'

### Expected Behavior:

The user can view the 'test' project.

### Environment:
  
  - Dependency-Track Version: 4.3.1
  - Distribution: Docker
  - BOM Format & Version: unrelated
  - Database Server: PostgreSQL
  - Browser: Chrome

### Additional Details:

Removing the 'standard-user' team from the user, and assigning the VIEW_PORTFOLIO permission directly to the 'test-portfolio-view' team allows the user to see the 'test' project. This only happens if the user has more than one team.

**Comment by stevespringett** [comment]
Thanks for identifying the issue and for the PR. A similar logic flaw for components has also been resolved.

v4.3.2 has been released which includes both fixes.

Thanks again.
