### ISSUE TITLE
Updating database and checking projects

### ISSUE THREAD

**Issue by savujevi** [DependencyTrack/dependency-track#1138]
All questions should be directed to the Dependency-Track Slack channel or to GitHub discussions
Questions submitted through GitHub issues will be closed.

Slack channel
  - https://dependencytrack.org/slack

Slack invite
  - https://dependencytrack.org/slack/invite
  
GitHub discussions
  - https://github.com/DependencyTrack/dependency-track/discussions

Groups.io (mailing list)
  - https://dependencytrack.org/discussion

Providing as much detail as possible, what is your question?

Hello Developers,

could you please tell me in which frequency the database is updated in the api server and in which frequency the project will be checked for vulnerabilities if the bom of a project does not change for a while.

Thank you for your help.

Best regards
    Sascha Vujevic

**Comment by stevespringett** [comment]
Refer to:
https://docs.dependencytrack.org/datasources/nvd/
https://docs.dependencytrack.org/datasources/npm/
https://docs.dependencytrack.org/datasources/ossindex/
https://docs.dependencytrack.org/datasources/vulndb/
https://docs.dependencytrack.org/analysis-types/known-vulnerabilities/
https://docs.dependencytrack.org/usage/cicd/

**Comment by savujevi** [comment]
Thank you for the hints.
