### ISSUE TITLE
Component Vulnerability Screen "Undefined" Affected Project

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#1154]
### Current Behavior:

Dependency-Track has a page dedicated to each individual vulnerability.  The page has two tabs...  "Overview" and "Affected Projects".  On at least two occasions I have seen the project listing display a project named "undefined" that links to a project called "undefined" (a name, not a UUID),  resulting in an HTTP 404 if clicked.

![image](https://user-images.githubusercontent.com/4938718/130118256-a96c8dbe-bd11-4d4c-a4f1-3339183bdfc5.png)

For the instance represented by this screenshot,  my new DT 4.3.1 server had been up and running for a couple of weeks with 10 projects and I had just reconfigured my Jenkins servers with new URL and Token,  causing 23 new projects to be created in DT over the space of 3.5 hours.

I kept watch on the problem listing for a couple of hours and it did not change, but now (another 4 hours later),  the "undefined" project has gone and all 6 listed projects are valid.  ie, the system **has** corrected itself.

### Steps to Reproduce:
See above.  I have only noticed this twice so do not know if there is a surefire way to reproduce.

### Expected Behavior:
Project should not list as "undefined".  ie,  there should be less lag between creation of the project (detection of the vulnerability) and the updating of the project listing for the vulnerability.

Failing that, maybe the "undefined" could link to a landing page that would explain that metrics are not updated straight away and to try again later?  ie,  avoid HTTP 404.

### Environment:
  
  - Dependency-Track Version:  4.3.1
  - Distribution: [ Docker ]
  - BOM Format & Version:  CycloneDX 1.2  (cyclonedx-maven-plugin 2.5.1)
  - Database Server: [ PostgreSQL ]
  - Browser:  Firefox 91.0

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by nscuro** [comment]
I bet this is because the `project` object wasn't correctly or completely loaded by DataNucleus before being serialized. It probably "recovered" because something else forced DN to load these fields (browsing through *Projects* maybe). DN does have an internal cache, which now contains the complete object. 

@stevespringett Can this be caused by `Project`'s `uuid`, `name` and `version` not being in the `defaultFetchGroup`? `Project` properties [are never accessed](https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java#L423-L444) in this execution path, so nothing's forcing DN to lazy-load them.

**Comment by stevespringett** [comment]
What does the DT logs say when you receive `undefined` in this list?

**Comment by msymons** [comment]
> 
> 
> What does the DT logs say when you receive `undefined` in this list?

Unfortunately,  I have no idea at all.  With the upgrade to DT 4.3.1, my server is now using Kubernetes delivered by [Argo CD](https://argo-cd.readthedocs.io/en/stable/).   An older version of Argo CD which has an app log viewer that totally sucks.  However,  the log viewer is totally re-written in later releases and so we are now in the process of updating.  But that does not help me research the "undefined" problem until such time as it happens again.

But even if it does happen again, I might miss it.  It would necessitate inspecting multiple individual vulnerabilities, and doing so at exactly the right time (assuming the defect is always transient).
