### ISSUE TITLE
response X-Total-Count always *，Cause paging failure（Showing 1 to null of null rows）

### ISSUE THREAD

**Issue by xxywyc** [DependencyTrack/dependency-track#1161]
### Current Behavior:
when update the dt to 4.3.2、4.3.3
the dt api response X-Total-Count value always set to *
Cause paging failure（Showing 1 to null of null rows）

### Environment:
  - Dependency-Track Version: 4.3.2、4.3.3
  - Distribution: Docker
  - BOM Format & Version: CycloneDX
  - Database Server: PostgreSQL
  - Browser: chrome、firefox

**Comment by nscuro** [comment]
Hi @xxywyc, is this for a specific API resource / UI view or does if affect everything that's paged? 

I'm running DT v4.3.3 on Postgres and I don't have this issue anywhere.

**Comment by xxywyc** [comment]
> Hi @xxywyc, is this for a specific API resource / UI view or does if affect everything that's paged?
> 
> I'm running DT v4.3.3 on Postgres and I don't have this issue anywhere.

hi，In my environment, all the apis and ui return the same way

![image](https://user-images.githubusercontent.com/14202004/130545656-792af923-6a39-4889-b28e-9106a425a195.png)
![image](https://user-images.githubusercontent.com/14202004/130546920-c41f75c9-ad33-4a0c-a089-fb8334307388.png)

**Comment by stevespringett** [comment]
@xxywyc I don't think DT is capable of sending that response. If you refer to https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/resources/v1/ProjectResource.java#L84 , you'll notice that the resource will always return a value (getTotal()).

The PaginatedResult class defines getTotal() as a long (primitive), which means that the value can never be null. At worst the total will be 0.
https://github.com/stevespringett/Alpine/blob/master/alpine/src/main/java/alpine/persistence/PaginatedResult.java#L46

Is there a proxy between your browser and the DT server that perhaps is rewriting headers?

**Comment by xxywyc** [comment]
> @xxywyc I don't think DT is capable of sending that response. If you refer to https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/resources/v1/ProjectResource.java#L84 , you'll notice that the resource will always return a value (getTotal()).
> 
> The PaginatedResult class defines getTotal() as a long (primitive), which means that the value can never be null. At worst the total will be 0.
> https://github.com/stevespringett/Alpine/blob/master/alpine/src/main/java/alpine/persistence/PaginatedResult.java#L46
> 
> Is there a proxy between your browser and the DT server that perhaps is rewriting headers?

thank you, I think it's probably a front end problem

**Comment by xxywyc** [comment]
when i remove response header Access-Control-Expose-Headers
it's ok.
