### ISSUE TITLE
Error Cloning Audit History when Adding Project Version

### ISSUE THREAD

**Issue by ddurham2** [DependencyTrack/dependency-track#1169]
### Current Behavior:
- When adding a project version, the project is cloned, but the audit history is not cloned
- apiserver log shows:
```
21:00:16.191 INFO [ProjectResource] Project ACME : 21.3.1-nightly is being cloned by ddurham
21:00:16.192 INFO [CloneProjectTask] Cloning project: 2d6d0075-e8ce-4048-ba5f-1abbe77a7d77
21:00:16.582 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: null
	at org.dependencytrack.persistence.ProjectQueryManager.clone(ProjectQueryManager.java:493)
	at org.dependencytrack.persistence.QueryManager.clone(QueryManager.java:350)
	at org.dependencytrack.tasks.CloneProjectTask.inform(CloneProjectTask.java:43)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
It appears to have started the clone, but failed in the process

### Steps to Reproduce:
Though, not quite sure what about my dependencies are causing this error-causing state.  I'm happy to answer any followup questions.
- Added a version and asking it to clone all items (though, I've narrowed it down to "Include components" + "Include Audit History" are the necessary flags)

### Expected Behavior:
- New version to be added with audit history to be cloned too

### Environment:
    - Dependency-Track Version: api-server v4.3.3
  - Distribution: Docker
  - BOM Format & Version: cyclonedx-1.2
  - Database Server: PostgreSQL
  - Browser: Firefox and Chrome

### Additional Details:
Is there a way to enable more debug logging that might reveal more about the cause?
I'd be happy to build from a dev branch if there is more logging you need to add around the problem area.

**Comment by stevespringett** [comment]
I'm unable to reproduce on a small project using v4.4-SNAPSHOT.

**Comment by stevespringett** [comment]
Based on the version of DT you're running, it appears that one of the variables on this line is null:

```java
this.addVulnerability(vuln, clonedComponent, sourceAttribution.getAnalyzerIdentity(), sourceAttribution.getAlternateIdentifier(), sourceAttribution.getReferenceUrl());
```

Do you have any vulnerabilities in this project that does not have an attribution (e.g. internal, oss index, etc)?

**Comment by ddurham2** [comment]
Okay I've tried creating new versions of all our repos, and none are exhibiting this problem any more.  I cannot say for sure if there was / wasn't an empty attribution at the time in the past.

Thank you for looking at this.  If it's possible for you to do that null check, and simply accept null, that seems like a reasonable thing to do, however that might happen.
