### ISSUE TITLE
Component update is broken

### ISSUE THREAD

**Issue by vmvarga** [DependencyTrack/dependency-track#1174]
### Current Behavior:
Currently hashes for some components are stored in uppercase format and it's accepted by UI
![image](https://user-images.githubusercontent.com/38255353/131505274-e2dbd8c1-c1eb-4b23-a30b-618a119f0378.png)

In case you need to update component API call is failing with 400 error
![image](https://user-images.githubusercontent.com/38255353/130919931-c5f8fa50-e5f6-44d5-8c8e-3fcd7ad2b7ea.png)

This happens due to API is not accepting uppercase SHA, after converting to lower component is updated
![image](https://user-images.githubusercontent.com/38255353/130920458-d9cc90db-ec01-4fac-a4f0-a821d4b3bfc5.png)

### Expected Behavior:
Convert hash to lower before processing

**Comment by cdaven** [comment]
I was just about to write a new issue about this.
