### ISSUE TITLE
Fetch project list by classifier

### ISSUE THREAD

**Issue by ifree92** [DependencyTrack/dependency-track#1185]
I would like to have the ability to fetch the project list by a classifier. E.g. I want to fetch the list of my LIBRARY-es or APPLICATION-s. In other words, filter by a classifier.

**Comment by stevespringett** [comment]
@ifree92 support for querying project list by classifier has been implemented. Currently there is not a way to initiate this type of request from the UI. I think there's room for further improvement there. However, the following URL construct will work in Dependency-Track v4.5.

```
http://dtrack.example.com/projects/?classifier=APPLICATION
```

Where classifier is one of:
* APPLICATION
* FRAMEWORK
* LIBRARY
* CONTAINER
* OPERATING_SYSTEM
* DEVICE
* FIRMWARE
* FILE
