### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by ruckc** [DependencyTrack/dependency-track#1213]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
Dependency Track is unable to deploy on arm64 environments

### Proposed Behavior:
Change github workflow to use buildkit to build containers for commonly used architectures (linux/amd64, linux/arm64, darwin/amd64, darwin/arm64).

This enhancement would be beneficial to users/potential developers that use arm64 processors.

**Comment by ruckc** [comment]
with the buildkit github actions its super simple to implement multi-arch containers, so the Temurin migration can be uncoupled

**Comment by stevespringett** [comment]
This was an interesting exercise. I had a personal need to do this as I recently migrated my personal development machine to an Apple M1 Pro. What I found was that no Alpine images that included Java were available on ARM. So I had to make a switch from Alpine to Debian Slim, which I intended to do anyway (#1090), and at the same time, I had to find another OpenJDK distribution. Temurin is not available on Debian Slim and Debian packages are not yet available. So I migrated to Azul OpenJDK 17, which I'm using on my development machine anyway. So lots of changes were involved in getting an image that was supported on x86_64 and arm64.

```
03:27:51.092 INFO [Config] --------------------------------------------------------------------------------
03:27:51.093 INFO [Config] OS Name:      Linux
03:27:51.094 INFO [Config] OS Version:   5.10.47-linuxkit
03:27:51.094 INFO [Config] OS Arch:      aarch64
03:27:51.097 INFO [Config] CPU Cores:    5
03:27:51.100 INFO [Config] Max Memory:   6.2 GB (6,672,089,088.0 bytes)
03:27:51.100 INFO [Config] Java Vendor:  Azul Systems, Inc.
03:27:51.101 INFO [Config] Java Version: 17+35-LTS
03:27:51.102 INFO [Config] Java Home:    /usr/lib/jvm/zulu17-ca-arm64
03:27:51.102 INFO [Config] Java Temp:    /tmp
03:27:51.102 INFO [Config] User:         dtrack
03:27:51.102 INFO [Config] User Home:    /data/
03:27:51.102 INFO [Config] --------------------------------------------------------------------------------
03:27:51.102 INFO [Config] Initializing Configuration
03:27:51.103 INFO [Config] System property alpine.application.properties not specified
03:27:51.103 INFO [Config] Loading application.properties from classpath
03:27:51.106 INFO [Config] --------------------------------------------------------------------------------
03:27:51.106 INFO [Config] Application:  Dependency-Track
03:27:51.106 INFO [Config] Version:      4.4.0-SNAPSHOT
03:27:51.106 INFO [Config] Built-on:     2021-11-25T03:12:37Z
03:27:51.106 INFO [Config] --------------------------------------------------------------------------------
03:27:51.107 INFO [Config] Framework:    Alpine
03:27:51.107 INFO [Config] Version :     1.10.2
03:27:51.107 INFO [Config] Built-on:     2021-08-31T14:25:52Z
03:27:51.107 INFO [Config] --------------------------------------------------------------------------------
```

**Comment by ruckc** [comment]
Not that I have any major issue with Azul... but temurian has the 17-focal. tag, which is debian, not sure if being on a slim makes any difference when there aren't any JRE only 17 images yet.

**Comment by stevespringett** [comment]
I'm currently relying on `zulu17-ca-jre-headless`. IMO, this should be a short-term strategy with the intent of moving to Temurian once they support Slim and have a JRE headless distribution.
