### ISSUE TITLE
Failed to process a new BOM when MetricsUpdateTask is running

### ISSUE THREAD

**Issue by guillomep** [DependencyTrack/dependency-track#1216]
### Current Behavior:
We are using dependency track to check for vulnerabilities in our projects. We are using the jenkins plugin in order to upload BOM to our dependency-track instance.
We notice that the BOM processing failed when the dependency-track is running the MetricsUpdateTask that process all the projects. (we have a timeout of 10min)

### Steps to Reproduce:
Wait for dependency track to run the MetricsUpdateTask.
Upload a BOM using the jenkins plugin.

### Expected Behavior:
The BOM is uploaded and processed correctly in parallel.

### Environment:
  
  - Dependency-Track Version: 4.3.6
  - Distribution: Docker
  - BOM Format & Version: XML CycloneDX v1.3
  - Database Server: PostgreSQL

### Additional Details:

We currently running the frontend and the API separated in a Kubernetes cluster.
The error we get after ten minutes:
```
[DependencyTrack] Publishing artifact to Dependency-Track - https://dependencytrack-api.example.com
[DependencyTrack] The artifact was successfully published. You may now navigate to https://dependencytrack.example.com/projects/ to view the results.
[DependencyTrack] Polling Dependency-Track for BOM processing status
[DependencyTrack] Polling Dependency-Track for results is taking longer than expected - polling limit exceeded
```

There is no error in the dependency-track logs.
The BOM seems to be processed after the MetricsUpdateTask.
Is there some kind of limitations that made impossible to run the tasks in parallel ?
If it the case then the plugin should be aware that the DT is not able to currently process the BOM and wait until the MetricsUpdateTask is completed before starting the timeout.

**Comment by stevespringett** [comment]
Thats correct. You'll need to ensure the database server is also properly tuned as those other threads may be in a wait state, or may be busy processing other tasks (vulnerability analysis, repo analysis, etc).
