### ISSUE TITLE
Remove NpmAuditAnalysisTask - Create GitHubAdvisoryAnalysisTask

### ISSUE THREAD

**Issue by StyleT** [DependencyTrack/dependency-track#1225]
See https://github.blog/2021-10-07-github-advisory-database-now-powers-npm-audit/

### Current Behavior:
```
12:30:52.442 INFO [VulnerabilityAnalysisTask] (244 out of 245) Analyzing 2018 components in project: cf2aa72a-d64e-449e-9f53-10ff24ddd808
12:30:52.482 INFO [NpmAuditAnalysisTask] Starting Node Audit analysis task for 2018 components
12:30:57.730 INFO [NpmAuditAnalysisTask] Processing NPM advisories
12:30:57.735 ERROR [VulnerabilityAnalysisTask] An unexpected error occurred performing a vulnerability analysis task
java.lang.NullPointerException: null
	at org.dependencytrack.persistence.VulnerabilityQueryManager.contains(VulnerabilityQueryManager.java:258)
	at org.dependencytrack.persistence.QueryManager.contains(QueryManager.java:635)
	at org.dependencytrack.util.NotificationUtil.analyzeNotificationCriteria(NotificationUtil.java:56)
	at org.dependencytrack.tasks.scanners.NpmAuditAnalysisTask.processResults(NpmAuditAnalysisTask.java:205)
	at org.dependencytrack.tasks.scanners.NpmAuditAnalysisTask.analyze(NpmAuditAnalysisTask.java:163)
	at org.dependencytrack.tasks.scanners.NpmAuditAnalysisTask.inform(NpmAuditAnalysisTask.java:74)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.performAnalysis(VulnerabilityAnalysisTask.java:166)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.analyzeComponents(VulnerabilityAnalysisTask.java:126)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.inform(VulnerabilityAnalysisTask.java:88)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to Reproduce:
Upload NPM project with vulnerabilities to DTrack

### Expected Behavior:
Should be working as normal

### Environment:
  
  - Dependency-Track Version: latest
  - Distribution: Docker
  - BOM Format & Version: 
  - Database Server: PostgreSQL 

### Additional Details:

Commit wit temp fix: https://github.com/StyleT/dependency-track/commit/205ab0a66d59fa0f8cb799de8923b7489468aaee

But generally - we need to remove `NpmAdvisoryMirrorTask` (now it's useless), and create `GithubAdvisoryMirrorTask` which would work not only for NPM projects ([see API here](https://developer.github.com/v4/explorer?query=%7B%0A%20%20securityAdvisories(orderBy%3A%20%7Bfield%3A%20PUBLISHED_AT%2C%20direction%3A%20DESC%7D%2C%20first%3A%2010)%20%7B%0A%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20description%0A%20%20%20%20%20%20ghsaId%0A%20%20%20%20%20%20summary%0A%20%20%20%20%20%20publishedAt%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)).

**Comment by stevespringett** [comment]
https://github.com/advisories does not provide any way to contact the team regarding the feed. I have a [message posted in the GitHub Security Lab Slack workspace](https://ghsecuritylab.slack.com/archives/CQJN6KQHX/p1634166544038700) trying to get more information on how to report the issue so it can get resolved.

**Comment by Mario-Hofstaetter** [comment]
Just noticed the same exception in logs after upgrading dtrack to `4.3.6` which got me nervous, good to see there is already an issue for it.

**Comment by ddurham2** [comment]
I'm also seeing this today.  I'm concerned that it's leaving some vulns showing that we've fixed i.e. still showing packages that aren't in the uploaded sbom anymore.

**Comment by stevespringett** [comment]
NPM Advisory mirroring will cease to work after February 16, 2022.
https://github.blog/changelog/2021-11-16-deprecating-non-audit-related-advisory-fetch-endpoints-for-the-npmjs-com-registry-api/

**Comment by stevespringett** [comment]
Observations while working on this ticket:
* It is not possible to perform a vulnerability scan against a specific version of a component using GitHub advisories. 
* It is possible to mirror the contents of GitHub Advisories, although doing so requires an API token to be created on GitHub and configured in DT. I spoke with Kate Catlin who is the product manager over GitHub Advisories about the poor usability of this as well as other observations.
* GitHub Advisories does provide enough information for it to be used by the Internal Analyzer. Therefore, the plan is to mirror the contents of GitHub Advisories and use the Internal Analyzer for identifying vulnerabilities in components.

**Comment by stevespringett** [comment]
Mirroring of GitHub Advisories is nearly complete.
<img width="1725" alt="Screen Shot 2021-12-04 at 3 46 11 PM" src="https://user-images.githubusercontent.com/3878933/144725578-df7f6fc4-33b6-4307-9799-c78ddeba2d11.png">

**Comment by stevespringett** [comment]
Here's an update on this ticket. Now that all GitHub Advisories are mirrored to the DT database (just like NVD ones are), I needed to make some changes to the Internal Analyzer - specifically to add support for using Package URL to identify known vulnerabilities. Previously, the internal analyzer relied solely on CPE. With this change, it also provides a prerequisite for #96 (a private/internal vulnerability repository).

<img width="1722" alt="Screen Shot 2022-01-25 at 9 49 42 AM" src="https://user-images.githubusercontent.com/3878933/151011805-1366a151-4c4a-4ed5-8f60-fa39c929a00c.png">

GitHub Advisories currently supports:
* Maven
* Rust Cargo
* Pypi
* Ruby Gems
* Golang
* NPM
* PHP Composer
* NuGet

DT incorporates support for all of these ecosystems when using GitHub Advisories.

**Comment by stevespringett** [comment]
Also debuting in v4.4 is finer control over mirroring of vulnerability sources, GitHub being one of them.

<img width="1529" alt="Screen Shot 2022-01-26 at 4 54 41 PM" src="https://user-images.githubusercontent.com/3878933/151260891-88bc4c22-7ebd-4bb4-94d8-787d9ea7441d.png">

**Comment by iamrahul127** [comment]
Hi @stevespringett, Great work. I am trying this out and wondering how to get API token for GitHub advisory API. Could you please help me with some reference? If required I can create PR to create documentation.

**Comment by iamrahul127** [comment]
@stevespringett With this change is following a valid setting or will be removed in near future?
![image](https://user-images.githubusercontent.com/24877322/157247191-896683fe-5081-40ea-89b4-da7e16c6cc1c.png)

**Comment by stevespringett** [comment]
@iamrahul127 The npm Audit analyzer has already been removed, but it looks like I missed removing its configuration from the frontend.
