### ISSUE TITLE
Login with OIDC_ENABLED results in 500

### ISSUE THREAD

**Issue by cmenzi** [DependencyTrack/dependency-track#1252]
When login via OIDC on Azure AD, the api-server endpoint `/api/v1/user/oidc/login` returns a `500`.  I also started the api server  with TRACE logging enabled, but no error entry is shown.

### Current Behavior:
It's not possible to login via OIDC on Azure AD.

### Steps to Reproduce:

```
    # Optional OpenID Connect (OIDC) Properties
    - ALPINE_OIDC_ENABLED=true
    - ALPINE_OIDC_ISSUER=https://login.microsoftonline.com/<tenantId>/v2.0
    - ALPINE_OIDC_USERNAME_CLAIM=email #prefered_username is not available
    # - ALPINE_OIDC_TEAMS_CLAIM=groups
    - ALPINE_OIDC_USER_PROVISIONING=true
    # - ALPINE_OIDC_TEAM_SYNCHRONIZATION=true
```

### Expected Behavior:
- Login works on Azure AD. 
- In previous versions of dependency track (I don't remember which one), Azure AD worked.

### Environment:
  - Dependency-Track Version: 4.3.6
  - Distribution: Docker
  - Database Server: PostgreSQL
  - Browser: Chrome

**Comment by cmenzi** [comment]
Any update on this? Or do you need additional information?

**Comment by nscuro** [comment]
Your compose file is missing the `ALPINE_OIDC_CLIENT_ID` environment variable. It is required since v4.3.0 and was mentioned in the changelog's upgrade notes. See https://docs.dependencytrack.org/changelog/

![image](https://user-images.githubusercontent.com/5693141/141517032-2dee4ad4-f7f2-4ef2-b066-66fe12e2c60f.png)

**Comment by cmenzi** [comment]
That worked! Thank you! I will also update my example in the discussions: https://github.com/DependencyTrack/dependency-track/discussions/1104
