### ISSUE TITLE
Send projects's notification to a specific teams channel/email.

### ISSUE THREAD

**Issue by Whisper40** [DependencyTrack/dependency-track#1255]
I think that can be a good idea to push notifications about one project to a specific teams channel.

### Current Behavior:
The notification can be pushed to only one channel.

### Proposed Behavior:
When we create a team we should be able to specify a teams url/email/.. specific to the team.
And then when the notification has to be pushed, we send the notification to each team that is related to this project.

**Comment by stevespringett** [comment]
This functionality is already possible. You would create an alert for every team you want the alert sent to and specify the project(s). If you do not use the 'limit to' projects functionality, then DT will send notifications for all projects.

**Comment by stevespringett** [comment]
Per the [docs](https://docs.dependencytrack.org/integrations/notifications/):

> By default, portfolio notifications are published regardless of which project is affected. This behavior can be altered by optionally limiting the projects. Expand the ‘Limit To’ button to reveal and configure the list of projects.

**Comment by Whisper40** [comment]
Yes you are right ! thanks !
