### ISSUE TITLE
Component and Dependency graph is not showing same number of components

### ISSUE THREAD

**Issue by bhuvi11** [DependencyTrack/dependency-track#1269]
Hello Team,

Below is the screenshot for component and dependency graph tab

Dependency Graph 
![image](https://user-images.githubusercontent.com/14215473/141071032-0749b554-8c48-47a3-8b7b-c23227b7cc82.png)

Component
![image](https://user-images.githubusercontent.com/14215473/141077703-8c05fbf3-1e82-4388-96b0-43c9c05b720b.png)

If you see i have 17 components but the graph has only 14 components.
The Bom file however shows the overall dependencies 
Attaching the bom file as well
[bom.zip](https://github.com/DependencyTrack/dependency-track/files/7511066/bom.zip)

Please help

**Comment by msymons** [comment]
The Dependency-Graph currently only displays two levels of dependencies (ignoring "level 0", which is "fooworld" in your screenshot).   This leads to transitive dependencies often not being displayed, an issue already recorded in [Front End issue 85](https://github.com/DependencyTrack/frontend/issues/85).

I worry that simply extending the existing graph implementation to display more levels would lead to something that becomes hard to read.  Thus, I logged [Front End enhancement issue 87](https://github.com/DependencyTrack/frontend/issues/87) to suggest the addition of filtering options that would allow one to really focus on what is of interest.  Which might be a vulnerable component today,  or a component with a dodgy license tomorrow.
