### ISSUE TITLE
REST API - date type mismatch

### ISSUE THREAD

**Issue by ruckc** [DependencyTrack/dependency-track#1276]
### Current Behavior:
The swagger.json documents ProjectMetrics firstOccurrence and lastOccurrence as string/date-time.  The response payload is a unix timestamp in milliseconds since Jan 1 1970.  This makes it difficult to autogenerate client code something like openapi-generator.  This is likely due to the usage of the `java.util.Date` object instead of the newer JSR310 date types for JSON marshalling.

### Expected Behavior:
It would be ideal if the REST API matched the response type.

### Environment:
  
  - Dependency-Track Version: 4.3.6
  - Distribution: Docker
  - BOM Format & Version: N/A
  - Database Server: PostgreSQL
  - Browser: N/A

**Comment by JorisVanEijden** [comment]
Alternatively change the swagger,.json to say
```
"type" : "integer",
"format" : "int64"
```
in stead of 
```
"type" : "string",
"format" : "date-time"
```
Obviously less preferable from a correctness standpoint, but it would not constitute a breaking change.

**Comment by taladar** [comment]
I just ran into this issue too. Is there a reason this minor fix has not been implemented in over a year?

Also, the breaking change label is still wrong, at least for the solution that fixes swagger to reflect what the API actually does.

**Comment by danhallin** [comment]
As the output from http://{hostname}:{port}/api/swagger.json is not following the Swagger 2.0 specification:

https://swagger.io/specification/v2/
https://www.ietf.org/rfc/rfc3339.txt

This error should at least be mentioned in the documentation here:

https://docs.dependencytrack.org/integrations/rest-api/
