### ISSUE TITLE
HTTP POST and PUT method have been mixed up

### ISSUE THREAD

**Issue by tonnyhideyori** [DependencyTrack/dependency-track#1277]
In the API `/v1/repository`  method POST and PUT are mixed, the place of POST there is PUT and vice versa, and I have seen this in many APIs throughout the project.

**Comment by stevespringett** [comment]
I'm not sure I understand. The conventions of this project is to use PUT for create and POST for update. This convention should be fairly consistent throughout the project and appears to be properly applied to `/v1/repository`.

**Comment by tonnyhideyori** [comment]
But, if I use POST as an update, won't I create new data and not update the existing data

**Comment by stevespringett** [comment]
No, a POST will not create. POSTs require the UUID of objects to be provided so DT can lookup the object. If the UUID of the repository is not provided or cannot be found, the following message will be displayed: `The UUID of the repository could not be found.`

Refer to the swagger for additional information.

**Comment by tonnyhideyori** [comment]
ok thank you
