### ISSUE TITLE
Did Dtrack support OpenLDAP?

### ISSUE THREAD

**Issue by nibiwodong** [DependencyTrack/dependency-track#1278]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
The document do not notise OpenLDAP config method.
https://docs.dependencytrack.org/getting-started/ldap-configuration/

### Proposed Behavior:
If Dtrack support OpenLDAP, hope update the document.

**Comment by stevespringett** [comment]
Dependency-Track does not officially support OpenLDAP. In reality, it will likely work fine, however, OpenLDAP schemas deviate quite dramatically based on where you've obtained OpenLDAP from (e.g. various Linux distros or hardware appliances).
