### ISSUE TITLE
Remove Vulnerabilities after add on Suppression not work

### ISSUE THREAD

**Issue by stboissdev** [DependencyTrack/dependency-track#128]
I have a component with vulnerabilities (FP), i add this component in suppression File.
in next report, all vulnerabilities are marked in the tag "suppressedVulnerability" but still appear in GUI.

**Comment by stevespringett** [comment]
Which suppression file was it marked in?

ODT performs its own scans independent of ODC. Importing ODC reports is used primarily to identify the individual components, not vulnerabilities, as ODT performs its own scans.

In this case, you can use the global suppression capability in ODT. https://docs.dependencytrack.org/triage/suppressions/. In v3.1, an auditing workflow is being incorporated that will offer much better flexibility. See #65.

**Comment by stboiss** [comment]
I add suppression file in ODT in ~/.dependency-track/dependency-check
the report is the ODT report  on ~/.dependency-track/dependency-check/reports

**Comment by stevespringett** [comment]
Closing as DT no longer integrates DC
