### ISSUE TITLE
DefectDojo Integration not working

### ISSUE THREAD

**Issue by iamrahul127** [DependencyTrack/dependency-track#1318]
### Current Behavior:
We have configured and enabled DT to DefectDojo (DD) integration and It's not working. I could capture some logs after enabling debug level log. 

09:47:26.476 DEBUG [EventService] Dispatching event: class org.dependencytrack.event.DefectDojoUploadEventAbstract
09:47:26.476 DEBUG [EventService] Alerting subscriber org.dependencytrack.tasks.DefectDojoUploadTask
09:47:26.477 DEBUG [EventService] Dispatching event: class org.dependencytrack.event.DefectDojoUploadEventAbstract
09:47:26.477 DEBUG [EventService] **No subscribers to inform from event: org.dependencytrack.event.DefectDojoUploadEventAbstract**
09:47:26.477 DEBUG [DefectDojoUploadTask] Starting DefectDojo upload task
09:47:26.510 DEBUG [DefectDojoUploadTask] DefectDojo upload complete

I think highlighted line in logs above might be hinting towards a problem. I checked code and was expecting "_Initializing integration point:_" in logs from _VulnerabilityManagementUploadTask_ class  _processProjectFindings_ method.

### Steps to Reproduce:
1. Setup DT.
2. Setup DD
3. Configure integration in DT.
4. Watch logs

### Expected Behavior:
Issues should synched.

### Environment:
  
  - Dependency-Track Version: 4.3.6
  - Distribution: [ Docker+AKS ]
  - DD Version: 2.5.0
  - BOM Format & Version: CycloneDX 1.3
  - Database Server: [ PostgreSQL ]
  - Browser: Chome

### Additional Details:

DT & DD both hosted in AKS and using http.

**Comment by iamrahul127** [comment]
Do we need to configure anything at DT project level?

**Comment by nibiwodong** [comment]
> Do we need to configure anything at DT project level?

https://docs.dependencytrack.org/integrations/defectdojo/
![image](https://user-images.githubusercontent.com/17465789/148186510-bc1244fc-7f16-4dd2-b853-1bcc8c35bfa3.png)

https://github.com/DefectDojo/django-DefectDojo/issues/5666

**Comment by nibiwodong** [comment]
> Do we need to configure anything at DT project level?

By the way, I'm not sure how to  configure the logical correspondence between dtrack(project and version) and defectdojo(product type/product/engagement/tests). 

Hope to discuss best practices.

**Comment by iamrahul127** [comment]
> > Do we need to configure anything at DT project level?
> 
> https://docs.dependencytrack.org/integrations/defectdojo/ ![image](https://user-images.githubusercontent.com/17465789/148186510-bc1244fc-7f16-4dd2-b853-1bcc8c35bfa3.png)
> 
> [DefectDojo/django-DefectDojo#5666](https://github.com/DefectDojo/django-DefectDojo/issues/5666)

Integration worked after I added an engagement to already created product in DefectDojo(DD) and configuring the project property as suggested. 
I understand engagement in DD has certain duration and  not sure if that's the format we would like to use. We will discuss it further and I hope we come up with use case.

**Comment by stevespringett** [comment]
Yes. The per-project configuration details are at the bottom of https://docs.dependencytrack.org/integrations/defectdojo/

**Comment by iamrahul127** [comment]
Closing as documentation is updated.
