### ISSUE TITLE
List Project for tag

### ISSUE THREAD

**Issue by stboissdev** [DependencyTrack/dependency-track#132]
When you have a list of project for a tag  with more than 10 project, on .../projects/?tag=Test if you click on second page or change number displayed elements, in the list, appears all projects.

**Comment by stboiss** [comment]
@stevespringett, up please

**Comment by stevespringett** [comment]
I fixed an issue related to this, but cannot reproduce the issue reported with v3.1 snapshot. Perhaps it's already been fixed or is only an issue with a specific browser.

**Comment by stboissdev** [comment]
@stevespringett, it's OK with 3.1.1. thank's
