### ISSUE TITLE
Template Docker Compose, Wrong CORS Headers

### ISSUE THREAD

**Issue by silvio201** [DependencyTrack/dependency-track#1325]
The current template for docker-compose has an error at the following line:

`# - ALPINE_CORS_ALLOW_METHODS=GET POST PUT DELETE OPTIONS`

There have to be commas in between these Options in order to work.

### Environment:
  
  - Dependency-Track Version: 4.3.6
  - Distribution: [ Docker ]

**Comment by markusdresch** [comment]
thank you! i have been pulling my non-existent hair out over this...
