### ISSUE TITLE
New vulnerabilities in one project can trigger NEW_VULNERABILITY notifications for a different project where the vulnerability is not new

### ISSUE THREAD

**Issue by viatrip-sc** [DependencyTrack/dependency-track#1327]
### Current Behavior:
Adding a new dependency with a vulnerability to a project triggers NEW_VULNERABILITY notifications for any other project which already had the same dependency, regardless of the "limit to" selection for the notification.

This creates repeat alerts which incorrectly indicate new issues for the project that already had the vulnerability.

### Steps to Reproduce:
Add a project with NEW_VULNERABILITY notifications limited to that project. 
Add a vulnerable dependency to that project.
  The notification fires (correctly)
Add a second project with the same vulnerability.
  The notification fires (incorrectly, as there is nothing new in the first project).

### Expected Behavior:
Adding a vulnerability to a project should not fire NEW_VULNERABILITY notifications where the notification is configured to exclude the project in their "Limit to" selection. The notification should only fire if the projects in the "limit to" list have had the vulnerability newly added/discovered as well.

### Environment:
  
  - Dependency-Track Version: 4.3.6
  - Distribution: Docker 
  - BOM Format & Version: Cyclone DX 1.1
  - Database Server: PostgreSQL
  - Browser: Firefox

### Additional Details:

#616 and #975 sound similar

**Comment by sephiroth-j** [comment]
This sounds the same as #1150

**Comment by viatrip-sc** [comment]
I agree, thanks for pointing that out. I will close this as a duplicate of #1150 .
