### ISSUE TITLE
Add export of vulnerabilities and VEX

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#1365]
When exporting a CycloneDX BOM from DT, there should be an option to include vulnerabilities with and without audit decisions (VEX).

**Comment by stevespringett** [comment]
The existing auditing workflow in Dependency-Track has been updated with a few new fields. 

* Analysis (existing field) - maps to CycloneDX [Analysis State](https://cyclonedx.org/docs/1.4/json/#vulnerabilities_items_analysis_state)
* Comment (existing field) - internal only - will not be mapped to VEX output
* Audit trail (existing read-only field) - internal only - will not be mapped to VEX output
* Justification (new field) - maps to CycloneDX [Analysis Justification](https://cyclonedx.org/docs/1.4/json/#vulnerabilities_items_analysis_justification)
* Vendor Response (new field) - maps to CycloneDX [Analysis Response](https://cyclonedx.org/docs/1.4/json/#vulnerabilities_items_analysis_response)
* Detail (new field) - maps to CycloneDX [Analysis Details](https://cyclonedx.org/docs/1.4/json/#vulnerabilities_items_analysis_detail)

https://user-images.githubusercontent.com/3878933/152282838-a2f0ab51-7c84-4b60-b14b-2d07a3e63d99.mp4

**Comment by msymons** [comment]
This looks awesomely useful. I think it addresses #357, except for covering BACKPORT and DISCONTINUE,  

But for all my devs,  all this good stuff will still be hidden from view.  Is there a possibility that we might see a VIEW_VULNERABILITY permission, as detailed in #338?

**Comment by stevespringett** [comment]
The frontend has been updated to be able to download all three variants of BOMs (inventory, inventory with vulnerabilities, and vex)

<img width="830" alt="Screen Shot 2022-02-10 at 7 40 38 PM" src="https://user-images.githubusercontent.com/3878933/153525539-86c729b7-e01b-4152-8c8a-dfd50cda995f.png">
