### ISSUE TITLE
Out of memory crash...

### ISSUE THREAD

**Issue by logopk** [DependencyTrack/dependency-track#138]
When Running on docker-ce 18.04 on MacOS and VMware I do get this error and the container is killed...

[docker.log](https://github.com/stevespringett/dependency-track/files/1939485/docker.log)

Any idea? no other container are running.

Thank you.

Peter

**Comment by logopk** [comment]
I actually just wanted to play around with it on my local Mac docker.

My workaround with just one project is:

**Comment by torstenwalter** [comment]
You could use [run-java.sh](https://github.com/fabric8io-images/run-java-sh) as startup script, to calculate the amount of memory for the JVM based on container constraints on memory and cpus.

**Comment by stevespringett** [comment]
Closing
