### ISSUE TITLE
Empty "Last BOM Import" and "BOM Format" field

### ISSUE THREAD

**Issue by yutayamate** [DependencyTrack/dependency-track#1384]
### Current Behavior:
`Last BOM Import` and `BOM Format` fields are not displayed (empty) for some projects after importing BOM file, while `Risk Score` and `Vulnerability` are displayed as `0`.

I confirmed the project is listed on `/v1/project` API but the fields are not included in the response. I also tried metrics refresh but no luck.

<img width="1504" alt="Screen Shot 2022-02-11 at 11 51 03" src="https://user-images.githubusercontent.com/11874627/153531904-9ec3bfdc-d1fb-4dd1-961e-abfc7f8dd928.png">

### Steps to Reproduce:
Import BOM JSON file (Cyclone DX 1.4) via `/v1/bom` API.

### Expected Behavior:
`Last BOM Import` and `BOM Format` are displayed with correct number of vulnerabilities and risk score once BOM analysis for the project is completed.

### Environment:
  
  - Dependency-Track Version: v4.3.6 / Frontend v4.3.1
  - Distribution: Docker
  - BOM Format & Version: CycloneDX
  - Database Server: PostgreSQL
  - Browser: Chrome, Postman

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
CycloneDX v1.4 will be supported in the upcoming release of Dependency-Track v4.4. It it not supported in v4.3.

**Comment by yutayamate** [comment]
Thank you for prompt confirming @stevespringett. OK, I'll use Cyclone DX v1.3 instead.
