### ISSUE TITLE
restrict access to projects

### ISSUE THREAD

**Issue by stboissdev** [DependencyTrack/dependency-track#140]
is it possible to restrict access to some projects for a group of users ?

**Comment by stevespringett** [comment]
Note to self. Replicate the logic and UI metaphor in [Hakbot Origin Controller](https://github.com/hakbot/hakbot-origin-controller) (also built on Alpine) to bring this functionality to Dependency-Track.

**Comment by msymons** [comment]
Restriction of access to projects is a really interesting idea.  How might it impact the way that dependency-track-plugin works?  ie, currently, one configures a single DT server in Jenkins with a single token...and can see all projects.

**Comment by stevespringett** [comment]
Theoretically it could work very similar to the restrict functionality present in notifications. Ideally it would be an assignment of projects a user or team have access to it.

**Comment by adaptivui** [comment]
> 
> 
> This feature is going to require a lot more time than originally thought. It's also going to require a tremendous amount of testing to ensure there are no vulnerabilities in ACL logic. 

@stevespringett, for the tests, we can propose you our help as beta-testers. 
We already have implemented such feature for our company because it's a must-have feature (as a transitionnal phase waiting for the official implementation) and we could compare the expected behaviours.

PS : Our implementation is diffferent from yours but the behaviour is the same (users linked to teams, permissions for teams on projects)

**Comment by stevespringett** [comment]
@adaptivui I'll likely start working on this feature right after the release of 3.6 so that all the details are still fresh in my mind. Would appreciate any help, especially around test cases that your team and the rest of the community could provide.

**Comment by technoo10201** [comment]
Hello @stevespringett,
I come back to you to get more informations & details regarding the feature to restrict user's access to projects. Do you have news about this ?

By the way, i saw you move this feature for the future 3.9 version, do you have any branch which you can give me access to in order to test it ?

Many thanks in advance !

**Comment by stevespringett** [comment]
@technoo10201 I'm trying to get v3.8 released which included a rewrite of the UI. The release of the new UI was necessary prior to to the introduction of new enhancements requiring UI changes, such as project acl assignments.

Once 3.8 is released, I'll start working on 3.9. however, pull requests are highly encouraged, especially for features that are important to organizations.

**Comment by valentijnscholten** [comment]
Just expressing my interest here and my availability to help testing or even help implementing.
This is the primary reason we haven't yet adopted dependency track. Our aim is to have all projects in it, but seggregate access between teams. We have about ~15 teams + ~100 projects.

**Comment by ericykchan** [comment]
Hi all, I think per project access is an important security feature. If everybody can read the potential vulnerability of every projects, this helps insiders to decide what to attack.

**Comment by stevespringett** [comment]
This is going to be a large effort. I am reserving v4.3 exclusively for this feature.

**Comment by stevespringett** [comment]
Ok. The time has come. v4.3 is dedicated specifically for this feature.

**Comment by technoo10201** [comment]
> Ok. The time has come. v4.3 is dedicated specifically for this feature. Let the work begin.

Hello, thanks for sharing !

**Comment by csturiale** [comment]
> Ok. The time has come. v4.3 is dedicated specifically for this feature. Let the work begin.

Is there a milestone planned for this feature? Thanks

**Comment by stevespringett** [comment]
@csturiale, yes, the milestone is [4.3](https://github.com/DependencyTrack/dependency-track/milestone/17).

**Comment by stevespringett** [comment]
## Update
ACL logic has been implemented. In its current form, Portfolio Access Control will be a beta feature in v4.3. That means that this project will not treat bypass or absent ACL logic as a security defect. In fact, there are a few known gaps in ACL logic that will exist in v4.3.

What does exist is ACL logic for:
* /v1/bom/*
  * Uploading SBOMs to projects or exporting SBOMs from projects or components
* /v1/component/*
  * CRUD operations on components
* /v1/project/*
  * _RUD operations on projects
* /v1/service/*
  * CRUD operations on components
* /v1/vulnerability/*
  * CRUD operations on vulnerable projects or components

The user interface clearly states that Portfolio Access Control is beta. By default, Portfolio Access Control is disabled.

**Comment by stevespringett** [comment]
I also added ACL logic for:

* /v1/metrics/*
  * Project and component metrics
* /v1/violation/*
  * Project and component policy violations
* /v1/finding/*
  * Security findings for projects and components  

These will be included in v4.3

**Comment by stevespringett** [comment]
Known gaps that will exist in v4.3 are documented in #1127 which will be implemented in v4.4.
