### ISSUE TITLE
Project > Audit Vulnerabilities tab not visible after upgrade to v4.4.0

### ISSUE THREAD

**Issue by nil4** [DependencyTrack/dependency-track#1404]
After upgrading a canary DT instance from v4.3.6 to v4.4.0, the *Audit Vulnerabilities* tab is no longer visible for any project for the internal `admin` user. 

Before upgrade, with v4.3.6, the *Audit Vulnerabilities* tab was visible:

![image](https://user-images.githubusercontent.com/139133/154638455-a8d9842e-4d82-48df-9a04-ff50e44142af.png)

After upgrade, with v4.4.0, it no longer is:

![image](https://user-images.githubusercontent.com/139133/154638595-451dacf6-635f-4575-be66-7c8701c910b7.png)

Under Access Management > Managed Users, the `admin` user appears to have all required permissions assigned, including:
- `SYSTEM_CONFIGURATION`
- `VIEW_VULNERABILITY`
- `VULNERABILITY_ANALYSIS`
- member of the `Administrators` built-in team, which also has these permissions

### Current Behavior:

The *Audit Vulnerabilities* tab is not visible to the admin user.

### Expected Behavior:

The *Audit Vulnerabilities* tab should be visible to administrators and users with `VIEW_VULNERABILITY` or `VULNERABILITY_ANALYSIS` permissions.

### Environment:
  
  - Dependency-Track Version: 4.4.0
  - Distribution: Executable WAR
  - BOM Format & Version: N/A
  - Database Server: MSSQL
  - Browser:  N/A

### Additional Details:

The v4.4.0 instance makes a call to `/api/v1/user/self` which returns the following permissions:

```
GET http://localhost:8080/api/v1/user/self

HTTP/1.1 200 OK
Date: Fri, 18 Feb 2022 07:37:13 GMT
Content-Type: application/json
X-Powered-By: Dependency-Track v4.4.0

{
    "username": "admin",
    "lastPasswordChange": 1609941224545,
    "fullname": "Administrator",
    "email": "admin@localhost",
    "suspended": false,
    "forcePasswordChange": false,
    "nonExpiryPassword": true,
    "teams": [
        {
            "uuid": "1cf94561-50c8-4f20-a12f-b7dd8d7dec58",
            "name": "Administrators"
        }
    ],
    "permissions": [
        {
            "name": "ACCESS_MANAGEMENT",
            "description": "Allows the management of users, teams, and API keys"
        },
        {
            "name": "BOM_UPLOAD",
            "description": "Allows the ability to upload CycloneDX and SPDX Bill of Materials (BOM)"
        },
        {
            "name": "POLICY_MANAGEMENT",
            "description": "Allows the creation, modification, and deletion of policy"
        },
        {
            "name": "POLICY_VIOLATION_ANALYSIS",
            "description": "Provides the ability to make analysis decisions on policy violations"
        },
        {
            "name": "PORTFOLIO_MANAGEMENT",
            "description": "Allows the creation, modification, and deletion of data in the portfolio"
        },
        {
            "name": "PROJECT_CREATION_UPLOAD",
            "description": "Provides the ability to optionally create project (if non-existent) on BOM or scan upload"
        },
        {
            "name": "SYSTEM_CONFIGURATION",
            "description": "Allows the configuration of the system including notifications, repositories, and email settings"
        },
        {
            "name": "VIEW_PORTFOLIO",
            "description": "Provides the ability to view the portfolio of projects, components, and licenses"
        },
        {
            "name": "VIEW_VULNERABILITY",
            "description": "Provides the ability to view the vulnerabilities projects are affected by"
        },
        {
            "name": "VULNERABILITY_ANALYSIS",
            "description": "Provides the ability to make analysis decisions on vulnerabilities"
        }
    ]
}
```

Under *Access Management*, the `admin` user permissions are:

![image](https://user-images.githubusercontent.com/139133/154639822-918914cf-6dd6-49b8-99f5-d35334061622.png)

And the `Administrators` team's permissions are:

![image](https://user-images.githubusercontent.com/139133/154639944-0d0c9c8b-79a3-45d2-a2a1-6b2d24b7fd71.png)

**Comment by nscuro** [comment]
Please make sure that:
* You're using v4.4.0 of the frontend
* You re-login to DT after the upgrade completed

Changes to permissions require you to reauthenticate, because the frontend uses the bearer token issued by the API server to to verify permissions.

**Comment by nil4** [comment]
Spot on! I was using v4.4.0 frontend, but did *not* log out and back in -- that was the culprit, and fixed the issue straight away.
Thanks a lot @nscuro!
