### ISSUE TITLE
QuickStart is not starting

### ISSUE THREAD

**Issue by PascalTurbo** [DependencyTrack/dependency-track#1426]
### Current Behavior:
When following the docker-compose quick start guide, apiserver stops with the following message:

2022-03-02 09:32:05,763 ERROR [RequirementsVerifier] Dependency-Track requires a minimum of 4GB RAM (heap). Cannot continue. To fix, specify -Xmx4G (or higher) when executing Java.

### Steps to Reproduce:

```
curl -LO https://dependencytrack.org/docker-compose.yml
docker-compose up
```

### Expected Behavior:

ApiServer should start

**Comment by stevespringett** [comment]
Refer to https://docs.dependencytrack.org/getting-started/deploy-docker/

it appears the Docker host is not allocating a minimum of 4GB of RAM to the Docker container. If you're running on macOS or Windows, these default to 2GB. Consult the Docker documentation for how to change this.
