### ISSUE TITLE
NVD Mirroring Connection Hangs, needs timeout

### ISSUE THREAD

**Issue by officerNordberg** [DependencyTrack/dependency-track#1431]
Mirroring started having issues for us on February 25th.  Initially a NistMirrorTask hung after logging "Downloading... "  This task was still hung March 2nd. 
When restarting the containers from docker-compose, a handful of years hung just after the previous log "Initiating download of {...}"

HttpClient should specify a timeout 

https://github.com/DependencyTrack/dependency-track/blob/10d94467007a1446fc7f89f8c62e5a90a8c862de/src/main/java/org/dependencytrack/tasks/NistMirrorTask.java#L206-L239

**Comment by stevespringett** [comment]
Thanks for the report. I should be able to include support for user configurable timeout settings globally for all HTTP client connections.

**Comment by stevespringett** [comment]
I have an important defect that's been fixed, so I'll be releasing 4.4.1 shortly. I'll try to get this in there.

**Comment by stevespringett** [comment]
In Dependency-Track v4.4.2, you'll be able to set these properties using:

`ALPINE_HTTP_TIMEOUT_CONNECTION`
`ALPINE_HTTP_TIMEOUT_SOCKET`
`ALPINE_HTTP_TIMEOUT_POOL`

The first two are likely the ones you'll care about. The last one is a timeout for the pool of available HttpClient objects, which can be tweaked if the server is under heavy load doing a lot of inbound/outbound tasks.
