### ISSUE TITLE
Not allowed to upload sbom to project I create.

### ISSUE THREAD

**Issue by JorisVanEijden** [DependencyTrack/dependency-track#1435]
### Current Behavior:
As a team with BOM_UPLOAD and PROJECT_CREATION_UPLOAD permissions
When uploading a new sbom with autoCreate=true
I get an error "Access to the specified project is forbidden"
The project is created, but the sbom is not uploaded.

### Expected Behavior:
As a user or team with BOM_UPLOAD and PROJECT_CREATION_UPLOAD permissions
When uploading a new sbom with autoCreate=true
I want the newly created project to be added to my allowed list of projects
so that the bom upload succeeds.

### Environment:
  - Dependency-Track Version: v4.4.1
  - Distribution: Docker
  - BOM Format & Version: json 1.4
  - Database Server: PostgreSQL
  - Browser: Brave

**Comment by rstmm** [comment]
Same happens with MANAGE_PORTFOLIO permission and cloning a project. I can clone it via API but then not access the new project to upload a SBOM failing build pipelines.

See also my discussion here https://github.com/DependencyTrack/dependency-track/discussions/1425 which is the result of this problem

**Comment by JorisVanEijden** [comment]
Looks like there is already a TODO in the code for this: https://github.com/DependencyTrack/dependency-track/blob/10d94467007a1446fc7f89f8c62e5a90a8c862de/src/main/java/org/dependencytrack/resources/v1/BomResource.java#L271

**Comment by valentijnscholten** [comment]
When a project is created via the API using an API Key, the solution is quite straightforward indeed. Give the Team access to the new Project.

But what to do when a user creates a new project via the UI or API. We update the ACL because it works solely on Teams.. A user can have 0 or more Teams, which one(s) should we add to the ACL?

**Comment by valentijnscholten** [comment]
> Same happens with PORTFOLIO_MANAGEMENT permission and cloning a project. I can clone it via API but then not access the new project to upload a SBOM, which then fails the build pipeline.
> 
> See also my discussion here #1425 which is the result of this problem

I think this is an issue of its own, so created one: https://github.com/DependencyTrack/dependency-track/issues/1534

**Comment by rstmm** [comment]
> When a project is created via the API using an API Key, the solution is quite straightforward indeed. Give the Team access to the new Project.
> 
> But what to do when a user creates a new project via the UI or API. We update the ACL because it works solely on Teams.. A user can have 0 or more Teams, which one(s) should we add to the ACL?


I would say if a user creates it manually, he can (wants to?) also assign the groups manually. At least in my case I create the base of each project myself and assign the teams then. UI wise it would be nice this could be done already in the creation screen though. Currently First I need to create and then remember to assign in the admin menu. 
But if there are use cases where a user creates a project and has no ACL permission, I'm not sure what to do.

**Comment by valentijnscholten** [comment]
The problem is that a user has no access to the project that is autocreated during BOM upload. If a user has ACCESS_MANAGEMENT permission, the user can do everything so there is no issue.

**Comment by rstmm** [comment]
> The problem is that a user has no access to the project that is autocreated during BOM upload. If a user has ACCESS_MANAGEMENT permission, the user can do everything so there is no issue.

Yes autocreation by API is a problem. The only reasonable idea which I have, is that the API which allows autocreation also needs a parameter to supply group names for acl permissions. Logic wise that makes most sense (when I create a project I should be able to tell who gets access). But API wise that would be ugly. If the API should be "nicer" then the project needs the suggested "owner" field, so that the ACL API can be used either, if you have permission to modify ACL generally, or on projects on which you are the owner.

**Comment by valentijnscholten** [comment]
Yes, those suggestions are on the list above.
The problem also occurs when creating a project via the UI. The user creates a project, but won't be able to see it afterwards. The API, I think, is mainly used with API Keys which will belong to a Team and in #1435 the Team will have access to it when autocreating a Project.
