### ISSUE TITLE
Filter to show only vulnerable components in a project

### ISSUE THREAD

**Issue by StephenTrombetti** [DependencyTrack/dependency-track#145]
This is an enhancement idea/suggestion similar to #144.

When looking at a specific project the list of components can be rather long and clicking through 10+ pages to search for a single vulnerable component is tedious. A filter (check box, toggle, etc) of some sort to display only the vulnerable components in a project would be very useful.

**Comment by stevespringett** [comment]
This ticket is likely already implemented as part of #65 since in the 'audit' tab, the only components that are displayed are ones with vulnerabilities.

**Comment by msymons** [comment]
The audit tab is not accessible to those who lack the requisite permissions...  but the desired functionality has actually been implemented in the Project "Components" tab (renamed from "Dependencies" in 3.8.0 and earlier), although it's not actually filtering.

The addition of a sortable "risk score" column to the page means that you can display all your vulnerable components at the top of component page 1 with but one or two clicks.

**Comment by msymons** [comment]
The introduction of VIEW_VULNERABILITY permission means that the audit tab can now be accessed without having the ability to perform triage.

Thus, there is now more than one way to view only those components in a project that are affected by vulnerabilities.
