### ISSUE TITLE
Refactor to support multiple CWEs

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#1467]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
Only a single CWE can be specified for a vulnerability. This design decision was based on legacy implementation detail from the NVD.

### Proposed Behavior:
Add support for an array of CWEs per vulnerability. This will be a breaking change for the vulnerability REST APIs and notifications.

Related to #96

**Comment by sephiroth-j** [comment]
@stevespringett, may I ask you to not add a breaking change to the API for this? You could leave the existing elements and let them return the values of the first entry of the list of CWEs while `cwes` holds the complete list. Similar to what [you did here in the `KennaDataTransformer`](https://github.com/DependencyTrack/dependency-track/commit/6356a5125fa93dc0236c8d39ee55aaa6e694eeb6#diff-d8f31b62814912a74927c568ccdc01cecffa007fe1bb7a9f63e6ff52ee8d316c).

And isn't the API supposed to be versioned by its URI (based on that "v1" in the URI)? If so, adding breaking changes would not be permitted.

**Comment by nscuro** [comment]
@sephiroth-j That's a valid concern. I opened a PR #1633 that addresses this by including a `cwe` field, in addition to the new `cwes` array.

**Comment by sephiroth-j** [comment]
@nscuro , thank you but the fields where previously named `cweId` and `cweName` -> https://github.com/DependencyTrack/dependency-track/blob/4.4.2/docs/_docs/integrations/file-formats.md#L63,L64

**Comment by nscuro** [comment]
@sephiroth-j Good catch! Fix is underway.
