### ISSUE TITLE
Add support for OWASP RR

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#1493]
### Current Behavior:
CVSSv2 and CVSSv3 are supported severity scores

### Proposed Behavior:
Add support for the OWASP Risk Rating methodology. This should compliment the existing auditing framework AND be supported by vulnerabilities themselves. 

Multiple ratings are supported in CycloneDX, including OWASP. Therefore for VEX and other use cases, it's important to support it in DT.

Refer to https://javierolmedo.github.io/OWASP-Calculator/ for inspiration.

**Comment by syalioune** [comment]
Hello @stevespringett, do you mind if i take on this one ?
I've also spotted this one https://github.com/stevespringett/owasp-risk-rating-calculator that could be useful for the implementation.

**Comment by stevespringett** [comment]
Go for it @syalioune
