### ISSUE TITLE
Upgrade To MYSQL 8

### ISSUE THREAD

**Issue by Whisper40** [DependencyTrack/dependency-track#1497]
### Current Behavior:
Mysql 5.6 and 5.7, deprecated

### Proposed Behavior:
Mysql 8 is available for a long time now, since 2018, is DT compatible with it ? 
If no, when will it be possible ? 

(Mysql 5.6 and 5.7 should not be used anymore, 5.6 at least !)

**Comment by stevespringett** [comment]
MySQL 8 may work, it may not work. The overwhelming majority of adopters use Postgres or SQL Server. 

> If no, when will it be possible ?

Only when contributors test, make any necessary alterations, and document compatibility will it be possible. The focus of the project is cybersecurity risk identification and reduction. Any tasks that take time away from the core mission are deprioritized. So community contributions are extremely important for enhancements like this.

**Comment by Whisper40** [comment]
Ok i understand, will try Postgres as the adopters choose it :)
