### ISSUE TITLE
produce SuppressionFile for ODC

### ISSUE THREAD

**Issue by stboissdev** [DependencyTrack/dependency-track#153]
add url in order to have a suppressionFile for ODC corresponding to suppressed vulnerabilities add via GUI.

**Comment by stboiss** [comment]
No, it's in order to have a suppressionFile extracted from suppressed Vulnerabilities of ODT for external ODC execution

**Comment by stevespringett** [comment]
This actually won't be benefitual to ODC. The suppressions in ODC are very tightly integrated to the file-based scanners that it uses. Maven coordinates, JarAnalyzer, filenames, etc. ODT would not be able to produce a suppression file that ODC would likely benefit from. Suppressions will largely vary based on the ecosystem the component is a part of, the type of data causing a false positive, and the corrective measures to eliminate the false positive. ODT simply doesn't have any of that information.
