### ISSUE TITLE
Cloning a project should optionally clone the ACL

### ISSUE THREAD

**Issue by valentijnscholten** [DependencyTrack/dependency-track#1534]
### Current Behavior:
When cloning a project, the ACL for Portfolio Access Control cannot selected to be included in the clone.

### Proposed Behavior:
Allow the ACL to be cloned similar to Properties, Dependencies, Components, Services, Audit History

**Comment by valentijnscholten** [comment]
I have fix in the works, just need to get my head around Vue and state changes which I have never worked with before.
https://github.com/valentijnscholten/dependency-track/tree/clone-acl

**Comment by step50** [comment]
This feature is very important to us.

Do you have an idea of the integration schedule for this feature ?
