### ISSUE TITLE
Can't manage or authenticate with LDAP users

### ISSUE THREAD

**Issue by paulosbarros** [DependencyTrack/dependency-track#154]
Hello :smile: 
I'm running this app version:
`Application: Dependency-Track
Version:     3.0.4
Built-on:    2018-05-02 17:02:31`

1 - Reading de docker log, i know the LDAP synchonization has done succesfully
2 - But, when i'm trying to use an LDAP user to authenticate, the docker log has returned 'Unauthorized'
3 - Using the ADMIN user, i can't see any user on the list of LDAP users
4 - Inspecting the network log with Chrome, i have a response with HTTP 200 with an empty array as the response
5 - I've clicked on 'Create User' in the LDAP tab, and the user created have the atribute DN with de value 'INVALID', and i can't delete this user using the button on the user description block, but using the javascript function i can delete this user using his name.

Help me when it possible :heart: !
Thank you!

**Comment by stevespringett** [comment]
Are you using Active Directory, OpenLDAP, something else?

Also, a user account in the directory server will not automatically have access to Dependency-Track. You have to add an ldap user, then they will be able to authenticate. I'll have to take a look a the admin functions to see if there's a problem with deleting an 'invalid' user or not.

In v3.0.x, the username is automatically appended with whatever value is in `alpine.ldap.domain`.  So for Active Directory, if my base DN = `dc=example,dc=com`, then `alpine.ldap.domain` would likely be  `example.com`, but this is not always true. So ensure that you have the correct value that corresponds to your directory servers' configuration.

Also in 3.0.x, only *simple* authorization is supported. Refer to https://docs.oracle.com/javase/tutorial/jndi/ldap/authentication.html for the authorization modes.

In v3.1, the format of the username is definable as is support for strong LDAP authorization.

**Comment by paulosbarros** [comment]
I'm using an Active Directory 2016

I got the base DN by the A.D. Manager of the company and tested it inspecting the class used to LDAP authentication service on github project and 
 injecting an `application.properties` on docker

Can the latest version of docker have a diffrent version of code then the github code?

Any user will be shown when the LDAP syncronization are ok?

Thank you so much for fast answer my questions!

**Comment by paulosbarros** [comment]
When I create LDAP user using name 'jenkins' I can delete this user

When I create LDAP user using name 'jenkins@soc.com.br' the javascript console log is:
> Uncaught Error: Syntax error, unrecognized expression: #deleteUser-jenkins@soc.com.br
    at Function.ga.error (jquery-3.2.1.min.js:2)
    at ga.tokenize (jquery-3.2.1.min.js:2)
    at ga.select (jquery-3.2.1.min.js:2)
    at Function.ga [as find] (jquery-3.2.1.min.js:2)
    at r.fn.init.find (jquery-3.2.1.min.js:2)
    at new r.fn.init (jquery-3.2.1.min.js:2)
    at r (jquery-3.2.1.min.js:2)
    at <anonymous>:2:9
    at p (jquery-3.2.1.min.js:2)
    at Ja (jquery-3.2.1.min.js:3)

I think the `@` is an invalid character in this case, or the dots

**Comment by paulosbarros** [comment]
I solved my case, but can be a problem to other AD users.

Using the complete user name, and the full DN the AD configuration return the user information.

In my case, I can just configure users if they are in the same DN.

At this company, all the integration users are allocated in another DN scope than the people users, at this time i will just create an user in the same DN to solve that, but it will be a problem later.

I think the LDAP have an way to perform this query in a top organization unit and search in this childs, but I don't know how to do that.

Talking about the javascript errors, I found an little issue, the user registration can return some errors when tried to delete or edit an user, you can simulate this situation using a name containing invalid characters to CSS selectors.

**Comment by stevespringett** [comment]
@paulosbarros Thanks for reporting the issue. The issue has been corrected and will be included in the upcoming v3.1.0 release in June.

**Comment by paulosbarros** [comment]
@stevespringett I'm impressed with your speed and attention! Thank you!

**Comment by stevespringett** [comment]
Included in v3.1.0. Closing.
