### ISSUE TITLE
GAV identifier output from Gradle is not in parenthesis

### ISSUE THREAD

**Issue by jskovjyskebankdk** [DependencyTrack/dependency-track#156]
So scan imports will fail with the message:

Error while processing scan result
null

A gradle scan report will contain names like "de.schlichtherle.truezip:truezip-swing:7.7.7", not "(de.schlichtherle.truezip:truezip-swing:7.7.7)". I guess the latter is what would appear in a Maven generated scan?!

Anyway, I have an incoming fix for it.

**Comment by stevespringett** [comment]
Included in v3.1.0. Closing.
