### ISSUE TITLE
Support for tags in the policy conditions.

### ISSUE THREAD

**Issue by VinodAnandan** [DependencyTrack/dependency-track#1565]
Organizations may have different attributes/tags associated (e.g: risk, network connectivity, etc.) with a project. They may want to create custom policies to prioritise the findings associated with these projects. Having tag support in the policy will enable this.

### Proposed Behavior:

Policy Test : Log4j version 1.2.3 AND tag=network-internet

**Comment by stevespringett** [comment]
Thanks for the suggestion. Makes sense.

**Comment by AbdelHajou** [comment]
I think this shouldn't be part of the conditions because a condition applies to a specific component. IMO it makes more sense to be able to limit the policy to projects with certain tags, similar to how the "Limit to projects" functionality works now:
![limitto](https://user-images.githubusercontent.com/62144407/166111249-df8d7356-a90b-4b26-bca0-6bec43de1e48.png)

**Comment by nscuro** [comment]
> IMO it makes more sense to be able to limit the policy to projects with certain tags

That's a good point actually. Maybe we should have something like "Project Selectors" which allow you to match on multiple project fields, including group, name, version etc., but also tags and properties. This could be useful in other areas as well, like alerts ("send notifications for all projects having the `production` tag") and potentially ACLs ("team X has access to all projects of group `com.example.teamx`").

**Comment by sahibamittal** [comment]
'Limit to Tags' sounds good idea and would allow more branched filtering on policies and projects.
I checked and it is feasible to add this feature following the path of 'Limit to projects'. 
I would like to work on implementing this and test if it helps.

**Comment by nscuro** [comment]
Implemented in #1694.
