### ISSUE TITLE
Cannot add active directory users with 

### ISSUE THREAD

**Issue by luidoc** [DependencyTrack/dependency-track#1575]
### Current Behavior:

Dependency Track LDAP using Active Directory is working correctly for authentication with DA users. It works fine for users that don't have characters like a comma in the DN. In these cases, the DA escapes the comma with a backslash and when adding it in the Dependency-Track it indicates "INVALID" in the "Distinguished name" field.

### Steps to Reproduce:
Create a user in active directory: samAccountName=user01 and with a comma in the DN. For example CN=LastName\\, FirstName, OU=my ou, DC=domain, DC=local
Try to add this user in Access Management->LDAP Users->+Create User.  Entry user01 in "username" field. Push button Create.
The user is added, but the text "INVALID" appears in the "Distinguished name" field, and the user cannot log in.

### Expected Behavior:
A user that contains escaped characters in their DN must be able to log in.

### Environment:
  
  - Dependency-Track Version: 4.4.2
  - Distribution:  Docker
  - Database Server:  MSSQL

**Comment by AbdelHajou** [comment]
I wasn't able to reproduce this with an OpenLDAP installation so the issue seems specific to LDAP configurations with Active Directory.
<img width="980" alt="added user" src="https://user-images.githubusercontent.com/62144407/166101017-b71c8e71-d185-4bc8-a3f4-754463f95c9b.png">

**Comment by luidoc** [comment]
If you check line 70 of https://github.com/stevespringett/Alpine/blob/master/alpine-model/src/main/java/alpine/model/LdapUser.java
yo can see  @Pattern(regexp = "[\\P{Cc}]+", message = "The distinguished name must not contain control characters")
This regular expression excludes DNs with backslashes.

Could it be a persistence problem in the database? I'm using Sql Server

**Comment by luidoc** [comment]
Finally I have verified that it is not a problem, it was a configuration error. I had to set ALPINE_LDAP_ATTRIBUTE_NAME=samAccountName and ALPINE_LDAP_AUTH_USERNAME_FORMAT=%s, because in my environment the userPrincipalName values can have different domains.
