### ISSUE TITLE
It is not possible to activate the "National Vulnerability Database" option

### ISSUE THREAD

**Issue by luidoc** [DependencyTrack/dependency-track#1576]
### Current Behavior:
When I disable the "Enable National Vulnerability Database mirroring" option within Administration->Vulnerability Sources->National Vulnerability Database, if I subsequently try to check the option again by setting the url to "https://nvd.nist.gov/feeds" and pressing the update button, the change is not made. When re-entering this menu option the changes do not appear.

### Steps to Reproduce:
Go to the "National Vulnerability Database" option in the Administration->Vulnerability Sources menu.
Uncheck the "Enable National Vulnerability Database mirroring" checkbox, click the "Update" button.
Navigate to any other menu option.

Return to the "National Vulnerability Database" option in the Administration->Vulnerability Sources menu. Check that the check is unchecked and the "NVD Feeds URL" field has no value.
Mark the check "Enable National Vulnerability Database mirroring", write in the "NVD Feeds URL" field the url "https://nvd.nist.gov/feeds" and press the "Update" button.
Navigate to any other menu option.

Return to the "National Vulnerability Database" option in the Administration->Vulnerability Sources menu. It is verified that the check is unchecked again and the "NVD Feeds URL" field has no value.

### Expected Behavior:
It is expected that by checking the "Enable National Vulnerability Database mirroring" checkbox, typing a url in the "NVD Feeds URL" field and clicking the "Update" button, the changes will be saved and remain.

### Environment:
  
  - Dependency-Track Version: 4.4.2
  - Distribution:  Docker
  - Database Server:  MSSQL

### Additional Details:

When you press the update button, using the "Developer tools" of the browser, you can verify that this message is always sent in the post petition:
[{"groupName":"vuln-source","propertyName":"nvd.enabled","propertyValue":null},{"groupName":"vuln-source","propertyName":"nvd.feeds.url ","propertyValue":null}]
when it should be:
[{"groupName":"vuln-source","propertyName":"nvd.enabled","propertyValue":true},{"groupName":"vuln-source","propertyName":"nvd.feeds.url","propertyValue":"https://nvd.nist.gov/feeds"}]

If you run this call with curl, the changes are made:
curl --location --request POST 'https://url-api/api/v1/configProperty/aggregate' \
--header 'Authorization: Bearer xxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '[{"groupName":"vuln-source","propertyName":"nvd.enabled","propertyValue":true},{"groupName":"vuln-source","propertyName":"nvd.feeds.url","propertyValue":"https://nvd.nist.gov/feeds"}]'

**Comment by stevespringett** [comment]
Duplicate of https://github.com/DependencyTrack/frontend/issues/137

**Comment by nscuro** [comment]
Fixed in DependencyTrack/frontend#143.
