### ISSUE TITLE
error in behavior when uploading a BOM

### ISSUE THREAD

**Issue by redaabdellah21** [DependencyTrack/dependency-track#1579]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
uploading a BOM file when dependencies already exist causes them to disappear

### Steps to Reproduce:
- create a project.
- add a component.
- upload a bom file.

### Expected Behavior:
the component first added will disappear.

### Environment:
  
  - Dependency-Track Version: 4.4.2
  - Distribution: Docker
  - BOM Format & Version: CycloneDX, specVersion : 1.3, version : 1
  - Database Server:  H2 
  - Browser: edge

### Additional Details:
the opposite works. if iupload a BOM before adding a component it works fine and i can see all components.

**Comment by AbdelHajou** [comment]
I think this is intended behavior, the SBOM is considered the source of truth for the components in the project. When uploading a new SBOM, all existing components are removed and the new components are added

**Comment by redaabdellah21** [comment]
@AbdelHajou thank you so much for your response. But what if the information in the SBOM are not enough. in my project we want to check frameworks, database versions, language versions... So how can i add this kind of information?

**Comment by AbdelHajou** [comment]
@redaabdellah21 What you could try doing is to add your databases/frameworks manually, downloading (exporting) the SBOM for those components and then merging that SBOM with the SBOM you generate in your build pipeline. You can use the cyclonedx-cli to merge two SBOM files, so merge the one you generated with the one you exported.

**Comment by redaabdellah21** [comment]
@AbdelHajou i will see how i can do that. really gratefull for your responses. thanks.
