### ISSUE TITLE
Ingesting multiple reports

### ISSUE THREAD

**Issue by adeline-chew-sp** [DependencyTrack/dependency-track#158]
Hi Steve, I'm current configuring the report in Dependency Check for gradle. The project has multiple modules so there will be multiple reports as noted here - https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html

However, Dependency-Track can only ingest one report at a time, what is the recommended approach to get all the reports published?

**Comment by stevespringett** [comment]
Closing
