### ISSUE TITLE
How to use Slack channel for Dependency Track?

### ISSUE THREAD

**Issue by phanisrirs8** [DependencyTrack/dependency-track#1590]
Is there any Slack Email ID for Dependency Track? Please help me how to ask questions using slack.

**Comment by valentijnscholten** [comment]
If you click this link from the README, you should be able to join the OWASP Slack workspace: https://dependencytrack.org/slack/invite

And then join #proj-dependency-track or click the other link from the README: https://dependencytrack.org/slack

**Comment by phanisrirs8** [comment]
Thank you for your Response.
