### ISSUE TITLE
Upload Dependency-Check XML/HTML report manually to Dependency-Track

### ISSUE THREAD

**Issue by quentinkhoo** [DependencyTrack/dependency-track#160]
Is there a way to do the aforementioned in the title? I don't seem to see any options which would allow me to import my own XML report generated by Dependency-Check into Dependency-Track.

**Comment by zuhalv** [comment]
Hi,
I have the same issue, could you please help about this issue?
Thank you

**Comment by stevespringett** [comment]
Dependency-Track is designed to be use in a continuous integration/delivery environment and has much more functionality available via its REST API than it does via the UI. ( The UI is actually a simplified client to the REST API but the API is more feature complete )

Using the Dependency-Check Jenkins plugin is the easiest way to publish dependency-check-report.xml to Dependency-Track. If you're not using Jenkins or want to manually upload it, you'll still need to leverage the REST API.

Refer to https://docs.dependencytrack.org/usage/cicd/ for examples on how to do this using curl.

**Comment by stevespringett** [comment]
@mikezhu8 payload.json should simply be the text representation of the json to be sent to the server. Its the exact same payload as you would send otherwise only that you're referencing a file of where the payload resides rather than supplying the content of the payload on the command line.

**Comment by mikezhu8** [comment]
@stevespringett 
Does the payload.json include project info? If not how to pass 'project' to dependency track server for where to put the dependency check result in? Can you please provide a sample of payload.json file?

**Comment by stevespringett** [comment]
@mikezhu8 Yes, the payload contains the project. The docs have examples of both scan and bom payloads. Here's the example of the scan payload:

```json
{
  "project": "f90934f5-cb88-47ce-81cb-db06fc67d4b4",
  "scan": "PD94bWwgdm..."
}
```

**Comment by Bojanits** [comment]
Hi @MichaelGissingNC, I tried to run your script with my params and I get the following error: 

base64: invalid option -- w
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)

any help would be greatly appreciated.

**Comment by eastmadc** [comment]
@Bojanits - the version of your base64 (OS/X?) doesn't have the -w (wrap) option.  That's ok, just use: 

`  "scan": "$(cat depcheck/dependency-check-report.xml |base64 -)"`

**Comment by Arunraj89** [comment]
@Bojanits : you can try the below code, it works for me.

`cat > payload.json <<__HERE__
{
  "project": "2621e83c......",
  "scan": "$(cat dependency-check-report.xml |base64 -)"
}
__HERE__

curl -X "PUT" "http://localhost:8080/dtrack/api/v1/scan" \
     -k \
     -H 'Content-Type: application/json' \
     -H 'X-API-Key: fgtr845th89y.....' \
     -d @payload.json`

**Comment by dancornell** [comment]
Here's a crappy (may only work on my machine) Python 3.7 script to wrap the upload process. Need to clean up the #! on the first line and a couple of other things then I'll try to find a home for it. Doesn't properly handle HTTPS servers and has some other issues, but may be a good starting point for folks looking for a more general solution to do uploads across projects, servers, API keys, etc.

#!/usr/local/bin/python3

import argparse
import base64
import http.client
from urllib.parse import urlparse

api_endpoint = 'api/v1/scan'

parser = argparse.ArgumentParser()

parser.add_argument("server", help="Dependency Track server URL")
parser.add_argument("project", help="Dependency Track project")
parser.add_argument("api_key", help="Dependency Track API key")
parser.add_argument("file", help="File to upload to Dependency Track")

args = parser.parse_args()

print ('Server: ' + args.server)
print ('Project: ' + args.project)
print ('API key: ' + args.api_key)
print ('File: ' + args.file)

file = open(args.file, 'rb')
file_contents = file.read()

base64_string = base64.b64encode(file_contents).decode('ascii')

print ('Base64File: ' + str(base64_string))

target_url = args.server + api_endpoint

print ('API endpoint: ' + target_url)

json_str = '{"project": "' + args.project + '", "scan": "' + str(base64_string) + '"}'

my_url = urlparse(target_url)

hostname = my_url.netloc.split(':', 1)[0]

print ('Netloc: ' + my_url.netloc)
print ('Hostname: ' + hostname)
print ('Port: ' + str(my_url.port))
print ('Path: ' + my_url.path)

headers = {'Content-Type': 'application/json', 'X-API-Key': args.api_key}

conn = http.client.HTTPConnection(hostname, my_url.port)
conn.set_debuglevel(1)
conn.request("PUT", my_url.path, json_str, headers)
response = conn.getresponse()
print (response.status, response.reason)

data = response.read()
print (str(data))

**Comment by sebastienbianco** [comment]
Hello,

I trying to use Dependency-track to have an overview of a set of projects. I first try with a single (big) project.

I succeed to generate a report with Depency-Check maven plugin. I generate all format output and  when I open the XML result, I see some vulnerabilities listed.

```
cat dependency-check-report.csv| wc -l
1219

grep -o '<vulnerability source=' dependency-check-report.xml  | wc -l
1218
```


Then I trying to import thoses results in Dependency-track. I use the trick listed in this track to generate my payload from the xml report and PUT it by curl.
In the interface, the dependencies appear after few minutes, but the vulnerabilities are not listed...

```
 cat > payload.json <<__HERE__                                                                                                                                                                      
 {
   "project": "7ba941bf-3446-4ed9-b9d9-27f30152d6a2",
   "scan": "$(cat dependency-check-report.xml  |base64 -w 0 -)"
 }
 __HERE__
 
 curl -X "PUT" "http://<somewhere>/dependency-track/api/v1/scan" -H 'Content-Type: application/json' -H 'X-API-Key: lmOOdrmPXAZPodmW0PpwxKGpodreU9o1' -d @payload.json
```

I also tryed by using "import BoM", but I had the same result.

**Did I miss something ?**

NB : 
- I use :
  - Dependency-Track v3.3.1 (Build ID: 5dc0f195-9f5b-4b57-ae99-8a39c1a4ecd5)
  - Dependency-Check v4.0.2 (only Maven check, retire.JS is disabled)
 
- My generated XML report weight 11Mo
- My Dependency-Track instance is totally offline (so no access to any vulnerability database or to maven central)
- I create a mirror of nist DB and use it with Dependency-Check but I don't find how to link it to dependency-track.

Regards,

**Comment by stevespringett** [comment]
Dependency-Track requires access to the Internet. Dependency-Track includes NVD mirroring functionality already. You can point Dependency-Check instances to the Dependency-Track mirror. Track also needs access to public repositories (Maven, NPM, RubyGems, etc) to outdated version detection as well as to use other sources of vulnerability intelligence (OSSIndex, NPM Audit, etc).

**Comment by sebastienbianco** [comment]
Thanks confirming what I thought. 

In this condition, it will be hard to use it when company force strong network restrictions !

**Comment by mkkeffeler** [comment]
looks like since this the /scan endpoint was deprecated and removed, is there a pattern today for uploading scans from check to track?

**Comment by scolytus** [comment]
@mkkeffeler Very short answer: No.

Bit longer: It just doesn't make sense any more.

Please see "I updated Dependency Track and now I can not upload Dependency-Check reports" in the [FAQ](https://docs.dependencytrack.org/FAQ/) and the [Dependency-Check Comparison](https://docs.dependencytrack.org/odt-odc-comparison/)

**Comment by mkkeffeler** [comment]
Yeah, ended up seeing the other issues. just was hard to find :) thanks.
