### ISSUE TITLE
NEW_VULNERABLE_DEPENDENCY notification not working

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#1611]
While working on adding policy violation support to notifications, I realized that the NEW_VULNERABLE_DEPENDENCY notification doesn't work at all and is not hooked up to anything. This is likely a result from the data model migration from 3.x to 4.x, but it's interesting that it hasn't been reported.

**Comment by AbdelHajou** [comment]
I noticed this when testing Dependency-Track for the first time but I thought I had something misconfigured. Any pointers on where this issue could be fixed?

**Comment by stevespringett** [comment]
Its targeted for v4.6

**Comment by pimschrama** [comment]
I also thought it was a misconfiguration. Could you add a notification graph to the dashboard? So that we can check if a notification was sent.

**Comment by nscuro** [comment]
Does the notification even make sense anymore? 

* `NEW_VULNERABILITY` already fires when `NEW_VULNERABLE_DEPENDENCY` would be fired
* `NEW_VULNERABLE_DEPENDENCY` includes a list of projects where the dependency was introduced, which, based on the new component model, doesn't make sense anymore, since component identity is now bound to individual projects

**Comment by Kretikus** [comment]
The default notification template only includes the affected PROJECT(s) on the event NEW_VULNERABLE_DEPENDENCY.

Is it possible to show the affected Project(s) also on NEW_VULNERABILITY?

**Comment by redaabdellah21** [comment]
@Kretikus yes you can list the affected project(s) when getting a NEW_VULNERABILITY. 
check this: https://docs.dependencytrack.org/integrations/notifications/

**Comment by redaabdellah21** [comment]
@pimschrama i agree, since there is nothing that indecates if a notification was sent or not, you can't be sure if you configured it right. in my case i thought maybe it was me who didn't understand when the notification is triggered.
