### ISSUE TITLE
Add support for private Azure Artifacts packages

### ISSUE THREAD

**Issue by AbdelHajou** [DependencyTrack/dependency-track#1618]
### Current Behavior:
The system only supports public package repositories. When scanning for outdated components, private components are ignored and are not shown as outdated. 
![image](https://user-images.githubusercontent.com/62144407/168191448-6fe5e332-160d-47b0-99ae-8a3deaa9d3aa.png)

### Proposed Behavior:
My company uses Azure Artifacts to store private packages. Azure Artifacts is a universal package repository, meaning it can store packages for multiple ecosystems (currently nuget, npm, maven and python). Unfortunately there is no standardized authentication protocol for private package repositories, otherwise it would be possible to implement this functionality for every private package repository. However, I think Azure Artifacts would be a great first step. 

Azure Artifacts can be accessed through the Azure DevOps REST API. For access the user would need to provide a Personal Access Token with the "Packaging (read)" scope. OAuth 2.0 authorization is supported as well, but for this the user would need to configure OIDC integration with Azure AD as well. 

One limitation of the API is that it doesn't support querying for packages by name, which is what Dependency-Track currently does for all other package repositories. Instead there is an endpoint for querying all packages within an Azure DevOps organization. The existing RepositoryMetaAnalyzer scans each package one by one, which would not be possible for this API. A workaround for this would be to add a task that retrieves the latest versions for packages periodically and stores these in the database. The RepositoryMetaAnalayzer could then query a single component via the database.

The implementation for this should be made as generic as possible so that it would be possible for other contributors to add support for other (private) package repositories. If you agree that this feature would be an enhancement to the project, I would like to work on implementing it. I've already developed a prototype that demonstrates that it's feasible.

**Comment by stevespringett** [comment]
In the case of npm and Maven for example, wouldn't Azure Artifacts have to implement the native protocol and conventions of npm and Maven? If they didn't npm and Maven dependency resolution would not work.

Dependency-Track already allows users to add their own private repositories. So if Azure Artifacts supports Maven, then add it to the Maven repository settings in Dependency-Track. Same for npm, nuget, and any other ecosystem. This seems to be the exact same use case that users of Sonatype Nexus Repo, JFrog Artifactory, and GitHub Packages use today.

**Comment by AbdelHajou** [comment]
> In the case of npm and Maven for example, wouldn't Azure Artifacts have to implement the native protocol and conventions of npm and Maven? If they didn't npm and Maven dependency resolution would not work.

@stevespringett That's a good point actually, I hadn't considered that.

> Dependency-Track already allows users to add their own private repositories. 
I can't seem to find this option in my Dependency-Track instance, when adding a repository it doesn't ask for a Personal Access Token (even when Internal is selected). Am I missing something?
<img width="603" alt="afbeelding" src="https://user-images.githubusercontent.com/62144407/168427402-fc93e62a-b6a0-49fe-a43f-16ec8ea74c8d.png">

**Comment by AbdelHajou** [comment]
I see #1311 has been opened to solve this, but it has been inactive for 6 months and has merge conflicts. If the original author contributor wont finish it I would like to pick it up if that is OK with you.

**Comment by stevespringett** [comment]
That would be great @AbdelHajou.

**Comment by msymons** [comment]
This issue thus seems to duplicate #881
