### ISSUE TITLE
Creating an internal vulnerability without CWE results in internal error

### ISSUE THREAD

**Issue by dlancho** [DependencyTrack/dependency-track#1664]
### Current Behavior:
When creating a new internal vulnerability without CWE the process seems to work, but every time that that vulnerability is listed as a vulnerability in a project, then VEX data cannot be exported and vulnerabilities are not listed in the audit tab. In the log of the docker the following message can be seen:
```
2022-05-27 14:29:20,421 WARN [CollectionIntegerConverter] Unable to convert value to Integer
java.lang.NumberFormatException: For input string: ""
```

This happens also every time that the vulnerability is edited and the "update" button is clicked and whenever the vulnerability is shown in a list.

### Steps to Reproduce:
Create an internal vulnerability but do not assign a CWE. Assign a CPE of a component in a project and wait until that project is updated with the new vulnerability.

### Expected Behavior:
If a CWE is required then the creation process should fail. If a CWE is not required then there should be no error when listing it.

### Environment:
  
  - Dependency-Track Version: 4.5.0 and 4.5.1 frontend
  - Distribution: Docker
  - BOM Format & Version:
  - Database Server: PostgreSQL
  - Browser: Edge

### Additional Details:

Related to: https://github.com/DependencyTrack/dependency-track/issues/1655

**Comment by nscuro** [comment]
Thank you for the detailed description @dlancho. I was able to reproduce and fix the issue.
