### ISSUE TITLE
Session management issues when opening secondary tabs in browser

### ISSUE THREAD

**Issue by cosmin91ro** [DependencyTrack/dependency-track#167]
When opening a link (e.g. from Vulnerabilities page) in new tab, application ask for login again and even after submitting credentials, the page content is not fully loaded. Page refresh is required in order the content to be displayed

![image](https://user-images.githubusercontent.com/13283745/41341335-2c2689a0-6f02-11e8-8429-589d701f8475.png)
![image](https://user-images.githubusercontent.com/13283745/41341433-5c7be05a-6f02-11e8-893a-fc31bd8603cc.png)
![image](https://user-images.githubusercontent.com/13283745/41341469-71f32af6-6f02-11e8-9e1d-6ae4cdd171ef.png)

**Comment by stevespringett** [comment]
Thanks for reporting. I've replicated the issue and will attempt to get it pushed prior to the 3.1.0 launch today,

**Comment by darkblinded** [comment]
Is there a reason why one has to login again when opening links in a new tab?

**Comment by stevespringett** [comment]
@darkblinded This is a security control. In traditional sessions, leaving a browser running with no active window will still allow someone to open a new window and be authenticated to the app. This is especially problematic on Linux and Mac where the display of the window doesn't have any relation to the running of the browser engine, and is a known issue when organizations use shared computers.  In addition, this approach can prevent specific types of CSRF and login detection attacks.
