### ISSUE TITLE
Installation instructions broken

### ISSUE THREAD

**Issue by hohwille** [DependencyTrack/dependency-track#1671]
### Current Behavior:
Your installation instructions are broken.
The actual error was made by github when they updated their TLS certificates and broke *ALL* raw content views.
So if you go to https://github.com/DependencyTrack/dependency-track/blob/master/src/main/docker/docker-compose.yml
and click an raw, you end up here: https://raw.githubusercontent.com/DependencyTrack/dependency-track/master/src/main/docker/docker-compose.yml

This page currently has a TLS certificate matching to domain `*.github.io` but not to `raw.githubusercontent.com`.
Therefore you get an TLS error and browser prevents downloading the content.
As a result the `curl` command from your instructions downloads `HTML` garbage instead of valid `YAML` content.

### Steps to Reproduce:
1. open https://dependencytrack.org/
2. click download or scroll down to `Installation`
3. follow installation instructions
4. error

### Expected Behavior:
Correct `YAML` gets downloaded and docker compose up can understand it and launch dependency track.

### Environment:
  
  - Dependency-Track Version: *
  - Distribution: Docker
  - BOM Format & Version: *
  - Database Server: *
  - Browser: firefox, curl

**Comment by nscuro** [comment]
Can't reproduce. 

While `*.github.io` is the certificate's subject name, it also has loads of alternative names, including `*.githubusercontent.com`:

![Certificate](https://user-images.githubusercontent.com/5693141/170944918-94b58c7c-3048-4201-b59f-533ffa7fdb1f.png)

Maybe an issue with your corporate proxy?

**Comment by hohwille** [comment]
Github already fixed it. It is working today on my end as well.
