### ISSUE TITLE
Separate project (version) creation  from generic portfolio management permission

### ISSUE THREAD

**Issue by aikebah** [DependencyTrack/dependency-track#168]
For Continuous Integration environments it would be beneficial if project(version) creation was separated from the remainder of the portfolio management tasks.

I would not like to have CI build tools to throw away existing projects, but I would like to have them able to create new projects and versions of projects as they appear without a need for a portfolio admin to predefine the version.

Making project(version) creation a separate permission would allow for this:
Grant that new permission to e.g. the Automation group and configure the scan- or BoM upload in the CI tool with an appropriate projectName, projectVersion and autoCreate set to true.

**Comment by stevespringett** [comment]
@aikebah thanks for the suggestion. I agree, having finer-grained permissions would be ideal.

Currently, PORTFOLIO_MANAGEMENT is a high-level permission used for:

- Creating, modifying, deleting projects
- Creating, modifying, deleting components
- Creating and deleting dependency relationships between components and projects
- Refreshing portfolio, project, component, and dependency metrics
- Creating (and soon), modifying, and deleting internally-managed vulnerabilities

I don't want to go down the path of breaking up PORTFOLIO_MANAGEMENT into all of it's possible finer-grained permissions. If this was done, you're CI example would require:

- Create project
- Create component
- Create and delete dependency

So four permissions would be required and it wouldn't be obvious which ones would be needed. It would also likely lead to an influx of tickets.

But I think if we left PORTFOLIO_MANAGEMENT the way it is, and add a CREATE_PROJECT permission, that would likely satisfy your use-case. Can you confirm?

**Comment by aikebah** [comment]
@stevespringett Seems to me that it would indeed satisfy my use-case. My main reason for suggesting the separation is that it might be less obvious to users that those same rights are granted by the PORTFOLIO_MANAGEMENT permission.
However it wouldn't hurt if they therefor granted both PORTFOLIO_MANAGEMENT and CREATE_PROJECT and I can not think of a use-case where you would want to give PORTFOLIO_MANAGEMENT but leave out the CREATE_PROJECT rights. So just adding a new permission-set appears OK to me as well.
