### ISSUE TITLE
Report difference in Dependency Check and Dependency Track

### ISSUE THREAD

**Issue by adeline-chew-sp** [DependencyTrack/dependency-track#169]
Hi Steve, one of our components, Dependency Check is reporting 3 Normal vulnerabilities. However, when published to Dependency Track, it is reporting 4 vulnerabilities, 1 critical, 2 high, 1 medium.

Dependency Check
![image](https://user-images.githubusercontent.com/10201631/41785136-3ddcb78a-7607-11e8-8ce8-be1ff23ed39e.png)

Dependency Track
![image](https://user-images.githubusercontent.com/10201631/41785313-d0e0d64c-7607-11e8-82bb-62ae9b356f79.png)
![image](https://user-images.githubusercontent.com/10201631/41785197-7059abfa-7607-11e8-83e9-0891841c9e14.png)
![image](https://user-images.githubusercontent.com/10201631/41785344-e98dafb2-7607-11e8-9536-617ccab82a82.png)

Additional vulnerability that wasn't listed in Dependency Check:
![image](https://user-images.githubusercontent.com/10201631/41785255-aabf952a-7607-11e8-840e-72701ece38e1.png)

I was wondering how those vulnerabilities are converted, thank you!

**Comment by stevespringett** [comment]
Dependency-Track operates on the concept of bill-of-materials. It supports CycloneDX and SPDX BoM formats. Dependeny-Check XML reports also contain a BoM, which Dependency-Track can import.

When Dependency-Track imports a Dependency-Check report, it will import the BoM (all the components), and assign the included vulnerabilities identified in the report, in your case, 3.

Once a BoM has been imported into Dependency-Track, the system will scan all the components and will continue to do so every 24 hours , or whenever the BoM for the project changes. These are independent scans internal to Dependency-Track. Dependency-Track uses Dependency-Check along with it's own internal scanner (for NPM).

If your Jenkins job had suppressed findings, those suppressions do not carry over to Dependency-Track.  Dependency-Track supports a Dependency-Check style global suppressions file, and it supports per project and global audit workflow.

**Comment by stevespringett** [comment]
Closing
