### ISSUE TITLE
Add badge for policy violations

### ISSUE THREAD

**Issue by tmehnert** [DependencyTrack/dependency-track#1690]
### Current Behavior:
Currently, I can only create badges for vulnerable components of a project.

### Proposed Behavior:
I would like to create badges for policy violations of a project as well. I would place the badges in our gitlab project so all developers know the current status of the default branch. This works well with vulnerable components, so it would be nice to also have a badge for policy violations.

![project-vio](https://user-images.githubusercontent.com/92546601/172199727-614256d3-651f-43f6-8c88-ca42958222b3.svg)
![project-vio-none](https://user-images.githubusercontent.com/92546601/172199766-f7b6b8a3-4a29-455c-a360-106a17d2d09e.svg)
![project-vio-nometrics](https://user-images.githubusercontent.com/92546601/172199784-62d5f49e-3410-4061-8ae9-3bc1a0219b77.svg)

**Comment by jeggers-88** [comment]
This sounds reasonable, would be a great feature!

**Comment by nscuro** [comment]
Implemented in #1691.
