### ISSUE TITLE
Use jCasbin instead of Shiro for authorization

### ISSUE THREAD

**Issue by veotax** [DependencyTrack/dependency-track#171]
[jCasbin](https://github.com/casbin/jcasbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.
4. multiple models like ACL, BLP, RBAC, ABAC, RESTful are supported.

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

This project uses Shiro as authorization. The problem of Shiro is that for every call, you have to decorate it with the same ``@RequiresRoles`` grammar, I can see a lot of such code here: https://github.com/DependencyTrack/dependency-track/commit/a8590966cafb5703dfdd581faad627f811c6ace2. With jCasbin, you can remove most of these decorations. Just group the similar RESTful paths and setup an authorization rule for those paths. So the readability and maintainability can be improved. What do you think? Thanks.

**Comment by stevespringett** [comment]
Actually, this project no longer uses Shiro, and hasn't in over two years. 

In addition, having the permissions required for authorization in the same place as the automatically generated Swagger/OpenAPI docs containing those permissions, is actually preferred.
