### ISSUE TITLE
Audit table not reflecting the correct values for Analysis and Suppressed columns

### ISSUE THREAD

**Issue by swright787** [DependencyTrack/dependency-track#172]
I recently marked some items as false positives and suppressed the items however they are still showing in the auditing table as not being marked as such. I tired to clear my cache, delete the project and this still did not resolve the issue.

I am currently using the latest version of Dependency Track (v3.1.1)

![2018-07-03 13_42_04-dependency-track - project details](https://user-images.githubusercontent.com/40796327/42220527-2103f510-7ec7-11e8-86c4-b506c06536f8.png)

Update: Looking at the ANALYSIS database table, it looks like only the 1 reported issue is being set in this table.

Managed to track the issue down to the SQL query from the Finding.QUERY (https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/owasp/dependencytrack/model/Finding.java). The last left join on the ANALYSIS table is creating the duplicate entries, since there are other entries associate with other projects. The join should include the project ID as well.

**Comment by stevespringett** [comment]
@swright787 thanks for the report and a big thanks for discovering where the flaw resides along with recommendation on how to fix. I've replicated the issue and believe I have a fix ready.
