### ISSUE TITLE
License information supports only one format

### ISSUE THREAD

**Issue by kishankarun** [DependencyTrack/dependency-track#1757]
### Current Behavior:
The license information provided in only one format is displayed in the dependency track tool

Only the below formatted license information is displayed

```
"licenses": [
        {
          "license": {
            "id": "Apache-2.0",
            "text": {
              "contentType": "text/plain",
              "encoding": "base64",
              "content": "CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA..."
            },
            "url": "https://www.apache.org/licenses/LICENSE-2.0.txt"
          }
        }
      ]
```

License information provided in SBOM reports in the following format is not displayed

```
"licenses": [
        {
          "expression": "EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0"
        }
      ]
```

### Steps to Reproduce:
SBOM Format provided by Syft tool ( https://github.com/anchore/syft ) is supported, 

![image](https://user-images.githubusercontent.com/323202/176109158-7bcb7279-1a29-4ff9-90e4-cb088db8538a.png)

SBOM format provided by Trivy tool (https://github.com/aquasecurity/trivy ) is not supported.

![image](https://user-images.githubusercontent.com/323202/176109043-227a76db-b2d6-452f-95bd-ba2b33a662e5.png)

Trivy support only format 2 as per this issue raised.

https://github.com/aquasecurity/trivy/issues/2354

### Expected Behavior:

License information of all formats mentioned in CycloneDx documentation should be supported.

https://cyclonedx.org/docs/1.4/json/#tab-pane_services_items_licenses_items_oneOf_i0

### Environment:
  
  - Dependency-Track Version:   v4.5.0
  - Distribution: Docker
  - BOM Format & Version: JSON 
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]
  - Browser: Chrome

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by msymons** [comment]
Seems to duplicate #170
