### ISSUE TITLE
"Add new version" feature

### ISSUE THREAD

**Issue by darkblinded** [DependencyTrack/dependency-track#176]
When creating new versions of projects or components, metadata like name, tags, group/vedor, license etc. will most likely not change. Therefore I propose to add a feature to create a new version from an existing object.

For _components_ this should at least copy:
* Name
* Group/Vendor
* Descripion
* License
* Classifier

For _projects_ this should at least copy:
* Name
* Description
* Tags

Maybe this should also include audit results, at least for False Positives. I get a lot of them, due to wildcard-CPEs beeing used for missing version-CPEs.

**Comment by stevespringett** [comment]
Completely agree. This is one feature that the original v1.0 release had that I wish made its way to the current v3.x codebase. This is especially important for projects, and I'd also like to see audit history cary over.

**Comment by stevespringett** [comment]
I'm going to try to get this added to v3.3. I think it's important to include audit results etc as part of adding a new version as there's typically a lot of manual effort that goes into that activity.

Also note about the false positives, in v3.2 you can completely disable Dependency-Check if you want if you're using a BoM approach, which will give you much more accurate results. I have yet to see false positives from OSSIndex or NPM Audit, but they may miss environmental findings that Dependency-Check can possibly find (with noise as the trade-off).

**Comment by stevespringett** [comment]
The backend services and API now support project cloning.  It accepts a JSON payload such as 

```json
{
  "project": "54b01720-cb24-42f7-92d6-841370ad3154",
  "version": "3.0",
  "includeTags": true,
  "includeProperties": true,
  "includeDependencies": true,
  "includeAuditHistory": true
}
```

Where `project` is the UUID of an existing project to clone and `version` is the version of the new project being created.

The cloning is performed asynchronously since it may take awhile depending on the number of objects being cloned. I plan on adding a UI metaphor to trigger the cloning prior to the release of 3.3.
