### ISSUE TITLE
OpenID Login Button does not show

### ISSUE THREAD

**Issue by lsauer** [DependencyTrack/dependency-track#1795]
### Current Behavior:
The OIDC Button does not show.

### Steps to Reproduce:
I have configured everything as laid out here https://docs.dependencytrack.org/getting-started/openidconnect-configuration/ and the OpenID Login Button does not show.

![image](https://user-images.githubusercontent.com/996117/179500820-cd072da2-b804-4672-af18-1547b46fda79.png)
![image](https://user-images.githubusercontent.com/996117/179500887-6d2cd2cd-3a5e-4bc3-93bb-54c6f04e1c27.png)
![image](https://user-images.githubusercontent.com/996117/179501183-6b80052f-2790-41ce-9d4c-9f9e411bca3e.png)

I have set all required paramters and everything in the config.json / Parameters as well. 

When I docker exec a printenv into the API container I cannot see the OIDC_ENABLED option but assume that this var is reset somwhere.

### Expected Behavior:
The OIDC Button should show as soon as the ALPINE_OIDC_ENABLED=true is set in the image

### Environment:
  
  - Dependency-Track Version: 4.5
  - Distribution: [ Docker | Executable WAR | Traditional WAR ]: Docker
  - BOM Format & Version: -
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]: H2
  - Browser: current EDGE, Firefox

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by lsauer** [comment]
The container was recreated afterwards. I am using the docker-compose stack.
There are no OIDC errors. Keycloak creates a session for the OIDC "client" which I called dtrack-client.

I ended up making the button visible through css, yet as no matter what I tried, I could not get it to show up any other way.

There are no unresolved files as far as I can see in the web-dev console: network, and no complaints in the docker log from the api-server.

I cannot get OIDC to work. This has probably to do with that VUE.JS does not know about the contextPath. 
There is a function in Vue.js called getContextPath(). 
The log is as follows
```bash
dtrack-apiserver_1  | 2022-07-20T18:37:45.613767299Z 2022-07-20 18:37:45,613 INFO [MetricsUpdateTask] Completed metrics update on vulnerability database
dtrack-frontend_1   | 2022-07-20T18:53:07.971480591Z 172.18.165.150 - - [20/Jul/2022:18:53:07 +0000] "GET /img/dt-logo-vertical-white-text.fe7a49e8.svg HTTP/1.0" 304 0 "https://idesuite-test.hlb.de/dtrack/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:07.973314229Z 172.18.165.150 - - [20/Jul/2022:18:53:07 +0000] "GET /img/openid-logo.705c93cd.svg HTTP/1.0" 200 7733 "https://idesuite-test.hlb.de/dtrack/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:12.577495846Z 172.18.165.150 - - [20/Jul/2022:18:53:12 +0000] "GET /static/oidc-callback.html?state=2662284ae79c4665a288b2a74bb1984c&session_state=f57f3da3-5693-4fa3-b748-fbdd048e356b&code=8ace46c9-919b-4d3e-a136-5456f869624e.f57f3da3-5693-4fa3-b748-fbdd048e356b.d34afdfd-0f78-40ec-ba08-dd95fdd10574 HTTP/1.0" 200 2296 "https://idesuite-test.hlb.de/dtrack/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:12.620773279Z 172.18.165.150 - - [20/Jul/2022:18:53:12 +0000] "GET /static/js/axios.min.js HTTP/1.0" 200 19157 "https://idesuite-test.hlb.de/static/oidc-callback.html?state=2662284ae79c4665a288b2a74bb1984c&session_state=f57f3da3-5693-4fa3-b748-fbdd048e356b&code=8ace46c9-919b-4d3e-a136-5456f869624e.f57f3da3-5693-4fa3-b748-fbdd048e356b.d34afdfd-0f78-40ec-ba08-dd95fdd10574" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:12.684760051Z 172.18.165.150 - - [20/Jul/2022:18:53:12 +0000] "GET /static/js/oidc-client.min.js HTTP/1.0" 304 0 "https://idesuite-test.hlb.de/static/oidc-callback.html?state=2662284ae79c4665a288b2a74bb1984c&session_state=f57f3da3-5693-4fa3-b748-fbdd048e356b&code=8ace46c9-919b-4d3e-a136-5456f869624e.f57f3da3-5693-4fa3-b748-fbdd048e356b.d34afdfd-0f78-40ec-ba08-dd95fdd10574" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:12.687065823Z 172.18.165.150 - - [20/Jul/2022:18:53:12 +0000] "GET /static/js/axios.min.map HTTP/1.0" 200 3712 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:12.828153969Z 172.18.165.150 - - [20/Jul/2022:18:53:12 +0000] "GET /static/config.json HTTP/1.0" 200 290 "https://idesuite-test.hlb.de/static/oidc-callback.html?state=2662284ae79c4665a288b2a74bb1984c&session_state=f57f3da3-5693-4fa3-b748-fbdd048e356b&code=8ace46c9-919b-4d3e-a136-5456f869624e.f57f3da3-5693-4fa3-b748-fbdd048e356b.d34afdfd-0f78-40ec-ba08-dd95fdd10574" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:41.677427307Z 172.18.165.150 - - [20/Jul/2022:18:53:41 +0000] "GET /dtrack/ HTTP/1.0" 200 3712 "https://idesuite-test.hlb.de/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:41.707812665Z 172.18.165.150 - - [20/Jul/2022:18:53:41 +0000] "GET /css/chunk-vendors.b8f6faa3.css HTTP/1.0" 200 111291 "https://idesuite-test.hlb.de/dtrack/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:41.733594987Z 172.18.165.150 - - [20/Jul/2022:18:53:41 +0000] "GET /css/app.a6c3cdfc.css HTTP/1.0" 304 0 "https://idesuite-test.hlb.de/dtrack/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
dtrack-frontend_1   | 2022-07-20T18:53:41.767211536Z 172.18.165.150 - - [20/Jul/2022:18:53:41 +0000] "GET /js/chunk-vendors.3d3007b1.js HTTP/1.0" 304 0 "https://idesuite-test.hlb.de/dtrack/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0" "9.20.7.93"
```

**Comment by nscuro** [comment]
The frontend performs a request to the API server's `/api/v1/oidc/available` endpoint to determine whether OIDC has been *successfully* configured in the API server. *Successfully* mostly referring to the API server being able to resolve the OIDC configuration (`.well-known/openid-configuration`) from the configured issuer. If this fails, it will be logged. If the API server responds to the frontend with `false`, the OIDC login button will not be shown.

**Comment by lsauer** [comment]
Thanks. I checked this and it seems to be like you said, even though it is a digicert certificate. But perhaps the RCA is a less known one.
Within the API Server: 
`dtrack@febb1449ba40:/opt/owasp/dependency-track$ /usr/bin/wget -k https://idesuite.....de
--2022-07-27 07:25:26--  https://idesuite.....de/
Resolving idesuite.... (idesuite.)... 1*2.**********
Connecting to idesuite. (idesuite.)|1*2.***********... connected.
ERROR: The certificate of ‘idesuite.’ is not trusted.
ERROR: The certificate of ‘idesuite.’ doesn't have a known issuer.
Converted links in 0 files in 0 seconds.
`

How can I fix this?

**Comment by nscuro** [comment]
You need to import the certificate of your IdP into the trust store used by DT's Java runtime. I posted about how to do it yesterday, see https://github.com/DependencyTrack/dependency-track/discussions/1831#discussioncomment-3230180
