### ISSUE TITLE
Include dependencies when downloading the SSOM from project component.

### ISSUE THREAD

**Issue by halaharr** [DependencyTrack/dependency-track#1805]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
Currently when you download the SBOM from Home->Projects-><YourProject>->Components tab dependencies are not included.

### Proposed Behavior:
Please include dependence when downloading the SBOM. Thanks

**Comment by leec94** [comment]
I'd like to take this card on, if it's still relevant. 

I did a test download BOM on my local instance and looks like the components are downloaded, and there is a field called `dependencies` which is an array of objects with `ref` and `dependsOn` keys. What is missing from the current BOM to complete this issue?

**Comment by nscuro** [comment]
Hey @leec94, thanks for stepping up here! 

I think this issue may no longer be relevant; as you identified already, the BOM downloads include the [dependency graph](https://cyclonedx.org/use-cases/#dependency-graph) already. We have tests in place that assert this, e.g.:

https://github.com/DependencyTrack/dependency-track/blob/924a007cd6a37d75a2c4a8ea048814975fb85fcd/src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java#L98-L244

I can't quite remember when the graph was added to BOM downloads, but we definitely missed to close this issue.
