### ISSUE TITLE
Question: Intranet download of CVE data?

### ISSUE THREAD

**Issue by csharpPrgmmr** [DependencyTrack/dependency-track#181]
Can the CVE files be supplied manually if the server cannot pull from the internet?

### Issue Type:
Enhancement / Question

**Comment by stevespringett** [comment]
Dependency-Track requires access to the Internet.

- Mirrors the NVD
- Uses public repos to determine out-of-date components
  - RubyGems
  - Maven Central + 7 other public Maven repos
  - NPM
- Relies on Node Security Platform (NSP) REST APIs to check Node components for vulns
- Next release will additionally use OSSIndex and NPM Audit APIs

NOTE TO SELF: Create documentation that specially calls out this requirement and provides a list of hostnames for which access is required.
