### ISSUE TITLE
Add GitHub as repository

### ISSUE THREAD

**Issue by JN-CSIRT** [DependencyTrack/dependency-track#1825]
We work with OSS sources placed in Github. 
So we need to check the Package for actuality and for security issues.
Is it planned to integrate GitHub as Repository to DT?

**Comment by stevespringett** [comment]
DT should support GitHub Packages. I have not personally tried it, but assuming GitHub implements the proper semantics and APIs for Maven, Pypi, npm, etc, then you should be able to use GitHub for this purpose.

**Comment by JN-CSIRT** [comment]
> DT should support GitHub Packages. I have not personally tried it, but assuming GitHub implements the proper semantics and APIs for Maven, Pypi, npm, etc, then you should be able to use GitHub for this purpose.

Right, it is supported, but for repositories only and it works fine - maven, golang, etc
What's about direct requests to Github? Lot of SW components are placed there without to be integrated into repositories.
E.g. PURL: pkg:github/boostorg/boost@1.67.0
Can you add to DT a direct support for Github.com as repository?

**Comment by stevespringett** [comment]
Ah, so it sounds like you would like support for GitHub Releases. Yes, I think that's something we can do.

Perhaps even make it configurable to enable/disable support for pre-releases when identifying the latest version.

Support for Git branches would be extremely difficult. I wouldn't know how to even approach that.

**Comment by JN-CSIRT** [comment]
> Perhaps even make it configurable to enable/disable support for pre-releases when identifying the latest version.

this is what I look for. At second is the link to the related GHSA if any.

**Comment by lnksz** [comment]
This would be extremely helpful in the C/C++ ecosystem, where there isn't (yet?) a package management system to rule them all!

#1840 looks like a duplicate.

**Comment by lnksz** [comment]
It could be added as a custom repo with the pass being the token maybe?

And then the REST API could be used to fetch the latest version?

https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release
