### ISSUE TITLE
Can't update the dependency-check embedded database with dependency-track

### ISSUE THREAD

**Issue by jblamotte** [DependencyTrack/dependency-track#183]
### Issue Type:
  - [x] defect report
  - [ ] enhancement request
  
### Current Behavior:
When starting dependency-track, i keep getting an error when it update dependency-check.

### Steps to Reproduce (if defect):
Just start dependency-track (i don't know if it's the case for everybody ?), with no specific settings (except mysql database settings)

java -Dalpine.application.properties="/home/dtrack/application.properties" -Xmx4G -jar dependency-track-embedded.war

### Expected Behavior:
Start as expected ;)

### Workaround:
To workaround the issue, and get it to work, i have to copy a "fresh" dc.h2.db from a standalone dependency-check and add the flag "-Dautoupdate=false" to disable update from the embedded dependency check in dependency-track.
I don't have already tested to use a dependency-check external DB, but i think it may fix the issue. (i am just testing the solution for now :) ).

### Environment:
  
  - Dependency-Track Version: 3.1.1
  - Distribution: [Executable WAR]
  - BoM Format & Version:
  - Database Server: [MySQL]
  - Browser: 

### Other Details:
Here the stacktrace : 

17:41:06.245 INFO [DownloadTask] Download Started for NVD CVE - Modified
17:41:06.245 WARN [DownloadTask] Download Failed for NVD CVE - Modified
Some CVEs may not be reported.
17:41:06.245 INFO [DownloadTask] If you are behind a proxy you may need to configure dependency-check to use the proxy.
17:41:06.322 INFO [DownloadTask] Download Complete for NVD CVE - 2003  (78 ms)
17:41:06.329 INFO [ProcessTask] Processing Started for NVD CVE - 2003
17:41:06.520 INFO [DownloadTask] Download Complete for NVD CVE - 2004  (276 ms)
17:41:06.520 INFO [ProcessTask] Processing Started for NVD CVE - 2004
17:41:06.683 INFO [DownloadTask] Download Complete for NVD CVE - 2002  (439 ms)
17:41:06.687 INFO [ProcessTask] Processing Started for NVD CVE - 2002
17:41:06.696 INFO [DownloadTask] Download Complete for NVD CVE - 2005  (452 ms)
17:41:06.698 INFO [ProcessTask] Processing Started for NVD CVE - 2005
17:41:06.869 INFO [DownloadTask] Download Complete for NVD CVE - 2007  (625 ms)
17:41:06.922 INFO [ProcessTask] Processing Started for NVD CVE - 2007
17:41:06.953 INFO [DownloadTask] Download Complete for NVD CVE - 2006  (708 ms)
17:41:06.971 INFO [ProcessTask] Processing Started for NVD CVE - 2006
17:41:06.975 INFO [DownloadTask] Download Complete for NVD CVE - 2008  (731 ms)
17:41:06.988 INFO [ProcessTask] Processing Started for NVD CVE - 2008
17:41:06.994 INFO [DownloadTask] Download Complete for NVD CVE - 2009  (750 ms)
17:41:06.998 INFO [ProcessTask] Processing Started for NVD CVE - 2009
17:41:07.039 INFO [DownloadTask] Download Complete for NVD CVE - 2018  (794 ms)
17:41:07.056 INFO [ProcessTask] Processing Started for NVD CVE - 2018
17:41:07.071 INFO [DownloadTask] Download Complete for NVD CVE - 2015  (826 ms)
17:41:07.072 INFO [ProcessTask] Processing Started for NVD CVE - 2015
17:41:07.086 INFO [DownloadTask] Download Complete for NVD CVE - 2014  (841 ms)
17:41:07.096 INFO [DownloadTask] Download Complete for NVD CVE - 2013  (851 ms)
17:41:07.098 INFO [DownloadTask] Download Complete for NVD CVE - 2012  (853 ms)
17:41:07.103 INFO [DownloadTask] Download Complete for NVD CVE - 2010  (858 ms)
17:41:07.109 INFO [DownloadTask] Download Complete for NVD CVE - 2016  (864 ms)
17:41:07.109 INFO [ProcessTask] Processing Started for NVD CVE - 2012
17:41:07.109 INFO [ProcessTask] Processing Started for NVD CVE - 2014
17:41:07.114 INFO [DownloadTask] Download Complete for NVD CVE - 2017  (869 ms)
17:41:07.114 INFO [ProcessTask] Processing Started for NVD CVE - 2013
17:41:07.115 INFO [ProcessTask] Processing Started for NVD CVE - 2016
17:41:07.131 INFO [ProcessTask] Processing Started for NVD CVE - 2010
17:41:07.137 WARN [DownloadTask] An exception occurred downloading NVD CVE - 2017
Some CVEs may not be reported.
17:41:07.395 INFO [DownloadTask] Download Complete for NVD CVE - 2011  (1150 ms)
17:41:07.395 WARN [DownloadTask] An exception occurred downloading NVD CVE - 2011
Some CVEs may not be reported.
17:41:07.397 ERROR [DependencyCheckTask] An error occurred executing Dependency-Check scan agent
org.owasp.dependencycheck.exception.ScanAgentException: One or more exceptions occurred during analysis; please see the debug log for more details.
	at org.owasp.dependencycheck.agent.DependencyCheckScanAgent.execute(DependencyCheckScanAgent.java:1017)
	at org.owasp.dependencytrack.tasks.scanners.DependencyCheckTask.performUpdateOnly(DependencyCheckTask.java:101)
	at org.owasp.dependencytrack.tasks.scanners.DependencyCheckTask.inform(DependencyCheckTask.java:77)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: Unable to perform update
	The download was interrupted; unable to complete the update
	at org.owasp.dependencycheck.agent.DependencyCheckScanAgent.executeDependencyCheck(DependencyCheckScanAgent.java:910)
	at org.owasp.dependencycheck.agent.DependencyCheckScanAgent.execute(DependencyCheckScanAgent.java:1000)
	... 8 common frames omitted
17:41:07.397 INFO [DependencyCheckTask] Dependency-Check update-only complete

**Comment by jblamotte** [comment]
Yep, i tried a lot's of things like that, but everytime, the error was back. 
The mirrored files look good, and the only way to avoid the error, is to set the property "-Dautoupdate=false", a dependency-check property.

How the embedded dependency-check use the mirrored file ? from file system, or from http ? 
(i use the executable war in a custom docker image)

For now, I am going to try to store the dc.h2.db in a real DB, and keep it updated with a dedicated dependency-check update only (and keep the flag autoupdate=false on dependency-track).

**Comment by stevespringett** [comment]
The internal mirror of the NVD is provided to clients via HTTP/HTTPS. Refer to https://docs.dependencytrack.org/datasources/nvd/

However, the embedded Dependency-Check uses the local file URL to the mirrored directory.

It shouldn't matter, but do you have a proxy server defined?

**Comment by stevespringett** [comment]
Ok thank for confirming. I may try some timing-based tests to see if I can reproduce. 

The alpine config issue can safely be ignored. Nothing to worry about.

**Comment by stevespringett** [comment]
The embedded dependency-check library is being removed from v3.6.0.
