### ISSUE TITLE
API PUT /v1/vex return nullpointerException

### ISSUE THREAD

**Issue by dGuerr** [DependencyTrack/dependency-track#1836]
### Current Behavior:
When uploading a VEX through the api PUT /v1/vex we encounter the NPE shown in the attached picture.

### Steps to Reproduce:
Call API PUT/v1/vex
[outputPath3.txt](https://github.com/DependencyTrack/dependency-track/files/9200023/outputPath3.txt) is a VEX file who has been renamed to .txt
![unexpected](https://user-images.githubusercontent.com/11680935/181274589-b3a5d533-4d0d-41da-85bc-9793c7326fc2.png)

### Expected Behavior:
![expected](https://user-images.githubusercontent.com/11680935/181274493-feb292df-f17d-4d64-a61d-d84ab94549ef.png)

### Environment:
  
  - Dependency-Track Version: 4.5
  - Distribution: Docker
  - BOM Format & Version:  1.4
  - Database Server: PostgreSQL

### Additional Details:
Uploading the same VEX using the GUI is OK. The only difference is that the GUI use the api POST /v1/vex.
Looking at the code of VexResource, we have the following differences :

```java
// POST /v1/vex - https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/resources/v1/VexResource.java#L221
final VexUploadEvent vexUploadEvent = new VexUploadEvent(project.getUuid(), content);
Event.dispatch(vexUploadEvent);
```
```java
// PUT /v1/vex - https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/resources/v1/VexResource.java#L201
final BomUploadEvent bomUploadEvent = new BomUploadEvent(project.getUuid(), decoded);
Event.dispatch(bomUploadEvent);
```

**Comment by nscuro** [comment]
Thanks for reporting @dGuerr! 

This looks an awful lot like the bug @syalioune [reported](https://owasp.slack.com/archives/C6R3R32H4/p1658851036756679) in Slack yesterday. The screenshots look identical, are you two working in the same team by chance?

**Comment by syalioune** [comment]
Hello @nscuro, yeah we work on the same team. I'm guiding @dGuerr through the PR submit process
