### ISSUE TITLE
Dependency track landing page throws error

### ISSUE THREAD

**Issue by Arunraj89** [DependencyTrack/dependency-track#184]
Team, 

When I Up the server and hit the localhost in browser for the first time. I am getting below error:
```
HTTP ERROR 404 
/;jsessionid=nodexxxxxxxxxxxxxxxx.node0/api/v1/metrics/vulnerability
Reason:
Not Found
```
If I click CLOSE and continue to next page also, In the next Home page page loading icon appears and it keep on buffering and not proceeding to HOME dashboard page. 

Help me to resolve the same. Please find the attached screenshot for your reference. I have used WAR file to UP the server.  

### Issue Type:
  - [x] defect report
 
### Current Behavior:
Keep on loading

### Steps to Reproduce (if defect):
Attached screenshot

### Expected Behavior:
Takes me to dashboard page or login page

### Environment:
  
  - Dependency-Track Version: 3.1.1
  - Distribution:  Executable WAR
  - BoM Format & Version:
  - Database Server: H2 
  - Browser: Chrome / IE
![snap 1](https://user-images.githubusercontent.com/16404627/43916531-65d0d4d4-9c2b-11e8-9e9e-7e6d2a7fb272.png)
![snap 2](https://user-images.githubusercontent.com/16404627/43916532-6608680e-9c2b-11e8-90f2-11b04322960b.png)

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
Ensure you’re using a later version of Java 8. Java 11 won’t be supported until next year and 9 and 10 are not supported at all, because they’re non LTS releases.

**Comment by stevespringett** [comment]
If the version of Java is in fact the issue, there's code in the next release that will ensure Java 8 with a minimal update of 162 or higher is being used and will throw a runtime exception with a message stating that.

**Comment by Arunraj89** [comment]
I am using Java 8 update 181. I hop[e it s the latest JAVA 8 release.

**Comment by stevespringett** [comment]
The URL should not have jsessionid nor should it have nodexxxxxxxxxxxxxxxx.node0

I don't know where these are coming from. Are you accessing Dependency-Track through a proxy server perhaps? Maybe the original request is being altered in a way that it's breaking the app?

**Comment by Mazorius** [comment]
Hello @stevespringett ,

I have the same problem with my newly installed Dependency Track.

Here is a screenshot of the application:
![errordependencytrack3 1 1](https://user-images.githubusercontent.com/11423826/44014116-3e5d5b38-9eca-11e8-9ad1-17f3db9772eb.png)

I have a newly installed PostgreSQL DB and also Dependency Track 3.1.1 is, via embedded setup, completely new.

Regards,
Ron

**Comment by Arunraj89** [comment]
I am not using any proxy, I just ran the WAR file 
-jar -Xmx6G Dependency.war
hit the browser with localhost.

**Comment by stevespringett** [comment]
I'm unable to reproduce and I'm not sure why the server is sending back the sessionId on the URL.

As a potential workaround, you can modify WEB-INF/web.xml and add the following snipplet near the end (directly above `</web-app>`.

```xml
    <session-config>
        <session-timeout>1</session-timeout>
        <cookie-config>
            <name>DEPENDENCY-TRACK_JSESSIONID</name>
            <http-only>true</http-only>
            <max-age>0</max-age>
        </cookie-config>
        <tracking-mode>COOKIE</tracking-mode>
    </session-config>
```

So the end of the file should look like:
```xml
    <session-config>
        <session-timeout>1</session-timeout>
        <cookie-config>
            <name>DEPENDENCY-TRACK_JSESSIONID</name>
            <http-only>true</http-only>
            <max-age>0</max-age>
        </cookie-config>
        <tracking-mode>COOKIE</tracking-mode>
    </session-config>

</web-app>
```

You'll have to clear you cache and restart the server. I'd be interested if this resolves the issue or not.

**Comment by Shakyy** [comment]
Just built the current master branch, where the fix is contained, but the problem still occurs.

**Comment by Shakyy** [comment]
For me the problem occurs with default config, but then only once. After refreshing the page everything works well. If I delete website data (cookies, etc.), the problem occurs again for one time.

If I instead use custom configs with deactivated authentication & authorization, the problem remains even after refreshing the page.

**Comment by stevespringett** [comment]
@Shakyy I made one more minor change that may fix this. I'm no longer able to reproduce so hopefully this will do it.

Compile from master, deploy, and ensure you clear your browsers cache.

**Comment by Shakyy** [comment]
@stevespringett Change fixes the error message. When enforcing authentication & authorization now everything works fine. Until logging in, there are some 401 unauthorized messages in chrome developer console. Maybe they are helpful for the still consisting problem without authentication & authorization.
![dtrack_chrome_with_auth](https://user-images.githubusercontent.com/9571773/45085174-5e006280-b100-11e8-9029-c7392f0ec290.png)

When deactivating authentication & authorization, the page loading icon appears again and keeps on buffering.
Console messages in firefox & chrome developer tools - especially the chrome message is pretty precise:
![dtrack_firefox](https://user-images.githubusercontent.com/9571773/45085279-99029600-b100-11e8-930a-c19be09abfd8.png)
![dtrack_chrome](https://user-images.githubusercontent.com/9571773/45085281-99029600-b100-11e8-8d8c-13b737ac1362.png)

**Comment by stevespringett** [comment]
The 401's are normal and expected. These show up with and without authorization enabled. When they're received, the login page is displayed.

Disabling authentication is a feature of the Alpine framework, but it's not actually supported in Dependency-Track. Lots of things won't work correctly when authentication is disabled. 

Since the original issue reported appears to be fixed, I'm going to close this issue. Hopefully it's squashed for good.
