### ISSUE TITLE
problems deleting a project under a policy

### ISSUE THREAD

**Issue by redaabdellah21** [DependencyTrack/dependency-track#1852]
### Current Behavior:
deleting a project will delete the components but not the project. and that happens when there is a policy applied on the project. 
you have to remove the project from the policy project list so you can delete it. 
check the GIF
### Steps to Reproduce:
create a project (with some components) and a policy.
apply the policy on the project. (don't no if there has to be a policy violation or not, better be)
delete the project.

### Expected Behavior:
the project should be removed automatically from the policy list than deleted

### Environment:
  
  - Dependency-Track Version:4.5.0
  - Distribution: [ Docker | Executable WAR | Traditional WAR ] docker
  - BOM Format & Version: cycloneDX 
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ] postgresql
  - Browser: edge

### Additional Details:

Notice that DT is giving stats for 5 projects; even though i only have 2 and that the other 3 are inactive; this also happens even though portfolio access managment is activated. people who can only see 2 projects, still see stats for all the projects in the portfolio.

![msedge_oxebSfdeX8](https://user-images.githubusercontent.com/43956285/182604091-3cfcbb1c-c2d6-46f0-a2cf-3febfcf1c53d.gif)

**Comment by nscuro** [comment]
Thanks for reporting, I'll try to reproduce later today.

> Notice that DT is giving stats for 5 projects; even though i only have 2 and that the other 3 are inactive

That's most likely because the overall portfolio metrics haven't been recalculated since you marked the 3 projects as inactive. Portfolio metrics calculation is an expensive operation (#1210) and only takes place upon explicit request, or hourly. 

> people who can only see 2 projects, still see stats for all the projects in the portfolio.

Correct, it's a known gap in the current ACL implementation. This is tracked in #1682.

**Comment by nscuro** [comment]
Thanks again for the great report @redaabdellah21! I was able to reproduce and fix the issue.
