### ISSUE TITLE
Make path context configurable

### ISSUE THREAD

**Issue by stoneburner** [DependencyTrack/dependency-track#186]
Please make server context path configurable when using  
the embedded version.

### Issue Type:
  - [ ] defect report
  - [x] enhancement request
  
  
### Current Behavior:
The app just starts under localhost:8080/ 

### Expected Behavior:
There is a possibility to set a custom context path by for example passing arguments while starting the embedded version. For example „java -jar dependency-track-embedded.war dt“ would start the application under localhost:8080/dt.

### Environment:
  
  - Dependency-Track Version: 3.1.1
  - Distribution: [ Executable WAR ]

**Comment by stevespringett** [comment]
This is an Alpine enhancement request
https://github.com/stevespringett/Alpine

**Comment by stevespringett** [comment]
The next release of Dependency-Track will include this ability. Alpine executable WAR v1.1.0 now has the following options:

| Argument | Default | Description |
|:---------|:--------|:------------|
| -context | /       | The application context to deploy to |
| -host    | 0.0.0.0 | The IP address to bind to |
| -port    | 8080    | The TCP port the server listens on |

Example:
```bash
# Execute with default options
java -jar dependency-track-embedded.war
```

```bash
java -jar dependency-track-embedded.war -context /dt
```

```bash
java -jar dependency-track-embedded.war -context /dt -host 192.168.1.1 -port 9000
```

**Comment by stoneburner** [comment]
Many thanks!
