### ISSUE TITLE
OSV : replace ecosystem hardcoding with list of ecosystems managed by Google

### ISSUE THREAD

**Issue by sahibamittal** [DependencyTrack/dependency-track#1903]
### Current Behavior: 
For OSV mirroring, we hard code the list of ecosystems to get vulnerabilities.

### Proposed Behavior: 
OSV has enabled a list of ecosystems they maintain -> https://osv-vulnerabilities.storage.googleapis.com/ecosystems.txt

Issue: https://github.com/google/osv.dev/issues/619

### Proposed UI interaction: 
While enabling the OSV mirroring in UI, user can select (list or all) ecosystems to mirror. This will reduce load if all ecosystems are not required.

**Comment by sahibamittal** [comment]
@VinodAnandan @nscuro

**Comment by nscuro** [comment]
Oh wow, that was quick. 😄
