### ISSUE TITLE
More projects shown in affected Projects of Notifications than expected

### ISSUE THREAD

**Issue by niklaskeerl** [DependencyTrack/dependency-track#1914]
I am not sure if this is a enhancement request or defect report.

### Current Behavior:

When I create an alert (Notification) and use the `Limit to` feature, and a notification is fired, I see in the `affectedProjects` field projects which I have not selected in the `Limit to` feature.

### Proposed Behavior:

Add another field or change the current `affectedProjects` field to only include projects which are selected with the `Limit to` feature.

**Comment by redaabdellah21** [comment]
Hi, 
i think that limit to means send notifications only for this project. i don't think it is sending you notifications for the other projects, is it? 

https://docs.dependencytrack.org/integrations/notifications/

check the link to see the template of the notifications.

i think it is necessary to send all the affected projects. i had to send a webhook notification to create a jira ticket for each project and this field was really helpful.  

PS: i am not a contributor, just a user

**Comment by nscuro** [comment]
I suspect this is a duplicate of #1866, which was already addressed and will be shipped with 4.6.0.

Can you confirm that this covers your ask, @niklaskeerl?

**Comment by niklaskeerl** [comment]
Yes, I confirm this is a duplicate, @nscuro . Sorry, I was not able to find this using the search. I will close this and am happy to know it will be fixed in 4.6.0 :)
