### ISSUE TITLE
Implement caching for `RepositoryMetaAnalyzerTask`

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/dependency-track#1943]
### Current Behavior:

In order to reduce the amount of calls to external systems, `BaseComponentAnalyzerTask` uses a caching mechanism to store and retrieve results from external analyzers (e.g. OSS Index). We don't do this for `RepositoryMetaAnalyzerTask` right now, causing lots of redundant lookups in external repositories.

### Proposed Behavior:

Implement caching in a similar manner as we currently do it for vulnerability analysis.

**Comment by nscuro** [comment]
Note to self: Because `RepositoryMetaEvent`s are currently dispatched for all components of an uploaded BOM (see https://github.com/DependencyTrack/dependency-track/issues/1759#issuecomment-1178266149), there will be situations where multiple threads are analyzing the same component. This in itself can cause issues (e.g. unique constraint violations), but introducing caching will amplify this.

When we add cache checks (is this cached? -> If not, populate cache) we will most likely need a form of synchronization to prevent race conditions.

**Comment by syalioune** [comment]
@nscuro @stevespringett If that's ok for you, i can work on this one.

**Comment by nscuro** [comment]
Closing as #2129 has been merged.
