### ISSUE TITLE
OSV feed base URL

### ISSUE THREAD

**Issue by sahibamittal** [DependencyTrack/dependency-track#1964]
### Current Behavior: 
We are using OSV base url (https://osv-vulnerabilities.storage.googleapis.com) for ecosystems and mirroring. But, if user using DT cannot access this domain due to proxy, he should be able to use a (custom) mirrored domain instead.

### Proposed Behavior: 
Similar to NVD feeds URL, allow user to provide another domain if default (https://osv-vulnerabilities.storage.googleapis.com) cannot be accessed.

**Comment by sahibamittal** [comment]
@VinodAnandan @nscuro

**Comment by nscuro** [comment]
Implemented in #1973. Thanks @sahibamittal!
