### ISSUE TITLE
Versioncompare gets confused by a leading v

### ISSUE THREAD

**Issue by mphilipps** [DependencyTrack/dependency-track#1968]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:

![screen02](https://user-images.githubusercontent.com/17722151/191235822-894e817e-22ba-4241-9b80-6eeedf64188c.png)

Seems like dependency-track is comparing 1.0.1 and v1.0.1 and considers them to be not equal.

### Steps to Reproduce:

upload a sbom with apache-pack

```
    <component type="library" bom-ref="pkg:composer/symfony/apache-pack@1.0.1">
      <group><![CDATA[symfony]]></group>
      <name><![CDATA[apache-pack]]></name>
      <version><![CDATA[1.0.1]]></version>
      <description><![CDATA[A pack for Apache support in Symfony]]></description>
      <licenses>
        <license>
          <id><![CDATA[MIT]]></id>
        </license>
      </licenses>
      <purl><![CDATA[pkg:composer/symfony/apache-pack@1.0.1]]></purl>
      <externalReferences>
        <reference type="distribution">
          <url><![CDATA[https://github.com/symfony/apache-pack.git]]></url>
          <comment><![CDATA[As detected by composer's `getSourceUrls()` (type=git & reference=3aa5818d73ad2551281fc58a75afd9ca82622e6c)]]></comment>
        </reference>
        <reference type="distribution">
          <url><![CDATA[https://api.github.com/repos/symfony/apache-pack/zipball/3aa5818d73ad2551281fc58a75afd9ca82622e6c]]></url>
          <comment><![CDATA[As detected by composer's `getDistUrls()` (type=zip & reference=3aa5818d73ad2551281fc58a75afd9ca82622e6c & sha1=UNDEFINED)]]></comment>
        </reference>
        <reference type="issue-tracker">
          <url><![CDATA[https://github.com/symfony/apache-pack/issues]]></url>
          <comment><![CDATA[As set via `support.issues` in composer package definition.]]></comment>
        </reference>
        <reference type="distribution">
          <url><![CDATA[https://github.com/symfony/apache-pack/tree/master]]></url>
          <comment><![CDATA[As set via `support.source` in composer package definition.]]></comment>
        </reference>
      </externalReferences>
    </component>

``` 

### Expected Behavior:

I feel like the version compare function should just skip over a leading v.

### Environment:
  
  - Dependency-Track Version: v4.5.0
  - Distribution: Docker
  - BOM Format & Version: cyclonedx 1.3 created with [cyclonedx-php-composer](https://github.com/CycloneDX/cyclonedx-php-composer)
  - Database Server: H2
  - Browser: firefox

**Comment by syalioune** [comment]
Hello,
I believe that it is rather a SBOM generation issue. Even if DT stripped the leading `v` prefix from composer metadata for comparison, you'll still have issues finding vulns related to your component as they will be linked to `pkg:composer/symfony/apache-pack@v1.0.1` in OSS Index or Github Advisories.

I suggest to use the option `--no-version-normalization` of [cyclonedx-php-composer](https://github.com/CycloneDX/cyclonedx-php-composer) to have the correct purl to begin with.
