### ISSUE TITLE
Error while hitting "Administration" tab in 3.2.0

### ISSUE THREAD

**Issue by Arunraj89** [DependencyTrack/dependency-track#200]
While hitting the Administration tab on D-Track, I am getting below error. 
![on hold](https://user-images.githubusercontent.com/16404627/45376318-29673c00-b615-11e8-98c4-01f8733af00b.jpg)

> HTTP ERROR 403

**Comment by Arunraj89** [comment]
Even after logout and login, I am getting the same error again....

**Comment by stevespringett** [comment]
and did you add the SYSTEM_CONFIGURATION permission to the admin account?

**Comment by Arunraj89** [comment]
where?

**Comment by stevespringett** [comment]
<img width="1687" alt="screen shot 2018-09-11 at 11 04 04 am" src="https://user-images.githubusercontent.com/3878933/45378627-dc527e00-b5b2-11e8-90f5-32fc70b0f27f.png">

**Comment by Arunraj89** [comment]
Thank you so much @stevespringett. This was resolved.
