### ISSUE TITLE
Add the possibility to use Single Sign-On via OpenID Connect/SAML

### ISSUE THREAD

**Issue by Shakyy** [DependencyTrack/dependency-track#202]
### Issue Type:
  - [ ] defect report
  - [x] enhancement request

### Current Behavior:
Currently, users must be added manually and there's no way to connect to an external authentication tool.

### Expected Behavior:
An external authentication tool (e.g. Keycloak) can be connected to dependency-track to allow Single Sign-On with Identity Management and Access Management. Therefore an authentication layer like OpenID Connect or SAML must be provided within dependency-track.

### Environment:
  - Dependency-Track Version: 3.2.1

**Comment by stevespringett** [comment]
https://github.com/stevespringett/Alpine/issues/10

**Comment by stevespringett** [comment]
Closing. OIDC is implemented in v4.0 - to be released soon.
