### ISSUE TITLE
DT 4.5 Sonatype OSS Index Not Generating Vulnerabilities

### ISSUE THREAD

**Issue by lukas-adoma** [DependencyTrack/dependency-track#2021]
### Current Behavior:
Since the update to v4.5, Sonatype OSS Index vulnerabilities with the format sonatype-xxx-xxx have disappeared. This appears to be a bug. I checked my v4.5 install both with the default token and with a personal token and there are no sonatype-xxx-xxx vulnerabilities shown. Has anyone else been successful with adding Sonatype OSS Index vulnerabilities in v4.5? 

### Steps to Reproduce:
I connected my Sonatype OSS Index API token and have projects containing valid PURL's that have identified vulnerabilities by OSS Index.

### Expected Behavior:
In DT 4.4.2 OSS Index issues which did not have an associated CVE were shown with the reference of eg sonatype-2020-1234

**Comment by nscuro** [comment]
Can you provide an example PURL or SBOM for which you expect `SONATYPE-*` vulnerabilities to be reported?

**Comment by lukas-adoma** [comment]
Example PURL: pkg:maven/org.mozilla/rhino@1.7.7.2?type=jar

The PURL above shows sonatype-2018-0590 as the issue in Dependency Track v2.4.2 and in DT v2.5 there are no issues.

DT v2.4.2 gives the following link to the given Sonatype vulnerability: 
https://ossindex.sonatype.org/vulnerability/sonatype-2018-0590?component-type=maven&component-name=org.mozilla/rhino

**Comment by nscuro** [comment]
I just tested this with DT 4.6.0 and the vulnerability is showing up for me:

![image](https://user-images.githubusercontent.com/5693141/195543484-3f832369-ed55-4aeb-a8b1-28be45969987.png)

I used this minimal BOM based on the data you provided:

```json
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "version": 1,
  "components": [
    {
      "type": "library",
      "group": "org.mozilla",
      "name": "rhino",
      "version": "1.7.7.2",
      "purl": "pkg:maven/org.mozilla/rhino@1.7.7.2?type=jar"
    }
  ]
}
```

Please ensure that you configured valid credentials (see https://docs.dependencytrack.org/datasources/ossindex/#authentication). Also keep in mind that a re-scan is happening after 24 hours, or upon every BOM upload.

**Comment by lukas-adoma** [comment]
Issue was likely related to rate limitations that occur when using an unauthenticated Sonatype account. 

We will register an account and further test.
