### ISSUE TITLE
Help me in configuring LDAP with D-Track

### ISSUE THREAD

**Issue by Arunraj89** [DependencyTrack/dependency-track#203]
I need some assistance in mapping LDAP with dependency tracker. any documentation is highly appreciated.

**Comment by stevespringett** [comment]
Documentation for Active Directory, eDirectory, ApacheDS, and Fedora 389 Directory is coming with the next release.

In the meantime, can you provide some information about your directory?

- LDAP Vendor/Provider:
- BaseDN

**Comment by Arunraj89** [comment]
We are using Microsoft LDAP. BaseDN we cannot share.

**Comment by stevespringett** [comment]
Well here's what it should look like. Replace example.com and dc=example,dc=com with the actual basedn.

```ini
alpine.ldap.server.url=ldap://hostname:3268
alpine.ldap.domain=example.com
alpine.ldap.basedn=dc=example,dc=com
alpine.ldap.security.auth=simple
alpine.ldap.bind.username=Administrator
alpine.ldap.bind.password=*******
alpine.ldap.auth.username.format=
alpine.ldap.attribute.name=userPrincipalName
alpine.ldap.attribute.mail=mail
```

Instead of Administrator, use a service account with read-only access to the entire directory and global catalog.

**Comment by Arunraj89** [comment]
Thanks @stevespringett I am working on this. In this mean time can you please give configuration for OpenLDAP? 

I got the OpenLDAP connection URL, Port SSL certificate. Not sure about configuring it to D-track. Can you please help me on this.

**Comment by stevespringett** [comment]
The majority of LDAP integration testing in the current version of Dependency-Track was focused on Active Directory. In the upcoming 3.3.0 release, an immense amount of work has gone into ensuring LDAP support is universal with equal support for AD, ApacheDS, Fedora 389, eDirectory, and OpenLDAP. Some refactoring was involved, and a few configuration options have been added or slightly modified. In all, LDAP support has been greatly improved across the board (including Active Directory).

IMO, if you're just getting started with LDAP integration, I would hold off until the 3.3.0 release. You can track the progress here. https://github.com/DependencyTrack/dependency-track/milestone/7

Configuration examples for each of the directory servers will also be provided in the documentation upon release. The changelog will also describe some of the LDAP configuration changes necessary in application.properties.

**Comment by Arunraj89** [comment]
Any tentative 3.3 release date?

**Comment by stevespringett** [comment]
I'm targeting the end of October (possibly first week of November). So within 2-3 weeks time.

**Comment by stevespringett** [comment]
Closing
