### ISSUE TITLE
OIDC support for state instead of redirect_url

### ISSUE THREAD

**Issue by pierresouchay** [DependencyTrack/dependency-track#2033]
We want to use deptrack with Azure AD.

The setup do work, but we also want to use links to projects to login automatically, such as:

https://deptrack.acme.com/projects/0db2a9c0-82f4-4396-95ef-da9b5c39953c => a link created when displaying badges for instance.

### Current Behavior:

In such case, if the user is not logged-in, this will result in such URL: `https://deptrack.acme.com/login?redirect=%2Fprojects%2F0db2a9c0-82f4-4396-95ef-da9b5c39953c`

If the user is then choosing OpenID, the return URL will be: 
`https://deptrack.acme.com/static/oidc-redirect.html?redirect=%2Fprojects%2F0db2a9c0-82f4-4396-95ef-da9b5c39953c`

The problem: for several OIDC providers (such as Azure AD), you cannot tune anything else than the `state` parameter in a redirect URL (to avoid some possible abuse with redirect URL), or you have to add 1 redirect URL per possible return URL 

Thus, in order to work with azure, we would need to add all possible projects (which is anyway limited to 255 values), and this is both boring and bad.

This could be achieved by using the state parameter instead, so instead of using:

`https://deptrack.acme.com/static/oidc-redirect.html?redirect=%2Fprojects%2F0db2a9c0-82f4-4396-95ef-da9b5c39953c` as return URL, we could use: `https://deptrack.acme.com/static/oidc-redirect.html?state=%2Fprojects%2F0db2a9c0-82f4-4396-95ef-da9b5c39953c` => which would solve the issue.

Reference in Azure AD documentation: https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url#use-a-state-parameter .

This behaviour of Azure AD is very likely to avoid open redirector (see https://www.rfc-editor.org/rfc/rfc6749#section-10.15), but very likely some other OpenID implementation might have the same issue.

### Proposed Behavior:

1. In method that redirect to IdP, encode redirect_url as state
2. when getting back the callback in `static/oidc-redirect.html`, convert state into `redirect_url`

**Comment by eldis80** [comment]
Hasn't this been already fixed in v4.4.1 in response to #1107 ?

**Comment by pierresouchay** [comment]
@eldis80 Indeed, seems to be a duplicate of #1107 (sorry, I did not find it when creating the issue)

**Comment by nscuro** [comment]
Thanks for pointing that out @eldis80. I have closed the linked issue as it has been shipped with 4.4.

@pierresouchay, I take from this you're not running 4.4 or newer?
