### ISSUE TITLE
Policy Violation Display Bug

### ISSUE THREAD

**Issue by SeanWrightFeat** [DependencyTrack/dependency-track#2043]
### Current Behavior:

When viewing the Policy Violation of a project, it is not displaying the State or Policy Name in the table. When you delete the policy and recreate it, it then shows. However it disappears as soon as you change any view options on the table, such as sorting the items in the table or changing the amount of items to display.

### Steps to Reproduce:

View the Policy Violation section of a project.

### Expected Behavior:

Be able to see the State and Policy Name fields.

### Environment:
  
  - Dependency-Track Version: 4.6.0
  - Distribution: Docker
  - BOM Format & Version: N/A
  - Database Server: PostgreSQL
  - Browser: Brave and Firefox

### Additional Details:

Here is a screenshot showing the issue:
![image](https://user-images.githubusercontent.com/105295111/195576206-0c9201e2-5e1f-4b8c-b3eb-01dd04314814.png)

**Comment by nscuro** [comment]
Thanks for reporting @SeanWrightFeat! 

Was able to reproduce and have a fix in the pipeline. Once again our ORM is shining with some quirky lazy loading behavior...

As this is impacting a core feature of DT, We'll most likely push a bugfix release out for it.

**Comment by SeanWrightFeat** [comment]
@nscuro thank you for getting onto this so quickly! I really appreciate it. Please shout if there's anything at all that I can do to help.

**Comment by nscuro** [comment]
@SeanWrightFeat The fix is now available with version 4.6.1 of the API server / bundled distribution. Release of the frontend was not necessary, so the latest version for that remains 4.6.0. Thanks again for reporting!
