### ISSUE TITLE
Quickstart with docker-compose is not working

### ISSUE THREAD

**Issue by willyw0nka** [DependencyTrack/dependency-track#2046]
### Current Behavior:
`curl -LO https://dependencytrack.org/docker-compose.yml` does not download a yaml but an html file

### Steps to Reproduce:
```bash
$ curl -LO https://dependencytrack.org/docker-compose.yml
$ cat docker-compose.yml
```

### Expected Behavior:
`curl -LO https://dependencytrack.org/docker-compose.yml` downloads the expected yaml file to run dependencytrack with docker-compose

### Additional Details:
The error is that the requested page (https://dependencytrack.org/docker-compose.yml) shows the homepage instead of the expeced yaml file

**Comment by nscuro** [comment]
Thanks for reporting, @willyw0nka!

The website was updated yesterday, and it looks like some redirects broke along the way.

In any case, the link you shared just redirects to https://raw.githubusercontent.com/DependencyTrack/dependency-track/master/src/main/docker/docker-compose.yml. You can use that instead for now, in case you need it.

**Comment by nscuro** [comment]
The website URL has been fixed in the meantime. Thanks again for reporting!
