### ISSUE TITLE
Dependency-Track taking too much time to install

### ISSUE THREAD

**Issue by pankajmalhotra** [DependencyTrack/dependency-track#206]
The issue may already be reported! Please [search for the issue](../) before creating one. Only create issues for bug reports or feature requests. All support inquiries and questions should be posted to [Slack](https://owasp.slack.com/messages/proj-dependency-track) ([invite](https://owasp.herokuapp.com/)), [Gitter](https://gitter.im/dependency-track/Lobby), or [Google Groups](https://groups.google.com/forum/#!forum/dependency-track).

### Issue Type:
  - [ *] defect report
  - [ ] enhancement request
  
  
### Current Behavior:
I ran the following command on windows 2016 server
java -Xmx6G -jar dependency-track-embedded.war -context /dtrack  -port 8080
Its been running for over 24 hours still not installed.

00:11:39.695 INFO [DownloadTask] Download Complete for NVD CVE - 2017  (11845 ms)
00:11:47.446 INFO [ProcessTask] Processing Complete for NVD CVE - 2005  (32888 ms)
00:11:47.446 INFO [ProcessTask] Processing Started for NVD CVE - 2008
00:11:53.052 INFO [ProcessTask] Processing Complete for NVD CVE - 2007  (30797 ms)
00:11:53.052 INFO [ProcessTask] Processing Started for NVD CVE - 2012
00:12:00.772 INFO [ProcessTask] Processing Complete for NVD CVE - 2006  (35470 ms)
00:12:00.772 INFO [ProcessTask] Processing Started for NVD CVE - 2013
00:12:02.007 INFO [ProcessTask] Processing Complete for NVD CVE - 2009  (23122 ms)
00:12:02.007 INFO [ProcessTask] Processing Started for NVD CVE - 2010
00:12:28.864 INFO [ProcessTask] Processing Complete for NVD CVE - 2008  (41418 ms)
00:12:28.879 INFO [ProcessTask] Processing Started for NVD CVE - 2014
00:12:31.317 INFO [ProcessTask] Processing Complete for NVD CVE - 2012  (38247 ms)
00:12:31.317 INFO [ProcessTask] Processing Started for NVD CVE - 2015
00:12:38.021 INFO [ProcessTask] Processing Complete for NVD CVE - 2010  (36014 ms)
00:12:38.021 INFO [ProcessTask] Processing Started for NVD CVE - 2016
00:12:42.178 INFO [ProcessTask] Processing Complete for NVD CVE - 2013  (41406 ms)
00:12:42.178 INFO [ProcessTask] Processing Started for NVD CVE - Modified
00:12:44.476 INFO [ProcessTask] Processing Complete for NVD CVE - Modified  (2282 ms)
00:12:44.476 INFO [ProcessTask] Processing Started for NVD CVE - 2011
00:13:38.929 INFO [ProcessTask] Processing Complete for NVD CVE - 2015  (67612 ms)
00:13:38.929 INFO [ProcessTask] Processing Started for NVD CVE - 2018
00:13:42.242 INFO [ProcessTask] Processing Complete for NVD CVE - 2014  (73363 ms)
00:13:42.242 INFO [ProcessTask] Processing Started for NVD CVE - 2017
00:13:42.570 INFO [ProcessTask] Processing Complete for NVD CVE - 2011  (58094 ms)
00:13:47.587 INFO [ProcessTask] Processing Complete for NVD CVE - 2016  (69566 ms)
00:14:02.620 INFO [ProcessTask] Processing Complete for NVD CVE - 2018  (23691 ms)
00:14:31.202 INFO [ProcessTask] Processing Complete for NVD CVE - 2017  (48960 ms)
00:14:31.202 INFO [NvdCveUpdater] Begin database maintenance.
00:14:34.062 INFO [NvdCveUpdater] End database maintenance.
00:14:34.921 INFO [Engine] Check for updates complete (204254 ms)
00:14:34.921 INFO [DependencyCheckTask] Dependency-Check update-only complete
00:52:47.153 INFO [MetricsUpdateTask] Executing metrics update on portfolio
00:52:48.075 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
01:52:47.163 INFO [MetricsUpdateTask] Executing metrics update on portfolio
01:52:48.090 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
02:52:47.182 INFO [MetricsUpdateTask] Executing metrics update on portfolio
02:52:48.104 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
03:52:47.199 INFO [MetricsUpdateTask] Executing metrics update on portfolio
03:52:48.121 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
04:52:47.208 INFO [MetricsUpdateTask] Executing metrics update on portfolio
04:52:48.133 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
05:52:37.150 INFO [DependencyCheckTask] Analyzing portfolio
05:52:37.166 INFO [DependencyCheckTask] Portfolio analysis complete
05:52:37.150 INFO [NpmAuditAnalysisTask] Starting Node Audit analysis task
05:52:37.166 INFO [NpmAuditAnalysisTask] Analyzing portfolio
05:52:37.166 INFO [NpmAuditAnalysisTask] Portfolio analysis complete
05:52:37.166 INFO [NpmAuditAnalysisTask] Node Audit analysis complete
05:52:47.232 INFO [MetricsUpdateTask] Executing metrics update on portfolio
05:52:48.154 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
06:52:47.238 INFO [MetricsUpdateTask] Executing metrics update on portfolio
06:52:48.160 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
07:52:47.252 INFO [MetricsUpdateTask] Executing metrics update on portfolio
07:52:48.174 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
08:52:47.277 INFO [MetricsUpdateTask] Executing metrics update on portfolio
08:52:48.199 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
09:52:47.286 INFO [MetricsUpdateTask] Executing metrics update on portfolio
09:52:48.208 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
10:52:47.291 INFO [MetricsUpdateTask] Executing metrics update on portfolio
10:52:48.213 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
11:52:37.184 INFO [NpmAuditAnalysisTask] Starting Node Audit analysis task
11:52:37.184 INFO [NpmAuditAnalysisTask] Analyzing portfolio
11:52:37.184 INFO [NpmAuditAnalysisTask] Portfolio analysis complete
11:52:37.184 INFO [NpmAuditAnalysisTask] Node Audit analysis complete
11:52:37.184 INFO [DependencyCheckTask] Analyzing portfolio
11:52:37.184 INFO [DependencyCheckTask] Portfolio analysis complete
11:52:47.324 INFO [MetricsUpdateTask] Executing metrics update on portfolio
11:52:48.246 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
12:52:47.345 INFO [MetricsUpdateTask] Executing metrics update on portfolio
12:52:48.266 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
13:52:47.360 INFO [MetricsUpdateTask] Executing metrics update on portfolio
13:52:48.282 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
14:52:47.379 INFO [MetricsUpdateTask] Executing metrics update on portfolio
14:52:48.301 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
15:52:47.397 INFO [MetricsUpdateTask] Executing metrics update on portfolio
15:52:48.319 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
16:52:47.416 INFO [MetricsUpdateTask] Executing metrics update on portfolio
16:52:48.337 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
17:52:37.250 INFO [NpmAuditAnalysisTask] Starting Node Audit analysis task
17:52:37.250 INFO [NpmAuditAnalysisTask] Analyzing portfolio
17:52:37.250 INFO [NpmAuditAnalysisTask] Portfolio analysis complete
17:52:37.250 INFO [NpmAuditAnalysisTask] Node Audit analysis complete
17:52:37.250 INFO [DependencyCheckTask] Analyzing portfolio
17:52:37.250 INFO [DependencyCheckTask] Portfolio analysis complete
17:52:47.438 INFO [MetricsUpdateTask] Executing metrics update on portfolio
17:52:48.359 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database

Suggest what should I do to install.

### Environment:
  
  - Dependency-Track Version:
  - Distribution: [ Docker | Executable WAR | Traditional WAR ]
  - BoM Format & Version:
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]
  - Browser: 

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
Looks fine to me. Are you unable to connect to http://localhost:8080

**Comment by pankajmalhotra** [comment]
Thanks @stevespringett I was not putting /dtrack in the end of the url while accessing it. Thanks for the clue.
