### ISSUE TITLE
Dependency graph not working

### ISSUE THREAD

**Issue by 2013kaa** [DependencyTrack/dependency-track#2064]
Not working for all projects.
I must have forgotten to include something.
Could you tell me where to add something during deployment or where to see the debug.
I use Dependency-Track  v4.5.0 
![error](https://user-images.githubusercontent.com/46608135/196691521-42ad4c8f-1255-4aa5-b5c3-580fcc162e53.JPG)

**Comment by nscuro** [comment]
This may be a data quality issue in the BOM you're uploading.

What tool did you use to generate the BOM? If you inspect the file, does it contain a [dependency graph](https://cyclonedx.org/use-cases/#dependency-graph)?

**Comment by 2013kaa** [comment]
@nscuro baaaa)))thanks, i'm going to try

**Comment by 2013kaa** [comment]
@nscuro yes, the problem is in the gradle plugin, I tried version 1.7.2 for gradle, but still I don't see the "dependencies" and "dependsOn" fields.
And cyclonedx-maven-plugin-2.7.1. works fine.
com.cyclonedx:cyclonedx-gradle-plugin:1.7.2 doesn't work.

I'll go see them and find out why.

**Comment by 2013kaa** [comment]
the problem is in cyclonedx-gradle-plugin
