### ISSUE TITLE
[Too many requests] OSSIndex Analysis triggers HTTP Status Code 429 since Update to 4.6.0

### ISSUE THREAD

**Issue by holdebeSICKAG** [DependencyTrack/dependency-track#2066]
### Current Behavior:
I use Sonatype OssIndex integration with an API token.
Since the update to 4.6.0 and later to 4.6.1, I get reports from developers that vulnerabilities are not displayed and even two uploads of the same bom in different projects get different counts of vulnerabilities.

I had a look into the logs and see that the OssIndexAnalysisTask aborts batches of components due to HTTP Status 429 and therefore components are not analyzed.

### Steps to Reproduce:
Update to 4.6.x, upload a bom and run a OssIndexAnalysisTask.

### Expected Behavior:

OssIndexAnalysisTask should analyze components or schedule a retry for aborted batches of components.

### Environment:
  
  - Dependency-Track Version: 4.6.1
  - Distribution:  Docker
  - BOM Format & Version: CycloneDX 1.4
  - Database Server: PostgreSQL 
  - Browser: Brave

### Additional Details:

2022-10-20 07:08:11,786 INFO [OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
2022-10-20 07:08:13,213 INFO [OssIndexAnalysisTask] Analyzing 33 component(s)
2022-10-20 07:08:13,873 ERROR [OssIndexAnalysisTask] HTTP Status : 429
2022-10-20 07:08:13,873 ERROR [OssIndexAnalysisTask]  - Analyzer URL : https://ossindex.sonatype.org/api/v3/component-report
2022-10-20 07:08:13,874 INFO [OssIndexAnalysisTask] Analyzing 26 component(s)
2022-10-20 07:08:13,874 INFO [OssIndexAnalysisTask] Sonatype OSS Index analysis complete

Could be important, i updated from image dependencytrack/apiserver:issue-1644 to dependencytrack/apiserver:4.6.0 and finally to  dependencytrack/apiserver:4.6.1

**Comment by nscuro** [comment]
Thanks for reporting @holdebeSICKAG. 

We did not change anything related to the OSS Index analysis in 4.6. There is an open issue however that appears to relate to your problem: https://github.com/DependencyTrack/dependency-track/issues/2023

For context: How many projects / components are you tracking with Dependency-Track? How many components (roughly) are in the BOMs you upload? Are many BOM uploads happening in parallel? 

OSS Index does not provide specific numbers as to when users may be rate limited sadly, I'm trying to get a feeling for when users may run into this.

**Comment by holdebeSICKAG** [comment]
So just to be more clear about the reported issue. This is not happening like every time a OssIndexAnalysis task runs. I would say I have 2.6k projects with about 1 million components. The amount of components per project varies a lot, from like 50 to 1.500. We have on average a hundert BOM uploads per day, but with spikes of up to 15 BOM per second. 

if it matters:
we have 14 vCPU and 32 GB RAM.

**Comment by holdebeSICKAG** [comment]
I saw #2023, but I consider it not as an issue but more an enhancement.

**Comment by nscuro** [comment]
We got the feedback from OSS Index that there was an issue on their side that caused rate limiting to kick in too soon. It should be resolved now. Please let us know when this continues to be an issue for you.

**Comment by holdebeSICKAG** [comment]
Thanks for investigating! Awesome that it got resolved so quickly. I can confirm that the rate for HTTP Status 429 from OssIndex has dropped to zero.
