### ISSUE TITLE
Need assistance in MSSQL setup

### ISSUE THREAD

**Issue by Arunraj89** [DependencyTrack/dependency-track#207]
We are trying to setup MSSQL DB in place of embedded H2 DB. 

It requires DB Table creation script /schema for MSSQL after which we can link it to Dtrack. Can you please let us know the place we're I can get the schema file? Migration of h2 to MSSQL? 

Simply mapping MSSQL details in application.properties will create table?

**Comment by stevespringett** [comment]
The schema will be created for you upon server startup. It's important that you set the configuration properly, especially the sql_mode.

https://docs.dependencytrack.org/getting-started/database-support/

When the server starts, it will check to ensure the schema is correct. If it's not (or doesn't exist), it will be created/updated dynamically.

**Comment by stevespringett** [comment]
Closing
