### ISSUE TITLE
Limit on /api/v1/project

### ISSUE THREAD

**Issue by stboissdev** [DependencyTrack/dependency-track#209]
With REST API, when I call curl -X GET "http://.../api/v1/project" -H "accept: application/json" -H "X-Api-Key: ..." I have only 100 projects but i have 275 projects in database.

### Issue Type:
  - [x] defect report
  - [ ] enhancement request
  
### Environment:
  
  - Dependency-Track Version: 3.2.1
  - Distribution: [ Docker ]
  - Database Server: [  MySQL ]

**Comment by stevespringett** [comment]
Most APIs are paginated so if you have more than 100 results you’ll need to page through them.

You can either specify `offset` or a combo of `page` and `size`. Some APIs also allow you to specify `filter`, `sort`, and `orderBy`.

**Comment by amagar1** [comment]
@stevespringett , any example of using offset or page for this?

**Comment by stevespringett** [comment]
`/api/v1/project?page=1&limit=100`
`/api/v1/project?page=2&limit=100`

or 

`/api/v1/project?offset=0`
`/api/v1/project?offset=100`

Paginated responses will always have an `X-Total-Count` header. So if you see this header, you'll know you need to paginate through the results.

**Comment by stevespringett** [comment]
Closing
