### ISSUE TITLE
Report Database Type & Version in Log and UI

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#2093]
### Current Behavior:
Dependency-Track v4.6.1  (and 4.7.0-SNAPSHOT) does not report the database type (eg PostgreSQL) or the database version... either in log or UI.

This information can be crucial when administering the system or reporting problems.
* Our platform people migrated a bunch of servers to new environments and the PostgreSQL used by Dependency-Track was upgraded from 10.x to 14,x.  And I had no idea that this had happened!
* A user investigating a problem needs to know that they are NOT using the embedded H2 database in production.

### Proposed Behavior:

* Log database type and version on startup.
* Display database type and version in the UI "About" Dialog.

Note that logs can roll-over or not be accessible to all users.  Hence the value in providing the info in two ways.

Implementation of this enhancement might also require touching Alpine,

**Comment by nscuro** [comment]
Raised PR to report database name and version via Alpine's `About` model, which is exposed via the `/api/version` route in DT: https://github.com/stevespringett/Alpine/pull/565

Once this change is available, we can update the *About* dialog of the UI.

The change in Alpine provides extensibility, such that we can do the same for other components in the future if needed.

**Comment by nscuro** [comment]
Blocked until Alpine PR is merged.
