### ISSUE TITLE
Add a Helm chart to make usage in Kubernetes easier

### ISSUE THREAD

**Issue by jvz** [DependencyTrack/dependency-track#210]
### Issue Type:
  - [ ] defect report
  - [x] enhancement request
  
  
### Current Behavior:
Dependency-Track is currently distributed as a Docker image (among other formats). Kubernetes is a runtime for Docker containers in a clustered environment. Installing DT into K8s is currently a pain as everything needs to be manually configured.

### Expected Behavior:
I'd like to be able to run something like `helm install stable/dependency-track` (or wherever the helm repo is until then), potentially supplying a values.yaml to customize any settings. This chart should depend on setting up a proper Postgres database (or even be configurable via the template) along with any other production-ready settings required for deployment.

### Environment:
  
  - Dependency-Track Version: latest
  - Distribution: [ Docker | Executable WAR | Traditional WAR ] Docker, but adding a new one
  - BoM Format & Version: latest
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ] Postgres by default
  - Browser: any

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by davidkarlsen** [comment]
Related: https://github.com/DependencyTrack/dependency-track/issues/547
I've started a chart in https://github.com/evryfs/helm-charts/tree/feature/dependencytrack - it can go upstream after being stabilized if you want to.

**Comment by davidkarlsen** [comment]
OK, we're running with this chart and it seems to work well. Do you want to have it upstream, or should we just keep it? It's development is based heavily on github-actions. Any input to the chart as it is ?

**Comment by jvz** [comment]
Oh nice! I haven't tried it out yet, though I am working on some new security automation pipelines at work where this might be useful to try out. Isn't upstream over at https://github.com/helm/charts/ anyways? Or are projects maintaining the charts in their own forks and pushing upstream from there?

**Comment by davidkarlsen** [comment]
That's going to retire. However I have no problem just maintaining it in our repo. The chart repo is public.

**Comment by jvz** [comment]
Oh, I see they've changed their distribution model since I last checked. A public helm chart like you suggest would be great. I'm not a maintainer here, though, so I'm not sure what the preferences here might be.

**Comment by stevespringett** [comment]
I also think a public helm chart would be great. I don't want to maintain one here as I don't have the expertise or resources for testing it.

**Comment by davidkarlsen** [comment]
Okidok. I'll add a bit of governance around it and get in onto the helm.hub and get back and close this 🎫

**Comment by davidkarlsen** [comment]
OK, it's over at the hub now: https://hub.helm.sh/charts/tietoevryfs/dependency-track - let's close this. Any issues can be opened in https://github.com/evryfs/helm-charts

**Comment by stevespringett** [comment]
Fantastic. Thanks @davidkarlsen
