### ISSUE TITLE
Rewrite UI as a Single Page Application (SPA)

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#213]
Rewrite UI with Vue.js

Use:
- https://bootstrap-vue.js.org/
- https://apexcharts.com/

**Comment by VinodAnandan** [comment]
For Vue.js OIDC integration = https://damienbod.com/2019/01/29/securing-a-vue-js-app-using-openid-connect-code-flow-with-pkce-and-identityserver4/

**Comment by stevespringett** [comment]
Development is taking place in https://github.com/DependencyTrack/front-end
