### ISSUE TITLE
Support Regex on Policy PURL

### ISSUE THREAD

**Issue by BlythMeister** [DependencyTrack/dependency-track#2144]
### Current Behavior

Condition PURL is not match `.*myCompayName.*`

### Proposed Behavior

Do not match on compoents which have a PURL patch

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by malice00** [comment]
This behavior should already be possible, you just need to change the value you are matching against! Currently in the code, a `contains` is done on the purl, so changing your input to 'myCompanyName' (so without the RegEx-Characters) should give you the result you are looking for.
Generally though, I admit RegEx would be a nice addition. I'll give this a try.

**Comment by BlythMeister** [comment]
Yeah I am more looking for checking multiple things `.*(x|y|z).*` for example
At the moment I need multiple rules and use an "Any" But then also means you can't pair with other conditions for an "And"

**Comment by malice00** [comment]
Understood. Just wanted to let you know that if you wanted exactly your described case, you could do it without a fix. :-)
