### ISSUE TITLE
SBOM import- PURL's are not entered

### ISSUE THREAD

**Issue by av1n95h** [DependencyTrack/dependency-track#2162]
### Current Behavior

Hi,

When i try to import sbom file CycloneDX 1.4 format into dependency tracker, the PURL's are not identified after the import.

The sbom in cyclonedx format is crated using cyclonedx-cli tool where i'm converting csv file into sbom. I used the same fields that are in dependency tracker. 

### Steps to Reproduce

1. This is the file csv file 
2. 
[bom.csv](https://github.com/DependencyTrack/dependency-track/files/10034719/bom.csv)

3. Convert it into cyclonedx format using cyclonedx-cli utility. https://github.com/CycloneDX/cyclonedx-cli
Command: ./cyclone-cli convert --input-file bom.csv --input-format csv --output-format json --output-file bom.json

![Screenshot 2022-11-17 at 1 03 17 PM](https://user-images.githubusercontent.com/66168530/202535457-70d1701e-79fc-49b4-bb35-964306722bed.png)
![Screenshot 2022-11-17 at 1 05 42 PM](https://user-images.githubusercontent.com/66168530/202535847-15bc68f6-fcd9-44ea-bb00-49020aedcac2.png)

### Expected Behavior

When imported SBOM, it should detect the purl field. 

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Container Image

### Database Server

N/A

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by stevespringett** [comment]
The purls specified do not conform to the purl specification and are invalid. I would recommend reaching out to the maker of the tool that originally created the purl and have them correct the issue. In this case, `pkg:nuget\\` should be replaced with `pkg:nuget/` to make the purl valid.

**Comment by nscuro** [comment]
Closing as this is not an issue on DT's side.
