### ISSUE TITLE
Add a "new project" notification

### ISSUE THREAD

**Issue by KramNamez** [DependencyTrack/dependency-track#2173]
### Current Behavior

Currently, there's no direct way to receive an alert about a new project being created. It would be possible to work around this by receiving the "BOM processed/consumed" notifications and tracking all projects separately for example, but this is duplicated effort.

### Proposed Behavior

Dependency-Track should offer a notification type NEW_PROJECT which triggers when a project is created through the GUI or when a BOM is uploaded with auto-create. I'm a security team member and would like to see when / if members of the dev teams at my company add projects to DT.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by KramNamez** [comment]
I figured that I'd take a shot at implementing this.

**Comment by rkg-mm** [comment]
I'd be happy to see this too :-) same situation as you are

**Comment by KramNamez** [comment]
Yes, and my current pull request keeps those semantics within Dependency-Track, although I'm not sure that it's really the right way to go.

But that's for a different issue / MR 🙂
