### ISSUE TITLE
GHSA vulenrabilities not showing.

### ISSUE THREAD

**Issue by rohan-birtia** [DependencyTrack/dependency-track#2180]
### Current Behavior

Although I have enabled GHSA and all the GHSA vuln DB has been in the Dependency track dashboard. But it's not detecting the vulnerabilities. After enabling, Do I have to perform any extra steps? 

As you can see from the attached screenshot, GHSA-36jr-mh4h-2g58 has not been detected. It's just an example, I have 30 repos, none of them have GHSA-related issue.

![image](https://user-images.githubusercontent.com/110599270/203265720-1121c2a2-b715-458f-bced-a1df67645840.png)
![image](https://user-images.githubusercontent.com/110599270/203266664-0e83b245-8364-470c-a7cc-322e9bf11dce.png)

![image](https://user-images.githubusercontent.com/110599270/203266916-e72592f0-fff4-4300-8bc0-339a4b40aee8.png)

### Steps to Reproduce

1. install dependency-track.
2. enabled GHSA.
3. upload SBOM.

### Expected Behavior

find 

### Dependency-Track Version

4.5.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
Hello @rohan-birtia, can you please provide an anonymized SBOM for reproduction ?
In the given example, DT behavior seems normal to me as package d3-color is totally different from @types/d3-color.

**Comment by rohan-birtia** [comment]
@syalioune ,  I will give an example with a repo https://github.com/anxolerd/dvpwa. As you can no GHSA issues on dependency track.
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/110599270/205069310-fe84615a-3ce4-49a2-8a7d-b23e16f3f8c7.png">
<img width="493" alt="image" src="https://user-images.githubusercontent.com/110599270/205069427-d388415a-d655-4754-86e3-8d17bae2746b.png">

`{
  "bomFormat" : "CycloneDX",
  "specVersion" : "1.4",
  "serialNumber" : "urn:uuid:0d3fb1d5-5344-403b-9b1d-69130c6686c6",
  "version" : 1,
  "metadata" : {
    "timestamp" : "2022-12-01T12:43:26Z",
    "tools" : [
      {
        "vendor" : "OWASP",
        "name" : "Dependency-Track",
        "version" : "4.5.0"
      }
    ],
    "component" : {
      "name" : "dvpwa",
      "version" : "SNAPSHOT",
      "type" : "application",
      "bom-ref" : "d622ebcd-9d8a-4f73-8a1b-167fb6a46e4f"
    }
  },
  "components" : [
    {
      "name" : "aiohttp",
      "version" : "3.5.3",
      "cpe" : "cpe:2.3:a:python-aiohttp:python-aiohttp:3.5.3:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/aiohttp@3.5.3",
      "type" : "library",
      "bom-ref" : "c7316539-2f5e-4698-8aae-b13cb94b15ae"
    },
    {
      "name" : "aiohttp-jinja2",
      "version" : "1.1.0",
      "cpe" : "cpe:2.3:a:python-aiohttp-jinja2:python-aiohttp-jinja2:1.1.0:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/aiohttp-jinja2@1.1.0",
      "type" : "library",
      "bom-ref" : "92f93d23-701b-4546-8801-5384a772b6c1"
    },
    {
      "name" : "aiohttp-session",
      "version" : "2.7.0",
      "cpe" : "cpe:2.3:a:python-aiohttp-session:python-aiohttp-session:2.7.0:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/aiohttp-session@2.7.0",
      "type" : "library",
      "bom-ref" : "6efb7487-88f7-4463-a704-a1d451653881"
    },
    {
      "name" : "aiopg",
      "version" : "0.15.0",
      "cpe" : "cpe:2.3:a:python-aiopg:python-aiopg:0.15.0:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/aiopg@0.15.0",
      "type" : "library",
      "bom-ref" : "f981795f-e52e-4583-8806-4e4207b8e439"
    },
    {
      "name" : "aioredis",
      "version" : "1.2.0",
      "cpe" : "cpe:2.3:a:python-aioredis:python-aioredis:1.2.0:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/aioredis@1.2.0",
      "type" : "library",
      "bom-ref" : "787de106-915d-4bcb-a232-835b4940fadd"
    },
    {
      "name" : "async-timeout",
      "version" : "3.0.1",
      "cpe" : "cpe:2.3:a:python-async-timeout:python-async-timeout:3.0.1:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/async-timeout@3.0.1",
      "type" : "library",
      "bom-ref" : "9c90fa7c-0664-4997-979d-1e159a023979"
    },
    {
      "name" : "attrs",
      "version" : "18.2.0",
      "cpe" : "cpe:2.3:a:python-attrs:python-attrs:18.2.0:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/attrs@18.2.0",
      "type" : "library",
      "bom-ref" : "07e19a5b-23f8-43a4-9a48-a1a5d0f0735c"
    },
    {
      "name" : "chardet",
      "version" : "3.0.4",
      "cpe" : "cpe:2.3:a:python-chardet:python-chardet:3.0.4:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/chardet@3.0.4",
      "type" : "library",
      "bom-ref" : "bded77d2-dfc8-4916-8ae6-ee545e053064"
    },
    {
      "name" : "hiredis",
      "version" : "0.3.1",
      "cpe" : "cpe:2.3:a:python-hiredis:python-hiredis:0.3.1:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/hiredis@0.3.1",
      "type" : "library",
      "bom-ref" : "ee16e4e5-9db5-4c14-9a0f-d1fbf9e9cb7a"
    },
    {
      "name" : "idna",
      "version" : "2.8",
      "cpe" : "cpe:2.3:a:python-idna:python-idna:2.8:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/idna@2.8",
      "type" : "library",
      "bom-ref" : "172278d7-3fe9-43f5-99ff-976014011dec"
    },
    {
      "name" : "jinja2",
      "version" : "2.11.3",
      "cpe" : "cpe:2.3:a:python-jinja2:python-jinja2:2.11.3:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/jinja2@2.11.3",
      "type" : "library",
      "bom-ref" : "6555fc0e-7b53-4a12-92e3-23f4b1edcfb6"
    },
    {
      "name" : "markupsafe",
      "version" : "1.1.0",
      "cpe" : "cpe:2.3:a:python-markupsafe:python-markupsafe:1.1.0:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/markupsafe@1.1.0",
      "type" : "library",
      "bom-ref" : "af0284cc-6e20-4420-8c31-7c1437d74e6d"
    },
    {
      "name" : "multidict",
      "version" : "4.5.2",
      "cpe" : "cpe:2.3:a:python-multidict:python-multidict:4.5.2:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/multidict@4.5.2",
      "type" : "library",
      "bom-ref" : "7a21db6f-7e71-4ad2-8acb-1c9ced69917b"
    },
    {
      "name" : "psycopg2",
      "version" : "2.7.6.1",
      "cpe" : "cpe:2.3:a:python-psycopg2:python-psycopg2:2.7.6.1:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/psycopg2@2.7.6.1",
      "type" : "library",
      "bom-ref" : "d163587a-1e74-4b34-a8a4-c2261e758f45"
    },
    {
      "name" : "pyyaml",
      "version" : "3.13",
      "cpe" : "cpe:2.3:a:python-pyyaml:python-pyyaml:3.13:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/pyyaml@3.13",
      "type" : "library",
      "bom-ref" : "637ccae6-d0c7-400f-974c-9728316168f1"
    },
    {
      "name" : "trafaret",
      "version" : "1.2.0",
      "cpe" : "cpe:2.3:a:python-trafaret:python-trafaret:1.2.0:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/trafaret@1.2.0",
      "type" : "library",
      "bom-ref" : "571fdfb1-795e-49b2-aee5-e887efde7cde"
    },
    {
      "name" : "trafaret-config",
      "version" : "2.0.2",
      "cpe" : "cpe:2.3:a:python-trafaret-config:python-trafaret-config:2.0.2:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/trafaret-config@2.0.2",
      "type" : "library",
      "bom-ref" : "20e3e1a5-7946-413a-bcdd-51b4d4bb6671"
    },
    {
      "name" : "yarl",
      "version" : "1.3.0",
      "cpe" : "cpe:2.3:a:python-yarl:python-yarl:1.3.0:*:*:*:*:*:*:*",
      "purl" : "pkg:pypi/yarl@1.3.0",
      "type" : "library",
      "bom-ref" : "ac348fe8-c25b-420a-a1db-07d7f3a34cf1"
    }
  ]
}`

**Comment by syalioune** [comment]
Thanks, I was able to reproduce your issue.
There's indeed a problem with v4.5.x for component having both CPE and PURL identifier. It was fixed in v4.6.0 with the work done on [Fuzzy Matching](https://github.com/DependencyTrack/dependency-track/pull/1799).

**Can you check that all your problematic projects have the same configuration (i.e. components with both CPE and PURL) ?**

If so, you'll have to move to a 4.6.x release.

![fix-4-6-3](https://user-images.githubusercontent.com/6144741/205505148-a35c0d01-709d-465e-8cb1-7e1329c64f17.png)
