### ISSUE TITLE
User landing to "Home/Administration" by default

### ISSUE THREAD

**Issue by rightphp** [DependencyTrack/dependency-track#2186]
### Current Behavior

We are using DT version v4.6.2.

Our users are connected using "OpenID Connect Users" feature. They first connect using SSO and then we assign permissions to them via terraform scripts.

Most of the users do not have admin permissions. I noticed that after login users are landing at  "Home/Administration" instead of  "Home/Dashboard".  Since they do not have admin permission they see the Red bar with 403 Forbidden issue.

Following are the logs we captured

2022-11-22 11:09:47,187 INFO [UserResource] Successful OpenID Connect login / username: <user> ....
2022-11-22 11:09:47,395 INFO [AuthorizationFilter] Unauthorized access attempt made by <user> to <dt-url>  

Following is the error on screen
![image](https://user-images.githubusercontent.com/8712458/203751666-1175a0bb-3591-40a9-8047-aa286d6e9934.png)

### Steps to Reproduce

1. Connect user using SSO
2. User will land at admin page by default

### Expected Behavior

When a user logs in, he should be landing to "Home/Dashboard" page.

I could not find any option in UI where we could set default landing page for each user!

Can we set it in docker config or in ingress? 

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Hey @rightphp, thanks for reporting! 

The path users are redirected to after OIDC login is determined by the path they tried to access while unauthenticated.

So if they open `https://dtrack.example.com/admin`, then are presented the login form, then login via OIDC, they will be redirected to `/admin`. You should be able to see the URLs your users are initially trying to access in your reverse proxy logs.

**Comment by rightphp** [comment]
Helllo @nscuro,

I confirmed with user and found that he tried to access /admin unauthenticated and see that 403 after successful login because he do not have permission to see admin page. 

www.example.com/admin url was shared by a user to him who had admin access.

Thanks for sharing that information and looking into it.

**Comment by nscuro** [comment]
@rightphp Thanks for confirming!
