### ISSUE TITLE
API /v1/project not all project are shown

### ISSUE THREAD

**Issue by shizzgar** [DependencyTrack/dependency-track#2193]
### Current Behavior

Our dep-track instance have very big ammount of projects (~156), 
And when we are executing 
/v1/project get request, not all 
Projects are returned.

### Steps to Reproduce

1. Add 150 projects to deptarck 
2. Request to /v1/project endpoint
3. Look at results and approve, that not all projects are shown.

### Expected Behavior

Return all projects
Or, maybe, implement some pagination mechanism... 

In afterwords:
DepTrack is AWESOME!
THANK YOU FOR YOU WORK, TEAM <3

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by valentijnscholten** [comment]
There is paging using `limit` and `offset` parameters, you can see from the network tab in the UI how it is used.

**Comment by nscuro** [comment]
Paging is there and works by either using `limit`+`offset`, or `pageNumber`+`pageSize` query parameters. The total number of items available in a given endpoint is indicated via the `X-Total-Count` response header. 

Paging is working, as this is what the frontend is using for various views. Feel free to reopen if you run into any bugs related to paging.
