### ISSUE TITLE
Allow to bypass starting requirements

### ISSUE THREAD

**Issue by nathan-mittelette** [DependencyTrack/dependency-track#2197]
### Current Behavior

Currently, when trying to start the dependency-track API, if your system does not meet the required requirements, the application will not start.

This behavior can force you to allocate a lot of resources.

### Proposed Behavior

I suggest keeping the current behavior but allowing the user to easily override the requirements using an environment variable.
We can create an **system.requirements.bypass** environment variable. By default, this variable will be set to false. But it can be replaced by true if we want to bypass this mechanism.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by stevespringett** [comment]
> This behavior can force you to allocate a lot of resources.

I know "a lot" is subjective, but I don't think 4.5 GB and 2 cores is "a lot". The system will not function correctly below 3GB.

https://docs.dependencytrack.org/getting-started/deploy-docker/

**Comment by nathan-mittelette** [comment]
I understand, but currently in my company we are running dependency-track API with 2Gi and 1 CPU because we don't have huge projects that needs a lot of memory while doing scans. Using dependency-track with this setup isn't perfect, but it's sufficient for our use.
Maybe if we allow users to bypass the requirements with obviously an warning at the start, that might help in some cases.

**Comment by nscuro** [comment]
IMO it's OK to provide the ability to opt out of this restriction.

Ideally we would have recommendations as to what workload requires (approximately) how many resources. But we don't currently.

At the moment we have users modifying DT internally to disable the check, and DT runs fine for them. There were multiple occasions in Slack where this was mentioned.

**Comment by nathan-mittelette** [comment]
> At the moment we have users modifying DT internally to disable the check, and DT runs fine for them. There were multiple occasions in Slack where this was mentioned.

Yes, it's exactly what we've done in my company, and I taught that we may not be alone and it can be useful to provide an implementation to properly disable the check.
