### ISSUE TITLE
Getting an Error when updating SMTP configuration settings without username and password

### ISSUE THREAD

**Issue by amagar1** [DependencyTrack/dependency-track#220]
The issue may already be reported! Please [search for the issue](../) before creating one. Only create issues for bug reports or feature requests. All support inquiries and questions should be posted to [Slack](https://owasp.slack.com/messages/proj-dependency-track) ([invite](https://owasp.herokuapp.com/)), [Gitter](https://gitter.im/dependency-track/Lobby), or [Google Groups](https://groups.google.com/forum/#!forum/dependency-track).

### Issue Type:
  - [ ] defect report
  
  
### Current Behavior:
Getting an Error when updating SMTP configuration settings without username and password
![image](https://user-images.githubusercontent.com/26895900/47964994-244bc980-e067-11e8-9b2a-6e0a32d2c357.png)

### Steps to Reproduce (if defect):
Go to Administration->Configuration->Email.
Enter all the SMTP details except username and password.

### Environment:
  
  - Dependency-Track Version: v3.3.0
  - Distribution: [ Traditional WAR ]
  - BoM Format & Version:
  - Database Server: [ PostgreSQL ]
  - Browser: 

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
This will be included in 3.4.0. It's also been backported to 3.3.1 which is being released this week.
