### ISSUE TITLE
use "dependency management" feature of maven

### ISSUE THREAD

**Issue by 06kellyjac** [DependencyTrack/dependency-track#2206]
### Current Behavior

Currently you're using maven to track the dependencies of `dependency-track` however maven doesn't have a concept of lockfiles to pin the versions of transitive dependencies.

Even if I can see the transitive versions via the SBOM you publish each release, I should be able to track the dependencies of `dependency-track` for a specific tag to ensure I can build it with the same versions the release was built with

### Proposed Behavior

The "dependency management" feature is as far as I can tell the closest to lockfiles that maven gets
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-management 

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by syalioune** [comment]
Hello @06kellyjac 

I'm not sure to understand your use case, however :

- Maven dependency management is not an alternative to a "package-lock", it only serves for maven project's hierarchy to centralize dependencies versions
- Maven does not work like NPM  with acceptable version ranges. To the best of my knowledge,  a given POM file always result in a deterministic and reproductible set of libraries / version

**Comment by 06kellyjac** [comment]
Ok so for example

https://github.com/DependencyTrack/dependency-track/blob/master/pom.xml#L93

`pkg:maven/com.konghq/unirest-java@3.13.11?type=jar`

depends on `pkg:maven/org.apache.httpcomponents/httpclient@4.5.13?type=jar` (among other things)

which depends on `pkg:maven/org.apache.httpcomponents/httpcore@4.4.13?type=jar`

since they're all "type=jar" is the jar artifact always used & in this case the `unirest-java@3.13.11` jar was built with the `httpclient@4.5.13` jar which was built with the `httpcore@4.4.13` jar?

If I wanted to recursively build from source and not use a prebuilt jar for `unirest-java@3.13.11` I'd still need to work out the transitive versions from the SBOM or work it out from the jars themselves

The other thing is there's no checksum so how would I know the `unirest-java@3.13.11` jar I download is the same as the `unirest-java@3.13.11` used for the release build?

---

this is the StackOverflow answer that lead me to "dependency management"
https://stackoverflow.com/a/54580971

**Comment by syalioune** [comment]
> since they're all "type=jar" is the jar artifact always used & in this case the `unirest-java@3.13.11` jar was built with the `httpclient@4.5.13` jar which was built with the `httpcore@4.4.13` jar?

Yes, at build time, maven is going to download all transitive dependencies of a given module for compilation.
For example, when `unirest-java@3.13.11` is built `httpclient@4.5.13` and `httpcore@4.4.13` are automatically downloaded. Same goes for Dependency Track.

> If I wanted to recursively build from source and not use a prebuilt jar for unirest-java@3.13.11 I'd still need to work out the transitive versions from the SBOM or work it out from the jars themselves

No you don't. You just have to clone the source with the appropriate tag and perform a `mvn clean package`. Maven will do the job for you and download all the correct transitive dependencies. Actually, the SBOM is generated using [cyclonedx-maven-plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin) which ask maven the transitive dependency list.
If you don't trust maven/pom, you don't have any reason to trust the SBOM either as it is generated from them.

> The other thing is there's no checksum so how would I know the unirest-java@3.13.11 jar I download is the same as the unirest-java@3.13.11 used for the release build? (again, in the SBOM but not a pom/maven thing)

This is again enforced by maven central and maven cli. Whenever you deploy a release version to maven central, the same version cannot be redeployed again. Checksum are generated and placed next to the artifacts (c.f https://repo1.maven.org/maven2/com/konghq/unirest-java/3.13.11/). You can perform a strict check using `mvn clean package --strict-checksums`
If you compare for instance the SHA1 checksum in the SBOM and the one in maven central, you can see that there are the same.

![checksum](https://user-images.githubusercontent.com/6144741/204550722-bc0a4a39-b0a8-48a7-b300-6e6af6f09fa6.png)

> this is the StackOverflow answer that lead me to "dependency management" https://stackoverflow.com/a/54580971

Unless the project uses snapshot dependencies, the whole process is simple and deterministic. The rules are described here https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#transitive-dependencies.

**Comment by 06kellyjac** [comment]
> Yes, at build time, maven is going to download all transitive dependencies of a given module for compilation.
For example, when unirest-java@3.13.11 is built httpclient@4.5.13 and httpcore@4.4.13 are automatically downloaded. Same goes for Dependency Track.

My assumption there was the only download is the top-level `unirest-java@3.13.11` jar since it has already been built. Does it actually need to download all transitive `jar`s in order to do a build?

> No you don't. You just have to clone the source with the appropriate tag and perform a mvn clean package.

My point is I either need to work those tags out out myself looking at the dependencies' pom files recursively or use the SBOM (or I guess ask maven registry myself)
I'd need the tags in order to know which version to clone

> Maven will do the job for you and download all the correct transitive dependencies.

If I'm doing a recursive source build I don't want to source build the top-level dependency but still fetch prebuilt artifacts for that dependency's dependencies

> If you don't trust maven/pom, you don't have any reason to trust the SBOM either as it is generated from them.
That's not completely true. Since your artifact is created trusting maven it's appropriate to trust the SBOM generated from the same source at the same time at the very least to pick versions necessary in order to attempt a recursive reproducible build to then compare the resulting artifacts.

---

And yeah my goal is to not *have* to trust maven. Just because they say they don't allow changing artifacts that doesn't mean it couldn't happen.
Are there transparency logs or mirrors that could notice a change to an existing artifact?

Simply keeping checksums in a lockfile helps to defend against this but the java ecosystem doesn't like that. A lockfile is more than just pinning versions

**Comment by 06kellyjac** [comment]
Ok, after discussing this I think the situation is that maven is the source of truth for artifacts and their checksums. Maven doesn't really have a concept of commiting a lockfile of those checksums to the repo. But every release comes with the SBOM so that's about all I'd need for most of the things I'm interested in trialing.

I'll close this issue but there might be some things that can be adopted from https://reproducible-builds.org/docs/jvm/ since maven apparently needs some configuration to build reproducible artifacts.
And I'm going to have a read into https://github.com/jvm-repo-rebuild/reproducible-central
