### ISSUE TITLE
dl.google.com:443 failed to respond

### ISSUE THREAD

**Issue by AndreiTrW** [DependencyTrack/dependency-track#2207]
### Current Behavior

boms while usual adding process either fail to add or show components at all or adds not all components

dl.google.com:443 failed to respond shows in logs

### Steps to Reproduce

stock settings..
### Expected Behavior

adding sbom to analyse

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Database Server Version

15

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Hmmm... I don't see any location in our code where we call out to `dl.google.com`, but it may just be used as a CDN for a package repository.

Can you please post the complete stacktrace of the error? `dl.google.com:443 failed to respond` by itself is not that helpful to us. 😅
