### ISSUE TITLE
Server Error (0)

### ISSUE THREAD

**Issue by mehrdad2000** [DependencyTrack/dependency-track#2208]
### Current Behavior

Hi
after run docker version of dependency-track, when i try to login with admin user give me "Server Error (0)"
![dt](https://user-images.githubusercontent.com/26499665/204533586-3c3f9c66-6204-45cc-88dc-34c14d010a11.jpg)

Any idea?
Thanks

### Steps to Reproduce

remove everything and start to run it from scratch.

### Expected Behavior

login successfully 

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by WeissFabian** [comment]
This is probably because of the CORS Policy Security of Chrome (see chrome console), this happens if both the front and backend are on localhost.

Try to start Chrome with the Flags: --disable-web-security --user-data-dir=~/devChromeTemp --cookies-without-same-site-must-be-secure   
this will disable this security feature and it should work.

Like: **chrome.exe --disable-web-security --user-data-dir=~/devChromeTemp --cookies-without-same-site-must-be-secure**

Then try to login again and it should work

**Comment by valentijnscholten** [comment]
I think it's better to investigate why. Advising users to disable web security completely in chrome doesn't sound like the right thing todo. @mehrdad2000 can you check the netwerk / console tab on what error messages are shown in the browser? It might be easier to discuss this on Slack: http://dependencytrack.org/slack/invite

**Comment by valentijnscholten** [comment]
>can you check the netwerk / console tab on what error messages are shown in the browser? It might be easier to discuss this on Slack: http://dependencytrack.org/slack/invite

**Comment by nscuro** [comment]
Did you see this section in the `docker-compose.yml` file?

```yml
    environment:
      # The base URL of the API server.
      # NOTE:
      #   * This URL must be reachable by the browsers of your users.
      #   * The frontend container itself does NOT communicate with the API server directly, it just serves static files.
      #   * When deploying to dedicated servers, please use the external IP or domain of the API server.
      - API_BASE_URL=http://localhost:8081
```

To me it looks like the API server container is either not running, or you deployed DT to a dedicated server without updating the `API_BASE_URL` environment variable as advised in `docker-compose.yml`.

**Comment by mehrdad2000** [comment]
@nscuro here is my docker compose
https://dependencytrack.org/docker-compose.yml

**Comment by mehrdad2000** [comment]
@nscuro after set api base url explicitly, issue resolved.
But it is sounds good from user point of view that fix in source, and after run docker compose everything work correctly without any further user action.
