### ISSUE TITLE
Hangs after some time

### ISSUE THREAD

**Issue by jskovjyskebankdk** [DependencyTrack/dependency-track#221]
### Issue Type:
  - [X] defect report
  
### Current Behavior:

Dependency Track stops answering connections after some time (days).

I reported some warnings from the log a some weeks ago. I filed that report because of the same behavior, but the warnings were not relevant.

I have set up DT with PostgresDB this time, but the problem (hangs) persists.

The calls used by both the web frontend and jenkins stop answering.

I restart the service as a workaround.

### Steps to Reproduce (if defect):

Let it run for days, collect data via Jenkins.

### Expected Behavior:

Not hang :)

### Environment:
  
  - Dependency-Track Version: 3.3.0
  - Distribution: Traditional WAR (run in Docker)
  - BoM Format & Version:
  - Database Server: PostgreSQL
  - Browser: FireFox

### Other Details:
I made a stack trace after the dependency track application was hung. Hope this can tell you something.

The dependency-track.log ends with:
````
2018-11-04 12:07:42,892 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: bea4aa45-a4b8-4625-af8e-0175a3cbacdb
2018-11-04 12:07:43,712 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: d807291f-1832-4992-a7e7-f50d7fa60ad9
````

I have added part of the server.log from the same time - there are no entries from the 4th.
But just repeating SQL exceptions - and I have those in the log repeatedly pretty much from when it was switched on (and appeared to be working fine).

Let me know if there is something else I can do to track the cause of this.

[server.log](https://github.com/DependencyTrack/dependency-track/files/2551813/server.log)
[stacktrace-hung.txt](https://github.com/DependencyTrack/dependency-track/files/2551814/stacktrace-hung.txt)

**Comment by stevespringett** [comment]
The contents of server.log tells you what's wrong. Postgres appears to be dropping the database connections and Dependency-Track is not being informed, so the connections time out. You may want to investigate some of the issues at https://github.com/brettwooldridge/HikariCP and see if anything applies to your environment. You may also want to investigate if you have network hardware (routers, firewall, etc) that look for idle TCP connections and kill them.

Diagnosing this issue will require some research on your part to determine what specifically is causing the connections to drop. Once the cause is identified, we can determine if there's anything in Dependency-Track or HikariCP that can be done to prevent that.

**Comment by jskovjyskebankdk** [comment]
As I said, the timeouts appear throughout the log (without apparent ill effect).

 So as last time, they are probably just taking focus from my real problem which is that DT hangs after some days.

I will try to fix the DB warnings/errors and see where that leads me.

(FWIW, this is between two docker containers, so there should be no risk of external networking agents at work)

Cheers

**Comment by jskovjyskebankdk** [comment]
We restart the container with DT nightly as a workaround, and have not had problems since.

**Comment by Drewster727** [comment]
Just FYI -- I'm having this same exact problem. I have cron'd a nightly container restart, but that's not cool... :)

**Comment by msymons** [comment]
The stacktrace sttached to this issue shows that @jskovjyskebankdk is using npm scanner.  This makes me wonder if this is the same problem that I have been reporting in #264.

@Drewster727, are you using NPM scanner in your server?
