### ISSUE TITLE
Policy with ALL operator not working

### ISSUE THREAD

**Issue by jrobledog** [DependencyTrack/dependency-track#2212]
### Current Behavior

When a policy with multiple conditions is created and the operator is ALL, the evaluation assigns a policy vulnerability per each condition vulnerated. Policy evaluator doesnt seem take into account the "ALL" operator and it is working like if policy was ANY operator always.

### Steps to Reproduce

1. Create new Policy, operator all
2. create condition license group IS NOT All Licenses, being All Licenses a group containing all licenses.
3. Create condition purl MATCHES pkg:maven (because we want only check  mavenized components with empty license field)
4. Update any project containing components with purl and with license.
5. A policy violation is assigned to this component showing it violates the purl condition, because the component has a purl value matching the purl condition.

### Expected Behavior

As the ALL operator says, policy evaluation must only trigger a policy violation when all conditions are violated. Because the component has a license matching the "all licenses" group, first condition is not violated, so this policy violation should not be triggered.

Verion  Version is 4.6.3 bundled.

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Executable WAR

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by eldis80** [comment]
I think this is related to #1924 and #1925. Those tickets have more information about the errors in logic of PackageURLPolicyEvaluator and PolicyEngine.

**Comment by malice00** [comment]
I think this is more related to #2146 than the others.

**Comment by eldis80** [comment]
I think this might be related to #1925 where it's explained why the PURL evaluator might return multiple violations even when it shouldn't.

**Comment by malice00** [comment]
Then I may have misunderstood the issue and it should be fixed in #2333. But whichever it is, there is still an issue with ALL-policies that is not fixed, which is the reason I started looking into all these issues in the first place. :-)
