### ISSUE TITLE
Start embedded server failed due to 'RequirementsVerifier' under Debian and openjdk-8 package

### ISSUE THREAD

**Issue by heurtemattes** [DependencyTrack/dependency-track#223]
### Issue Type:
  - [ X ] defect report
  - [  ] enhancement request
    
### Current Behavior:
Impossible to start embedded server

### Steps to Reproduce (if defect):
Run embedded server under Debian with openJdk-8 package

### Expected Behavior:

Server start

### Environment:
  
  - Dependency-Track Version: 3.3.0
  - Distribution: Executable WAR
  - BoM Format & Version:
  - Database Server: H2
  - Browser: Firefox

### Other Details:

stack from server start : 
 ERROR [RequirementsVerifier] Using Java version: 8.0.0+0
 ERROR [RequirementsVerifier] Dependency-Track requires Java 8 with a minimum update of 162 or higher. Cannot continue.

Class alpine.util.JavaVersion
function NumberUtils.toInt convert to '0' for update debian like '0_181-8u181-b13-1~deb9u1-b13'

java.runtime.version return '1.8.0_181-8u181-b13-1~deb9u1-b13' under Debian

**Comment by stevespringett** [comment]
This issue has been resolved in Alpine v1.4.1 which has been released to Maven Central. The next version of Dependency-Track (either v3.3.1 or v3.4.0) will include this fix.
