### ISSUE TITLE
Progressive inconsistencies between Dependency Track database and lucene indexes

### ISSUE THREAD

**Issue by syalioune** [DependencyTrack/dependency-track#2235]
### Current Behavior

Overtime, the content of dependency track lucene drift from the database because of several factors :

- Lucene indexes are updated asynchronously and can thus fail due to a lot of reasons (apiserver restart, I/O issues,...) whereas DB is correctly updated
- There are areas in the code where lucene indexes are not updated accordingly (e.g : [When deleting a project using the API, the related components are deleted from the database but not from lucene indexes](https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java#L655-L684))

### Steps to Reproduce

1.Create a project
2.Upload a SBOM
3.Check that lucene component index is updated using API /api/v1/search/component
4.Recursively delete the project
5.Check that lucene component index is untouched using API /api/v1/search/component (Same results as in step 3)

### Expected Behavior

Dependency Track database is as consistent as possible with Dependency Track Lucene index without resorting to multiple index rebuild

### Dependency-Track Version

4.7.0-SNAPSHOT

### Dependency-Track Distribution

Container Image, Executable WAR

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
By design, there will always be an **unwanted** drift. However, I feel like we can spend some time reviewing the database update flow to identifiy trivial gaps to fill like the example given in the description.
Maybe also improve the implementation to make indexing easier, straightforward and oversight resistant. I'm thinking about [DN Lifecycle listeners](https://www.datanucleus.org/products/accessplatform_6_0/jdo/persistence.html#lifecycle_listeners) and [Transaction synchronization](https://www.datanucleus.org/products/accessplatform_6_0/jdo/persistence.html#transaction_synchronisation) to automatically hook into entities update and DN commit/rollback.

**Comment by nscuro** [comment]
We started using lifecycle listeners as recommended in a few places:

* https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/persistence/listener/IndexingInstanceLifecycleListener.java
* https://github.com/DependencyTrack/dependency-track/blob/ab9d19dbce5b752401fc736b64232ab702f12301/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java#L261-L262
