### ISSUE TITLE
How is `application.properties` specified when running with docker?

### ISSUE THREAD

**Issue by memelet** [DependencyTrack/dependency-track#224]
### Issue Type:
  - [x] defect report (for documentation?)
  - [ ] enhancement request
  
  
### Other Details:

The docs instruct the use of `-Dalpine.application.properties=` when running with java. But there seems to be no indication on how to specify `application.properties` when running via docker. Should `application.properties` be located in a mount at `APP_DIR`? Or must `JAVA_OPTIONS` be overridden?

**Comment by stevespringett** [comment]
You must add it to JAVA_OPTIONS. Looking at the config, I could simplify this in the future. I'm going to change this to an enhancement so that the properties can be specified easier, and I'll update the docs in the process.

**Comment by memelet** [comment]
Thanks Steve.
