### ISSUE TITLE
Extensive test suite for CPE matching

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/dependency-track#2243]
### Current Behavior

We maintain a custom CPE matching logic, yet our test coverage is very scarce.

Making changes to the existing logic is a high risk, because we don't quite know if it negatively affects matching on real-world data.

### Proposed Behavior

Setup a test suite with loads of real-world CPE data. 

Note that we also pull versions information from component PURLs if the analyzed component has no CPE assigned to it, so that aspect should be covered as well.

The test subject will be the [`InternalAnalysisTask`](https://github.com/DependencyTrack/dependency-track/blob/4.6.3/src/main/java/org/dependencytrack/tasks/scanners/InternalAnalysisTask.java).

To cover as much data as possible without having to write too much code, setting up a test that just reads from a CSV file or so would be preferable.

```csv
cpe,componentCpe,componentPurl,match
cpe:2.3:a:...,cpe:2.3:a:...,,true
cpe:2.3:a:...,,pkg:maven/...,true
```

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by RingoDev** [comment]
Hi, I would be interested inhelping out here. Do you have a starting point of where somebody could generate such test input data from?
