### ISSUE TITLE
Track Components in dependency tree in Dependency Track. 

### ISSUE THREAD

**Issue by mathuriga** [DependencyTrack/dependency-track#226]
[Question:]

When we add the component [Component A] manually in dependency track by giving components name, Is Dependency Track capable to track the vulnerabilities of the components which are listed in the dependency tree of Component A?

**Comment by stevespringett** [comment]
Dependency-Track utilizes software bill-of-material (SBOM). This is typically a flat list of components including all transitive dependencies.

The recommended SBOM format to import is CycloneDX. If you manually add components without supplying a BoM, you’ll need in also manually include the transitive dependencies.

**Comment by mathuriga** [comment]
@stevespringett ,

Thanks for the quick clarification.
