### ISSUE TITLE
Indicate BOM processing failure

### ISSUE THREAD

**Issue by rkg-mm** [DependencyTrack/dependency-track#2264]
### Current Behavior

In rare cases processing a BOM file may fail. Since processing happens after the upload has finished and returned a 200-OK, this is only visible in logfiles. If someone has attached a log-analytics system to his logfiles, or is using email-notifications on errors, he might notice a problem, but otherwise it's hard to identify. Since many won't have log-systems in place, and email errors also contain a lot of noise about vuln-db updates, many won't have that either. Especially not the ones responsible for specific projects.

### Proposed Behavior

Even though implementing a full error notification in UI might be too much for this project, at least some indication on a project would be helpful.

Idea:

- If processing a BOM file produces errors, set a flag with timestamp at the project "bomUploadFailure=DateTime".
- Indicate with a red exclamation mark or similar icon in the project List and Project view and a tooltip "Last BOM Upload at [Timestamp] produced errors. See Logs for Details."
- If a following BOM upload succeeded without errors, the timestamp shall be cleared again

This would help to notice problems at low cost, and the timestamp gives a chance to identify the issue in logfiles/log-analytics systems. Ideally, the Project ID should be logged at such errors if not the case already, too. A project responsible could then request help from administrators if necessary.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by valentijnscholten** [comment]
Could it be a notification i.e. BOM_FAILED? In a ideal world failing BOM uploads should be very very rare so not sure if it's worth the effort to add more fields, deal with timing/parallelism, etc.

**Comment by rkg-mm** [comment]
Hmm ok I agree, this could be done as additional system error alert instead. The current system alerts don't cover it.

**Comment by msymons** [comment]
> this could be done as additional PORTFOLIO alert instead

"instead" or "in addition to"?  There are merits to both approaches.

**Comment by rkg-mm** [comment]
I meant: Instead of a UI visibility, put a new option in PORTFOLIO alerts :)

**Comment by nscuro** [comment]
We definitely also need to communicate / store the failure _reason_ somehow. Having this information persistent (until the next BOM upload succeeds, at least), would allow clients to determine whether or not they should retry the upload.

**Comment by rkg-mm** [comment]
@nscuro  the client would not get this information because the failure happens in a task after the upload call finished.

**Comment by nscuro** [comment]
But perhaps adding a notification and providing more details to clients are two separate enhancements. The former is trivial to add, the latter requires a bit more planning.

**Comment by nscuro** [comment]
Implemented in #2264. Thanks @rkg-mm & @rbt-mm!
