### ISSUE TITLE
Plugin v2.0.0: JsonException: Cannot auto-detect encoding, not enough chars

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#229]
### Issue Type:
  - [x] defect report
  - [ ] enhancement request

I hope I am logging this in the correct place...  I could not find "issues" in dependency-track plugin repo.

### Current Behavior:
Dependency-Track publishing succeeds in publishing but then fails build with JsonException exception

### Steps to Reproduce (if defect):
Use dependency-track plugin v2.0.0 in Jenkins job  (v1.1.1 suceeded after I downgraded to this older version).

### Expected Behavior:
Build succeeeds.

### Environment:
  
 - Jenkins 2.138.2
 - Dependency-Check plugin 3.3.4
 - Dependency-Track plugin 2.0.0 (just released)
 - Dependency-Track Server 3.3.1 
  - Distribution: [ Executable WAR]
  - Database Server: [ H2 ]

 - Standard Jenkins Maven Job:
 - Dependency-Track project selected from pull-down
 - Artifact:  dependency-check-report.xml
 - Artifact Type:  Depenendency-Check Scan Result (XML)
 - Synchronous publishing mode was not enabled.

### Other Details:

The exception was seen only with plugin v2.0.0...  the exception disappeared and build suceeded after downgrade to plugin v1.1.1
```
16:43:41 [DependencyTrack] Publishing artifact to Dependency-Track
--
16:43:42 [DependencyTrack] The artifact was successfully published
16:43:42 ERROR: Build step failed with exception
16:43:42 javax.json.JsonException: Cannot auto-detect encoding, not enough chars
16:43:42 	at org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:131)
16:43:42 	at org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:76)
16:43:42 	at org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:76)
16:43:42 	at org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:68)
16:43:42 	at org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:131)
16:43:42 	at javax.json.Json.createReader(Json.java:220)
16:43:42 	at org.jenkinsci.plugins.DependencyTrack.ApiClient.upload(ApiClient.java:117)
16:43:42 	at org.jenkinsci.plugins.DependencyTrack.DependencyTrackPublisher.perform(DependencyTrackPublisher.java:196)
16:43:42 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
16:43:42 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
16:43:42 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
16:43:42 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
16:43:42 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
16:43:42 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
16:43:42 	at hudson.model.Run.execute(Run.java:1844)
16:43:42 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
16:43:42 	at hudson.model.ResourceController.execute(ResourceController.java:97)
16:43:42 	at hudson.model.Executor.run(Executor.java:429)
16:43:42 Build step 'Publish BoM to Dependency-Track' marked build as failure
```

**Comment by stevespringett** [comment]
This was reported on the mailing list today and will likely push out a fix in a few hours.

**Comment by stevespringett** [comment]
v2.0.1 has been released which corrects this behavior and will be available from the Jenkins update site later today. If you need it right away, it's available here: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/dependency-track/2.0.1/
