### ISSUE TITLE
Latest version feature is not working properly

### ISSUE THREAD

**Issue by mathuriga** [DependencyTrack/dependency-track#230]
The latest version of a component is not displayed in UI. Please refer to the screenshot.  
![selection_017](https://user-images.githubusercontent.com/11587426/48533167-5fe95d80-e8c9-11e8-895f-f33789371112.png)

commons-httpclient's latest version is 3.1.0 as per [1].

[1] [https://mvnrepository.com/artifact/commons-httpclient/commons-httpclient](https://mvnrepository.com/artifact/commons-httpclient/commons-httpclient)

Could you please clarify this?

**Comment by stevespringett** [comment]
How did the components get populated? CycloneDX BOM, Dependency-Check XML report, manually?

CycloneDX is the preferred method as it support PackageURL. Dependency-Check does not so the system has to guess, but it can only do so some of the time. It's not ideal.

Every component should have a valid PackageURL. If you edit the component, one should be displayed. Only with a valid PackageURL can out-of-date detection be done. It's also required to use the OSSIndex analyzer.

Refer to:
https://docs.dependencytrack.org/usage/scrm/

Also note, Dependency-Track needs access to the Internet. Refer to https://docs.dependencytrack.org/datasources/repositories/ for the list of repositories it uses for outdated version detection.

**Comment by mathuriga** [comment]
@stevespringett ,

Thanks for the clarification. So, In order to use the latest version, the best way is to use CycloneDX. Isn't it?

Further, I have a few more question. I would be appreciated if you provide the clarification for this as well?

01. Is there any feature which support lifecycle for adding suppression comment? 
(Which means Add comment -> Review Comment ->  Approve suppression)
02. When we give add suppression, is it storing in a configured database? or any kind of suppression file?

**Comment by stevespringett** [comment]
Correct, use CycloneDX whenever possible.

Approval workflows are not implemented nor planned, but it does require specific permissions so you can restrict who has the ability to make analysis decisions. You could externalize that functionality if you want by integrating into an existing workflow engine and leveraging Dependency-Tracks API to update the audit trail from the external system.

Dependency-Track stores everything in the database including all projects, components, vulns, and audit trails (analysis decisions, comments, suppressions). Everything you can do in the UI you can do over REST, and more.

**Comment by stevespringett** [comment]
FYI I’m producing another howto video for YouTube, should be published this weekend sometime, which actually goes over producing a CycloneDX BoM, publishing it to DT, and how that ties into the auditing workflow. The content may be of interest to you. It’ll be published here: 
https://www.youtube.com/channel/UC8xdttysl3gNAQYvk1J9Efg

**Comment by mathuriga** [comment]
@stevespringett ,

Thank you so much for the clarification. 

> FYI I’m producing another howto video for YouTube

It sounds great. I will refer this. Once again Thanks.
