### ISSUE TITLE
Test Button for Email Service Configuration

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#231]
As an enhancement, it would be useful for the Dependency-Track "Email Service Configuration" screen to have a button that would allow the email configuration to be tested.  ie, send a test email.

This would be useful for checking that SMTP password is correct, etc.

**Comment by mathuriga** [comment]
+1 for this if it does not exist already. I'm also looking on how to test "Email Service Configuration" in Dependency-Track.

**Comment by stevespringett** [comment]
This feature has been implemented and will be available in Dependency-Track v3.4.0
