### ISSUE TITLE
UI odes not show data?

### ISSUE THREAD

**Issue by GurdipS5** [DependencyTrack/dependency-track#2328]
### Current Behavior

Hi,
I installed DependencyTrack 4.7 as a Dockeer container and everything works correctly. However, I upload a sbom xml file to the application but no data is shown in the UI?

### Steps to Reproduce

1. Login to application
2. Upload a bom xml file
3. Optionally, try the same action via the API

### Expected Behavior

Data to be shown via the UI on the components etc.

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

N/A

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
@GurdipS5 Do you see some errors in the logs ? Can you share the SBOM for reproduction ?

**Comment by GurdipS5** [comment]
Hi, This is resolved, I realised i need to upload json files and not xml and all is good!
