### ISSUE TITLE
Switch to Packagist api v2 for Composer package metadata

### ISSUE THREAD

**Issue by valentijnscholten** [DependencyTrack/dependency-track#2337]
### Current Behavior

Compose Packagist api v1 is [deprecated](https://packagist.org/apidoc#get-package-data).
API v2 also handles non-existing packages better, see #2134  And it helps packagist to reduce server load on their end.

### Proposed Behavior

Use API v2. It's a very small change as far as I can see in https://packagist.org/apidoc#get-package-data.

Now that we are caching metadata, we could use the [If-Modified-Since header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) to hel preduce load on their server.
In theory also on our end because if the metadata is not modified since we last cached it, we don't have to process the response. But this might be micro optimizing, probably requires a change to the parameters passed into the `analyze` method and we need to persist the new `lastOccurrence` timestamp to the database anyway.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by ch8matt** [comment]
https://blog.packagist.com/shutting-down-packagist-org-support-for-composer-1-x/

**Comment by valentijnscholten** [comment]
From the blog post:

- February 1st, 2025: Composer 1.x metadata will become read-only. No new packages or new versions will be visible for Composer 1.x users after this date.
- August 1st, 2025: Composer 1.x metadata access will be entirely shut down. Attempting to update packages using Composer 1.x will no longer work.

**Comment by valentijnscholten** [comment]
When implementing V2 we should consider also getting the Vulnerabity information from the package repository. This will show more vulnerabilities, for example the Drupal advisories which don't have a CVE/GHSA/... identifief.

From: https://packagist.org/apidoc#get-package-data:

> List security advisories
> This endpoint provides a list of security advisories. Either a list of packages as query or request parameter or a timestamp as updatedSince query parameter need to be passed.
> 
> When querying with a list of packages, known packages will be included in the response with an empty array if they don't have any listed vulnerability. Package names which are not known to have no vulnerability will not be included at all to show that we do not have data on those.
> 

```
GET https://packagist.org/api/security-advisories/?updatedSince=[timestamp]&packages[]=[vendor/package]

{
  "advisories": {
    "[vendor]/[package]": [
      {
        "advisoryId": "[unique id]",
        "packageName": "[vendor]/[package]",
        "remoteId": "[deprecated, use sources instead]",
        "title": "[title]",
        "link": "[url to issue disclosure]",
        "cve": "[cve if available]",
        "affectedVersions": [affected version in form of a composer constraint]",
        "source": "[deprecated, use sources instead]",
        "sources": [
            {
                "name": "[Name of the source where the advisory was found e.g. GitHub or FriendsOfPHP/security-advisories]"
                "remoteId": "[A reference to identify the advisory in the source e.g. the GitHub advisory id]"
            }
        ],
        "reportedAt": "[date the issue was reported]",
        "composerRepository": "[composer repository the package can be found in]",
        "severity": [severity if available, following the CVSS3 spec]
      }
    ]
  }
}
```

Working example: https://packagist.org/api/security-advisories/?packages[]=monolog/monolog

**Comment by jkowalleck** [comment]
> When implementing V2 we should consider also getting the Vulnerabity information from the package repository. This will show more vulnerabilities, for example the Drupal advisories which don't have a CVE/GHSA/... identifief.

I'd support this idea. Thank you for creating https://github.com/DependencyTrack/dependency-track/issues/4465

**Comment by jkowalleck** [comment]
> In fact, Drupal has its own package repository that DT should index / query as well. And it returns vulnerabilities in the same response as for other package metadata: https://packages.drupal.org/files/packages/8/p2/drupal/mollie.json

Implementation-wise, I would go like it currently is: have the base urlconfigurable, so that multiple clients for this API spec could be enabled in DT.

see https://github.com/DependencyTrack/dependency-track/blob/45982a2e1a12a0b0de17f955b856b27008fee02a/src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java#L46
