### ISSUE TITLE
OCID with Gitlab fails with  "unknown client, no client authentication included, or unsupported authentication method."

### ISSUE THREAD

**Issue by brujoand** [DependencyTrack/dependency-track#2346]
### Current Behavior

I've deployed `4.7.0` of both `apiserver` and `frontend` to our k8s cluster using the helmchart provided by [evryfs](https://github.com/evryfs/helm-charts). I've configured both applications to use gitlab.com as a OCID provider with the following configurations:

Apiserver:
```yaml
ALPINE_OIDC_ENABLED: "true"
ALPINE_OIDC_ISSUER: https://gitlab.com
ALPINE_OIDC_CLIENT_ID: <redacted>
ALPINE_OIDC_USERNAME_CLAIM: nickname
ALPINE_OIDC_TEAMS_CLAIM: groups
ALPINE_OIDC_USER_PROVISIONING: "true"
ALPINE_OIDC_TEAM_SYNCHRONIZATION: "true"
ALPINE_CORS_ENABLED: "true"
ALPINE_CORS_ALLOW_ORIGIN: '*'
ALPINE_CORS_ALLOW_METHODS: "GET, POST, PUT, DELETE, OPTIONS"
ALPINE_CORS_ALLOW_HEADERS: "Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *"
ALPINE_CORS_EXPOSE_HEADERS: "Origin, Content-Type, Authorization, X-Requested-With, Content-Length,            Accept, Origin, X-Api-Key, X-Total-Count"
ALPINE_CORS_ALLOW_CREDENTIALS: "true"
ALPINE_CORS_MAX_AGE: "3600"
```

Frontend:
```yaml
API_BASE_URL: "http://localhost:8081"
OIDC_ISSUER: "https://gitlab.com"
OIDC_CLIENT_ID: <redacted>
OIDC_SCOPE: "openid profile"
OIDC_LOGIN_BUTTON_TEXT: "Gitlab SSO"
```

I've setup port fortwarding for both these containers to my localhost for testing, which is why the base url points to localhost. Frontend on 8080 and apiserver on 8081.  The callback url whitelisted in Gitlab is `http://localhost:8080/static/oidc-callback.html` and the scopes for the service user is "ocid, profile, api". Not quite sure that api is needed though.

Most of the flow succeeds until I'm redirected to `http://localhost:8080/static/oidc-callback.html?code=<redacted>&state=<redacted>` at which point the browser console shows me that a call to `https://gitlab.com/oauth/token` produces a `HTTP 401` and the descritpion: 

> 
> www-authenticate
> 	Bearer realm="Doorkeeper", error="invalid_client", error_description="Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."

At this point the OCID flow stops with an empty page. There are no interesting messages in the container logs except that this resources is bying accessed, but isnt found: `localhost:8080/static/config.json`

### Steps to Reproduce

1. Follow the description over at https://docs.dependencytrack.org/getting-started/openidconnect-configuration/#gitlab-gitlabcom
2. Try to authenticate using the SSO button
3. Error

### Expected Behavior

I would expect it to not fail I guess

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
Hello @brujoand 

> There are no interesting messages in the container logs except that this resources is bying accessed, but isnt found: localhost:8080/static/config.json

Should be an 'old' or transient message because if the `config.json` file were not found, the SSO button would have not appeared. On the other hand it make perfect sense with regard to the error message because the client id is fetched from `config.json`.

I just tested and it works for me. Could you please provide the redacted payload sent by DT on the `https://gitlab.com/oauth/token` call ? It should be something like 

```
client_id: <redacted>
code: xyz
redirect_uri: http://localhost:8080/static/oidc-callback.html
code_verifier: <something>
grant_type: authorization_code
```

**Comment by syalioune** [comment]
I thought I'll give it another try :smile:

![image](https://user-images.githubusercontent.com/6144741/210614040-e3372e16-ef9e-48e7-8fac-235593375513.png)

The issue occurs when the declared Gitlab client is confidential ==> DT can only work with public OIDC client because it cannot store safely the secret.

![image](https://user-images.githubusercontent.com/6144741/210614264-92320691-7d89-4f55-8952-4c428d1b1ef4.png)

**Comment by brujoand** [comment]
ah, I wrongly assumed that the secret would be stored in the apiserver. Unchecking the "Confidential" box indeed fixed my problem. Thanks 👍
