### ISSUE TITLE
Drop dependency on Unirest

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/dependency-track#2350]
### Current Behavior

We currently use [Unirest](https://github.com/Kong/unirest-java) in various places, which in turn makes use of Apache HTTP Client v4.

We're planning to use https://github.com/jeremylong/vuln-tools to support NVD mirroring from the new CVE API v2 (#1861),
That library only supports Apache HTTP Client v5, which is not supported by Unirest.

Quoting myself here from the [`#proj-dependency-track-beta`](https://owasp.slack.com/archives/CTC03GX9S/p1668958913115149?thread_ts=1667935093.852909&cid=CTC03GX9S) Slack channel:

> The library requires Apache httpclient5, we still use v4. We can migrate DT’s client pool to v5, but Unirest does not support that version of httpclient yet. I’d count staying on v4 as technical debt, so it has to be done anyway. Will be a bigger refactoring though, and we may need to drop Unirest or contribute httpclient5 support to it.

### Proposed Behavior

In areas where Unirest is currently used, refactor to use the Apache HTTP client directly.

This will make it easier to migrate to version 5 of the HTTP client in a later enhancement.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by stevespringett** [comment]
What if we submitted a PR to upgrade Unirest to HTTP Client v5 instead? It might be less work.

**Comment by msymons** [comment]
Why not switch DT Unirest usage to the shaded version?  Would that not allow DT to continite using Unirest AND Apache HTTP Client v5 side by side?

**Comment by nscuro** [comment]
@msymons Unirest is currently used a convenience wrapper around Apache HTTP client. The underlying client is configured by DT with various proxy-, timeout-, and connection pooling customizations. This is important so that all HTTP interactions initiated by DT behave the same. Using both v4 and v5 would work, but it's dirty and I'd rather not do it.

@stevespringett I will look into it. But there have been some breaking changes and I'm not really interested in refactoring large portions of Unirest's internal code. It will also be a breaking change for them, requiring a new major version etc.

**Comment by mehab** [comment]
If we adopt the latest release of unirest client then we would need more refactoring work in dependency track https://github.com/Kong/unirest-java/blob/v4.0.0-RC7/UPGRADE_GUIDE.md#upgrading-to-unirest-40 
I believe directly using the apache http client would be easier to work with. Also it would give uniformity in the DT code as well.

**Comment by nscuro** [comment]
Yeah, they dropped support for Apache HTTP clients completely in favor of the Java-native client. So now we'd not only have to migrate existing code, but write an entirely new integration. With the danger of us having to maintain that integration.

If https://github.com/jeremylong/vuln-tools would support the Java client, we could switch over to that one. But the lib is targeting Java 8 so there's no way that would work.

I think the best way forward would be to migrate to Apache HTTP Client v5 and drop Unirest.

**Comment by mehab** [comment]
I am working on this change :)

**Comment by nscuro** [comment]
@stevespringett FYI, as `vulndb-data-mirror` also had a dependency on Unirest, we decided to port the logic we needed over to the DT codebase and rewire it to use the Apache HTTP client instead. This will also make it easier for us to react to bug reports in the VulnDB logic, or adjust it to new API changes.
