### ISSUE TITLE
Dependency graph is not generated for NPM SBOM

### ISSUE THREAD

**Issue by g-sahil22** [DependencyTrack/dependency-track#2380]
### Current Behavior

I generate SBOM generated by cdxgen for NPM and when I upload the SBOM in the dependency track, the Dependency graph is not generated 
![image](https://user-images.githubusercontent.com/100830439/212307589-5432cbd7-8771-40f2-8849-7f068b833de0.png)

The dependencies section is also present in generated SBOM 

### Steps to Reproduce

1.  Generate SBOM using cdxgen (cdxgen -o bom.json)
2. upload SBOM in dependency track 

### Expected Behavior

Dependency graph will be visible 

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by stevespringett** [comment]
LIkely an issue with the SBOM. Can you attach please?

**Comment by sgupta22altair** [comment]
Thanks for the response @stevespringett 

Yes, the issue is only with the SBOM, I have already raised the issue in AppThreat
https://github.com/AppThreat/cdxgen/issues/216

But I also tried to generate SBOM using [cyclonedx-npm](https://www.npmjs.com/package/@cyclonedx/cyclonedx-npm) tool 
but I got the below error from Dependency Track
![image](https://user-images.githubusercontent.com/100830439/212411358-ec4597b1-fe28-462b-bf0d-07f830f1d061.png)

Not sure why cyclonedx-npm tool generates a purl with a length of more than 255

**Comment by nscuro** [comment]
> Not sure why cyclonedx-npm tool generates a purl with a length of more than 255

`cyclonedx-npm` has a flag for exactly this purpose:

```
  --short-PURLs Omit all qualifiers from PackageURLs.
                This causes information loss in trade of shorter PURLs, which might improve digesting these strings. 
                (default: false)

```

**Comment by prabhu** [comment]
I am fixing cdxgen for this bug. But is it possible to enhance the dependency track ui to render multiple dependency tree even if they do not have a single root node? For example,

```
A
B - C
D - E - F
G
H - I
```

This would tremendously benefit cdxgen with an upcoming mode called `universal` where it would opportunistically parse as many components as possible but only render the dependency tree for only those where it has a lock file.

**Comment by sgupta22altair** [comment]
I have one question, is it mandatory to add dev dependencies in SBOM, because in the Dependency graph I am only able to see production dependencies
