### ISSUE TITLE
Add support for signed XML SBOMs

### ISSUE THREAD

**Issue by jamesbeegen** [DependencyTrack/dependency-track#2386]
### Current Behavior

Currently, Dependency Track is not able to parse a CycloneDX XML SBOM with a <Signature> block indicating that it is signed. No components are listed after uploading a signed SBOM.

### Proposed Behavior

Allow dependency track to accept a CycloneDX XML SBOM with a <Signature></Signature> block to support SBOMs signed with the CycloneDX CLI. 

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by jamesbeegen** [comment]
To clarify, add support for the API to accept sign SBOMs. I can upload Signed SBOMs via the UI, but API functionality is needed.

**Comment by nscuro** [comment]
Hey @jamesbeegen, thanks for reporting!

If it works via UI, it should work via API, too. The UI is just invoking the REST API, there's no technical difference between it and other clients.

Can you share the API request you're using to upload via API, so we can better understand what is happening?

**Comment by jamesbeegen** [comment]
@nscuro Thanks for the reply - this issue can be closed. The issue falls under the scope of the Dependency Track Jenkins plugin. When using the API according to the docs there are no issues.
