### ISSUE TITLE
Task scheduler is not refreshing project vulnerabilities

### ISSUE THREAD

**Issue by Rokkart** [DependencyTrack/dependency-track#2387]
### Current Behavior

Hello.

It seems that I have an issue regarding the refresh of vulnerabilities in the project view.
I have multiple projects containing the zip4j:2.10.0 dependency. When a SBOM is uploaded on one of these projects, the vulnerability related to this dependency appears correctly. However, the same vulnerability is not displayed on other projects containing the same dependency. The only difference is that no SBOM has been uploaded since the vulnerability was published. That's why I think this problem is related to the task scheduler.

Here are the components :
![Screenshot 2023-01-16 at 16 13 31](https://user-images.githubusercontent.com/17828506/212743600-a1e99515-2fac-4ca0-b9b9-6f79965719cc.png)

Here is the component updated with the recent vulnerability :
![Screenshot 2023-01-16 at 16 29 00](https://user-images.githubusercontent.com/17828506/212743787-b41221f1-cf82-490a-b084-906dc9282712.png)

Here is the same component without any vulnerability related :
![Screenshot 2023-01-16 at 16 29 29](https://user-images.githubusercontent.com/17828506/212743915-99529912-d269-4d25-9891-b3656df2406b.png)

I recently updated Dependency Track to 4.7.0 and I manually refreshed the vulnerabilities on the second project. The vulnerability finally appeared and is related to the component.

### Steps to Reproduce

1. An existing vulnerability is not associated to an existing component
2. The scheduled tasks are configured
3. The vulnerability is not associated to the vulnerable dependency unless a SBOM is uploaded

### Expected Behavior

The vulnerability should be associated to the component when the task scheduler is running.

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

14

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
@Rokkart Could you please share a screenshot of your Task Scheduler configuration `Home > Administration > Configuration > Task Scheduler` and your apiserver logs (redacted if need be) ?

**Comment by mnanse** [comment]
Hello,

After some research, I found that the task scheduler is working well. My colleague edited the task scheduler configuration but didn't restart the server. 

Thank you anyway. This issue can be closed
