### ISSUE TITLE
"Azure Active Directory app registration" link in the "Getting Started" docs goes nowhere

### ISSUE THREAD

**Issue by roadSurfer** [DependencyTrack/dependency-track#2392]
### Current Behavior

When looking through the docs on how to configure [OpenID with Azure AD](https://docs.dependencytrack.org/getting-started/openidconnect-configuration/#azure-active-directory), I spotted a link to "Azure Active Directory app registration". On clicking it I was simply taken to the head of the document.

### Steps to Reproduce

1. Navigate to the docs on how to configure [OpenID with Azure AD](https://docs.dependencytrack.org/getting-started/openidconnect-configuration/#azure-active-directory)
2. Click on the "Azure Active Directory app registration" link
3. Get taken to the top of the document

### Expected Behavior

To go either to an MS site _or_ to DependencyTrack specific information.

Is there perhaps some specific config that is require for DT on the AD side of things? Would that explain defects like [1488](https://github.com/DependencyTrack/dependency-track/issues/1488)?

I am not altogether sure what is correct here.

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

N/A

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by roadSurfer** [comment]
We are going to be setting up DT against AD as an OpenID provider.
If I can get all the AD config details from IT, and permission to do so, I will create a merge request with a document update,
I am aware that you can test each and every possible system/combination.

**Comment by msymons** [comment]
@roadSurfer,  when I followed the steps to reproduce using Firefox 108.02, I was taken to the correct anchor.  I only get taken to the top of the page when copying the link and opening it in a new browser tab.

The section you want is right down at the bottom of the page.

**Comment by roadSurfer** [comment]
OK, so that is flippin' weird as it didn't work for me yesterday!
Works now though. Thanks!
