### ISSUE TITLE
Transitive dependenices are not handled after ingestion of hierarchically merged BOMs

### ISSUE THREAD

**Issue by roadSurfer** [DependencyTrack/dependency-track#2411]
### Current Behavior

The Dependency Graph from a hierarchically merged BOM does not show transitive dependencies.

### Steps to Reproduce

1. Upload "bom_foo.xml":
![foo_deps](https://user-images.githubusercontent.com/38717523/214949845-6e83aa56-e7b6-4af8-a6a2-93657960a3c4.png)
2. Upload "bom_bar.xml":
![bar_deps](https://user-images.githubusercontent.com/38717523/214949877-98e93007-8950-4561-b25e-e9d7fe9420ca.png)
4. Hierarchically merge to the `foo` and `bar` BOM: e,g, `docker run --rm -v<bom location>:/tmp/target --name cyclonedx cyclonedx/cyclonedx-cli:0.24.2 merge --input-files /tmp/target/bom_foo.xml /tmp/target/bom_bar.xml --input-format xml --output-file /tmp/target/bom_foobar.xml --output-format xml --hierarchical --group tld.domain --name foobar --version 0.0.1-SNAPSHOT`
5. Upload the resulting "bom_foobar.xml" and observe that only the top-level dependencies are present:
![missing_deps](https://user-images.githubusercontent.com/38717523/214950037-3ddb2459-2ca2-4667-9f48-fd4f585e537f.png)
8. Query the database and to confirm that the `direct_dependencies` information is missing (PGSQL): `SELECT "GROUP", "NAME", "DIRECT_DEPENDENCIES" FROM "COMPONENT"
WHERE "PROJECT_ID" IN (SELECT "ID" FROM "PROJECT"
WHERE "NAME" LIKE 'bom_foobar')`
![missing_directs](https://user-images.githubusercontent.com/38717523/214950171-95d6e45f-334a-45cf-8dc5-aa03c2289ee7.png)

[boms.zip](https://github.com/DependencyTrack/dependency-track/files/10512844/boms.zip)

### Expected Behavior

When the result of a hierachical merge is uploaded, one would expect the Dependency Graph to be able to drill down all the dependencies and not just the top level.

This _seems_ to be caused by the components no longer all being "top-level" in the BOM after the hierachical merge. Most are now components-of-components. This can be corrected on line 136 of `BomUploadProcessingTask.inform(Event)` by passing `flattenedComponents` instead. So:
`ModelConverter.generateDependencies(qm, cycloneDxBom, project, components);`
becomes:
`ModelConverter.generateDependencies(qm, cycloneDxBom, project, flattenedComponents);`
After this change everything seems to work because the transitive `for` loop in `generateDependencies` can now find all the components from the dependencies:
![fixed_deps](https://user-images.githubusercontent.com/38717523/214948498-ec3715f0-f3f2-4378-97ce-39b67f633670.png)
Running the previous query also shows the `direct_dependencies` column populated:
![populated_directs](https://user-images.githubusercontent.com/38717523/214948623-99821c4b-cb32-4f9f-b8af-77d4e8de3090.png)
Unfortunately I am not knowledgable enough about this code base to fully assess the impact of this change.

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

N/A

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by stevespringett** [comment]
The BOM provided (bom_foobar) has a break between direct and transitive dependencies.

* tld.domain.foobar@0.0.1-SNAPSHOT
  * tld.domain.foo@0.0.1-SNAPSHOT:pkg:maven/tld.domain/foo@0.0.1-SNAPSHOT?type=jar
  * tld.domain.bar@0.0.1-SNAPSHOT:pkg:maven/tld.domain/bar@0.0.1-SNAPSHOT?type=jar

Neither 
`tld.domain.foo@0.0.1-SNAPSHOT:pkg:maven/tld.domain/foo@0.0.1-SNAPSHOT?type=jar`
or 
`tld.domain.bar@0.0.1-SNAPSHOT:pkg:maven/tld.domain/bar@0.0.1-SNAPSHOT?type=jar`
have any dependencies listed in the BOM.

This is not an issue with Dependency-Track. The issue likely is with CycloneDX CLI.

**Comment by roadSurfer** [comment]
Really sorry to seemingly be wasting your time with this @stevespringett, but am I not seeing the dependencies stated on lines 85 and 92 of `bom_foobar.xml`?
```
<dependency ref="tld.domain.foo@0.0.1-SNAPSHOT:pkg:maven/tld.domain/foo@0.0.1-SNAPSHOT?type=jar">
    <dependency ref="tld.domain.foo@0.0.1-SNAPSHOT:pkg:maven/tld.domain/subfoo@0.0.1-SNAPSHOT?type=jar" /> 
</dependency>
```
And:
```
<dependency ref="tld.domain.bar@0.0.1-SNAPSHOT:pkg:maven/tld.domain/bar@0.0.1-SNAPSHOT?type=jar">
  <dependency ref="tld.domain.bar@0.0.1-SNAPSHOT:pkg:maven/tld.domain/subbar@0.0.1-SNAPSHOT?type=jar" />
</dependency>
```
When I stepped through the code prior to the proposed change, only the top two components (`foo` and `bar`) were passed for dependency matching and not their nested components.
It did look like all the dependencies (including the two mentioned above) were checked, but of course `subfoo` etc could not be matched to a component as they were never passed in.

I am more than happy to go and open an issue against `cyclonedx-cli`, but I am not sure I can explain this "break".

**Comment by nscuro** [comment]
@stevespringett I think @roadSurfer is correct in that we do pass the wrong components list to `ModelConverter.generateDependencies`. 

https://github.com/DependencyTrack/dependency-track/blob/7cfc466baf7548ddb758f9e7b008b2d4aaedd148/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java#L134-L137

The current implementation will only ever consider top-level components. And indeed, passing `flattenedComponents` instead of `components` to `ModelConverter.generateDependencies` fixes the issue. I was able to reproduce.

`bom_foobar.xml` has a complete dependency graph. I can't find any inconsistencies in it myself. 

@roadSurfer, would you like to submit a fix PR yourself to collect the well deserved credit, or do you prefer us doing it?

**Comment by stevespringett** [comment]
@nscuro I do not understand how a PR would fix this. `bom_foobar.xml` has an incomplete dependency graph which was a result of using the CycloneDX CLI.

The metadata component is `tld.domain.foobar@0.0.1-SNAPSHOT` which has two direct dependencies:
- `tld.domain.foo@0.0.1-SNAPSHOT:pkg:maven/tld.domain/foo@0.0.1-SNAPSHOT?type=jar`
- `tld.domain.bar@0.0.1-SNAPSHOT:pkg:maven/tld.domain/bar@0.0.1-SNAPSHOT?type=jar`

Neither of these two direct dependencies have an associated dependency element, thus the graph is broken. You'll never get to the transitive dependencies since the BOM doesn't specify what they are.

**Comment by nscuro** [comment]
Are we looking at the same BOM? All BOM refs in `bom_foobar.xml` have a corresponding `dependency` node for me. And the nodes correctly reference each other (`foobar -> foo -> subfoo -> subsubfoo` and `foobar -> bar -> subbar -> subsubbar`).

<img width="1025" alt="Screenshot 2023-01-29 at 22 59 51" src="https://user-images.githubusercontent.com/5693141/215357959-02d51954-ff69-438b-a3f4-a725b54f03c4.png">

<img width="1025" alt="Screenshot 2023-01-29 at 23 00 06" src="https://user-images.githubusercontent.com/5693141/215357968-225017f1-b067-49ee-bf85-f52af1207ce8.png">

**Comment by stevespringett** [comment]
Ah, my apologies. Issues with my editor...
