### ISSUE TITLE
/api/v1/search/project returns confusing results

### ISSUE THREAD

**Issue by uvwildos** [DependencyTrack/dependency-track#2414]
### Current Behavior

 https://dtrackapi.api/v1/search/project?query=project
 works fine
 
  https://dtrackapi.api/v1/search/project?query=project-be
  
 returns ALL existing projects.
 
 I have not seen any query syntax ever would support this.

 If its a feature it is probably just missing in the documentation. 

 I have seen a lot of code and systems over the decades and this simply does not make sense!

### Steps to Reproduce

crreate a few projects with dashes in the names

/api/v1/search/project?query=project
vs
/api/v1/search/project?query=project-be

### Expected Behavior

return the projects named in the query

### Dependency-Track Version

4.6.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

10

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by uvwildos** [comment]
https://github.com/DependencyTrack/dependency-track/issues/2310
i found this one pointing out the lack of documentation regarding the query syntax

**what is the query syntax??**

**Comment by uvwildos** [comment]
**after playing around a while I can confirm this is completely useless!!!**

**Comment by nscuro** [comment]
@uvwildos Thanks for raising the issue. I appreciate it can be frustrating when things don't work like expected. Still, when phrasing your sentences, please keep in mind this is a community-driven project, mostly maintained by folks in their free time. Tone it down a notch, and adhere to [basic open source etiquette](https://teejeetech.medium.com/etiquette-in-open-source-projects-f302b6e19c38).

The search API has not gotten lots of attention in a while, and we have a few issues pointing out flaws in it already. #2310, and especially https://github.com/DependencyTrack/dependency-track/issues/2310#issuecomment-1374896321 are good references for why the API behaves like it does right now. Thus, I'm closing this one as duplicate.

**Comment by uvwildos** [comment]
Thanks for the info.
Allow me one short question please. 

I found the other API calls that directly interface with the relational DB

However, my attempt to delete a project via /v1/project/{uuid} fails at the DB constraints towards the components Table. 
To rebuild a cascding delete in the REST controller seems like a very tedious way to do handle that.
Is there maybe another way / api call to delete a project which does a cascading delete? 
Those details are hard to find in the swagger doc.

**Comment by nscuro** [comment]
The endpoint you're using does in fact perform a recursive deletion on all resources related to the project. If this is giving you an error, it's likely a bug. Can you share the error logs so we can investigate?
