### ISSUE TITLE
Latest versions for OSGified a third party library

### ISSUE THREAD

**Issue by mathuriga** [DependencyTrack/dependency-track#244]
We are using OSGified third-party library in order to expose into the environment as OSGi bundles. In order to achieve this, we are creating an OSGi bundle on top of Third-party dependencies by creating a new package which includes the third-party dependencies. Here, I have noticed that when dependency track tries to identify the latest version of OSGified third-party libraries, It shows the incorrect latest available version.

Could you please share the reason for this behavior?

**Comment by stevespringett** [comment]
Latest version detection relies on an accurate PackageURL. If the PackageURL is incorrect or points to the wrong library, the results will not be what you'd expect.

If you're using CycloneDX to automatically generate the BOM (and thus the PackageURLs), then there may be an issue with the CycloneDX Maven plugin. I know I have not tested CycloneDX with OSGi.

**Comment by mathuriga** [comment]
@stevespringett ,

Thanks for the clarification. I'm using CycloneDX maven plugin to generate the BOM. As you mentioned there may be an issue with the CycloneDX maven plugin. I will try to reach out CycloneDX as well regarding this issue.

Further, If you find further insight into this let me know.
