### ISSUE TITLE
MetricsUpdateTask: Handle deleted components/projects more gracefully

### ISSUE THREAD

**Issue by valentijnscholten** [DependencyTrack/dependency-track#2457]
### Current Behavior

An exception occurs when the Metrics Update tasks runs into components that are no longer existing.

```
2023-02-04 22:52:18,075 [] ERROR [org.dependencytrack.tasks.metrics.ComponentMetricsUpdateTask] An unexpected error occurred while updating metrics of component 19d3b8a1-5a8d-4e51-9c5a-0e46532f719a
java.util.NoSuchElementException: Component 19d3b8a1-5a8d-4e51-9c5a-0e46532f719a does not exist
        at org.dependencytrack.tasks.metrics.ComponentMetricsUpdateTask.updateMetrics(ComponentMetricsUpdateTask.java:79)
        at org.dependencytrack.tasks.metrics.ComponentMetricsUpdateTask.inform(ComponentMetricsUpdateTask.java:63)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

https://github.com/DependencyTrack/dependency-track/blob/ceaadcdad26cd8da2382da6fe1e34830cc9dd774/src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java#L78-L81

https://github.com/DependencyTrack/dependency-track/blob/ceaadcdad26cd8da2382da6fe1e34830cc9dd774/src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java#L67-L70

### Proposed Behavior

Add some gracefullness like in 

https://github.com/DependencyTrack/dependency-track/blob/ceaadcdad26cd8da2382da6fe1e34830cc9dd774/src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java#L78-L89

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by msymons** [comment]
Hmm.  This is definitely something should be handled well.  After all, "components that are no longer existing" should be the mark of a Dependency-Track doing its' job well and helping devs to stay on top of thimgs.

eg:  for us,  10 versions of  component X reduced to just 1 (the latest) over the space of a month.  Lots of components no longer existing there!  And lots of instances of component existing transitioning  to component not existing in a very short period of time (we use scripts to  update 60 projects just as quickly as 5 Jenkins nodes can build them).

**Comment by valentijnscholten** [comment]
If #2466 gets merged, this will no longer happen as Component Metrics will be updated only via a Project Metrics event, which will catch the NoSuchElementException.
The only other place where a Component Metrics Update event is dispatched is when refreshing the metrics via the API. There is a check if the component exists. It should be rare to have the component deleted while the event is waiting to be executed.
So probably not worth refactoring the NoSuchElement handling?

**Comment by valentijnscholten** [comment]
Closing this as # 2466 has been merged. Will reopen if we keep getting lots of these.
