### ISSUE TITLE
No data for monitoring

### ISSUE THREAD

**Issue by LIFEcmd** [DependencyTrack/dependency-track#2489]
### Current Behavior

Back-end address：http://192.168.107.102:8080
configure
![image](https://user-images.githubusercontent.com/66239815/218470645-9d56a4cb-d219-49f3-9039-013efe42529d.png)

Prometheus address：http://192.168.107.102:9090
![image](https://user-images.githubusercontent.com/66239815/218470549-f7a5f5a1-5eb5-4590-a0d7-f492d0d5351b.png)
configure
![image](https://user-images.githubusercontent.com/66239815/218470851-65d3ce04-8bab-4ab7-8dd8-5c59dd3ac0b4.png)

grafana address：http://192.168.107.102:3000
![image](https://user-images.githubusercontent.com/66239815/218470377-ca02c19d-ed3a-403f-a0b9-5ad923325ff6.png)
configure
Import file：grafana-dashboard.json

### Steps to Reproduce

It has been used according to the document. Can you tell me what steps are wrong
https://docs.dependencytrack.org/getting-started/monitoring/

### Expected Behavior

The request  **/api/v1/metrics/vulnerability**  interface has data
[
	{
		"year": 2005,
		"month": 11,
		"count": 1,
		"measuredAt": 1676292282048
	},
	{
		"year": 2005,
		"count": 1,
		"measuredAt": 1676292282048
	},
	{
		"year": 2006,
		"month": 5,
		"count": 1,
		"measuredAt": 1676292282048
	},
       ...........
]

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Database Server Version

14

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
@LIFEcmd The metrics path is `/metrics`, not `/api/v1/metrics`.

**Comment by LIFEcmd** [comment]
> @LIFEcmd The metrics path is `/metrics`, not `/api/v1/metrics`.

Thank you for your answer
