### ISSUE TITLE
Downloading BOM cause graph deletion

### ISSUE THREAD

**Issue by FabioRighe** [DependencyTrack/dependency-track#2494]
### Current Behavior

I have a environment deployed in a Docker Swarm, using 4.7.1 versions of both api and front end.
After downloading BOM of any project for a specific version and reloading page, the dependency graph is no longer visible.

Before:
![image](https://user-images.githubusercontent.com/37578397/219009787-d4f45bb2-e73d-4492-a17e-0c963afcb756.png)

After:
![image](https://user-images.githubusercontent.com/37578397/219010251-233f91f3-1405-48d2-a66b-a4f4851f44dc.png)

### Steps to Reproduce

1. Navigate to Projects Tab
2. Click on any project
3. Navigate to Components Tab
4. Click on "Download BOM" -> Inventory
5. Reload page dependency graph 
6. Dependency graph now results empty

### Expected Behavior

Expected no changes in dependency graph

### Dependency-Track Version

4.7.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by Recurse-blip** [comment]
Experiencing the same issue here. I recently upgraded from 4.6.3 to 4.7.1. After downloading the BOM, the dependency graph is no longer available.

**Comment by msymons** [comment]
One question for both @FabioRighe and @Recurse-blip...   What CycloneDX schema version is your BOM?

 I am running DT v4.7.1 and v4.8.0 SNAPSHOT and have a couple of Maven projects still using Schema 1.2  and which do NOT display graphs.  I cannot go back and see now whether the graphs worked in (say)  DT 4.6...  but Schema 1.2 did support dependency graphs and I can see them in the BOMs.

**Comment by FabioRighe** [comment]
I generate my BOM using v2.7.4 of [https://github.com/CycloneDX/cyclonedx-maven-plugin](url). It generates BOM with CycloneDX v1.4, the last version. @msymons with v4.7.1 of dtrack, are you still able to view dependency graphs after downloading a project BOM from the tool UI?

**Comment by Recurse-blip** [comment]
Bom format is `CycloneDX 1.4` 
We use this action https://github.com/CycloneDX/gh-dotnet-generate-sbom on a .NET 6 project.
We have around 366 components as per dependency-track.

Before downloading : 
![image](https://user-images.githubusercontent.com/64206544/224163144-67ae9f4d-46d1-453d-9bb4-c09abea379cc.png)


After downloading the SBOM : 
![image](https://user-images.githubusercontent.com/64206544/224162708-754066cb-e4ba-4a54-b483-fc907b1b20ad.png)

SBOM sample : 
![image](https://user-images.githubusercontent.com/64206544/224163246-095ebae1-7838-4cd0-963f-35eaf07a6aaa.png)

**Comment by msymons** [comment]
Apologies for the delay in responding.  I have reproduced the defect.  It is very easy to do so.

I also uploaded a BOM to a project after the dependency-graph vanished...  the fresh upload restores the graph.
