### ISSUE TITLE
Unable to start normally

### ISSUE THREAD

**Issue by sxgnhs** [DependencyTrack/dependency-track#2498]
### Current Behavior

When I install dependency-track, I use the first method of the official website, but I have waited for a long time, and the vulnerability library has also been initialized. When I access the page, I cannot login using admin/admin

### Steps to Reproduce

1.# Downloads the latest Docker Compose file
curl -LO https://dependencytrack.org/docker-compose.yml

# Starts the stack using Docker Compose
docker-compose up -d

### Expected Behavior

可以正常访问

### Dependency-Track Version

4.6.x

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
Hello @sxgnhs,
What is the UI response when you login with `admin/admin` ? Do you happen to see some errors in the logs when you attempt to login ?

**Comment by nscuro** [comment]
Reporter didn't follow up. Closing.
