### ISSUE TITLE
Unable to render swagger.json definition of dependency tracker

### ISSUE THREAD

**Issue by arpit-singh-alation** [DependencyTrack/dependency-track#2509]
### Current Behavior

I have automated several dependency tracker functionalities (uploading SBOMs, downloading analysis findings etc) using dependency track APIs by following https://docs.dependencytrack.org/integrations/rest-api/ document.
But today all the APIs started failing, for further debugging when I try to render swagger.json definition and gave following error. Even I tried building dependency tracker in local still nothing worked.

![image](https://user-images.githubusercontent.com/91177761/220136067-99e2777b-cc8a-4833-bce4-fb32282dab1f.png)

```{"schemaValidationMessages":[{"level":"error","message":"Deprecated Swagger version.  Please visit http://swagger.io for information on upgrading to Swagger/OpenAPI 2.0 or OpenAPI 3.x"}]}```

### Steps to Reproduce

1. Build dependency tracker .
2. Open swagger UI console. Enter URL : <dependency_track_base_url>/api/swagger.json.

### Expected Behavior

Output the list of API and their usage like

![image](https://user-images.githubusercontent.com/91177761/220137754-3113f5ca-f989-4984-9377-eb7e7d881cc0.png)

### Dependency-Track Version

4.7.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

13.7

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Works fine for me:
![image](https://user-images.githubusercontent.com/5693141/220142515-a709d12d-f6a9-4ef2-a9b0-693df5509a1c.png)

What do you see when you visit `/api/swagger.json` directly, without using any sort of Swagger UI?
