### ISSUE TITLE
 lack of a image manifest for latest and 4.7.1 in dockerhub image

### ISSUE THREAD

**Issue by amergey** [DependencyTrack/dependency-track#2535]
### Current Behavior

Since 4.7.1 dependency track cannot be deployed anymore in Azure ACI, it fails with following error:

`Error: The image 'dependencytrack/apiserver:latest' in container group 'semdeptrackapi' is not accessible. Please check the image and registry credential.`

After lots of research, I found Azure requires images to have a manifest, to run in ACI. dependencytrack images have manifest until 4.7.0, but not for latest/4.7.1

Note there is same issue for frontend

### Steps to Reproduce

1.run `docker manifest inspect dependencytrack/apiserver:latest`

it gives

_no such manifest: docker.io/dependencytrack/apiserver:latest_

### Expected Behavior

Images should have manifest as for 4.7.0

`docker manifest inspect dependencytrack/apiserver:4.7.0`
_{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1369,
         "digest": "sha256:ac0ca24e97a5445d16b2429d6307673a6404b6b54ace206c6027c264cf64ea48",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1369,
         "digest": "sha256:d8cb62058b3a62cd1acb9467e3569884e3187e766ae0847ce00d60069b86fb71",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}_

### Dependency-Track Version

4.7.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Both `4.7.1` and `latest` tags have a manifest for me:

```shell
$ docker manifest inspect dependencytrack/apiserver:4.7.1
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1246,
         "digest": "sha256:33b5ce9c576becb653ff9533be55957f7d0459e36be244dee19a89e8167f09b4",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1246,
         "digest": "sha256:c34ea77d837a39776c808e20f0290eee460e405213990528fb54895609fed24a",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:ab2df30831843c4b17a3c4c406f470dcab38568f84a84ce365da5286008b99e5",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:2b41b0d9b2f69db1e1689b822c41b7084ac0e090e31148b2cefe9a3a55f2b815",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

```shell
$ docker manifest inspect dependencytrack/apiserver:latest
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1246,
         "digest": "sha256:33b5ce9c576becb653ff9533be55957f7d0459e36be244dee19a89e8167f09b4",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1246,
         "digest": "sha256:c34ea77d837a39776c808e20f0290eee460e405213990528fb54895609fed24a",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:ab2df30831843c4b17a3c4c406f470dcab38568f84a84ce365da5286008b99e5",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:2b41b0d9b2f69db1e1689b822c41b7084ac0e090e31148b2cefe9a3a55f2b815",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

Is the behavior you're seeing reproducible on multiple machines / environments?

**Comment by amergey** [comment]
- I see this behavior from my laptop (ubuntu) in my personal network (from France), 
- same behavior for a collegue in office network from  laptop (ubuntu, windows, mac)  (from France), 
- same behavior from an ubuntu VM inside azure (West Europe)

I found no one able to get manifest for latest and 4.7.1, maybe related to the area ? (europe)

**Comment by syalioune** [comment]
FWIW, I'm located in France (Rennes) and both tags do have a manifest :

```shell
$ docker manifest inspect dependencytrack/apiserver:4.7.1
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1246,
         "digest": "sha256:33b5ce9c576becb653ff9533be55957f7d0459e36be244dee19a89e8167f09b4",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1246,
         "digest": "sha256:c34ea77d837a39776c808e20f0290eee460e405213990528fb54895609fed24a",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:ab2df30831843c4b17a3c4c406f470dcab38568f84a84ce365da5286008b99e5",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:2b41b0d9b2f69db1e1689b822c41b7084ac0e090e31148b2cefe9a3a55f2b815",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

```shell
$ docker manifest inspect dependencytrack/apiserver:latest                
{                                                                                                           
   "schemaVersion": 2,                                                                                      
   "mediaType": "application/vnd.oci.image.index.v1+json",                                                  
   "manifests": [                                                                                           
      {                                                                                                     
         "mediaType": "application/vnd.oci.image.manifest.v1+json",                                         
         "size": 1246,                                                                                      
         "digest": "sha256:33b5ce9c576becb653ff9533be55957f7d0459e36be244dee19a89e8167f09b4",               
         "platform": {                                                                                      
            "architecture": "amd64",                                                                        
            "os": "linux"                                                                                   
         }                                                                                                  
      },                                                                                                    
      {                                                                                                     
         "mediaType": "application/vnd.oci.image.manifest.v1+json",                                         
         "size": 1246,                                                                                      
         "digest": "sha256:c34ea77d837a39776c808e20f0290eee460e405213990528fb54895609fed24a",               
         "platform": {                                                                                      
            "architecture": "arm64",                                                                        
            "os": "linux"                                                                                   
         }                                                                                                  
      },                                                                                                    
      {                                                                                                     
         "mediaType": "application/vnd.oci.image.manifest.v1+json",                                         
         "size": 566,                                                                                       
         "digest": "sha256:ab2df30831843c4b17a3c4c406f470dcab38568f84a84ce365da5286008b99e5",               
         "platform": {                                                                                      
            "architecture": "unknown",                                                                      
            "os": "unknown"                                                                                 
         }                                                                                                  
      },                                                                                                    
      {                                                                                                     
         "mediaType": "application/vnd.oci.image.manifest.v1+json",                                         
         "size": 566,                                                                                       
         "digest": "sha256:2b41b0d9b2f69db1e1689b822c41b7084ac0e090e31148b2cefe9a3a55f2b815",               
         "platform": {                                                                                      
            "architecture": "unknown",                                                                      
            "os": "unknown"                                                                                 
         }                                                                                                  
      }                                                                                                     
   ]                                                                                                        
}                                                                                                           
```

@amergey 
What are your docker engine and docker cli versions ?

Only difference I see is that `dependencytrack/apiserver:4.7.0` manifest has a mediaType of `application/vnd.docker.distribution.manifest.list.v2+json` (v2 under docker specific namespace) and `dependencytrack/apiserver:latest | dependencytrack/apiserver:4.7.1` have a manifest version of `application/vnd.oci.image.manifest.v1+json` (v1 under OCI namespace). 

It's maybe some kind of version compatibility issue with the CLI ?

**Comment by amergey** [comment]
Docker version :
`Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        20.10.12-0ubuntu4
 Built:             Mon Mar  7 17:10:06 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       20.10.12-0ubuntu4
  Built:            Mon Mar  7 15:57:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu3.1
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
`
Note that the relevant issue is on azure ACI side, I am able to deploy dependency track in my local docker, so I am not looking  to fix docker manifest inspect on my local machine.

That's said, I did research that could explain why dependency track can be deployed on azure until 4.7.0 but not anymore since 4.7.1 and I found a post from microsoft explaining that public image without manifest could face such issue, it is why I had the idea to check manifest with my local cli and the results I get seemed coherant with their explanation 
 I do not know how to check which version of docker azure is using from ACI by the way

**Comment by syalioune** [comment]
Yup I understand. Since you can reproduce it locally I figure it had to do with either network issue (which I eliminated due to various networks you tested : local, office, azure cloud) or docker cli/engine version issue.

I can indeed reproduce it using a [Docker in Docker image](https://hub.docker.com/_/docker) with your version

1. Run a docker engine with version `20.10.12`

```shell
docker create network some-network && \
docker volume create some-docker-certs-ca && \
docker volume create some-docker-certs-client && \
docker run --privileged --name some-docker -d --network some-network --network-alias docker -e DOCKER_TLS_CERTDIR=/certs -v some-docker-certs-ca:/certs/ca -v some-docker-certs-client:/certs/client docker:20.10.12-dind
```

2. Try manifest inspection

```shell
docker run --rm --network some-network -e DOCKER_TLS_CERTDIR=/certs -v some-docker-certs-client:/certs/client:ro docker:20.10.12-dind manifest inspect dependencytrack/apiserver:4.7.0
```

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1369,
         "digest": "sha256:ac0ca24e97a5445d16b2429d6307673a6404b6b54ace206c6027c264cf64ea48",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1369,
         "digest": "sha256:d8cb62058b3a62cd1acb9467e3569884e3187e766ae0847ce00d60069b86fb71",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

```shell
docker run --rm --network some-network -e DOCKER_TLS_CERTDIR=/certs -v some-docker-certs-client:/certs/client:ro docker:20.10.12-dind manifest inspect dependencytrack/apiserver:4.7.1

no such manifest: docker.io/dependencytrack/apiserver:4.7.1
```

**Comment by syalioune** [comment]
Looking further into this, It's confirmed : [docker CLI < 23.0.1 does not support OCI image manifests](https://github.com/moby/moby/issues/43126).

For more details :

- docker buildx tool embedded in the CLI generate OCI image version since **v0.10.0** : c.f [buildx 1509](https://github.com/docker/buildx/issues/1509)
- DT uses Github Action [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action) in [here](https://github.com/DependencyTrack/dependency-track/blob/master/.github/workflows/_meta-build.yaml#L84)
- Since DT does not specify a release version of buildx to download by the action, the [lastest version is downloaded](https://github.com/docker/setup-buildx-action/blob/a19c1710881d7ce3cf668865cc8459bba5b912aa/src/main.ts#L45)
- [DT 4.7.1 image](https://hub.docker.com/layers/dependencytrack/apiserver/4.7.1/images/sha256-33b5ce9c576becb653ff9533be55957f7d0459e36be244dee19a89e8167f09b4?context=explore) was built on january 31st
- On january 31st, the latest version of buildx was [v0.10.2](https://github.com/docker/buildx/releases/tag/v0.10.2) hence why DT Github actions pipeline pushed an OCI image to docker registry for 4.7.1

Only way forward I see here for you :
- Reach out to Azure support to check the version of the underlying docker CLI and request an update (I can't find the info in Azure doc)
- Pull the image locally with a CLI version having an embedded version of buildx lower than v0.10.0 and push it back to a private registry like Azure Container Registry

**Comment by amergey** [comment]
Thanks for the investigation and the explanation it is really helpful !
