### ISSUE TITLE
Enhanced format od API keys (for easier leak detection)

### ISSUE THREAD

**Issue by szpak** [DependencyTrack/dependency-track#2543]
### Current Behavior

API keys are currently just a set of 32 character length alphanumerical string. This makes them harder to detect as "secrets" by the secret detection tools.

### Proposed Behavior

The new API key format might contain a prefix (e.g. `dta_`) as implemented in GitHub some time ago:
https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/
https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

While it is more important for publicly available services (to be able to quickly revoke leaked token), Dependency Track keys could also be "safer" when detected plaintext in (for example) a Git repository.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by valentijnscholten** [comment]
Great idea, but probably should be moved to https://github.com/stevespringett/Alpine ?

**Comment by nscuro** [comment]
Thanks to @kleest, this will be included in 4.9.

**Comment by szpak** [comment]
Great, thanks @kleest!

Once released we could work toward making it detectable in the security scanners.
