### ISSUE TITLE
The REST API doesn't provide a call to get all versions of a project by name or uuid

### ISSUE THREAD

**Issue by mawl** [DependencyTrack/dependency-track#2548]
### Current Behavior

The REST API doesn't provide a call to get all versions of a project by name or uuid.

And there's no alternative:
* The lookup call needs both, project and version.
* The search call has issues with slashes in project names: https://github.com/DependencyTrack/dependency-track/issues/2310
* There's no call to find projects by properties

### Proposed Behavior

So plz provide a call for that.

We need it to delete expired project versions (think of release channels with eol date) for a project name.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by syalioune** [comment]
Hello @mawl 

You can get all versions of a given project by name using `/api/v1/project?name=XXXX`.
For pagination, you can refer to https://github.com/DependencyTrack/dependency-track/discussions/2157

**Comment by mawl** [comment]
Hi @syalioune,

We are using group/subgroup/project for project names - and it doesn't lead to the expected result:

It searches for group (or) subgroup (or) project in the project name then instead of using the exact name.

Sounds like the same issue as in: https://github.com/DependencyTrack/dependency-track/issues/2310
