### ISSUE TITLE
cpu and disk usage

### ISSUE THREAD

**Issue by ochezeau** [DependencyTrack/dependency-track#255]
### Issue Type:
   [x] defect report

### Current Behavior:
I have installed my "Executable WAR" as a Windows Service to publish at each build my bom using jenkins pipeline, OWASP Dependency-Track Plugin and CycloneDX.

During analysis  my service take more than 90% of the CPU and a dtemp folders are created on my c:\window\temp (during "Dependency-Check analysis task" and "Processing NPM advisories").

Pretty quickly my VM is no longer usable due to :
- CPU overload
- Disk full due to dtemp folders (368Mo per folder)

Maybe my configuration is not correct or i have not understood something,
thank's for help.

### Steps to Reproduce (if defect):
- Install "Executable WAR" on Window 10 as service with WinSW
- publish CyclonDX Java and NodeJS bom with "Dependency-Check analysis task" on Jenkins
- Wait for analysis and several day for disk issue

### Expected Behavior:
- Normal consumption of CPU
- No accumulation of dtemp folders

### Environment:
  
  - Dependency-Track Version: 3.3.1
  - Distribution:  Executable WAR
  - BOM Format & Version: CyclonDx with Maven Plugin 1.2.0 and Npm Plugin 0.2.4
  - Database Server: PostgreSQL
  - Browser: Chrome
  - Jenkins Pipeline with step "dependencyTrackPublisher" (plugin OWASP Dependency-Track Plugin 2.0.2)
  - OS : Windows 10 VM deployed on VSphere with 16Go of Ram and 8 Core
  - Service management for "Executable WAR" : Winsw 2.1.2

**Comment by stevespringett** [comment]
Dependency-Track is designed to use all available CPU cores as it's typically deployed into environments where it's required to perform massive amounts of parallel processing.

You can tweak the amount of worker threads the system will use. Refer to: https://docs.dependencytrack.org/getting-started/configuration/

You can also configure the VM you're using to only use a minimal amount of CPU cores. Dependency-Track requires a minimum of 2 and will not start without that amount. But you can also limit it to only using two CPU cores by configuring the VM to only allocate that many.

Of course, not running Dependency-Track on Windows will be more efficient and make better use of the cores that are there.
