### ISSUE TITLE
Unable to Login - 504 Not allowed on Kubernetes Deployment

### ISSUE THREAD

**Issue by sathish-ather** [DependencyTrack/dependency-track#2566]
### Current Behavior

Unable to login to dependency-track web UI

### Steps to Reproduce

1. Deployed the app via the helm chart based on the steps on the Readme page.

2. All the pods are up and running without any error msg.

3. Exposed via nginx ingress controller with TLS termination.

4. When we try to login on the web-ui with the default creds (admin / admin), it throws 504 Not Allowed. 

PS : Attaching the YAML file for the reference.
[deptrack.txt](https://github.com/DependencyTrack/dependency-track/files/10899314/deptrack.txt)

### Expected Behavior

It should allow us inn with default creds and redirect to the password reset page for admin.

### Dependency-Track Version

4.6.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

13.7

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by sathish-ather** [comment]
![Screenshot 2023-03-06 at 8 12 09 PM](https://user-images.githubusercontent.com/81147114/223142634-18f581bb-022c-49cc-b4f4-fc0e06916710.png)


Added the inspect window on login request.

**Comment by syalioune** [comment]
Hello @sathish-ather 

The backend should be directly reachable from your browser. You need to update your ingress rules to route /api to the backend service.
Right now your browser is sending the API request to the NGINX inside DT frontend container which doesn't know what to do with it.

**Comment by sathish-ather** [comment]
@syalioune Thanks for the quick response.

And i tried with direct front end pod ip and it returning the same error. 

PS : In this case no ingress config in picture.

**Comment by sathish-ather** [comment]
@syalioune Also i am still wondering, How the frontend knows about the backend ?

Because on the deploy yaml of frontend, i don't see any config or env which tells about the backend.

**Comment by syalioune** [comment]
> How the frontend knows about the backend ?

It does not and should not. The frontend itself does not communicate with the backend. It only serves the `API_BASE_URL` to the browser through `config.json` file and then all communications happens between browser and the backend directly.
The frontend only serves static files.

**Comment by sathish-ather** [comment]
But in out helm deployment the "config.json" is commented.

And let me re-phrase the problem statement 

We just followed the below simple steps to re-produce again on diff env.

1.  helm install dependency-track-alpha evryfs-oss/dependency-track

After few mins, there were 3 pods were running
1. apiserver
2. frontend
3. postgres

Now i fetched frontend pod ip and accessed with port number 8080. And it gave the web UI page response and I just entered admin/admin as a creds.

It throws 504 Not Allowed.


We followed with the default values from the helm chart..! Are we missing something or anything needs to be done additionally ?

**Comment by syalioune** [comment]
> But in our helm deployment the "config.json"(configmap) is commented.

See [frontend docker-entrypoint.sh](https://github.com/DependencyTrack/frontend/blob/master/docker/docker-entrypoint.sh) for how it's handled. The file can be provided as is (only works on compose for now. See [issue 60](https://github.com/DependencyTrack/frontend/issues/60)) or generated from environment variables

> Are we missing something or anything needs to be done additionally ?

Yes, the steps I mentioned above. Just using the default values does not necessarily means that it will work. It depends on your configuration. You need to update the values file to

1. Add a routing from `/api` to `dependency-track-apiserver` in the ingress
2. Set env variable `API_BASE_URL` on `dependency-track-frontend` deployment to corresponding externally reachable url `arkadia.atherengineering.in/api`

**Comment by nscuro** [comment]
HTTP 504 indicates an issue with the ingress configuration which is out-of-scope of Dependency-Track. This issue was also raised before we had an official Helm chart.
