### ISSUE TITLE
LastBomImport incorrect type from api

### ISSUE THREAD

**Issue by brianwilkinson** [DependencyTrack/dependency-track#2591]
### Current Behavior

Cannot use generated swagger client / model to retrieve a list of projects from the API

### Steps to Reproduce

1. Helm installed Dependency-track v4.7.1 to private kube cluster
2. docker run -it --rm -v .:/generated openapitools/openapi-generator-cli:v6.4.0 generate -i https://<myurl>/api/swagger.json -g go -o /generated
3. Used generated client / model to perform GET /api/v1/project (get all projects)
4. Received 200 OK but got the following error :  Time.UnmarshalJSON: input is not a JSON string

### Expected Behavior

I managed to trace this down to the generated Project model:

// Project struct for Project
type Project struct {
        ....
	LastBomImport *time.Time `json:"lastBomImport,omitempty"`
        ....
}

I would expect this to be encoded like {..., "lastBomImport": "2023-03-10T14:46:13.000005366Z", ...},
Got {...,"lastBomImport":1678355957170, ...}

However, the generated code appears to be correct according to the swagger api doc so either:

1. The swagger doc is incorrect and should specify that 'LastBomImport' is an int64, or
2. More likely something goes wrong when this field is serialised.

### Dependency-Track Version

4.7.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
Hello @brianwilkinson 

The inconsistencies of the current exposed `swagger.json` are unfortunately already known : See #2492, #1958, #1276 and #840

For the time being, since you are trying to generate a go client, you can maybe try https://github.com/DependencyTrack/client-go ?

@msymons @nscuro : Is it possible to set milestone 4.9 to #840 ? I'm willing to work on this since I need it for my K8s operator project.
