### ISSUE TITLE
OIDC internal 500 error with AAD login

### ISSUE THREAD

**Issue by liquidcowgithub** [DependencyTrack/dependency-track#2613]
### Current Behavior

I'm getting an internal 500 error on the /login call on the SSO redirect back to dependency-track.

Tried enabling DEBUG logging level, but no additional insights in the logs.

Error stack trace as follows:

ERROR [GlobalExceptionHandler] Uncaught internal server error
java.lang.IllegalArgumentException: The value must not be null or empty string
	at com.nimbusds.oauth2.sdk.id.Identifier.<init>(Identifier.java:95)
	at com.nimbusds.oauth2.sdk.id.ClientID.<init>(ClientID.java:54)
	at alpine.server.auth.OidcIdTokenAuthenticator.authenticate(OidcIdTokenAuthenticator.java:70)
	at alpine.server.auth.OidcAuthenticationService.authenticate(OidcAuthenticationService.java:138)
	at org.dependencytrack.resources.v1.UserResource.validateOidcAccessToken(UserResource.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

### Steps to Reproduce

Following the recommended configuration for OIDC with Azure AD: https://docs.dependencytrack.org/getting-started/openidconnect-configuration/#azure-active-directory

Environment variables are as follows:

OIDC_CLIENT_ID=XXX
ALPINE_OIDC_ENABLED=true
ALPINE_OIDC_ISSUER=XXX
ALPINE_OIDC_USERNAME_CLAIM=preferred_username
ALPINE_OIDC_TEAMS_CLAIM=groups
ALPINE_OIDC_USER_PROVISIONING=true
ALPINE_OIDC_TEAM_SYNCHRONIZATION=true

Tried fiddling with enabling/disabling the teams and groups features.

### Expected Behavior

OIDC login with Azure AD should work.

### Dependency-Track Version

4.7.1

### Dependency-Track Distribution

Container Image

### Database Server

Microsoft SQL Server

### Database Server Version

Azure SQL DB

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
Hello @liquidcowgithub 
You are missing the `ALPINE_OIDC_CLIENT_ID` environment variable on the backend side.

**Comment by liquidcowgithub** [comment]
Thanks for the quick response @syalioune.

You were right, I had the `OIDC_CLIENT_ID` set on the backend instead of the correct `ALPINE_OIDC_CLIENT_ID `.

Works as expected now 🙏
Looking forward to taking DT for a test drive!
