### ISSUE TITLE
Dependency Track doesn't support pedigree

### ISSUE THREAD

**Issue by Souhila99** [DependencyTrack/dependency-track#2621]
### Current Behavior

When we import an SBOM with pedigree ( we have Enterprise packages with Third-party software packages), we have this behavior:

- Dependency Track shows only the Enterprise packages, the Third-party software components are not detected by dependency track.
- Dependency Track doesn't detect the vulnerabilities for the enterprise packages.

### Steps to Reproduce

- Build an SBOM with affected packages with pedigree and ancestors (Enterprise package that is built using third-party software packages).
- Create a new project and Import the SBOM to Dependency Track.
- Display the components list of the created project and check if it contains all the components that are in the SBOM (Enterprise component and third-party software components).
- Check if the vulnerabilities are detected.

### Expected Behavior

- Dependency Track has to show both the Enterprise packages and the Third-party software packages.
- Dependency Track has to detect the vulnerabilities for these packages.

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

15.1

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by stevespringett** [comment]
Duplicate of #919
