### ISSUE TITLE
Notification template MSTeams shows empty "Project" and "Component"

### ISSUE THREAD

**Issue by mvandermade** [DependencyTrack/dependency-track#2638]
### Current Behavior

![image](https://user-images.githubusercontent.com/33425497/229555560-7ef14c4c-a618-4d1f-88a7-1ebd2f439c79.png)

### Steps to Reproduce

1. Set up notification with the MSTeams template
2. Upload project with known vunerabilities

### Expected Behavior

Use the same values as the Slack integration does namely the values in subject.component. (Slack file here: <https://github.com/mvandermade/dependency-track/blob/9e3a50919206e7b265c629dbf9891907d3a4da91/src/main/resources/templates/notification/publisher/slack.peb>)

I have a commit here that makes the MSTeams notification populate the Project and Component again:
<https://github.com/DependencyTrack/dependency-track/compare/master...mvandermade:dependency-track:fix-project-component-missing-msteams#diff-822e5aeb4a9489b450743487fc97169fd20a562f787ac929d053e4bc6cea854d>

### Dependency-Track Version

4.7.1

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
Hello @mvandermade 

Thanks for the analysis and the suggested fix. Seems correct to me.

> I have a commit here that makes the MSTeams notification populate the Project and Component again:
https://github.com/DependencyTrack/dependency-track/compare/master...mvandermade:dependency-track:fix-project-component-missing-msteams#diff-822e5aeb4a9489b450743487fc97169fd20a562f787ac929d053e4bc6cea854d

Can you provide a PR with your changes ? See https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#contributing-code
