### ISSUE TITLE
Dependency Track High CPU Behaviour

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#264]
### Issue Type:
  - [X] defect report
  - [ ] enhancement request
  
### Current Behavior:
Dependency-Track v3.3.1 was running with 25 projects (all maven) succesfully analysed (manual upload of CycloneDX BOM) and with a total of 1000 components.

CPU usage was around 3%.

On 14 December, I then succesfully analysed my first npm project (also using cycloneDX but this time working in a Jenkins pipeline) with 1003 components.

Three days later (after a weekend and with me now being on vacation) the owner of the npm project disabled `dependencyTrackPublisher` in the pipeline as it was endlessly stuck on...

`[DependencyTrack] Polling Dependency-Track for BoM processing status`

The DT server logs show that the the last occurence of `DependencyCheckScanAgent` event was on 19 December.  

I returned to work 3 weeks later on 7th January to find DT UI displaying...

![image](https://user-images.githubusercontent.com/4938718/50983769-1c415780-14f8-11e9-9d27-f890196c90e7.png)

There were no errors in the logs from 14th December to 7th January apart from a couple of PostgreSQL connect errors (8003 and 8006).  Mostly, things looked OK (lots of `NistMirrorTask` etc).

After upgrading Dependeny-Track to v3.4.0 on 7th January, the UI looked OK...  but things were still not working properly.

A manual upload of a CycloneDX BOM reported success in the UI - but resulted in no analysis being performed.
A `dependencyTrackPublisher`  synch of CycloneDX BOM from Jenkins resulted in endless "Polling" entries in the Jenkins console output.
A restart of DT folllowed by an immediate manual CycloneDX BOM upload did produce and analysis... but this was temporary.

**I think I have solved the problem**.  I found that DT was still running on an [Azure B Series burstable VM](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#b-series)

This gave the folllowing CPU usage....

![image](https://user-images.githubusercontent.com/4938718/50985709-e94d9280-14fc-11e9-9dd0-3955ffbf0430.png)

Thus,  I upgraded the server to a higher spec and things look OK so far.  I have read #255 and the response (worker threads, etc), but upgrading the VM took only a few minutes to do!

In retrospect there are still a couple of things that were not as expected...

### Expected Behavior:
1. Should an npm project have such a huge performance impact?  (see CPU graph).  Although it doubled the number of components known to the system, the biggest visible difference seems to be that almost every license is "resolved" (has a link) whereas the maven projects all list licences as text alone.
2. DT server should spot and log CPU problems.  In my environment, I have access to the logs - but I had to request the CPU graph from someone else.  Covered by #260?
3. When polling for dependency-track-plugin should not wait so long when polling DT server before failing. 

### Environment:
  
  - Dependency-Track Version:  3.3.1 and then 3.4.0
  - Distribution: [Executable WAR]
  - BOM Format & Version: CycloneDX
  - Database Server: [PostgreSQL]

### Other Details:
Occurred a couple of time between 14th and 18th December but not sure if there is any connection to this issue.  The database is "Azure PostgreSQL" (ie, separate to DT VM) and uptime is supposed to be really good.

```
2018-12-14 18:08:03,169 [] WARN [com.zaxxer.hikari.pool.ProxyConnection] HikariPool-2 - Connection org.postgresql.jdbc.PgConnection@62928ff4 marked as broken because of SQLSTATE(08006), ErrorCode(0)
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:335)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
```

**Comment by stevespringett** [comment]
NPM will have a higher performance impact (as will OSSIndex) due to both of them being network services that have specific API restrictions in place to prevent abuse. So the DT server has to do more. But in v3.4 and previous, DT was very ineffecient in it's use to HttpClient objects, which are extremely expensive to make. This is being fixed in 3.5 (hardening release) with most of the work is already done.

DT will never be able to spot CPU problems. Thats the responsibility of the higher layers of abstraction or the actual host OS. If things need to be tuned, they can be in much the same way an Oracle database doesn't self tune, but it can be tuned.

Agree on adding a hard limit for the poling before failing the build. I'm currently working on the next version so I'll add this.

Hikari will typically recover from connection issues, that's why it was chosen. But with Postgres, it doesn't work as well as it does with others. This seems to be a driver issue, but the Hikari project has a bunch more info on that. Commercial drivers may be an option.

**Comment by msymons** [comment]
Thanks for the feedback... but what is Hikari?  I know you are not referring to the manufacturer of fish food =)

Revisiting our CPU graph a day after VM update gives us...

![image](https://user-images.githubusercontent.com/4938718/51045202-eadd9000-15ba-11e9-8ccf-7cc7373496e2.png)

Although we have not yet played with threads config, there still seems to be something wrong here.  The step change in CPU is exactly every 6 hours, matching `DependencyCheckScanAgent` event in logs.  I would expect the CPU usage to spike...  but not to stay high.

Is there anything you would like me to look at?

**Comment by stevespringett** [comment]
https://github.com/brettwooldridge/HikariCP

Every 6 hours there is an LDAP synchronization event and a vulnerability analysis event. The vulnerability analysis event will kick off scanners (NPM Audit, OSSIndex, Dependency-Check) if they are enabled. The DependencyCheckScanAgent is part of DependencyCheck, not Track. If you're using CycloneDX for your projects and have OSSIndex enabled, you may want to consider disabling Dependency-Check and see if that improves things.

**Comment by msymons** [comment]
I really do think that npm might be problem.  As originally reported, the problems only started after the 1st npm project was analysed.

I'm now using CycloneDX exclusively in DT, although jenkins jobs are still additionally generating DependencyCheck reports for local consumption and for comparison.  They'll be zappped when everyone is happy with DT.

I read the [best practice documentation](https://docs.dependencytrack.org/best-practices/) and understand that switching to OSSIndex is a good thing to do, in and of itself.

I registered for an OSSIndex account and configured Dependency-Track server v3.4.0 to enable OSSIndex and provide the username and token.

(Aside:  a test button would be useful on this screen).

I currently only have a single (maven) jenkins job that uploads a CycloneDX BOM - and it is currently configured to only run on demand,

My npm pipeline job with CycloneDX publishing that succesfully synched back on 14th December had the publish bit commented out in jenkinsfile on 18th december, pending a resolution to the CPU problem (that is, from the user's perspective, a resolution to the looping "Polling".

I just ran the maven job....  it got stuck on "polling".  CPU is flatlined at 90% and 
has been so since 12 hours after the last service restart (and 12 hours after the previous restart as well, as shown in CPU graph attached Friday 11th January.

So, I am pretty certain that restarting the service again will allow me to succeed with running that maven job, as long as it's run within 12 hours.

How best to test npm?  I can delete the npm project in DT - but is that enough?  Or I can disable NPM audit  in DT server.  Or do both.  I seem to remember that deleting with project will still retain the npm components in the database, right?

**Comment by stevespringett** [comment]
Deleting the project will not help, as the components will still be there as will continue to be scanned. Disabling the npm audit scanner should work.

**Comment by stevespringett** [comment]
In the future, if there are specific defects, create a defect for each. I've fixed the polling issue but cannot close this ticket because it contains other things.

**Comment by msymons** [comment]
I disabled both the npm and dependency-check scanners on the server  but, based on the CPU history, I'll only be able to see the impact after 12 or 18 hours.  If there is a big difference then I'll re-enable npm scanner but leave dependency-check disabled (thus using CycloneDX BOM and OSS Index scanner per best practice docs).

I'll most definitely log separate issues so that you get the visibility that you need.

**Comment by msymons** [comment]
Following on from my previous comment, disabling both the npm and dependency-check scanners on the server had the effect of dropping cpu usage from 90% to 3%  (after service restart) and staying there (bar period blips to 10% as DT tasks were run)

ie, there was no step change to 50% cpu usage after 6 hours followed by a further step change to 98% after another 6 hours elapsed.

This morning, I re-enabled npm alone (no dependency-check and no service restart).  Exactly 2 hours later the CPU usage surged to over 50% and stayed there.

The logs show:

```
2019-01-16 11:14:56,071 [] INFO [org.dependencytrack.tasks.scanners.NpmAuditAnalysisTask] Starting Node Audit analysis task
2019-01-16 11:14:56,071 [] INFO [org.dependencytrack.tasks.scanners.NpmAuditAnalysisTask] Analyzing portfolio
2019-01-16 11:14:57,549 [] INFO [org.dependencytrack.tasks.scanners.NpmAuditAnalysisTask] Processing NPM advisories
2019-01-16 11:14:57,888 [] INFO [org.dependencytrack.tasks.scanners.NpmAuditAnalysisTask] Analyzing 774 component(s)
```
I see that there is no event for the analysis task ending.  Searching through all my logs I see that there has never been such an event.  Is that significant?

**Comment by msymons** [comment]
@stevespringett, I have performed testing using the snapshot:
* Dependency-Track v3.5.0-SNAPSHOT
* Build ID: 50bb83e2-0c76-4f05-95ab-4245bd2014e8 

The only scanner that is enabled is npm.  After creating a single project, and manually uploading a BOM, DT snapshot reports (1,011 components and 6 vulnerabilities) and then CPU usage maxes out within a few hours.  ie, the same behaviour as with v3.3.1 and v3.4.0

Should this issue be reclassified from "question" to defect"?

**Comment by stevespringett** [comment]
Have you tried performance optimizing the worker threads?
```
alpine.worker.threads
alpine.worker.thread.multiplier
```

If using Postgres, have you tried disabling the connection pool?
```
alpine.database.pool.enabled
```

What Java version are you using and who is the vendor (IBM, Oracle, OpenJDK, etc)?

Do you have it running inside a Docker container?

**Comment by msymons** [comment]
Thanks for the response...  I'll be out of the office for the next few days but will investigate:

* worker threads
* connection pool

...on my return.

I do not think that connection pool would be the problem as my test instance of DT 3.5 Snapshot is running with local H2 database.

java = jdk1.8.0_181
DT is running with Executable WAR.  No Docker.

**Comment by stevespringett** [comment]
Confirmed to be an issue by multiple people in the Slack channel

**Comment by stevespringett** [comment]
To everyone experiencing this issue, please reply with your config.
For example:

- Dependency-Check enabled: (yes/no)
- NPM Audit enabled: (yes/no)
- OSS Index enabled: (yes/no)
- Notifications enabled: 
  - Slack/Microsoft Teams/Webhooks (yes/no)
  - Email: (yes/no)
  - Console: (yes/no)
- VulnDB enabled: (yes/no)
- LDAP enabled: (yes/no)
- LDAP synchronization enabled: (yes/no)
- LDAP user provisioning enabled: (yes/no)
- Database vendor/version:
- Java vendor/version:
- Host OS vendor/version:
- Distribution:
  - Traditional WAR
  - Executable (embedded Jetty) WAR
  - Docker
- Proxy server enabled: (yes/no)

Finally, are you able to test 3.5.0 SNAPSHOT releases on non-production data? (yes/no)

If you prefer to email your response, do so at steve [dot] springett [at] owasp.org

**Comment by larvel** [comment]
* Dependency-Check enabled: (yes/no)
Yes

* NPM Audit enabled: (yes/no)
Yes

* OSS Index enabled: (yes/no)
No

* Notifications enabled:
   * Slack/Microsoft Teams/Webhooks (yes/no)
Yes
  * Email: (yes/no)
Yes
  * Console: (yes/no)
No
* VulnDB enabled: (yes/no)
Not sure
* LDAP enabled: (yes/no)
Yes
* LDAP synchronization enabled: (yes/no)
Yes
* LDAP user provisioning enabled: (yes/no)
Yes
* Database vendor/version:
ALPINE_DATABASE_DRIVER=org.postgresql.Driver
ALPINE_DATABASE_DRIVER_PATH=/extlib/postgresql-42.2.5.jar

* Java vendor/version:
image: owasp/dependency-track
openjdk version "1.8.0_181"

* Host OS vendor/version:
Dockerimage: owasp/dependency-track

* Distribution:
   * Traditional WAR
  * Executable (embedded Jetty) WAR
  * Docker
Docker

* Proxy server enabled: (yes/no)
Yes, Nginx

**Comment by anderius** [comment]
* Dependency-Check enabled: No (but was enabled some weeks ago)
    * NPM Audit enabled: yes
    * OSS Index enabled: yes
    * Notifications enabled: Slack
    * VulnDB enabled: No
    * LDAP enabled: No
    * Database vendor/version: SqlServer 2012
    * Java vendor/version: Oracle 8u191
    * Host OS vendor/version: Windows Server 2012 R2 (com.microsoft.sqlserver.jdbc.SQLServerDriver from sqljdbc4-6.2.1.jar)
  * alpine.worker.thread.multiplier=1 (40 cores)
    * Distribution:      
      * Executable (embedded Jetty) WAR
    * Proxy server enabled: No

Finally, are you able to test 3.5.0 SNAPSHOT releases on non-production data? Sure!

**Comment by jvlivonius** [comment]
Hello,

I'm also experiencing the high CPU load with the following setup:

* Dependency-Check enabled: no
* NPM Audit enabled: yes
* OSS Index enabled: yes
* Notifications enabled: no
* VulnDB enabled: no
* LDAP enabled: yes
* LDAP synchronization enabled: no
* LDAP user provisioning enabled: no
* Database vendor/version: postgres:10
* Java vendor/version: 
* Host OS vendor/version:
* Distribution:
  * Docker: owasp/dependency-track (3.4)
* Proxy server enabled: yes (Apache reverse proxy)

**Comment by nbl9999** [comment]
Experience same thing where Dependency-Track gets stuck in a loop consumeing 30-40% CPU, UI is down and returns simple text error message. Can't even make it a day without this occurring. Last thing in log is always updating Executing metrics update on the NPM project. Had to resort to implementing an automated restart every 5 hours that alleviates the problem.

- Dependency-Check enabled: Yes
- NPM Audit enabled: Yes
- OSS Index enabled: Yes
- Notifications enabled: No (bugs where implied filters don't work and end up getting spammed as a result, so removed them all)
- VulnDB enabled: No
- LDAP enabled: Yes
- LDAP synchronization enabled: No
- LDAP user provisioning enabled: No
- Database vendor/version: Embedded
- Java vendor/version: Oracle 8u202
- Host OS vendor/version: Windows Server 2016
- Distribution: Executable (embedded Jetty) WAR
- Proxy server enabled: No

Finally, are you able to test 3.5.0 SNAPSHOT releases on non-production data? No

**Comment by ruimda** [comment]
We are experiencing the same CPU problem, goes above 100%, and not producing results as expected.

Dependency-Check enabled:  No
NPM Audit enabled: Yes
OSS Index enabled: Yes
Notifications enabled: No
VulnDB enabled: No
LDAP enabled: No
LDAP synchronization enabled: No
LDAP user provisioning enabled: No
Database vendor/version: H2, the default one
Java vendor/version:
	openjdk version "1.8.0_171"
	OpenJDK Runtime Environment (build 1.8.0_171-b10)
	OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
Host OS vendor/version:
	Linux 3.10.0-862.6.3.el7.x86_64 x86_64
Distribution:
	Traditional WAR in Apache Tomcat Version 9.0.12
Proxy server enabled: Yes
Finally, are you able to test 3.5.0 SNAPSHOT releases on non-production data? No

I have now disabled NPM Scanner and CPU has dropped.

**Comment by stevespringett** [comment]
I'm able to reproduce the issue in v3.4 and v3.5-snapshot. v3.5-snapshot doesn't behave _quite_ as bad, but still has the issue. I'll be diving deep over the next few days trying to determine the cause.

**Comment by stevespringett** [comment]
In my observations, the NPM Audit analyzer is having some issues, and in come instances goes into an endless loop. This will slowly cause thread exhaustion. However, the issue is compounded by the database connection pool which begins to consume threads for database connections it cannot get back. How fast or how often this occurs may be database specific, but fixing the cause (npm) will likely fix the entire cascading effect its having.

**Comment by stevespringett** [comment]
The fixes have been backported to the 3.4 branch. Since this is a p1 defect and v3.5 is likly a month away, I plan on releasing 3.4.1 to solve this issue.

It does not contain any of the other performance enhancements in 3.5, just the high CPU fix itself.

**Comment by stevespringett** [comment]
3.4.1 is released. I would normally close this issue at this point, but I'd like confirmation from @msymons and a few of the other folks that the issue has been resolved.

**Comment by nbl9999** [comment]
Thanks Steve! I'll get it install and tested today, will be back later on today with results. Need several hours to see if it goes off to lala land.

**Comment by jvlivonius** [comment]
Thanks, Steve. Just tested with the new 3.4.1 container and activated npm scanner. It's working fine. The CPU load drops after the scan is completed.

**Comment by nbl9999** [comment]
No issues with 3.4.1, NPM audit has run/completed numerous times and it seems much more stable. Thanks again Steve!

**Comment by msymons** [comment]
I have performed testing with v3.4.1 and everything looks great so far.
