### ISSUE TITLE
Redundant notifications being sent for existing policy violation

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/dependency-track#2655]
### Current Behavior

During policy evaluation, we currently do not check whether a violation existed before, and instead blindly dispatch a `POLICY_VIOLATION` notification for every identified violation.

This causes redundant notifications being sent, every time the policy evaluation is executed.

### Steps to Reproduce

1. Create a policy
2. Create a policy condition that matches at least one component
3. Configure an alert for group `POLICY_VIOLATION`
4. Trigger policy evaluation for the project that contains the chosen component
5. Verify that a notification has been received
6. Trigger policy evaluation again
7. Notice that the same notification has been received again

### Expected Behavior

A `POLICY_VIOLATION` notification should only be sent for newly identified violations, not for existing ones.

### Dependency-Track Version

4.8.0-SNAPSHOT

### Dependency-Track Distribution

Container Image, Executable WAR

### Database Server

N/A

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by sebastienDelcoigne** [comment]
Thanks for the quick fix !
