### ISSUE TITLE
Login failure，beacuse the api requests are set to the wrong host

### ISSUE THREAD

**Issue by zerostar7851** [DependencyTrack/dependency-track#2713]
### Current Behavior

https://docs.dependencytrack.org/getting-started/deploy-docker/
Deploy according to the documentation above， select  Quickstart (Docker Compose)
![image](https://user-images.githubusercontent.com/18433479/234460926-7678bf4a-1273-43ff-9fcb-1ef71f69eac8.png)

### Steps to Reproduce

1.

### Expected Behavior

error request : http://localhost:8081/api/version
right request : http://192.168.5.100:8081/api/version

### Dependency-Track Version

4.8.0

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Hi @zerostar7851, this is not a bug in Dependency-Track, it's a misconfiguration in your setup. 

The example Docker Compose YAML we provide is meant for local testing. It also states that the host configured in `API_BASE_URL` for the frontend container needs to be adjusted when deploying to a server:

```
# NOTE:
#   * This URL must be reachable by the browsers of your users.
#   * The frontend container itself does NOT communicate with the API server directly, it just serves static files.
#   * When deploying to dedicated servers, please use the external IP or domain of the API server.
```
