### ISSUE TITLE
Batch Teams/Slack Notifications

### ISSUE THREAD

**Issue by sebastienDelcoigne** [DependencyTrack/dependency-track#2714]
### Current Behavior

When a vulnerability scan is done, the notification channel receives a notification for each event. Let's say I configure a notification on NEW_VULNERABILITY and the latest scan finds 5 new vulnerabilities, I will receive 5 notifications.

### Proposed Behavior

Add the possibility to group the notifications into a single report so that a daily scan will produce a single notification with the list of the findings.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by msymons** [comment]
Duplicate of #322
