### ISSUE TITLE
Wrong URL generated when opening the Project-Tag on dependency graph site

### ISSUE THREAD

**Issue by maxbeckers** [DependencyTrack/dependency-track#2718]
### Current Behavior

When you're in the dependency graph view and then open the tag you will get 500 errors because of an invalid uuid. The problem in, that the url is generated with ``/projects/projects/?tag=mycooltag`` instead of ``/projects/?tag=mycooltag``

![Screenshot 2023-04-27 094419](https://user-images.githubusercontent.com/11738128/234795434-671218b9-dfc5-4494-8501-b50076114f68.png)

### Steps to Reproduce

1. go to the dependency graph of a project with a tag
2. try to open the tag

### Expected Behavior

The tag is correctly opened like ``/projects/?tag=mycooltag`` and no errors are comming up on the view.

### Dependency-Track Version

4.8.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by msymons** [comment]
I can reproduce this.  It has a defect that was reported last night in Frontend as DependencyTrack/frontend/issues/483
