### ISSUE TITLE
Make CORS configurable to allow cross-origin requests

### ISSUE THREAD

**Issue by adaptivui** [DependencyTrack/dependency-track#272]
Hello,

We would like to develop a portal which displays metrics based on Dependency-Track API. For the moment we use reverse-proxy to by-pass cross-origin request limitations.
It would be interresting to implement CORS in Dependency-Track and make it configurable via a properties file (declare safe domains)

### Issue Type:
  - [ ] defect report
  - [x] enhancement request
  
  
### Current Behavior:

Access to Dependency-Track API from external domains are disallowed 

### Steps to Reproduce (if defect):

Make an ajax request on Dependency-Track API from an external domain

### Expected Behavior:

Configure CORS in application.properties to allow a given domain accessing Dependency-Track API.
Allow fetching Dependency-Track API from the external domain declared as safe

### Environment:
  
  - Dependency-Track Version: 3.3.1
  - Distribution: Traditional WAR
  - BOM Format & Version: Any
  - Database Server: PostgreSQL
  - Browser: Any

**Comment by stevespringett** [comment]
Since you're using a traditional WAR (which provides the most flexibility), I'd recommend using the servlet containers built-in support for CORS. If using Tomcat for example, refer to https://tomcat.apache.org/tomcat-8.5-doc/config/filter.html#CORS_Filter

**Comment by adaptivui** [comment]
It works fine. Thank you @stevespringett !

**Comment by stevespringett** [comment]
Closing. Support for CORS configuration was included in v3.6. as well.
