### ISSUE TITLE
upgrade to Jetty 11 Maven plugin

### ISSUE THREAD

**Issue by melba-lopez** [DependencyTrack/dependency-track#2727]
The upgrade to Jetty 11 Maven plugin will likely break development environments due to the migration of javax to jakarta. DT still relies on Jetty 10. We should likely have a dedicated story specific to the upgrade of Jetty and migration from javax to jakarta. This will impact both DT and Java Alpine.

_Originally posted by @stevespringett in https://github.com/DependencyTrack/dependency-track/issues/2725#issuecomment-1532417022_

**Comment by melba-lopez** [comment]
@nscuro @msymons this was an issue i opened a long time ago per steve's comment.  not sure if there's another issue already opened for this and what extra information should be put in here.

**Comment by nscuro** [comment]
@melba-lopez This issue has a dependency on https://github.com/stevespringett/Alpine/issues/402, which in turn has a dependency on https://github.com/DependencyTrack/dependency-track/issues/840. 

I posted an outline of how all this can be progressed here: https://github.com/stevespringett/Alpine/issues/402#issuecomment-1593407468

... and if that wasn't enough, the above are also preconditions for updating to Java 21 once it's released. 🤪

**Comment by nscuro** [comment]
Will be upgrading to Jetty 12 (current latest version) via https://github.com/stevespringett/Alpine/pull/570 and https://github.com/DependencyTrack/dependency-track/pull/3730.
