### ISSUE TITLE
Dependency track does not show vulnerabilities recommandations

### ISSUE THREAD

**Issue by chaourarimine** [DependencyTrack/dependency-track#2739]
### Current Behavior

I scanned a docker image with Trivy and generated a CycloneDX containing all its vulnerabilities and the recommendations to fix them. The recommendations are not displayed when I upload the file to Dependency Track.
![bom_vulnerability](https://github.com/DependencyTrack/dependency-track/assets/96060278/55014706-418e-471c-b9f2-32be785e62bf)
![dtrack_empty_recommendation](https://github.com/DependencyTrack/dependency-track/assets/96060278/4a5fda02-40a6-44f5-aaa4-199b3f01ab5a)

 

### Steps to Reproduce

1.Upload this file containing all the vulnerabilities of an image and the recommendations to fix them(rename it to *.json). 
[report.txt](https://github.com/DependencyTrack/dependency-track/files/11461240/report.txt)

2. Go to dependency track to see that all recommendations values are empty

### Expected Behavior

I expect to see the recommendation for a vulnerability so I can fix it 

### Dependency-Track Version

4.8.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

10.15

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Duplicate of #1677.
