### ISSUE TITLE
Remove Dependency-Check XML report generation/parsing

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#278]
The embedded Dependency-Check implementation uses the DependencyCheckScanAgent which in-turn generates a report which Dependency-Track then consumes. The parsing of the report leads to increased complexity, model objects, testing requirements, and may be incompatible with report schema changes.

This ticket is to track the removal of XML report generation and parsing from Dependency-Track. In this case, it's beneficial to tightly couple the Dependency-Check integration with the dedicated Dependency-Check scanner. Overall, it will help improve performance and quality which is a focus of the v3.5 release.

**Comment by ZozoZoeLi** [comment]
Hi Steve. Is it possible to actually get CycloneDX Gradle BOM out of the door before this feature is down the ground? Otherwise, it isn't possible for Gradle projects to scan backend dependencies.

**Comment by stevespringett** [comment]
@ZozoZoeLi This is a technical debt/cleanup issue. This ticket does not imply that Dependency-Track will no longer be able to import Dependency-Check reports. That's not the case. This ticket is to document the fact that when Dependency-Track uses the embedded Dependency-Check scanner, that results from the analysis do not have to go through the process of report generation and parsing as it does does.

**Comment by stevespringett** [comment]
Moving to v3.6 as Dependency-Check v5.0.0 will be released shortly which has some changes and Dependency-Track v3.5 will still include ODC 4.0.2.

**Comment by stevespringett** [comment]
This ticket will no longer be done as the functionality is disabled by default in v3.6 (#397) and will be removed in v3.7 (#396)
