### ISSUE TITLE
Auto-Created Projects With Empty Name 

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#279]
### Issue Type:
  - [X] defect report
  - [ ] enhancement request
 
 ### Current Behavior:
Having set up pipeline jobs that use autocreate with `projectName` and `projectversion`, I see over 100 projects succesfully created overnight in Dependency-Track server as the matching Jenkins pipeline jobs run.

However, the implemenation bases `projectName` on Maven project.name - and two projects have been created in DT with blank names (each with a different version).

The problem is that, without a name, DT server provides no link  to the project and without a link there is:

- No way to inspect the project in DT and work out what the source was (where one could fix the problem)
- No way to delete the project via the UI- there's no knowledge of the uuid.

I am sure that I can track things down by using REST to produce the project list (including uuid).  However, I log this for completeness.

### Steps to Reproduce (if defect):
Use dependency-track plugin to auto-create a project using:

- `projectName `= null (I am assuming that the problem is when maven project.name does not exist).
- `projectversion` = something valid

Examine project in UI.

### Expected Behavior:
**Either**:  Dependency Track creates project with a dummy name, thus providing a link to the project.
**Or**: Dependency-Track does not create the project and returns REST response 400.

### Environment:
  
  - Dependency-Track Version: 3.4.0
  - Distribution: Executable WAR
  - dependency-track-plugin: 2.1.0
  - cyclonedx-maven-plugin:   1.3.1

**Comment by stevespringett** [comment]
Project names cannot be null. This is enforced both within input validation of the incoming name as well as in the database schema itself. I wonder however, if the name being used is simply an empty string or a one character space for a name. I'll add this to the quality tests I'm doing for v3.5 and will likely create an upgrader that will search for these types of names and rename them "Unknown" or something to that effect.

**Comment by stevespringett** [comment]
For all model classes that expected a name or some other type of identifier, there was a check for size min of 1, and a check for @NotNull. However, this wasn't good enough. Since upgrading to EE8, @NotBlank is now an option so this will be used in these cases instead. In addition, all string inputs from JSON will now be trimmed (to null) when deserialized automatically. There were a log of other occurrences in several model classes with this general weakness.
