### ISSUE TITLE
Resolve and display dependency trees

### ISSUE THREAD

**Issue by Drewster727** [DependencyTrack/dependency-track#280]
[Feature Request]

dependency-track 3.4.0
cyclonedx-node-module 0.2.4
npm 5.4.2
node 8.6.0

The below is a post from the cyclonedx-node-module issues.

I have a web project using npm to load dependencies. I have the cyclonedx-node-module running on my build server generating a bom file for my project. I'm seeing a dependency in the list that was flagged as critical, and I didn't recognize the package, so naturally I tried to find where it was being referenced.

See "macaddress" dependency in this image:
![image](https://user-images.githubusercontent.com/4528753/52352594-844d6580-29f2-11e9-8cf7-56f99b918290.png)

When I run a scan on my project folder I do not find a direct reference to the "macaddress" dependency in package.json, but I do find it in the package-lock.json file. 
```
"macaddress": {
      "version": "0.2.8",
      "resolved": "https://registry.npmjs.org/macaddress/-/macaddress-0.2.8.tgz",
      "integrity": "sha1-WQTcU3w57G2+/q6QIycTX6hRHxI="
    },
```

I then found that there was a second reference under package-lock.json for "macaddress"
```
"uniqid": {
      "version": "4.1.1",
      "resolved": "https://registry.npmjs.org/uniqid/-/uniqid-4.1.1.tgz",
      "integrity": "sha1-iSIN32t1GuUrX3JISGNShZa7hME=",
      "requires": {
        "macaddress": "0.2.8"
      }
    },
```
Which appears to be the parent dependency pulling "macaddress" in. 
And that comes from...
```
 "postcss-filter-plugins": {
      "version": "2.0.2",
      "resolved": "https://registry.npmjs.org/postcss-filter-plugins/-/postcss-filter-plugins-2.0.2.tgz",
      "integrity": "sha1-bYWGJTTXNaxCDkqFgG4fXUKG2Ew=",
      "requires": {
        "postcss": "5.2.18",
        "uniqid": "4.1.1"
      },
      "dependencies": {
```
And so on...
Eventually, this builds out to a dependency tree like this:
```
css-loader (referenced in "dependencies" section of package.json)
|-cssnano
 |--postcss-filter-plugins
  |---uniqid
   |----macaddress
```

My question is how can we resolve this dependency tree in the cyclonedx-node-module bom generation? Either that or dependency-track itself should resolve this. I'm going to have people asking about critical vuln dependencies and I would *love* to figure out how the heck these are getting pulled in without doing the time-intensive dirty work. Seems like this should be possible.

Let me know if I need to elaborate further.

Thanks!
Drew

**Comment by stevespringett** [comment]
Note to self: The idea here is to reconstruct a dependency tree based on the components in a given project and the ecosystem the components belong to.

**Comment by Drewster727** [comment]
Looking at the bom.xml file:
```
 <component type="library">
            <name>macaddress</name>
            <version>0.2.8</version>
            <description>Get the MAC addresses (hardware addresses) of the hosts network interfaces.</description>
            <hashes>
                <hash alg="SHA-1">5904dc537c39ec6dbefeae902327135fa8511f12</hash>
            </hashes>
            <licenses>
                <license>
                    <id>MIT</id>
                </license>
            </licenses>
            <purl>pkg:npm/macaddress@0.2.8</purl>
            <modified>false</modified>
        </component>
```

You might have to add some metadata to parent components listing their requirements/dependencies to reconstruct a tree? Unless you can communicate out to npm and obtain that info.

**Comment by stevespringett** [comment]
https://github.com/CycloneDX/specification/issues/14

**Comment by stevespringett** [comment]
Initial support for dependency graphs are complete. Future enhancements are planned.

![Dependency Prototype](https://user-images.githubusercontent.com/3878933/110577880-32272300-8129-11eb-94f5-fb6f792c5ab4.gif)

**Comment by nscuro** [comment]
I'm experiencing an issue where the frontend fails to load transitive dependencies. The API server returns the following for the project:

```json
[
    {
        "name": "cyclonedx-go",
        "version": "v0.1.0",
        "classifier": "LIBRARY",
        "directDependencies": "[{\"name\":\"github.com/bradleyjkemp/cupaloy/v2\",\"purl\":\"pkg:golang/github.com/bradleyjkemp/cupaloy/v2@v2.6.0\",\"version\":\"v2.6.0\",\"purlCoordinates\":\"pkg:golang/github.com/bradleyjkemp/cupaloy/v2@v2.6.0\",\"objectType\":\"COMPONENT\"},{\"name\":\"github.com/stretchr/testify\",\"purl\":\"pkg:golang/github.com/stretchr/testify@v1.7.0\",\"version\":\"v1.7.0\",\"purlCoordinates\":\"pkg:golang/github.com/stretchr/testify@v1.7.0\",\"objectType\":\"COMPONENT\"}]",
        "uuid": "1214e499-c23f-4710-ae11-3cead230c268",
        "lastBomImport": 1615413565244,
        "lastBomImportFormat": "CycloneDX 1.2",
        "lastInheritedRiskScore": 0.0,
        "active": true
    }
]
```

Note that the components in `directDependencies` do not have `uuid` fields.

The frontend then tries to fetch the components in its direct dependencies [via UUID](https://github.com/DependencyTrack/frontend/commit/c72e8eaa9518434b0f4a95541fadba9fcc7cff51#diff-a93f35c688d09a47bd65f1d39e511fa8eab6f4c42f7ae475c3f5e127447637c7R96). Because there are no UUIDs in `directDependencies`, it ends up requesting `/api/v1/component/undefined`, which fails.

The root cause seems to be that components have not been persisted at the time the `directDependencies` field is populated, which happens [here](https://github.com/DependencyTrack/dependency-track/blob/626d37f670daf1f10f1de601aa3a3594981b2607/src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java#L73). UUIDs are generated by the persistance layer, thus missing at this point.

**Comment by stevespringett** [comment]
@nscuro good catch. I was not able to reproduce in my local dev environment, but i've submitted a fix which should address the issue.

**Comment by nscuro** [comment]
@stevespringett Thanks, fix confirmed.
