### ISSUE TITLE
The project ID in the web interface and after calling the PUT-request to create the project are different.

### ISSUE THREAD

**Issue by ilichigor** [DependencyTrack/dependency-track#2819]
### Current Behavior

I am writing a small script to check sbom files using Dependency Track.
In the first step, we uploaded the bom file and received the token of the automatically generated project, then we waited for the verification and tried to get the verification results in the third step. The first screenshot shows the token that was returned after the project was created, and the second screenshot shows the identifier from the web interface, they are different. Accordingly, it is not possible to obtain results at the third stage.

![track-report](https://github.com/DependencyTrack/dependency-track/assets/89643928/2f160a69-3a4e-40ce-89bb-8bfca1573040)

![track-report-2](https://github.com/DependencyTrack/dependency-track/assets/89643928/f9f1679c-db33-49bf-941b-e836379b87dc)

### Steps to Reproduce

```
import json
import requests
import base64
import time

def get_vulnerability_report(api_key, url, project_uuid):
    headers = {
        "Content-Type": "application/json",
        "X-Api-Key": api_key
    }

    vulnerability_url = f"{url}/vulnerability/project/{project_uuid}/"
    print(vulnerability_url)
    response = requests.get(vulnerability_url, headers=headers)

    if response.status_code == 200:
        vulnerabilities = response.json()
        print("Vulnerability report retrieved successfully.")
        return vulnerabilities
    else:
        print(f"Error: {response.status_code}")
        print(response.text)
        return None

def upload_and_check_bom(api_key, url, bom_file_path, project_name, project_version, check_interval):
    headers = {
        "Content-Type": "application/json",
        "X-Api-Key": api_key
    }

    with open(bom_file_path, "r") as bom_file:
        bom_content = bom_file.read()
        bom_base64 = base64.b64encode(bom_content.encode()).decode()

    data = {
        "projectName": project_name,
        "projectVersion": project_version,
        "autoCreate": True,
        "bom": bom_base64
    }

    json_data = json.dumps(data)

    #Step 1
    response = requests.put(f"{url}/bom", headers=headers, data=json_data)

    if response.status_code == 200:
        print("BOM file uploaded successfully")
        token = response.json()['token']
        print(f"Token: {token}")

        check_url = f"{url}/bom/token/{token}"
        processing = True

        while processing:
            time.sleep(check_interval)
            #Step 2
            check_response = requests.get(check_url, headers=headers)

            if check_response.status_code == 200:
                processing = check_response.json()['processing']
                if not processing:
                    print("BOM file processing is complete.")
                    print(processing)

                    #Step 3
                    vulnerability_report = get_vulnerability_report(api_key, url, token)
                    print("Vulnerability report:")
                    print(vulnerability_report)
                    with open("vulnerability_report.json", "w") as report_file:
                        json.dump(vulnerability_report, report_file)
                else:
                    print("BOM file is still being processed...")
            else:
                print(f"Error checking BOM processing status: {check_response.status_code}")
                print(check_response.text)
                break
    else:
        print(f"Error: {response.status_code}")
        print(response.text)

url = "http://my-ip:8081/api/v1"
api_key = "my-key"
bom_file_path = "bom.json"
project_name = "Test"
project_version = "1"
check_interval = 10

upload_and_check_bom(api_key, url, bom_file_path, project_name, project_version, check_interval)
```

### Expected Behavior

It is expected that there will be the same project identifiers in the web muzzle and after the call of the PUT-request.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
The token you get back from `PUT /api/v1/bom` is not a project UUID, it's a randomly generated token that can be used to track processing completion (like you already do). To get the UUID of the project that was created, you need to use the `GET /api/v1/project/lookup?name=<NAME>&version=<VERSION>` endpoint.
