### ISSUE TITLE
Configure automatic purging of projects

### ISSUE THREAD

**Issue by manoswerts** [DependencyTrack/dependency-track#2825]
### Current Behavior

Some of our projects have many releases per year, which results in a long list of projects in Dependency Track. We want to keep some historical versions that are running on live environments to be able to detect vulnerabilities, but at some point they are not relevant anymore.

Currently there is no way to automatically remove projects from Dependency Track. As we have many project and many releases, it is hard to do this manually.

### Proposed Behavior

I would like to be able to configure the automatic removal of project versions from Dependency Track. I'd rather not do this time based as you never know how long it takes for subsequent releases to come out. I'd rather have a limit of the number of project versions and have the oldest one removed.

For example, I have the following 3 versions:

| Project | Version |
| fubar-service | 1.0.0 |
| fubar-service | 1.0.1 |
| fubar-service | 2.0.0 |

If I configure the purging to maintain a maximum of 3 versions per project, I would expect fubar-service:1.0.0 to be removed as soon as fubar-service:2.0.1 is uploaded.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by stevespringett** [comment]
Possible duplicate of #2136
