### ISSUE TITLE
Defectdojo integration not working

### ISSUE THREAD

**Issue by gulsezim11** [DependencyTrack/dependency-track#2837]
### Current Behavior

I configured the integration with the instructions given in https://docs.dependencytrack.org/integrations/file-formats/
But the findings from deptrack are not sent to defectdojo, I don't get what did I miss? Could you help me?
Could you describe fully how it works as documentation do not provide details

### Steps to Reproduce

1. Configured integrations of Defectdojo in dependency track in Administration menu
<img width="1503" alt="Снимок экрана 2023-06-21 в 11 42 57" src="https://github.com/DependencyTrack/dependency-track/assets/38872591/5e10d53c-2012-4dcf-8536-a0c668f58f80">
2. Configured each project with EngagementId of DefectDojo
3. In the instruction there is no further actions taken https://docs.dependencytrack.org/integrations/file-formats/

### Expected Behavior

After configuration, the findings from deptrack should be sent to defectdojo.
It would be great there are other options of integrations https://github.com/DependencyTrack/dependency-track/issues/1323

### Dependency-Track Version

4.4.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Apple Safari

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by valentijnscholten** [comment]
Did you configure the [required properties](https://docs.dependencytrack.org/integrations/defectdojo/) for each Project? 
Can you provide the log output of the defectdojo publish task?

**Comment by gulsezim11** [comment]
Yes, I have configured the required properties. In the logs, I identified that DepTrack is showing error:
`PKIX path building failed`
I guess I should add the certificate of defectdojo in deptrack container on OS level

**Comment by nscuro** [comment]
We have a guide on how to add internal CAs to the trust store here: https://docs.dependencytrack.org/getting-started/internal-ca/

**Comment by gulsezim11** [comment]
Thank you!
