### ISSUE TITLE
Alert to Slack is failing with "invalid_blocks"

### ISSUE THREAD

**Issue by peter-nicholson** [DependencyTrack/dependency-track#2838]
### Current Behavior

The Slack Alert Template seems to be incorrectly formatted (an incorrect trailing comma in the payload).  e.g. The extra comma is in the code block `{% elseif notification.group == "PROJECT_AUDIT_CHANGE" %}`

```
{
		  "type": "button",
		  "text": {
		    "type": "plain_text",
			"text": "View Vulnerability"
		  },
		  "action_id": "actionId-3",
		  "url": "{{ baseUrl }}/vulnerabilities/{{ subject.vulnerability.source | escape(strategy="json") }}/{{ subject.vulnerability.vulnId | escape(strategy="json") }}"
		},
	  ]
	}
  ]
```
The trailing comma results in invalid json containing a trailing comma, and Slack erroring with "invalid_blocks".

### Steps to Reproduce

1. Define an Alert based on the default Slack template
2. Trigger an alert (e.g. suppression on a policy violation)
3. Slack message does not appear in the channel designated in the webhook
4. Logs show error mentioned in the Description for this ticket 

### Expected Behavior

When an alert is triggered, it is written correctly to the Slack channel defined in the webhook.

This seems to have been introduced in v4.8

### Dependency-Track Version

4.8.0

### Dependency-Track Distribution

Container Image

### Database Server

Microsoft SQL Server

### Database Server Version

Don't know sorry

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by msymons** [comment]
@peter-nicholson, have you tried the "Clone Template" feature to create a Template without the trailing comma?  If this edited Template then works for alerts then you have both confirrmed the defect AND worked around it.
