### ISSUE TITLE
Can't get WebhookPublisher to successfully send JSON payload to AWS API Gateway

### ISSUE THREAD

**Issue by jesseadams** [DependencyTrack/dependency-track#2841]
### Current Behavior

I wanted to inspect the payloads of events that would be sent out to an outbound webhook. I created a simple AWS API gateway that accepts a `POST` with a json payload, logs it, and returns it as well in the response. 

This works great with curl.

```
curl -X POST -H "Content-Type: application/json" -d '{"foo": "bar"}' https://nix213jk8a.execute-api.us-east-2.amazonaws.com
{"foo": "bar"}
```

But when I try to use it with the notification configuration it just fails when trying to send notifications through the API server.

```
2023-06-20 15:35:10,766 ERROR [WebhookPublisher] An error was encountered publishing notification to Outbound Webhookwith HTTP Status : 403 Forbidden Destination: https://nix213jk8a.execute-api.us-east-2.amazonaws.com Response: {"message":"Forbidden"}
```

### Steps to Reproduce

1. Configure an outbound webhook alert using `org.dependencytrack.notification.publisher.WebhookPublisher` with the correct API gateway URL
2. Submit an SBOM to process and wait for it to completely process, thus generating notifications.
3. See lambda executions with the payload in the AWS CloudWatch log console

### Expected Behavior

I would expect to see the payloads showing up in the CloudWatch logs of the lambda, just like when I send manual tests via curl requests.

### Dependency-Track Version

4.8.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
When you test with `curl`, did you do it from within the DT container image?

Symptoms like the one you're describing are oftentimes due to missing or incorrect proxy configuration. Perhaps you configured an HTTP proxy for DT, but did not add a corresponding `NOPROXY` for the `amazonaws.com` domain?

**Comment by valentijnscholten** [comment]
> I would expect to see the payloads showing up in the CloudWatch logs of the lambda, just like when I send manual tests via curl requests.

Is there also nothing in the API Gateway logs, could the API Gateway be returning a `403`?

**Comment by jesseadams** [comment]
@nscuro - I did the curl on my local machine. I have no proxy configured on my machine or in DT.

@valentijnscholten - I'm pretty sure the API Gateway access logs show nothing unless I use curl. I'm re-enabling and confirming.

**Comment by jesseadams** [comment]
@valentijnscholten 

Confirmed. I get this when using curl in the API Gateway access logs.

```
{
    "requestId": "G4ZfAgp8iYcEPHQ=",
    "ip": "24.21.65.230",
    "requestTime": "21/Jun/2023:18:07:27 +0000",
    "httpMethod": "POST",
    "routeKey": "ANY /",
    "status": "200",
    "protocol": "HTTP/1.1",
    "responseLength": "14"
}
```

Nothing ever shows up for DT

**Comment by jesseadams** [comment]
Is there anything I can do to help with triage?

**Comment by valentijnscholten** [comment]
You need to find out where the `403` is coming from, it's not coming from DT itself.

**Comment by jesseadams** [comment]
@valentijnscholten Can you please confirm that if I provide an endpoint, like `https://example.com` that that is exactly what DT is hitting, versus if I provide that endpoint and it is really trying to hit `https://example.com/foo`.

It looks like it isn't truly hitting `/` but I'd expect to see something in the API Gateway Access Logs regardless.

**Comment by nscuro** [comment]
The response

```json
{"message":"Forbidden"}
```

seems pretty indicative that you are hitting the API gateway. Maybe consult https://repost.aws/knowledge-center/api-gateway-troubleshoot-403-forbidden for further investigation.

Few possibilities that stand out to me:

* "The request is blocked by web application firewall filtering when [AWS WAF is activated in the API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-aws-waf.html)."
  * If the notification contains vulnerability details or special characters, the WAF may not like that
* "Invoking a private API from within an Amazon Virtual Private Cloud (Amazon VPC) using public DNS names incorrectly. For example: the "Host" or "x-apigw-api-id" header is missing in the request. For more information, see [Invoking your private API using endpoint-specific public DNS hostnames](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html#apigateway-private-api-public-dns)."
   * The API server may run in a VPC, while your workstation does not

The API server ships with `wget` installed. When you shell into the container, try using `wget` to POST something against your API gateway and see if you can reproduce.

**Comment by jesseadams** [comment]
@nscuro I wouldn't be able to access it on my local machine if any of those were true. It would even work for your machine.

`curl -X POST -H "Content-Type: application/json" -d '{"foo": "bar"}' https://nix213jk8a.execute-api.us-east-2.amazonaws.com`

I'll try to jump on the running container and see what it looks like there.

**Comment by jesseadams** [comment]
After a lot of playing around, it looks like DT wasn't happy with the default, invalid SSL cert. After I created a valid cert and attached a custom domain name to the API gateway it seems to work just fine. It may be useful to somehow make that more obvious for troubleshooting purposes in the future in the API container logs.
