### ISSUE TITLE
Queue tokens for project cloning

### ISSUE THREAD

**Issue by WDN2010** [DependencyTrack/dependency-track#2842]
### Current Behavior

API request "PUT /v1/project/clone" returns response 200 with new project UUID like if operation is finished
In fact, cloning a project is a continuous process that requires copying information about the components in use from the original repository to the new
That can lead to problems like #2768 when running two continuous operations at the same time leads to unwanted results

### Proposed Behavior

Return status token like `PUT /v1/bom` does.
This allows to track cloning process and sync task order for Dependency Track to aviod timing conflicts

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Additional note: Cloning is currently not executed in a single transaction, so it's possible that a failure leaves behind an incompletely cloned project. This is sub-optimal as it is hard to detect without accessing the logs. This needs to be addressed by wrapping the entire procedure into a single database transaction.

**Comment by rkg-mm** [comment]
@nscuro I did not find a way to implement the transaction part but the token I was able to do. not sure how transactions would work while wanting to use the existing token process of the event system?
