### ISSUE TITLE
Unable to setup LDAP with MS Active directory

### ISSUE THREAD

**Issue by hansemmanuel** [DependencyTrack/dependency-track#285]
### Environment:
  
  - Dependency-Track Version:    3.4.0
  - Distribution: Docker 
  - BOM Format & Version:
  - Database Server:  MySQL
  - Browser: 

I know that there is a similar issue https://github.com/DependencyTrack/dependency-track/issues/154. But I coudn't find a solution from that discussion. I am using latest docker image and setup environment variable for LDAP related properties. I believe DT is able to sync with LDAP , because log is showing as LDAP sync is complete and I can see 'Distinguished names' from AD when click on 'Add LDAP Group Mapping' under 'Teams' tab.  But I am unable to login using LDAP users, I tried creating a new team and mapped all LDAP groups and gave all permissions, but still no luck. Am I missing anything?

**Comment by stevespringett** [comment]
Did you refer to https://docs.dependencytrack.org/getting-started/ldap-configuration/

**Comment by hansemmanuel** [comment]
Yes I checked this and actually DT and Ad is syncing as per the logs, also
I can see AD Delegate names (DNs) while mapping Teams to LDAP groups. But
unable to login with LDAP users.

**Comment by stevespringett** [comment]
Ensure its not configured to use "Domain Users" for example. This simply won't work - it's a Microsoft thing. Take a look at #241 and see if the links from Microsoft help.

**Comment by tupev** [comment]
Can confirm this. We had similar problems as we have groups and users in different organizational units in AD. With correct base DN to our users `alpine.ldap.basedn=OU=Users,OU=UnitName,DC=example,DC=com` users could connect but Mapped LDAP groups would remain empty -> we couldn't setup automatic team synchronization based on LDAP groups. When we changed our base DN to be correct for groups `alpine.ldap.basedn=OU=eMail, OU=GroupUnit,DC=example,DC=com` LDAP users couldn't connect but Mapped LDAP groups did show all available AD groups. 

As a workaround we first used the group AD config to get all wanted groups mapped and then switched back to user based config. We cannot currently add more mappings to teams without changing base DN configs but at least users can now connect.

However, if we use the previously mentioned full base DN for our users, users are still not automatically updated to teams. Automatic synchronization is only working with `DC=example,DC=com`.  With this base DN setting we are getting 500 internal server error mentioned in here: https://github.com/DependencyTrack/dependency-track/issues/294

**Comment by Lexus-3141** [comment]
Hi. I have same throuble.

Ldap Authentication is ok. Account has generic read rights on all MS AD.
Config is same to: (only this params)
`alpine.ldap.enabled=true
alpine.ldap.server.url=ldaps://ldap.example.com:3269
alpine.ldap.basedn=dc=example,dc=com
alpine.ldap.security.auth=simple
alpine.ldap.auth.username.format=%s@example.com
alpine.ldap.bind.username=cn=ServiceAccount,cn=Users,dc=example,dc=com
alpine.ldap.bind.password=mypassword
alpine.ldap.attribute.name=userPrincipalName
alpine.ldap.attribute.mail=mail`

But i've got this:
[LDAP: error code 32 - 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:

**Comment by stevespringett** [comment]
@Lexus-3141 
`cn=ServiceAccount,cn=Users,dc=example,dc=com` ?

Perhaps it's suppose to be:
`cn=ServiceAccount,ou=Users,dc=example,dc=com`

**Comment by Lexus-3141** [comment]
=)
For the message I copypasted this from https://docs.dependencytrack.org/getting-started/ldap-configuration/
I my config strings copypasted from AD objects. Authentication is ok, i check it by logs.

**Comment by Lexus-3141** [comment]
What am I have to see if the config not contains "alpine.ldap.groups.filter" and "alpine.ldap.user.groups.filter" params, "alpine.ldap.basedn" leeds to domain root and the account have read rights throught AD?

**Comment by Lexus-3141** [comment]
Sorry, it was a my mistake. Copypaste in server url.
In my case it was like `alpine.ldap.server.url=ldaps://ldap.example.com:3269/DC=examle,DC=com`
Suddenly DT was connect successfully, without correct error.

**Comment by stevespringett** [comment]
Ah, glad its working, and thanks for pointing out the doc error. It's been corrected.
