### ISSUE TITLE
BOM file upload -> restricted file size (HTTP status 413)

### ISSUE THREAD

**Issue by datze** [DependencyTrack/dependency-track#2855]
### Current Behavior

BOM file upload.
File size is restricted (HTTP status 413) to something like 2Mb(?) in the Docker image.

### Proposed Behavior

The max file size should be increased to min 10Mb or (better) be configurable.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
There is no such limitation in any of the Docker images we ship. We regularly test with BOMs beyond the 20mb mark without issues.

Are you running a reverse proxy in front of your containers perhaps?

**Comment by datze** [comment]
Thanks, good point! I'll check this tomorrow.

**Comment by ybelMekk** [comment]
@troy256, same problem, thanks for fix 🦞

**Comment by ybelMekk** [comment]
think this issue can be closed, with a bit of doc?
