### ISSUE TITLE
DT is proposing incorrect version as 'latest'

### ISSUE THREAD

**Issue by malice00** [DependencyTrack/dependency-track#2858]
### Current Behavior

We have several projects where we are on the actual latest version of a component, however DT seems to think that they are not. I thnk the problem might be in the way DT is interpreting versionnumbers.

![Version](https://github.com/DependencyTrack/dependency-track/assets/12972577/9b3f4fb1-8669-45b4-84a2-82f90a557d75)

### Steps to Reproduce

1. Create a project or BOM with a dependency on:
```
<groupId>org.jboss.spec.javax.servlet<groupId>
<artifactId>jboss-servlet-api_4.0_spec</artifactId>
<version>2.0.0.Final-redhat-00001</version>
```

### Expected Behavior

I expect DT to see this version is the latest available version.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

unknown -- if relevant I can check with the DB-departement

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by valentijnscholten** [comment]
There's #2826 slightly related. Current version parsing is a bit generic, not tied to any standards: https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/util/ComponentVersion.java
An easy fix could be to add this redhat suffix that's commonly used. But these suffixes contradict `semver` in which these suffixes after the hyphen are considered pre-release versions.

**Comment by malice00** [comment]
I agree that that `semver` might not see this version as newer, Maven however doesn't use `semver` in its versioning. I guess it would be good if the version checking takes the ecosystem into consideration.

**Comment by valentijnscholten** [comment]
True. The difference is not that big though. I believe the maven scheme also considers the redhat suffix as an indicator of it being an older release.

**Comment by malice00** [comment]
Actually, it does not. Maven has some very specific rules: https://github.com/apache/maven/blob/master/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java. You can run this from cli (starting from Maven ~3.2) to compare versions, eg:
```
java -jar ~/.m2/repository/org/apache/maven/maven-artifact/3.9.3/maven-artifact-3.9.3.jar "2.0.0.Final" "2.0.0.Final-redhat-1"

Display parameters as parsed by Maven (in canonical form and as a list of tokens) and comparison result:
1. 2.0.0.Final -> 2; tokens: [2]
   2.0.0.Final < 2.0.0.Final-redhat-1
2. 2.0.0.Final-redhat-1 -> 2-redhat-1; tokens: [2, [redhat, [1]]]
```
As you can see, 'Final' is ignored in Maven, which makes '2.0.0.Final' == '2.0.0':
```
java -jar ~/.m2/repository/org/apache/maven/maven-artifact/3.9.3/maven-artifact-3.9.3.jar "2.0.0.Final" "2.0.0"

Display parameters as parsed by Maven (in canonical form and as a list of tokens) and comparison result:
1. 2.0.0.Final -> 2; tokens: [2]
   2.0.0.Final == 2.0.0
2. 2.0.0 -> 2; tokens: [2]
```

**Comment by valentijnscholten** [comment]
Interesting, I read https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855 which states 

> All versions with a qualifier are older than the same version without a qualifier (release version).
> 
> For example:
> 
> 1.2-beta-2 is older than 1.2.

But it's an Oracle document, so can't be trusted ;-)

**Comment by malice00** [comment]
I wouldn't say it isn't to be trusted. In the case of Oracle, which only mentions the qualifiers 'alpha' and 'beta', this is actually correct:
```
java -jar ~/.m2/repository/org/apache/maven/maven-artifact/3.9.3/maven-artifact-3.9.3.jar "2.0.0" "2.0.0-beta-1"

Display parameters as parsed by Maven (in canonical form and as a list of tokens) and comparison result:
1. 2.0.0 -> 2; tokens: [2]
   2.0.0 > 2.0.0-beta-1
2. 2.0.0-beta-1 -> 2-beta-1; tokens: [2, [beta, [1]]]
```
That's what I meant when mentioning Maven has some very specific rules... :-)

**Comment by valentijnscholten** [comment]
Seems like that, been using Maven for years but never dived into it.
The Oracle piece was also not clear for met it's only `alpha` and `beta`, but a bit further down I noticed they actually explain pathsets with x.x.x-y-z.

**Comment by malice00** [comment]
Hmmm... It seems DT actually does handle the version correctly, if you actually configure the repositories correctly!
