### ISSUE TITLE
Error while uploading BoM

### ISSUE THREAD

**Issue by fuzzynat0r** [DependencyTrack/dependency-track#286]
### Issue Type:
  - [ x ] defect report
  
  
### Current Behavior:

Hi,

i try to upload a BoM over the webinterface. Without getting any error the procces walks through.
I tried different BoM versions, small with only a few components as well as complete with several hundred components. (Also the test file from cyclonedx)

### Steps to Reproduce (if defect):

Projects > Project Name > Dependency > Upload BoM
On popup I select my BoM and upload.

### Expected Behavior:

processing the BoM and add the  components to list.

### Environment:
  
Ubuntu 18.04 
Docker 18.06.1-ce

### Other Details:

[javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,39]
Message: Content is not allowed in prolog.]
	at org.cyclonedx.BomParser.parse(BomParser.java:96)
	at org.cyclonedx.BomParser.parse(BomParser.java:69)
	at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:71)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.bind.UnmarshalException: null
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:470)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:402)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:371)
	at org.cyclonedx.BomParser.parse(BomParser.java:94)
	... 6 common frames omitted
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,39]
Message: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:149)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:400)
	... 8 common frames omitted

**Comment by stevespringett** [comment]
If you're uploading BOMs generated from the npm module, ensure each component has a name and version. package.json allows blank on both whereas Dependency-Track requires them but doesn't do a good job at telling you.

If that's not the issue, then please supply the BOMs being uploaded. Its likely something in the BOMs thats causing the issue.

**Comment by fuzzynat0r** [comment]
Hi Steve,
thanks for your fast response. My BoMs are 'selfmade' since we have an prop. format in my company and we want to switch to an other solution.

I tried the one from cyclonedx:

`<?xml version="1.0" encoding="UTF-8"?>�
<bom xmlns="http://cyclonedx.org/schema/bom/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1" xsi:schemaLocation="http://cyclonedx.org/schema/bom/1.0 http://cyclonedx.org/schema/bom/1.0">
  <components>
    <component type="library">
      <group>org.jboss.resteasy</group>
      <name>resteasy-jaxrs</name>
      <version>3.1.0.Final</version>
      <description>JAX-RS bindings for RestEasy</description>
      <hashes>
        <hash alg="SHA-1">6427a9a622bff4dbe99d6f08dabd0dd89af85235</hash>
        <hash alg="SHA-256">97bb6890cea26ed6f107603426fdb19f1444932c310705895ecf9cc24992da0d</hash>
      </hashes>
      <licenses>
        <license>
          <id>Apache-2.0</id>
        </license>
      </licenses>
      <purl>pkg:maven/org.jboss.resteasy/resteasy-jaxrs@3.1.0-Final?type=jar</purl>
      <cpe>cpe:2.3:a:redhat:resteasy:3.1.0:*:*:*:*:*:*:*</cpe>
      <modified>false</modified>
    </component>
    
  </components>
</bom>`

here is an part from one of my BoM's:
i checked against the 

<?xml version="1.0" encoding="UTF-8"?> 
<bom xmlns="http://cyclonedx.org/schema/bom/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1" xsi:schemaLocation="http://cyclonedx.org/schema/bom/1.0 http://cyclonedx.org/schema/bom/1.0"> 
		<component type ="application"> 
			<group></group> 
			<name>jsr305</name> 
			<version>3.0.1</version> 
			<description></description> 
			<hashes> 
			</hashes> 
			<licenses> 
				<license> 
					<id></id> 
				</license> 
			</licenses> 
			<purl></purl> 
			<cpe></cpe> 
			<modified>false</modified> 
		</component> 
		<component type ="application"> 
			<group></group> 
			<name>antlr</name> 
			<version>2.7.7</version> 
			<description></description> 
			<hashes> 
			</hashes> 
			<licenses> 
				<license> 
					<id></id> 
				</license> 
			</licenses> 
			<purl></purl> 
			<cpe></cpe> 
			<modified>false</modified> 
		</component> 
		<component type ="application"> 
			<group></group> 
			<name>aopalliance</name> 
			<version>1.0</version> 
			<description></description> 
			<hashes> 
			</hashes> 
			<licenses> 
				<license> 
					<id></id> 
				</license> 
			</licenses> 
			<purl></purl> 
			<cpe></cpe> 
			<modified>false</modified> 
		</component> 
		<component type ="application"> 
			<group></group> 
			<name>archaius-core</name> 
			<version>0.4.1</version> 
			<description></description> 
			<hashes> 
			</hashes> 
			<licenses> 
				<license> 
					<id></id> 
				</license> 
			</licenses> 
			<purl></purl> 
			<cpe></cpe> 
			<modified>false</modified> 
		</component> 
	 </components> 
</bom> `

**Comment by fuzzynat0r** [comment]
Found your file definition @ https://github.com/CycloneDX/specification/blob/master/examples/application-bom/bom.xml

With this i can upload so error on layer 8
