### ISSUE TITLE
Add a way to send test alerts

### ISSUE THREAD

**Issue by rdicroce** [DependencyTrack/dependency-track#2924]
### Current Behavior

There is no way to test an alert. So if you set up an alert using Slack/Teams/Jira/etc, you have no idea if you've done it correctly. And if some time later, you suspect that the alert is somehow broken, you have no way to check that it is still working.

### Proposed Behavior

The Alerts screen should have a button that lets you send a test alert, so users can verify that the alert is configured correctly.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Implemented in https://github.com/DependencyTrack/dependency-track/pull/3983
