### ISSUE TITLE
Administration UI error prompt: 500 Internal Server error based on empty ldap group searchText

### ISSUE THREAD

**Issue by tupev** [DependencyTrack/dependency-track#294]
### Issue Type:
  - [x] defect report
  
  
### Current Behavior:
Dependency tracks administration UI gives error prompt "An unexpected error occurred (500)" when opening Admin UI. 

### Steps to Reproduce (if defect):
Set AD base DN to `DC=example,DC=com`
Open Admin UI
Error prompt appears && Developer tools shows 500 Internal Server Error

### Expected Behavior:
AD either should work with different base DN `alpine.ldap.basedn=OU=Users,OU=UnitName,DC=example,DC=com` mentioned in here 
 https://github.com/DependencyTrack/dependency-track/issues/285 or should not give 500 internal server error with these settings (empty searchText parameter)
### Environment:
  
  - Dependency-Track Version: 3.4
  - Distribution: Docker
  - Database Server: PostgreSQL
  - Browser: Chrome & Firefox

### Other Details:
Error:
`GET http://dtrack.example.com/api/v1/ldap/groups?searchText=&sortOrder=asc` returns 500 Internal Server Error

**Comment by stevespringett** [comment]
Can you provide a gist of the stack trace? If not, perhaps email it to steve [dot] springett [at] owasp.org or hit me up on Keybase. I won't be able to fix it if I don't know where it's failing.

**Comment by Lexus-3141** [comment]
I have same.

**Comment by stevespringett** [comment]
I wasn't able to replicate in a testing environment, but was able to replicate when connected to a large AD environment. The additional logging added reveals that the query being performed by Dependency-Track exceeds the number of results the server is configured to return. The exact error message is:

```
javax.naming.SizeLimitExceededException: [LDAP: error code 4 - Sizelimit Exceeded]
```

The way this API currently works is to retrieve a list of all LDAP groups and then use client-side filtering to narrow down the list. This approach works for small-medium sized AD environments, but breaks down on larger ones, resulting in a 500.

The proper fix for this would be to change the API to be server-side filtering where the search filter is passed directly to the LDAP server thus narrowing down the number of results the server would return and suppressing any errors that are the result of Sizelimits.

**Comment by msymons** [comment]
So that this issue will be returned in searches of Github, the new properties in v3.5.0 are:

```
alpine.ldap.groups.search.filter
alpine.ldap.users.search.filter
```
