### ISSUE TITLE
component name

### ISSUE THREAD

**Issue by itmanju** [DependencyTrack/dependency-track#2944]
### Current Behavior

There was a SBOM I imported into DT and found a component named as comma (,) and when i checked the SBOM found a component with name name = "," and I think it should validate the component name from SBOM before it ingest into project
![component](https://github.com/DependencyTrack/dependency-track/assets/77400469/836e5c3a-81b2-4fdb-afe0-045035b55191)
![DT](https://github.com/DependencyTrack/dependency-track/assets/77400469/dccd1337-53a9-46f8-b15b-314f24646687)

### Steps to Reproduce

1.

### Expected Behavior

 I think it should validate the component name from SBOM before it ingest into project

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

10.1

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
To be honest I am not sure if DT can or should do anything here. 

Special characters are technically valid component names, so it's not like they are violating anything.

What would be the expected behavior exactly? Do you really want BOM uploads being rejected because one component is ill-named?
