### ISSUE TITLE
Empty Data Tables 

### ISSUE THREAD

**Issue by otmos** [DependencyTrack/dependency-track#295]
Hello , i tried using dependency Track from a docker container as well as using the executable war but i keep being blocked on the same issue on both instances , the datatables for the componements and projects update themselves to be empty after coming filled with data from the datasource , i can select an item but only if i was quick to click on it before it gets refreshed to be empty

### Issue Type:
  - [x] defect report
  - [ ] enhancement request
  
  
### Environment:
  
  - Dependency-Track Version: 3.4.0
  - Distribution: [ Docker | Executable WAR  ]
  - BOM Format & Version:
  - Database Server: [ H2 ]
  - Browser: Chrome 72

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
<img width="1280" alt="screen shot 2019-03-01 at 11 48 52 am" src="https://user-images.githubusercontent.com/43470049/53633819-6f8a7900-3c10-11e9-8011-9a59bc083b89.png">
<img width="1280" alt="screen shot 2019-03-01 at 11 48 56 am" src="https://user-images.githubusercontent.com/43470049/53633820-6f8a7900-3c10-11e9-8951-0329b7ac7694.png">

**Comment by stevespringett** [comment]
Do you have a component called 'admin'?

Also, did you follow the Docker instructions? There isn't a data volume so you need to create/mount one. https://docs.dependencytrack.org/getting-started/deploy-docker/

Also, the H2 database isn't supported as mentioned in the docs. What database server are you using?

**Comment by otmos** [comment]
Actually I found out that it was caused by some incompatibility in chrome , I opened up the web app in Safari and ran just fine , meanwhile in chrome it keeps loading then clearing out all the tables.

**Comment by stevespringett** [comment]
Chrome has some really bizarre caching issues. Once it has corrupted data in its cache it's nearly impossible to get rid of without wiping the entire cache, and doesn't seem to honor cache control settings to tell it otherwise.

**Comment by stevespringett** [comment]
Closing
