### ISSUE TITLE
 Getting Started Configuration

### ISSUE THREAD

**Issue by security101** [DependencyTrack/dependency-track#296]
Hi,

I just want to share my experience and my be this is of value for others too.

Following the provided example provided webpage https://docs.dependencytrack.org/getting-started/configuration/ "To start Dependency-Track using custom configuration, add the system property alpine.application.properties when executing. For example: -Dalpine.application.properties=~/.dependency-track/application.properties " did not worked out for me at the beginning. 

Since I am not using java very often it took me some time to figure out that the correct placing of the option -D... before and not after the -jar option.

The following example may help beginners to safe some time:

/usr/bin/java -Xmx4G -Dalpine.application.properties=~/.dependency-track/application.properties -jar dependency-track-embedded.war -port 8090

And then it worked perfectly. :-)

Cheers,
Andreas

**Comment by leec94** [comment]
this documentation suggestion is out of date, currently there is build documentation for developers located here that shows the entire build command including flags: https://github.com/DependencyTrack/dependency-track/blob/master/DEVELOPING.md#building

suggest closing this out
