### ISSUE TITLE
Configuring OIDC using the Bundled docker image

### ISSUE THREAD

**Issue by andreasmihm** [DependencyTrack/dependency-track#2962]
### Current Behavior

I'm using the bundled docker image in an Azure AppService for a DependencyTrack instance and I want to configure OIDC with Azure AD. I defined the settings for OIDC for both backend and frontend and placed it at the AppService.

    "alpine.oidc.enabled" = "true"
    "alpine.oidc.client.id" = "<...>"
    "alpine.oidc.issuer" = "https://login.microsoftonline.com/<...>/v2.0"
    "alpine.oidc.username.claim" = "preferred_username"
    "alpine.oidc.user.provisioning" = "true"
    "alpine.oidc.teams.claim" = "groups"
    "alpine.oidc.team.synchronization" = "true"
    "OIDC_CLIENT_ID" = "<...>"
    "OIDC_ISSUER" = "https://login.microsoftonline.com/<...>/v2.0"

But I do not see the OpenID Button on the Login screen. 
In the application log of the DepTrack backend I dont see errors or anything related to OIDC.

### Steps to Reproduce

1.

### Expected Behavior

Expected bahaiour is that the OpenID Button appears on the login screen and that it triggers the OIDC flow.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by valentijnscholten** [comment]
Not sure if this is true for the bundled docker image, but the docs state OIDC is not supported if the frontend and api are bundled into a single WAR file: https://docs.dependencytrack.org/getting-started/openidconnect-configuration/.
Other than that, are there are any errors in the api log or browser console?

**Comment by andreasmihm** [comment]
when using separate containers for apiserver and frontend, it works
