### ISSUE TITLE
Error: Could not find or load main class "-Xmx4G" / Caused by: java.lang.ClassNotFoundException: "-Xmx4G"

### ISSUE THREAD

**Issue by julien-lecomte** [DependencyTrack/dependency-track#2969]
### Current Behavior

docker-compose can't start the java program since EXTRA_JAVA_OPTIONS aren't "EXTRA", they overwrite whatever it was supposed to launch.

### Steps to Reproduce

1. Run `docker-compose up`
2. Error "dtrack-apiserver_1  | 2023-08-21 09:57:38,979 ERROR [RequirementsVerifier] Dependency-Track requires a minimum of 4GB RAM (heap). Cannot continue. To fix, specify -Xmx4G (or higher) when executing Java."
3. Set EXTRA_JAVA_OPTIONS="-Xmx4G"
4. Error: Could not find or load main class "-Xmx4G"

Since they're "EXTRA_", I expected it to work out of the box. Sadly, I have no clue on what the java class name is, nor even what to add to EXTRA_JAVA_OPTIONS for the thing to start.

### Expected Behavior

For docker-compose to correctly start the service.

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by julien-lecomte** [comment]
I've issued the following (not detached until I get it working ;-) )

```
curl -LO https://dependencytrack.org/docker-compose.yml
docker-compose up
```

**Comment by nscuro** [comment]
But you passed `EXTRA_JAVA_OPTIONS` somehow, no?

**Comment by julien-lecomte** [comment]
yes, if I edit the docker compose and set:
```
    # Optional environmental variables to provide more JVM arguments to the API Server JVM, i.e. "-XX:ActiveProcessorCount=8"
      - EXTRA_JAVA_OPTIONS="-Xmx4G"
```

It overrides whatever was used before. In other words, it's not much EXTRA_ options, but rather replacing the full command line that is used by java. Because of this, I then get:

```
root_dtrack-apiserver_1 exited with code 1
dtrack-apiserver_1  | Error: Could not find or load main class "-Xmx4G"
dtrack-apiserver_1  | Caused by: java.lang.ClassNotFoundException: "-Xmx4G"
```

I have no clue on what else to add to EXTRA_JAVA_OPTIONS for it to work.

**Comment by nscuro** [comment]
Ah, I see. Try removing the double quotes around `-Xmx4G`.

When using the array notation for `environment` in Compose, the entire thing is interpreted as a single string, so no need for quoting. So this should work:

```yaml
- EXTRA_JAVA_OPTIONS=-Xmx4G
```

Alternatively, use the object notation:

```yaml
EXTRA_JAVA_OPTIONS: "-Xmx4G"
```

**Comment by julien-lecomte** [comment]
oh! Thanks! That worked.
