### ISSUE TITLE
No Data Available

### ISSUE THREAD

**Issue by asdrubalos** [DependencyTrack/dependency-track#297]
Hi, help me solve the issue "No Data Available" in UI dependency track

### Issue Type:
  - [ x] defect report
  - [ ] enhancement request
  
  
### Current Behavior:
The problem is the following: Vulnerabilities are not seen in the dependency track UI, in the project vulenrabilities have been found by dependency check, the payload is sent through the api detailed in step 2

### Steps to Reproduce (if defect):
step 1) i'am runing dependency-track-embedded.war by next script
script.sh
#! /bin/sh
export JAVA_OPTIONS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xmx4G"
java $JAVA_OPTIONS -jar /opt/dtrack/dependency-track-embedded.war -Dalpine.application.properties=application.properties

step 2) I'am upload data from CI drone.io  file report: dependency-check-report.xm to: dependency track ui by next script
payload.sh 
#!/bin/bash
CI_PROJECT_DIR="$1"
CI_PROJECT_NAME="$2"
CI_JOB_ID="$3"
cat > $CI_PROJECT_DIR/payload.json <<HERE
{
"autoCreate": "true",
"projectName": "${CI_PROJECT_NAME}",
"projectVersion": "${CI_JOB_ID}",
"scan": "$(cat $CI_PROJECT_DIR/dependency-check/dependency-check-report.xml |base64 -)"
}
HERE
curl -s -X "PUT" "http://my_domain_here.com:8080/api/v1/scan" -k -H 'Content-Type: application/json' -H 'X-API-Key: KkSW4OFhKadAmNSyH3yiTh9C1mIDfW7f' -d @payload.json

### Expected Behavior:

The dependency of the user interface must show the results of the vulnerabilities, critical, high, medium, low.

### Environment:
  
  - Dependency-Track Version: v3.5.0
  - Distribution: [Executable WAR ]
  - BOM Format & Version:
  - Database Server: [  PostgreSQL ]
  - Browser: firefox, chrome

### Other Details:

![image](https://user-images.githubusercontent.com/44121338/53839253-ce842100-3f75-11e9-92df-b41407ad0958.png)
](url)[
![image](https://user-images.githubusercontent.com/44121338/53847293-ddc39880-3f8e-11e9-9475-a1ccfd4b819c.png)
](url)[
![image](https://user-images.githubusercontent.com/44121338/53847892-2aa86e80-3f91-11e9-9337-74ecbfdc8095.png)
](url)

**Comment by stevespringett** [comment]
Snapshot releases are not supported. This is clearly stated in the UI after first login.
