### ISSUE TITLE
The package javax.xml.parsers is accessible from more than one module

### ISSUE THREAD

**Issue by hborchardt** [DependencyTrack/dependency-track#2970]
### Current Behavior

Hi, while preparing to contribute to this project, after cloning and importing, eclipse (java 17) shows dozens of these errors on import statements:
```
The package javax.xml.parsers is accessible from more than one module: <unnamed>, java.xml
```
To give a concrete example, for the file `/src/main/java/org/dependencytrack/persistence/CweImporter.java`, the line `import javax.xml.parsers.DocumentBuilder;` has that error.

I was able to resolve it for me by changing the pom.xml in the following way:
```diff
diff --git a/pom.xml b/pom.xml
index 4501a246..eab3be76 100644
--- a/pom.xml
+++ b/pom.xml
@@ -307,6 +307,12 @@
             <groupId>xerces</groupId>
             <artifactId>xercesImpl</artifactId>
             <version>2.12.2</version>
+            <exclusions>
+                   <exclusion>
+                       <artifactId>xml-apis</artifactId>
+                       <groupId>xml-apis</groupId>
+                   </exclusion>
+               </exclusions>
         </dependency>
         <!-- Commons Compress -->
         <dependency>
```
However I am not sure if this is the correct way to resolve this, as apparently there is already a way to make builds with the current state of the repo. So maybe it is rather a configuration issue on my side?

I would be interested in your opinion - If need be, I can package my changes in a PR.

### Steps to Reproduce

1. Clone the repository
2. In eclipse, Import -> Existing Maven project, select the repository
3. Observe many files with the above error

### Expected Behavior

Checking out the repo and importing it in eclipse yields an immediately runnable project.

### Dependency-Track Version

4.9.0-SNAPSHOT

### Dependency-Track Distribution

Executable WAR

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Although this does not appear to be a problem when building with Maven directly (as we do in CI), nor when running with IntelliJ, I believe I vaguely remember `xml-apis` being problematic.

If excluding this dependency fixes Eclipse setups, and everything else still works, this is a legit change IMO.

**Comment by hborchardt** [comment]
From [my reading on this](https://stackoverflow.com/questions/55571046/eclipse-is-confused-by-imports-accessible-from-more-than-one-module), when using java modules, it is invalid to add classes to the javax.xml namespace (as does the xml-apis dependency), because the java runtime already provides classes in javax.xml. Not sure why eclipse is more picky than maven or IntelliJ, but eclipse seems to be technically correct.

As the needed APIs are already provided by the runtime, excluding the dependency seems safe to me. I would then create a PR, so you can try if your IDE is happy with it as well.
