### ISSUE TITLE
GitHub Actions workflow for publishing "feature build" container images to ghcr.io

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/dependency-track#2972]
### Current Behavior

Sometimes, before merging a feature implementation to `master`, we want to gather feedback from the community first.

Giving feedback based on PR descriptions and screenshots alone is limiting; Users need to get their hands on it to properly evaluate it.

We can't expect users to set up a Java and NodeJS build environment to test, that's not going to happen. Instead, we should have the possibility to build and publish container images from PRs.

### Proposed Behavior

Create a GitHub Actions workflow that can be triggered *manually* by maintainers.

The workflow should take a PR number as parameter.

The workflow should build and push a container image, using the existing [`_meta-build.yml`](https://github.com/DependencyTrack/dependency-track/blob/master/.github/workflows/_meta-build.yaml) workflow.

The image tag should be in the form `pr-<PR_NUMBER>`.

The image should be pushed to GitHub's container registry, *not* Docker Hub.

Example:

```
ghcr.io/dependencytrack/apiserver:pr-1234
```

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by 1oglop1** [comment]
hi @nscuro Is there a chance you can extend this to public ECR so that there's support for AWS as well? 
here's what's needed: https://docs.aws.amazon.com/AmazonECR/latest/public/public-getting-started.html
