### ISSUE TITLE
Add "Limits to Tags" for Alerts

### ISSUE THREAD

**Issue by sithmein** [DependencyTrack/dependency-track#2975]
### Current Behavior

Alerts can be limited to projects. Policies can be limited to projects *and* tags.

### Proposed Behavior

It should be possible to limit alerts also to tags.
We have many teams working with DT and we tag all projects with team names. We want to send alerts to teams only for "their" projects.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by sebD** [comment]
Hi,
I have started working on it.
