### ISSUE TITLE
VEX does not apply when source is empty or unequal source from analysis

### ISSUE THREAD

**Issue by Jasper-Ben** [DependencyTrack/dependency-track#2977]
### Current Behavior

A VEX file without a provided "source" block, or with the source differing from the previous run analysis will be silently dropped.

This behavior was introduced with commit https://github.com/DependencyTrack/dependency-track/commit/22c284411223c236ba1c396da727b25667f957bc

#### Testfiles
(rename from .txt to .json)

[bom.txt](https://github.com/DependencyTrack/dependency-track/files/12419097/bom.txt)
[vex_without_source.txt](https://github.com/DependencyTrack/dependency-track/files/12419096/vex_without_source.txt)
[vex_with_wrong_source.txt](https://github.com/DependencyTrack/dependency-track/files/12419093/vex_with_wrong_source.txt)
[vex_with_source.txt](https://github.com/DependencyTrack/dependency-track/files/12419094/vex_with_source.txt)

#### Steps

1. Create empty project
2. Import provided SBOM
3. Wait for analysis to complete
4. Upload provided vex_without_source -> nothing happens
6. Upload provided vex_with_wrong_source -> nothing happens
8. Upload provided vex_with_source
9. Success

### Expected Behavior

Uploading a VEX without providing a correct analysis source should work.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by Jasper-Ben** [comment]
Pinging @syalioune since you made the change what introduced this change in behavior :slightly_smiling_face:

**Comment by nscuro** [comment]
IIRC this change in behavior was intended, and in fact the previous behavior was *not* intended: https://github.com/DependencyTrack/dependency-track/pull/2549#issuecomment-1458447995

**Comment by Jasper-Ben** [comment]
I see. Would be great to have proper exception handling (or at least logging) there. I just spent hours of banging my head on the table because I was not able to get a VEX file applied and the logs did not mention anything. Had to did deep into the actual code to figure out what the issue was.

**Comment by syalioune** [comment]
@Jasper-Ben You have a fair point. I've added warning logs for that scenario.

**Comment by Jasper-Ben** [comment]
Thanks :)
