### ISSUE TITLE
Can't run NPM Audit 

### ISSUE THREAD

**Issue by otmos** [DependencyTrack/dependency-track#298]
Hi , I continue to run into issues with NPM Audit and Sonatype OSS Index whenever i upload a BOM generated by CycloneDX NPM Package , the logs always state this error :

[NpmAuditAnalysisTask] Received unexpected HTTP response 400 Bad Request

And the same error always gets thrown for OSS Index , so in the end the analysis don't give any relevant insights , it always states that projects are without any issues.

Thanks in advance

### Issue Type:
  - [x] defect report
  - [ ] enhancement request
  
  
### Environment:
  
  - Dependency-Track Version:3.40
  - Distribution: [  Executable WAR ]
  - BOM Format & Version: CycloneDX
  - Database Server: [ H2 ]
  - Browser: Safari on MacOS Mojave

**Comment by stevespringett** [comment]
Is DT sitting behind a proxy or firewall? If so, does the machine have access? Getting a 400 on both NPM Audit and OSS Index would lead me to believe there's an intermediate device somewhere on the network.

I assume that the BOM is processed without error?

**Comment by otmos** [comment]
What port is used to communicate with the servers ? I got the same error on different machines and configurations (Docker on macOS , Docker on Ubuntu and CentOS as well the Executable WAR)

**Comment by stevespringett** [comment]
Do you have a BOM to share that can reproduce the issue?

**Comment by otmos** [comment]
Here is the BOM that i used , i did generate it using the NPM Module
[bom.xml.zip](https://github.com/DependencyTrack/dependency-track/files/2945044/bom.xml.zip)
