### ISSUE TITLE
Add support for CycloneDX v1.1 (Part 1)

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#299]
Add partial support for CycloneDX 1.1 BOMs. This is a minimal-viable enhancement which will only support the importing of v1.1 BOMs without increasing the functionality in Dependency-Track. Additional enhancements to support specific 1.1 features (pedigree, resources, etc) will be created for future releases.

**Comment by msymons** [comment]
@stevespringett,  might it help in v3.5 to log and/or display the CycloneDX BOM version?
I am thinking that that might might help to make it easier to manually validate in v3.5 that DT Server is:
a) Recognising each version correctly.
b) Producing (in v3.5) the exact same results, no matter which version is imported.

**Comment by stevespringett** [comment]
Can you clarify b)?

**Comment by msymons** [comment]
Sorry...  I was rushing when I wrote the above.  Trying to get too many things done at once before leaving the office.

I mean that when one generates a v1.0 BOM from a given software project (maven, npm, etc) and then imports the BOM into a DT project, then DT will report a given set of components, threats, licences.

If DT 3.5 adds the ability to  "support the importing of v1.1 BOMs without increasing the functionality in Dependency-Track" then I would expect to be able to create a new project version in DT, import my "v1.1 BOM generated from same source project" into DT v3.5, and then be able to compare my two DT project versions quickly and easily by simply switching back and forth between them in the UI.

My expectation to see the same results for both project versions (one from Cyc;loneDX v1.0 BOM and one from CycloneDX 1.1 BOM) means that the identified dependencies, vulnerabilities, and licences should match.  All other things being equal!

The suggestion that DT v3.5 should report the BOM version is simply to make it easier to keep track of what is being compared to what.  

Also, having an "in your face" notification of BOM version would make it easier for users to provide such info when reporting issues here (especially going forward, with DT v3.6 and onwards),

I think there are other use cases.  When one has a large number of projects, it would be useful (after, say, a new version of cyclonedx-maven-plugin implements v1.1 BOM format support) to be able to quickly spot which have not yet updated to use the new plugin!

**Comment by stevespringett** [comment]
Tested with CycloneDX 1.0 and 1.1 BOMs. Dependency-Track (currently) doesn't need to know the difference. This is handled by https://github.com/CycloneDX/cyclonedx-core-java which handles this automatically. 1.0 and 1.1 BOMs will produce identical results
