### ISSUE TITLE
Component properties not present in downloaded BOM

### ISSUE THREAD

**Issue by muxmuse** [DependencyTrack/dependency-track#2991]
### Current Behavior

The downloaded BOM (file) doesn't include component properties that were present in a former upload.

### Steps to Reproduce

1. Create a new project
2. In the components tab, upload a CycloneDX file with at least one component with properties
3. Download the BOM and search for the properties

mve
``` json
{
  "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "version": 1,
  "serialNumber": "urn:uuid:5dd1cf22-47a8-4c0c-ac0e-f58eb356dbcb",
  "components": [
    {
      "type": "library",
      "name": "build-angular",
      "group": "@angular-devkit",
      "version": "16.1.0",
      "bom-ref": "@angular-devkit/build-angular@16.1.0",
      "purl": "pkg:npm/%40angular-devkit/build-angular@16.1.0",
      "properties": [
        {
          "name": "cdx:npm:package:path",
          "value": "node_modules/@angular-devkit/build-angular"
        },
        {
          "name": "cdx:npm:package:development",
          "value": "true"
        }
      ]
    }
  ]
}
```

### Expected Behavior

Uploaded component properties exist in downloaded BOM file.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by setchy** [comment]
We observed the same issue last week.

It looks like a subset of the component specification model is converted and persisted in https://github.com/DependencyTrack/dependency-track/blob/9ad07b59f8e91e0116c964baf844f2ca17c3f5ae/src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java#L157

Items that are currently omitted include component properties, component evidence, etc

**Comment by nscuro** [comment]
The properties part is being worked on here: https://github.com/DependencyTrack/dependency-track/pull/3499

As for the evidence, it is not imported because there is not a clear story yet as to what to actually do with it. Importing data for the sake of importing it is not something we want to do. The way *how* that information is stored has to work well with how it's going to be queried / used.
