### ISSUE TITLE
Standard Email Notification for Policy Violation doesnt work

### ISSUE THREAD

**Issue by andreasmihm** [DependencyTrack/dependency-track#2996]
### Current Behavior

When I setup an Email alert on POLICY_VIOLATION, and choose the Email Provider with the standard template, I don't get any emails, when new projects are uploaded and analyzed. The project display shows the violated policies.
When choosing the trigger NEW_VULNERABILITY it works.
The server log doesn't show any errors.
I don't know if this is relevant, but the policy creates a Waring and the Alert is also configured with notification level Warning.

### Steps to Reproduce

1. Create a policy 
2. create an email alert based on POLICY_VIOLATION, use standard email Provider template, use your email address as destination
2. Upload a project bom, which leads to a policy violation
3. no emails are sent out

### Expected Behavior

Email notification should be sent out

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by andreasmihm** [comment]
OK, I found out, that the notification works, when the alert is configured with Notification Level INFORMATIONAL. What is the purpose of the other two notification levels? and when do they occur?

**Comment by nscuro** [comment]
@andreasmihm Glad you were able to figure it out. The other two levels are mostly used for notifications in the `SYSTEM` scope. They're intended to inform admins when an error that requires immediate attention occurred (`ERROR`), or a potentially transient error that should *eventually* be investigated (`WARNING`).
