### ISSUE TITLE
components[].author attribute with more than 255 characters failing at DB insert

### ISSUE THREAD

**Issue by anshuman-mor** [DependencyTrack/dependency-track#3000]
### Current Behavior

I have a CycloneDX which has more than 255 characters in components [{"author": ""}] attribute and it fails to insert in DB due to 255 char restriction.

### Steps to Reproduce

1.Use any CycloneDX which has more than 255 characters in components[{"author": "....."}]

### Expected Behavior

I don't see any length mentioned in CycloneDX schema document, so should this be considered as bug?

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
This was fixed in v4.8.0: https://github.com/DependencyTrack/dependency-track/issues/2488
