### ISSUE TITLE
At least 1 license has an incorrect name

### ISSUE THREAD

**Issue by malice00** [DependencyTrack/dependency-track#3002]
### Current Behavior

LGPL-2.1+ should be called 'GNU **Lesser** General Public License v2.1 or later', but in DT it is added as 'GNU **Library** General Public License v2.1 or later'. This is confusing, especially because on some pages you see only the ID and on others only the name.

![DT](https://github.com/DependencyTrack/dependency-track/assets/12972577/24218975-98d2-49e0-bdd9-5eb50637b47e)
![SPDX](https://github.com/DependencyTrack/dependency-track/assets/12972577/98da683d-d67c-4f32-a5fe-4988faf02c66)

It would also be really great to be able to change (certain?) license data directly from the API and UI.

### Steps to Reproduce

1. Start DT from a fresh installation

### Expected Behavior

I would expect all licenses to have their correct names.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

unknown -- but not  relevant imho as it's reproducible in H2 also

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by msymons** [comment]
Dependency-Track 4.8.2 derives the license list from [cyclonedx-core-java](https://github.com/CycloneDX/cyclonedx-core-java) v7.3.2.   This, in turn, uses SPDX License List 3.17.   The latest version of the license list is 3.21 and the name of `LGPL-2.1+` has changed.  

See: [LGPL-2.1+.xml: fix license name](https://github.com/spdx/license-list-XML/commit/87941faf00734a4ef944a398fbd48660622b4538)


So, you are currently seeing the _old_ name in Dependency-Track.

The next version of  `cyclonedx-core-java` is under development and due very soon.  It includes SPDX License List 3.21

**Comment by malice00** [comment]
Ah, thanks for the info!
Do you have any idea if this will be automatically updated on a new release of DT??

**Comment by nscuro** [comment]
We may have to do this update ourselves, as the data is currently sourced from https://github.com/DependencyTrack/dependency-track/tree/master/src/main/resources/license-list-data/json

The version of the list we use ATM is [3.11](https://github.com/DependencyTrack/dependency-track/blob/15a9baa0816c00ee41bd488e86bf7200cf729576/src/main/resources/license-list-data/json/licenses.json#L2). 

> @malice00 Do you have any idea if this will be automatically updated on a new release of DT??

Once we update the list, the changes will be automatically applied when you update DT.

**Comment by nscuro** [comment]
@msymons Removing the blocked label, as this is something we have to deal with on our end.

**Comment by msymons** [comment]
@malice00. so can see from the above that Dependency-Track v.4.9 will be released with SPDX License List v3.21

I have also logged #3011 so that we can automate the update process and ensure that (in future) the license list will be up-to-date with each release of Dependency-Track.

**Comment by malice00** [comment]
@msymons awesome! Looking forward to the new release!
