### ISSUE TITLE
latest version api response is empty, breaking latest version feature

### ISSUE THREAD

**Issue by rback123** [DependencyTrack/dependency-track#301]
### Issue Type:
  - [x] defect report
  - [ ] enhancement request
  
  
### Current Behavior:
The `/api/v1/repository/latest` method returns an empty body in the response. The header `Content-Length` has a value of 0, to confirm this is happening. This appears to be breaking the latest version feature.

#### Example 1 PyPi

Request
```
curl -v -X GET --header 'Accept: application/json' --header 'X-Api-Key: REDACTED' 'http://192.168.66.139:8080/api/v1/repository/latest?purl=pkg%3Apypi%2Fdjango%401.7.10'
```

Response
```
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 192.168.66.139...
* TCP_NODELAY set
* Connected to 192.168.66.139 (192.168.66.139) port 8080 (#0)
> GET /api/v1/repository/latest?purl=pkg%3Apypi%2Fdjango%401.7.10 HTTP/1.1
> Host: 192.168.66.139:8080
> User-Agent: curl/7.54.0
> Accept: application/json
> X-Api-Key: REDACTED
> 
< HTTP/1.1 200 OK
< Date: Thu, 21 Mar 2019 17:29:54 GMT
< X-Powered-By: Dependency-Track v3.4.0
< Cache-Control: private, max-age=0, must-revalidate, no-cache
< Content-Security-Policy: default-src 'self';script-src 'self' 'unsafe-inline';style-src 'self' 'unsafe-inline';img-src 'self';connect-src 'self';font-src 'self';object-src 'self';media-src 'self';frame-src 'self';child-src 'self';form-action 'self';frame-ancestors 'none';
< X-Frame-Options: DENY
< Content-Length: 0
< Server: Jetty(9.4.z-SNAPSHOT)
< 
* Connection #0 to host 192.168.66.139 left intact
```

#### Example 2 Maven

Request
```
curl -v -X GET --header 'Accept: application/json' --header 'X-Api-Key: REDACTED' 'http://192.168.66.139:8080/api/v1/repository/latest?purl=pkg%3Amaven%2Fjunit%2Fjunit%404.12' 
```

Response
```
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 192.168.66.139...
* TCP_NODELAY set
* Connected to 192.168.66.139 (192.168.66.139) port 8080 (#0)
> GET /api/v1/repository/latest?purl=pkg%3Amaven%2Fjunit%2Fjunit%404.12 HTTP/1.1
> Host: 192.168.66.139:8080
> User-Agent: curl/7.54.0
> Accept: application/json
> X-Api-Key: REDACTED
> 
< HTTP/1.1 200 OK
< Date: Thu, 21 Mar 2019 17:29:20 GMT
< X-Powered-By: Dependency-Track v3.4.0
< Cache-Control: private, max-age=0, must-revalidate, no-cache
< Content-Security-Policy: default-src 'self';script-src 'self' 'unsafe-inline';style-src 'self' 'unsafe-inline';img-src 'self';connect-src 'self';font-src 'self';object-src 'self';media-src 'self';frame-src 'self';child-src 'self';form-action 'self';frame-ancestors 'none';
< X-Frame-Options: DENY
< Content-Length: 0
< Server: Jetty(9.4.z-SNAPSHOT)
< 
* Connection #0 to host 192.168.66.139 left intact
```

### Expected Behavior:
I expect some JSON output to inform me of the latest version for a given Purl.

### Environment:
  - Dependency-Track Version: v3.4.0
  - Distribution: Docker
  - BOM Format & Version: CycloneDX, via python cyclonedx-bom 0.2.0 
  - Database Server: Whatever the default is for Docker
  - Browser: curl

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I had success calling the other `/api/v1/repository` methods 
* `/api/v1/repository/MAVEN`
    * Successfully returned 5 repos
* `/api/v1/repository/latest?purl=badpurlformatinput` with an intentionally bad format
    * Successfully returned `HTTP/1.1 400 Bad Request`
* `/api/v1/repository/latest?purl=pkg%3Adoesnotexist%2Fjunk%2Fgarbagein%401.2.3` with a intentionally bad repo
    * Successfully returned `HTTP/1.1 204 No Content`

I called Pypi directly and verified my Dependency-Track server was not having connectivity issues.
```
$ curl -v -L --header 'Accept: application/json'  https://pypi.org/pypi/django/json
HTTP/1.1 200 OK
```

**Comment by stevespringett** [comment]
At the time being, only components being tracked in the system will have the necessary metadata to return the latest version. This endpoint (as of today) does not act as a pass-thru to retrieve the latest version of any component, only components being tracked in the system. If that functionality is desired, I'd recommend creating an enhancement request and getting it upvoted (or submit a PR).

Fix will be included in v3.5

**Comment by rback123** [comment]
I believe my Django 1.7.10 example from above is something that is being tracked in my system. Is there a way to verify that? I've only been using DependencyTrack for a short while but I think what I'm seeing qualifies for being tracked, yet there is still no response from the latest API response.

I can visit `http://192.168.66.139:8080/components/` and find Django 1.7.10 in a search. Clicking on the result brings me to the component page at `http://192.168.66.139:8080/component/?uuid=a88754a4-c148-478c-b6fd-c9617e7b8267`

I can query the API using that uuid and see that the component appears to be tracked and has the expected purl.
```
$ curl -s -X GET --header 'Accept: application/json' --header 'X-Api-Key: <REDACTED>' 'http://192.168.66.139:8080/api/v1/component/a88754a4-c148-478c-b6fd-c9617e7b8267' | python -m json.tool
{
    "classifier": "LIBRARY",
    "description": "A high-level Python Web framework that encourages rapid development and clean, pragmatic design.",
    "license": "BSD",
    "md5": "ba5adcf08d8b60bf82284a09a4d384a3",
    "name": "Django",
    "purl": "pkg:pypi/django@1.7.10",
    "sha256": "1db5dafe4fe8302f34449283864baa74d0d64013613aa200918187bf76902d5f",
    "uuid": "a88754a4-c148-478c-b6fd-c9617e7b8267",
    "version": "1.7.10"
}
```

**Comment by stevespringett** [comment]
I haven't tried v3.4, but tried v3.5-SNAPSHOT and it's working as expected. For example:

```bash
curl -v -X GET --header 'Accept: application/json' --header 'X-Api-Key: REDACTED' 'http://localhost:8080/api/v1/repository/latest?purl=pkg%3Apypi%2Fdjango%401.7.10'
```
produces:
```json
{
  "repositoryType":"PYPI",
  "name":"django",
  "latestVersion":"2.2",
  "published":1554140855000,
  "lastCheck":1555910936881
}
```

Also note that just because curl can make the request doesn't mean that the JVM can. This is especially true when SSL-terminating proxies are involved and certificates may be trusted by the OS, but not the JVM. You may want to check the logs to see if there's any indication of connectivity issues.

**Comment by stevespringett** [comment]
I found an issue with NuGet which has been corrected.

**Comment by rback123** [comment]
I just tested v3.5-SNAPSHOT with docker image `owasp/dependency-track:snapshot` and, like you said, it's working as expected. I'm good with closing this issue and I'll open another if it misbehaves again. Hopefully some of the additional logging from v3.5 will provide a clue as to where to look.

**Comment by stevespringett** [comment]
Sounds good. Thanks for confirming.
