### ISSUE TITLE
Remove the cpu requirement (for kubernetes)

### ISSUE THREAD

**Issue by jblamotte** [DependencyTrack/dependency-track#304]
Hi,

### Issue Type:
  - [ X] defect report
  
  
### Current Behavior:
When deploying dependency-track on kubernetes, i get this error : 
ERROR [RequirementsVerifier] Dependency-Track requires a minimum of 2 CPU cores. Cannot continue.
16 cpu in /proc/cpuinfo, but getting this error at startup.

### Steps to Reproduce (if defect):
Just run dependency-track on kubernetes.

### Expected Behavior:
No CPU check. Moreover, I think it's not the app responsibility to check if there is enough ressources.

### Environment:
  
  - Distribution: [ Docker ]

### Other Details:
Alternative should be : 
https://stackoverflow.com/questions/36453298/java-runtime-getruntime-availableprocessors-and-nproc-return-different-value

**Comment by stevespringett** [comment]
Many orgs are running Dependency-Track in Kubernetes with the CPU and memory checks enabled. This is designed to reduce the number of tickets created from folks using virtualized environments which think they have specific resources assigned to a container, but don't.

The stackoverflow article is ancient and no longer accurate. All container enhancements made to Java 10 (which has full Docker support) have been backported to 8u191 and the openjdk-alpine team has ported those to 8u181 which is what the Dockerfile specifies. So the container in Docker hub has full support for Docker and should report accurately on the number of CPUs. If it doesn't report accurately, you'll need to file a defect with the OpenJDK team.

You can disable the requirements check by removing the following line from web.xml:
```xml
<listener>
    <listener-class>org.dependencytrack.RequirementsVerifier</listener-class>
</listener>
```

Another option is to add the following to the existing JAVA_OPTIONS environment variable:
```bash
-XX:ActiveProcessorCount=<count>
```

See: https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html
