### ISSUE TITLE
Updating project tags via UI clears out ExternalReferences fields

### ISSUE THREAD

**Issue by calderonth** [DependencyTrack/dependency-track#3041]
### Current Behavior

When uploading an SBOM with ExternalReferences (say with a pointer to the VCS resource), it gets correctly added to the project.
However, when adding/removing/updating a given project tags, the external references field gets cleared out.

I believe when updating tags in the UI, essentially the whole project structure is passed to /api/v1/project as opposed to using the PATCH method for instance. It does seem like the UI is lacking first party support such updates.

### Steps to Reproduce

1. Upload a SBOM that includes an ExternalReference to VCS
2. Add a tag to the project
3. Observe that the ExternalReferences is now empty

### Expected Behavior

External references should be preserved when adding/removing/updating tags for a project.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by marob** [comment]
Same issue as https://github.com/DependencyTrack/frontend/issues/503

**Comment by nscuro** [comment]
This is a frontend issue and is being tracked here: https://github.com/DependencyTrack/frontend/issues/503
