### ISSUE TITLE
Support for Repository Managers such as Nexus

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#306]
### Issue Type:
  - [ ] defect report
  - [X] enhancement request

I believe that implementing support for  Repository Managers (eg Nexus Repository Managers, also referred to as NXRM) would address a number of important use cases.

Using just Maven to illustrate, Dependency-Track v3.4.0 integrates with the following Repositories:
* Maven Central
* Atlassian Public
* JBoss Releases
* Clojars
* Google Android

One omision from the list is Oracle...  important when using components such 

`pkg:maven/com.oracle/ojdbc6@11.2.0?type=jar`

The v3.40 documentation ([link to current documentation](https://docs.dependencytrack.org/datasources/repositories/)) states that:

> Future versions of Dependency-Track will support configurable repositories and additional ecosystems.

I am logging this issue so that actual implementation can be discussed and tracked.

Supporting a Repository Manager (RM) would:
* Add automatic support for additional repositories (such as Maven Oracle) as long as the RM is configured to proxy said repository
* Support repositories that require authentication (Oracle, again) as the authentication would be configured in the RM.
* Allow DT to perform outdated version tracking for **internal** components  (see also #303)
* Allow additional cleverness in the future?  We are using NXRM for yum and docker.

Blue sky thinking...  If CycloneDX BOM were pushed to an RM as release artefacts, then could they be pulled from there by DT in order to perform analysis?  What I am thinking of here is having a way to track vulnerabilities (licences, etc) for "integration" and "staging" and "production" environments, where each environment is running 100+ systems (microservices, etc) and where the versions of what is deployed in each environment changes over time.  The trick would be to get DT to use the right CycloneDX BOM "versions"...  but that could maybe be populated in DT via REST API?

**Comment by stevespringett** [comment]
Duplicate of #164

Related to #178

**Comment by msymons** [comment]
Duplicate?  Darn!  I did search GitHub before logging anything but managed to miss 164.  Still, I hope that the above use cases are valid.
