### ISSUE TITLE
Same component is risk scored differently in different instances of a project

### ISSUE THREAD

**Issue by scooby359** [DependencyTrack/dependency-track#3077]
### Current Behavior

I set up Dependency Track a couple of months ago and created and created all our projects using the API and auto-project creation. All went well, components seemed to be imported and scanned and risk scores were applied.

I've now had to recreate the projects due to changing names, so I archived the old projects, and imported the BOMs again using the API autocreation, just with new project names. Components have been imported and scanned, but this time round, the risk scores are lower for many components, even though they're the same components and same versions. I can't see an explanation why the components have scored a lower risk score on the second instance of a project.

We've seen this occur across several projects and components, though just shown one below as an example.

Suspected it may be related to https://github.com/DependencyTrack/dependency-track/issues/2519, but that relates to imports to a single project. In this case, it's a separate project.

Initial project, showing EJS v3.1.9 as a risk score of 10
![dt_old](https://github.com/DependencyTrack/dependency-track/assets/17240654/ef829840-a9f4-4e28-b254-2e2487274d1e)

Second project, showing EJS v3.1.9 as a risk score of 0
![dt_new](https://github.com/DependencyTrack/dependency-track/assets/17240654/3bc8c264-8340-4db5-83bf-fcfbb6f2a012)

### Steps to Reproduce

1. Use the Dependency Track API to import a BOM file and auto-create a project on the given name.
2. Allow scanning to happen and observe the output risk scores.
3. Archive the project.
4. Use the Dependency Tack API to import the BOM file with auto-create a project, using a different project name.
5. Allow scanning to happen and observe the output risk scores are lower than the initial project.

### Expected Behavior

Expect that for a given component at a specific version, the risk score would be the same across any project.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

Microsoft SQL Server

### Database Server Version

12.0.2000.8

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by valentijnscholten** [comment]
Do both have the exact same purl/cpe for the ejs component?

**Comment by poschi3** [comment]
We have the same issue and I can confirm that the purl is the same (cpe is empty).

jackson-core with problem:

![grafik](https://github.com/DependencyTrack/dependency-track/assets/825911/1bff7981-2fd4-40e0-9226-c76d993210ff)

jackson-core without problem:
![grafik](https://github.com/DependencyTrack/dependency-track/assets/825911/e4276f82-c53e-4193-9404-27e5aeef65fd)

**Comment by nscuro** [comment]
Note how in both cases shown here, the component had a vulnerability assigned to it previously, but does not have it anymore. If there's a difference in vulnerabilities identified, there will of course be a difference in the risk score.

Can you please verify whether the now-missing vulnerability is legit, or whether it was a false positive that has potentially been resolved in OSS Index in the meantime?

**Comment by poschi3** [comment]
I'm not sure if I understand you correct. In the case with problems (first image) there is one vulnerability. In the second case there are no vulnerabilities.

This is the vulnerability in case with problems: OSSINDEX sonatype-2022-6438 CWE-400
![grafik](https://github.com/DependencyTrack/dependency-track/assets/825911/2af69cad-5368-4fd7-a57f-207aa18f6bbb)

If I click on the name I get this information:
![grafik](https://github.com/DependencyTrack/dependency-track/assets/825911/1a0747e2-7751-495a-8ded-f73c3964d3f0)

The link on the bottom in References is https://ossindex.sonatype.org/vulnerability/sonatype-2022-6438?component-type=maven&component-name=com.fasterxml.jackson.core%2Fjackson-core&utm_source=dependency-track&utm_medium=integration&utm_content=v4.6.3 and leads me to 404 error page.

**Comment by scooby359** [comment]
For my example, in this case I have Snowflake.Data package in the first and second instances of a project. 

In the first Snowflake.Data has a known vulnerability and a risk score of 5, in the second instance, there's no recorded vulnerability and a risk score of 0.

![image](https://github.com/DependencyTrack/dependency-track/assets/17240654/c5e8bf4a-c1cf-49d9-9995-ad3dfb20cf69)

In both cases, the Package URL (PURL) is the same.

![image](https://github.com/DependencyTrack/dependency-track/assets/17240654/ac2b6a80-c062-46b2-8005-d44990a48300)

The first instance has a known vulnerability attached, the second instance has no vulnerability attached.

![image](https://github.com/DependencyTrack/dependency-track/assets/17240654/474325e5-d902-4a4d-a5dd-53ab86472924)

The known vulnerability links to a [Github Security Issue](https://github.com/snowflakedb/snowflake-connector-net/security/advisories/GHSA-223g-8w3x-98wr) which indicates the vulnerability affects Snowflake.Data < 2.0.18, so version 2.0.7 used in both the first and second instance of the Dependency Track projects should be flagging this as a vulnerability.

**Comment by nscuro** [comment]
@poschi3 Seems like you fell victim to Sonatype discontinuing their exposure of `sonatype-*` vulnerabilities. There was a time frame in which OSS Index would utilize Sonatype's proprietary vulnerability database to report vulns for which no CVE exists. This is no longer the case, so you won't see such vulns anymore.

@scooby359 I am unable to reproduce. I added the component you showed, and the CVE is correctly reported by OSS Index, and additionally by GitHub when the [GitHub integration](https://docs.dependencytrack.org/datasources/github-advisories/) is enabled:

<img width="1419" alt="image" src="https://github.com/DependencyTrack/dependency-track/assets/5693141/df1a65ca-c5ed-44cd-b9fb-21150718b0b4">

Perhaps clicking the *Reanalyze* button resolves this? If not, please check your API server logs for any errors.

**Comment by scooby359** [comment]
@nscuro Tried reanalysing and found an error message in the logs, appears the Sonatype OSS API Key had become corrupted. I've reset that and re-run vulnerability analysis and issues are now being found again.

Issue can be closed as solved, thanks.

![image](https://github.com/DependencyTrack/dependency-track/assets/17240654/024415c0-3c47-4b7a-9fef-0ea5604301a8)

**Comment by savek-cc** [comment]
@scooby359 I think you can close the issue yourself as author?
In general, some cleanup might be in order with currently more than 500 "open" issues?
