### ISSUE TITLE
http://{hostname}:{port}/api/swagger.json returns 404

### ISSUE THREAD

**Issue by qflowdev** [DependencyTrack/dependency-track#3078]
### Current Behavior

navigating to the swagger json endpoint (http://{hostname}:{port}/api/swagger.json) that the [documentation](https://docs.dependencytrack.org/integrations/rest-api/) lists returns a 404

    

### Steps to Reproduce

1. Navigate to http://{hostname}:{port}/api/swagger.json

### Expected Behavior

 returns the swagger api json

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

N/A

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by DenisSchettl** [comment]
What port are you used for calling the url?
For the api you have to use the defined port for the api-server, not the frontend.

When I use the frontend-port, i got an 404. When I use the api-server-port, then I got the json file back.

Please check the defined port from the container-start and retry the call again.

**Comment by nscuro** [comment]
What @DenisSchettl says. 

You're not supposed to *literally* call `http://{hostname}:{port}/api/swagger.json`, but instead replace the placeholders according to your deployment. If you used the default [`docker-compose.yml`](https://github.com/DependencyTrack/dependency-track/blob/master/src/main/docker/docker-compose.yml) on your laptop / workstation, it would be `http://localhost:8080/api/swagger.json`.
