### ISSUE TITLE
Dependency Check version lagging behind

### ISSUE THREAD

**Issue by surfinbird** [DependencyTrack/dependency-track#308]
Hi.

The latest release version of dependency check is 4.0.2, which amongst others resolved several false positives (https://github.com/jeremylong/DependencyCheck/issues/1637)
while it seems that dependency track is depending on 4.0.1.

I am wondering if you have plans to use 4.0.2 soon?

Best regards
Lars

**Comment by stevespringett** [comment]
The next release of Dependency-Track will likely include Dependency-Check v5. The version of Dependency-Check bundled is much less relevant in Dependency-Track as many (or most) of the suppressions defined in Dependency-Check do not work on Dependency-Track.

See also: https://docs.dependencytrack.org/best-practices/

**Comment by surfinbird** [comment]
Thank you so much.

I have another question:

I have been noticing a few false positives from time to time, so with the tips from the link you sent me, I tried to start a fresh dependency-track server locally(v3.4.0), disable dependency check and enable ossi scanner. I then created a project and uploaded a cyclonedx bom, and a dependency I suspected of being a false positive was then not marked as vulnerable here. In this project, no dependencies are marked as vulnerable

When I go to my other dependency track server (v3.4.0), disable dependency check, enable ossi scanner, delete the project, create new project manually, and manually upload the same cyclonedx bom, dependency track reports on two CVE's in one of the dependencies. 

Do you have any suggestions to why I am experiencing this mismatch?

Best regards
Lars

**Comment by stevespringett** [comment]
Disabling Dependency-Check on a server does not remove vulnerabilities it has discovered previously against the components. You would need to remove all components from the system in order to have the same set of results.

**Comment by surfinbird** [comment]
Okay.

Thank you very much for taking the time to answer my questions. You're doing great work.

Best regards
Lars
