### ISSUE TITLE
cannot inport Operating System SBOM from CDX gen

### ISSUE THREAD

**Issue by mjhillyer** [DependencyTrack/dependency-track#3084]
### Current Behavior

DT is erroring out while processing an SBOM that contains elements that have the "type": "data" tag.

### Steps to Reproduce

1. using cdxgen to create an SBOM for an operating system - cdxgen -t os -o bom.json --spec-version 1.4

2. sbom completes successfully, when importing into Dtrack I get the following error - 
 Cannot deserialize value of type `org.cyclonedx.model.Component$Type` from String "data": not one of the values accepted for Enum class: [application, container, device, library, file, framework, operating-system, firmware]

3. searching the bom I see several entries that have "type": "data"

4. if i manually replace all "type": "data", entries with "type": "file", the SBOM imports successfully.

### Expected Behavior

Import SBOM successfully  

not sure where the issue lies - is CDX gen using a newer schema (they do default to 1.5 spec-version) and DT needs to update or is CDX gen using a field that is not part of the supported standard?

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

15.3-1.pgdg110+1

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
This is a symptom of DT < 4.9.0 not supporting CycloneDX v1.5 BOMs. See https://github.com/DependencyTrack/dependency-track/issues/2850 for details. Will be fixed in the upcoming 4.9 release.
