### ISSUE TITLE
Jira Alert not working

### ISSUE THREAD

**Issue by visagansanthanam-unisys** [DependencyTrack/dependency-track#3088]
### Current Behavior

JIRA alert is not triggering event after configuring the alert and templates for JIRA. on investigating no record of publisher org.dependencytrack.notification.publisher.JiraPublisher
![DepTrack-JIRA1](https://github.com/DependencyTrack/dependency-track/assets/100369838/2824c1c9-4f08-4ca4-88fe-8b33ce28b16a)
![DepTrack-JIRA2](https://github.com/DependencyTrack/dependency-track/assets/100369838/98a5df04-651f-440f-b128-710ba6cfa40c)

### Steps to Reproduce

1. Configure Jira Integration by providing the JIRA Base URL, and credentials (username & password)
2. Create a new Alert with following details
Publisher Class = org.dependencytrack.notification.publisher.JiraPublisher
Notification Class = ERROR or Warning or Informational
3. Provide Destination Project Key and Jira Ticket Type
4. Select all the items in the group

### Expected Behavior

A Jira ticket needs to be created for any of the Group items activity performed.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Admittedly the confusion about levels is justified, we didn't have documentation on it so it was unclear what it does.

I added some documentation on it in a recent PR, which mainly evolved around improving the logging (#3211):

* How levels work: https://github.com/DependencyTrack/dependency-track/blob/master/docs/_docs/integrations/notifications.md#levels
* What levels to expect for each group: https://github.com/DependencyTrack/dependency-track/blob/master/docs/_docs/integrations/notifications.md#groups

This will be published to docs.dependencytrack.org with the next release. Please let me know if it still not clear, or if you have suggestions on how to improve this documentation :)

**Comment by jxlambda** [comment]
Thank you for updating, @nscuro! This makes it crystal clear (at least to me, as it's effectively a software logging level cascade).

**Comment by visagansanthanam-unisys** [comment]
@nscuro Thanks for the update. now the documentation is very clear on the different notification levels available.

**Comment by jovanz-getbgd** [comment]
It's already been said, but here's a thank you from me as well, the documentation update clarifies all this perfectly.

**Comment by visagansanthanam-unisys** [comment]
> Thanks both for the feedback!
> 
> With this sorted, is there anything else here that needs addressing? If not, are we OK with closing this issue?

@nscuro i think we can close the issue.
