### ISSUE TITLE
Encountering problems with Mattermost notifications related to 'PROJECT_AUDIT_CHANGE

### ISSUE THREAD

**Issue by khaledgithubwl** [DependencyTrack/dependency-track#3093]
### Current Behavior

Following a vulnerability audit, we observed that no Mattermost notifications were triggered.

Upon a more in-depth analysis of the logs, we discovered : " 2023- [] ERROR [org.dependencytrack.notification.publisher.MattermostPublisher] An error was encountered publishing notification to Mattermostwith HTTP Status : 400 Bad Request Destination: https://mattermost.kazan.myworldline.com/hooks/xxxxxxxxxxxx Response: {"id":"model.incoming_hook.parse_data.app_error","message":"Unable to parse incoming data.","detailed_error":"invalid character '\\\\' after object key:value pair","request_id":"xxxxxxxxxxxxxxxxxx","status_code":400} "

Can you please help us resolving the issue ? 

Best Regards

### Steps to Reproduce

1. Log in to Dependency-Track
2. Go to a specific project and access the "Audit Vulnerabilities" tab.
3. Perform a vulnerability audit on a vulnerability

### Expected Behavior

a mattermost notification should be seen

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Can you make out if the project, component, or vulnerability that's being audited contains special characters? Inclusion of `\\` hints at escaping going wrong somewhere. 

In any case I'll add more tests for the Mattermost integration.
