### ISSUE TITLE
Make vulnerabilities download optional

### ISSUE THREAD

**Issue by h3xstream** [DependencyTrack/dependency-track#311]
It would be nice, when we first login, to have the opportunity to select source of vulnerabilities needed.

### Issue Type:

enhancement request

### Current Behavior:

As soon as it started, it start downloading vulnerability from all sources.

### Wanted Behavior:

Being display a list of options and than start the download for the selected sources.

**Comment by stevespringett** [comment]
Whats the scenario you're trying to achieve?

I can see this being potentially valuable disabling NPM Audit findings. But OSS Index which by itself is a 'source' will most often refer to CVEs from the NVD which is a different source.

At one point it time it was also possible to do this same type of xref between NSP and the4 NVD, but NPM in their infinite wisdom took that ability away. But it they ever put it back, the same thing could apply.

**Comment by h3xstream** [comment]
Perfect.
It is actually less spaces than I expected. I see that the default docker container is just over 500 mb.
