### ISSUE TITLE
Add "Affected Projects" Count to Components and Vulnerabilities Screens

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#312]
### Issue Type:
  - [ ] defect report
  - [X] enhancement request

As an enhancement, it would be useful for the "Components" and "Vulnerabilities" screens to display a column that (respectively) provides a numeric count of:
* the number of projects that have a particular component as a dependency
* the number of projects that are affected by a particular vulnerability.

Thus, for "Components":
  
![Affected-Projects-Count](https://user-images.githubusercontent.com/4938718/55738718-944bea80-5a1f-11e9-8a37-86796de30c7a.png)
  
The column should be sortable for ease of use.

Note that the screenshot shows that some components are known to Dependency-Track but are currently unused in any projects (count = 0).  Thus, the display of "0" tells the user that there is no need to click thru and examine such a component (eg jackson-databind 2.8.10) which is otherwise looking like it needs attention (because it has vulnerabilities).

If implemented, this enhancement should improve the usability of separate enhancements such as #146.

Aside:  the screenshot also shows one component that should be displaying threats but which is not:  

`pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.9.4?type=jar`

 See #305.

### Environment:
  - Dependency-Track Version: 3.4.0

**Comment by msymons** [comment]
@stevespringett, is there a chance that this could make it into v3.7.0?  The functionality would help a lot.  It's not just being able to see when the project count is 0 (meaning that a component can be deleted from DT).  It would also be immensely useful to get an "at a glance" idea of the spread of version usage.  eg "version 1 used in 1 project and version 2 used in 100 projects" lets one know that a process of migration (version 1 to version 2) is almost complete...

**Comment by stevespringett** [comment]
Sorting is not being implemented as it will greatly impact performance.
