### ISSUE TITLE
why only busybox has cve?

### ISSUE THREAD

**Issue by chenjianquan7** [DependencyTrack/dependency-track#3138]
### Current Behavior

upload a sbom file
but only busybox has cve
![image](https://github.com/DependencyTrack/dependency-track/assets/26828709/90d80888-16f2-4b94-8f0a-c64d0d300331)

### Steps to Reproduce

1.

### Expected Behavior

output cve 

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
I am very sorry but we'll need a bit more info than this to investigate. Can you share the SBOM you uploaded?

In any case I'd encourage you to update your DT instance to 4.9.0, as we resolves some false negative issues WRT matching with NVD vulnerabilities: https://docs.dependencytrack.org/changelog/

**Comment by chenjianquan7** [comment]
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "version": 1,
  "components": [
    {
      "type": "library",
      "name": "busybox",
      "version": "1.22.1",
      "cpe": "cpe:2.3:a:busybox:busybox:1.22.1:*:*:*:*:*:*:*"
    },
    {
      "type": "library",
      "name": "hostapd",
      "version": "2.5",
      "cpe": "cpe:2.3:a:hostapd:hostapd:2.5:*:*:*:*:*:*:*"
    },
    {
      "type": "library",
      "name": "kernel",
      "version": "3.10.14",
      "cpe": "cpe:2.3:a:kernel:kernel:3.10.14:*:*:*:*:*:*:*"
    },
    {
      "type": "library",
      "name": "libcurl",
      "version": "7.65.1",
      "cpe": "cpe:2.3:a:libcurl:libcurl:7.65.1:*:*:*:*:*:*:*"
    },
    {
      "type": "library",
      "name": "sed",
      "version": "4.0",
      "cpe": "cpe:2.3:a:sed:sed:4.0:*:*:*:*:*:*:*"
    },
    {
      "type": "library",
      "name": "udhcp",
      "version": "1.22.1",
      "cpe": "cpe:2.3:a:udhcp:udhcp:1.22.1:*:*:*:*:*:*:*"
    },
    {
      "type": "library",
      "name": "wpa_cli",
      "version": "2.6",
      "cpe": "cpe:2.3:a:wpa_cli:wpa_cli:2.6:*:*:*:*:*:*:*"
    },
    {
      "type": "library",
      "name": "wpa_supplicant",
      "version": "2.6",
      "cpe": "cpe:2.3:a:wpa_supplicant:wpa_supplicant:2.6:*:*:*:*:*:*:*"
    }
  ]
}

**Comment by chenjianquan7** [comment]
[f21_cyclonedx_sbom.json](https://github.com/DependencyTrack/dependency-track/files/13175497/f21_cyclonedx_sbom.json)

**Comment by nscuro** [comment]
@chenjianquan7 Other than the `busybox` one, none of the CPEs in that SBOM have any matches in the NVD. It seems like whatever tool you used to generate the SBOM populated the `vendor` attribute of the CPE with the `product` attribute's value.

If you change `cpe:2.3:a:libcurl:libcurl:7.65.1:*:*:*:*:*:*:*` to `cpe:2.3:a:*:libcurl:7.65.1:*:*:*:*:*:*:*` (changing the `vendor` from `libcurl` to `*`), you'll get vulnerabilities. The same can be done for the other components in your SBOM.

Also note that the Linux kernel is tracked as operating system by the NVD (the `part` attribute is `o` not `a`), and the `product` attribute is `linux_kernel`, not `kernel`: https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Ao%3Alinux%3Alinux_kernel%3A3.10.14%3A*%3A*%3A*%3A*%3A*%3A*%3A*

The NVD has a CPE search functionality where you can validate whether your CPEs are valid: https://nvd.nist.gov/products/cpe/
