### ISSUE TITLE
Gitlab integration support

### ISSUE THREAD

**Issue by sanjogpandasp** [DependencyTrack/dependency-track#314]
Hi,

I was wondering if dependency-track can be integrated with gitlab ci. Do you have any plans of supporting gitlab integration out of the box in the upcoming version?

Regards
Sanjog Panda

**Comment by stevespringett** [comment]
The project supplies a swagger definition for its APIs and has an API-first design. The Jenkins plugin for example, is a simple wrapper around the API with some optional functionality to break builds, etc.

While there are no plans on officially supporting Gitlab CI, it should be elementary to do so using the same API calls the Jenkins plugin makes - again, this is all documented in the swagger. I don't know if anyone else is using GitLab or not, but you may want to check the Slack channel as there's about a hundred or so members currently. Community-supported integration projects are highly encouraged.
