### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by mehrdad2000** [DependencyTrack/dependency-track#3174]
### Current Behavior

Hi
run this command to upload bom.xml to dependency-track server 
`curl -X PUT -H 'Content-Type: application/json' -H 'X-API-Key: $TOKEN' -d @/home/bom.xml http://$IP:8080/api/v1/bom?project=$ID`

got this error:
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.23.4</center>
</body>
</html>
```

FYI: I'm using dependency-track docker version 4.8.2
Any Idea?
Thanks

**Comment by ybelMekk** [comment]
This is answered: https://github.com/DependencyTrack/dependency-track/issues/916

**Comment by mehrdad2000** [comment]
@ybelMekk 
here is my nginx.conf on docker, try to     client_max_body_size 0;   but not work and return this error:
405 Not Allowed


here is /etc/nginx/nginx.conf
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /tmp/nginx.pid;


events {
    worker_connections  1024;
}


http {
    proxy_temp_path /tmp/proxy_temp;
    client_body_temp_path /tmp/client_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
    client_max_body_size 0;



}

**Comment by ybelMekk** [comment]
tried this? 
It is not Dp it self that gives you the error but nginx

https://github.com/DependencyTrack/dependency-track/pull/3167

**Comment by valentijnscholten** [comment]
> FYI: I'm using dependency-track docker version 4.8.2
If you're using the default docker-compose file you need to post to port 8081 (apiserver container) instead of 8080 (frontend container)

**Comment by mehrdad2000** [comment]
@valentijnscholten This is exactly the reason for the issue, after the change port issue was resolved! :))
Thanks
