### ISSUE TITLE
Portfolio Access Control

### ISSUE THREAD

**Issue by rozeru1125** [DependencyTrack/dependency-track#3193]
### Current Behavior

1. The dashboard lacks accuracy. Despite having access to only one project, the dashboard displays three. Refer to the image 
![image](https://github.com/DependencyTrack/dependency-track/assets/147065307/8c5fd518-72c4-4897-8285-a242fde50ab3)

### Proposed Behavior

1. The dashboard should exhibit precise data, reflecting only the projects accessible to the user.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Duplicate of #2323.
