### ISSUE TITLE
Massive deterioration of the Portfolio Vulnerability Analysis performance due to unnecessary increment in the amount of components to proceed.

### ISSUE THREAD

**Issue by dimitri-rebrikov** [DependencyTrack/dependency-track#3219]
### Current Behavior

**Issue in Code:** The `org.dependencytrack.tasks.VulnerabilityAnalysisTask` class defines the list of components to analyse as the class fields and does not reset them during the re-analysis of multiple projects which leads to massive performance issues.
**Details:** 
In context of PortfolioVulnerabilityAnalysisEvent  the VulnerabilityAnalysisTask  will collect all existing projects and re-analyse them. During the re-analysis it fills the component lists (internalCandidates, ossIndexCandidates, vulnDbCandidates, snykCandidates)  with matching components to analyse (method `analyzeComponents`) . As the lists are declared on the class level and are not reset after the project analysis they grooving with every next project to analyse. In case of many hundreds of  projects the lists of the components grows to many thousands which massively slows down the processing leading to processing time of weeks.
Example from our log:
```
	Line 114894: 2023-11-20 14:23:59,322 INFO [VulnerabilityAnalysisTask] Analyzing 165 components in project: 5483bca3-3461-436a-b28a-081934c66f67
	Line 114895: 2023-11-20 14:23:59,342 INFO [InternalAnalysisTask] Starting internal analysis task
	Line 114896: 2023-11-20 14:23:59,342 INFO [InternalAnalysisTask] Analyzing 86785 component(s)
	Line 114897: 2023-11-20 14:33:14,801 INFO [InternalAnalysisTask] Internal analysis complete
	Line 115787: 2023-11-20 14:58:02,310 INFO [VulnerabilityAnalysisTask] Completed scheduled analysis of 165 components in project: 5483bca3-3461-436a-b28a-081934c66f67
	Line 115789: 2023-11-20 14:58:02,337 INFO [VulnerabilityAnalysisTask] Analyzing 0 components in project: bc424d39-27c5-497d-9b52-f92f49b81664
	Line 115790: 2023-11-20 14:58:02,344 INFO [InternalAnalysisTask] Starting internal analysis task
	Line 115791: 2023-11-20 14:58:02,345 INFO [InternalAnalysisTask] Analyzing 86785 component(s)
	Line 116035: 2023-11-20 15:06:29,242 INFO [InternalAnalysisTask] Internal analysis complete
	Line 116062: 2023-11-20 15:28:11,952 INFO [VulnerabilityAnalysisTask] Completed scheduled analysis of 0 components in project: bc424d39-27c5-497d-9b52-f92f49b81664
	Line 116064: 2023-11-20 15:28:12,005 INFO [VulnerabilityAnalysisTask] Analyzing 56 components in project: 9c27d57a-2288-4495-b37a-1558eaaef52f
	Line 116065: 2023-11-20 15:28:12,020 INFO [InternalAnalysisTask] Starting internal analysis task
	Line 116066: 2023-11-20 15:28:12,020 INFO [InternalAnalysisTask] Analyzing 86841 component(s)
	Line 116067: 2023-11-20 15:35:59,650 INFO [InternalAnalysisTask] Internal analysis complete
	Line 116073: 2023-11-20 15:50:41,214 INFO [VulnerabilityAnalysisTask] Completed scheduled analysis of 56 components in project: 9c27d57a-2288-4495-b37a-1558eaaef52f
```
**Proposed solution:** define the corresponding list inside of the `analyzeComponents` method so they automatically emptied after each project analysis. 

### Steps to Reproduce

1. you shall have several projects
2. wait until the automatic task `[VulnerabilityAnalysisTask] Analyzing portfolio` is stared  (i.e. watch the log file)
3. analyse the log file for the amount of components to analyse for InternalAnalysisTask task
4. you will see the increasing amount of components to analyse

### Expected Behavior

only components of the current project shall be analysed

### Dependency-Track Version

4.9.1

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Ha, good catch @dimitri-rebrikov! Would you like to raise a PR with a fix to collect the well-deserved credit? :)


Slightly related, I also see that it is loading unnecessary data here:

https://github.com/DependencyTrack/dependency-track/blob/a6de47b920ecc4bd86d27666bdf85b67782e4263/src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java#L81-L86

It's fetching entire `Project` records for *all* projects at once, just to only use the `uuid` field, and reload the entire record again in each loop iteration. Instead we should load projects in chunks, and only those fields that we need instead of the entire record.

**Comment by dimitri-rebrikov** [comment]
Hi @nscuro , yes will do.
