### ISSUE TITLE
Assigning team recipients not possible for custom email publishers

### ISSUE THREAD

**Issue by andreasmihm** [DependencyTrack/dependency-track#3227]
### Current Behavior

We use a dedicated DependencyTrack Email Notification Template to filter only critical vulnerabilities.
We also use teams for Access control. I want to create an email alert using our template, which is assigned to a specific team as recipient and is limited to some projects.

When I try to configure it, DepTrack API returns this error:Team subscriptions are only possible on notification rules with EMAIL publisher.

Why is it not possible to assign a Team as recipient in this scenario?

### Proposed Behavior

It should be possible to create an alert based on a custom email template which uses a team as recipient

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
I believe this is mainly due to the "assign to team" feature predating the support for custom publishers. There was a hardcoded check for the default email publisher. Will be fixed with #3232.
