### ISSUE TITLE
Could not find artifact us.springett:vulndb-data-mirror:jar:1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by feliceg77** [DependencyTrack/dependency-track#331]
maven fails during building of 3.4.x

**Comment by stevespringett** [comment]
Not sure why your build cannot find it. My local builds as well as TravisCI all work. Snapshots of that library are here: https://oss.sonatype.org/content/repositories/snapshots/us/springett/vulndb-data-mirror/1.0.0-SNAPSHOT/

**Comment by stevespringett** [comment]
FYI, My focus is on getting v3.5.0 released which is happening in the master branch. I do not keep the branches updated unless I need to make a release in a branch, and there will not be further 3.4.x releases. 3.4.1 is the latest and last of the 3.4.x branch.
