### ISSUE TITLE
Mysql Binlog

### ISSUE THREAD

**Issue by feliceg77** [DependencyTrack/dependency-track#332]
### Current Behavior:
mysql binlog increase of 1GB every hour 

### Environment:
  - Dependency-Track Version: 3.4.0
  - Distribution:  Executable WAR
  - Database Server: MySQL 5.7.10

**Comment by stevespringett** [comment]
Current version is 3.4.1 which resolved an endless loop issue performing npm analysis. Try upgrading. Also what’s in the log? It shouldn’t be growing that fast.

**Comment by feliceg77** [comment]
Log Example: "UPDATE `VULNERABILITY` SET `CVSSV2VECTOR`=null WHERE `ID`=38275"

Is it possible schedule nist mirror update? now start every time Dtrack start... so if dtrack is started many times in a day, update on vulnerability table is continuous

**Comment by stevespringett** [comment]
DT is designed to be a long running process, not restarted often. In production, it should be rare that DT is restarted. Scheduling cannot be changed and there is no way (currently) to schedule the mirroring (or any other of the dozens of background processes).

**Comment by feliceg77** [comment]
In the event that the container is restarted automatically because an error such as an OOM has occurred, even if the download of the vulnerabilities has just ended, restart ...
It would be interesting to be able to update the vulnerability table again only a few hours after the last update.

**Comment by stevespringett** [comment]
Even on restarts, the vulnerability table will only be updated if there are changes in a NVD data feed. For example, if years 2002 - 2018 have remained unchanged and there was a change only in the 2019 feed, then only the data for 2019 will be updated. If there were no changes in the NVD since the last sync, the vulnerability table will not be updated at all.

**Comment by stevespringett** [comment]
Also of interest... Dependency-Track 3.4.1 and previous did not contain a shutdown hook when used with the embedded Jetty container (as is with Docker). Dependency-Track 3.5.0 will contain a shutdown hook as part of embedded Jetty which will respond to SIGTERM and will gracefully shutdown the server.
