### ISSUE TITLE
Unable to login to Dependency Track frontend dashboard

### ISSUE THREAD

**Issue by ynarewade** [DependencyTrack/dependency-track#3352]
### Current Behavior

I am trying to login to the Dependency Track frontend dashboard. On entering a username and password and clicking on the Login button, it takes me nowhere. It was working 10 days ago.
Could you please share if there is any solution for this?

### Steps to Reproduce

1. Launch docker and ensure that Dependency Track apiserver and frontend are running
2. Open the port 8080:8080 using the link next to the frontend container. A local login webpage will open. 
3. Enter username and password and click "Login" button. It goes nowhere. APIserver reports an error - **_ERROR [Schema] An exception was thrown while adding/validating class(es) : The database has been closed [90098-224]_**
2024-01-05 08:26:06 The database has been closed [90098-224]
4. It started happening on January 3. It was working 10 days ago. I have attached screenshot and whole log file. 
![image (81)](https://github.com/DependencyTrack/dependency-track/assets/148451253/306cd16c-1e47-4c90-a8c2-ae32aec000c6)
[apiserver.txt](https://github.com/DependencyTrack/dependency-track/files/13838028/apiserver.txt)

### Expected Behavior

1. Login to the DT frontend dashboard is successful, and a list of projects is displayed.

### Dependency-Track Version

4.10.0

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by dorianborovina** [comment]
I have a similar problem, if not the same. Where did you get that log from?
I was able to SSH into the API container, but I can't find that log.
Thanks!

**Comment by ynarewade** [comment]
I got the logs by clicking this hyperlink in Docker:
![image](https://github.com/DependencyTrack/dependency-track/assets/148451253/311f5d29-eb13-476b-997e-e1081adabce8)

**Comment by ynarewade** [comment]
FYI - I was able to fix this issue by deleting the container and adding it again by running the following commands:

curl -LO https://dependencytrack.org/docker-compose.yml
docker-compose up -d

**Comment by ynarewade** [comment]
FYI - I was able to fix this issue by deleting the container and adding it again by running the following commands:

curl -LO https://dependencytrack.org/docker-compose.yml
docker-compose up -d
