### ISSUE TITLE
 Request Tier 2 Plugin for Dependency Track CloudBees

### ISSUE THREAD

**Issue by mahi0x00** [DependencyTrack/dependency-track#3356]
### Current Behavior

**Description**: I'm requesting the development of a Tier 2 plugin for Dependency Track that integrates with CloudBees. 
Current Dependency Track plugin version: Version: 4.3.1
Tier 3: Community
Plugin ID: dependency-track
Minimum Jenkins required: 2.289.2
Last released: 8 months, 28 days ago

### Proposed Behavior

Tier 2 or Tier 1

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by valentijnscholten** [comment]
Not sure if this is the right place to ask. Did you see: https://github.com/jenkinsci/dependency-track-plugin, which is the home of the Jenkins plugin.

**Comment by mahi0x00** [comment]
Thank you @valentijnscholten, I did. Some organisations rely on CloudBees Assurance Program before installing any plugins.
Please refer to https://docs.cloudbees.com/docs/cloudbees-common/latest/plugin-support-policies

**Comment by nscuro** [comment]
Please raise your request in the Jenkins plugin repository. The DT team does not maintain the Jenkins plugin.
