### ISSUE TITLE
[Trivy] Support for properties

### ISSUE THREAD

**Issue by fnxpt** [DependencyTrack/dependency-track#3369]
### Current Behavior

Currently when scanning with trivy analyser we are not able to pass properties from sbom since they are not stored

### Proposed Behavior

As soon as #2560 is fixed we can use these properties in #3251

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by fnxpt** [comment]
Im not passing the properties yet... the test I did was simple sending it manually to trivy

**Comment by nscuro** [comment]
Yes I meant manual testing.

When I tested yesterday I modified the code accordingly.

**Comment by fnxpt** [comment]
I need to double check it... not sure if I will be able to do it today, but for sure tomorrow

**Comment by nscuro** [comment]
Thanks, but no reason to sweat it. 

I was hoping to close this gap before the 4.11 release. Adding support for component properties isn't that much work. There is a [pending PR from a contributor](https://github.com/DependencyTrack/dependency-track/pull/2717) that brings us 80% there. So if we can proof that forwarding properties works as expected, I can add this capability.
