### ISSUE TITLE
SBOM upload of two components with same CPE using a wildcard are not imported all.

### ISSUE THREAD

**Issue by groetingc** [DependencyTrack/dependency-track#3371]
### Current Behavior

![image](https://github.com/DependencyTrack/dependency-track/assets/12998174/a2dd1501-29b5-4d18-aa98-32564414a7f1)

### Steps to Reproduce

1. Create project
2. Upload this sbom.json into that project:

`{ "bomFormat": "CycloneDX", "specVersion": "1.4", "serialNumber": "urn:uuid:23d6e70a-4502-4da8-b196-efb41664c7fe", "version": 1, "metadata": { "timestamp": "2023-12-13T13:21:58+01:00", "component" : { "type" : "firmware" } }, "components": [
{
"name": "alsa-utils",
"version": "1.2.1.2",
"licenses" : [ { "license" : { "id" : "GPL-2.0" } } ],
"cpe": "cpe:2.3:*:alsa-project:alsa:1.2.1.2:*:*:*:*:*:*:*",
"type": "application"
},
{
"name": "alsa-lib",
"version": "1.2.1.2",
"licenses" : [ { "license" : { "id" : "LGPL-2.1" } } ],
"cpe": "cpe:2.3:*:alsa-project:alsa:1.2.1.2:*:*:*:*:*:*:*",
"type": "library"
}
] }`

4. Check after processing is complete how many components are listed.

**NOTE**: When changing the CPE from one component from:
"cpe": "cpe:2.3:*:alsa-project:alsa:1.2.1.2:*:*:*:*:*:*:*"
To:
"cpe": "cpe:2.3:**a**:alsa-project:alsa:1.2.1.2:*:*:*:*:*:*:*"

SBOM Upload works as expected!

### Expected Behavior

There should be 2 components listed.
![image](https://github.com/DependencyTrack/dependency-track/assets/12998174/aa323ef2-faba-406c-8b63-b03e90c30c3d)

### Dependency-Track Version

4.10.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

16.1

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Thanks for reporting and providing a sample BOM @groetingc!

I was able to reproduce, *and* I was able to verify that #3357 is going to fix it.
Added a regression test here: https://github.com/DependencyTrack/dependency-track/pull/3357/commits/54582368b418f43bbaac416bbd468cbd6764ac55
