### ISSUE TITLE
Generate BOM file for Multi Module Project

### ISSUE THREAD

**Issue by mathuriga** [DependencyTrack/dependency-track#339]
I'm using DT to monitor dependencies used in a multi-module project. To create a BOM file for the multi-module project, I'm using cyclonedx-maven-plugin:makeAggregateBom. Does the generated parent BOM file covers all the modules dependencies?

**Comment by stevespringett** [comment]
Yes, the makeAggregateBom goal will create a BOM consisting of all direct and transitive dependencies for all Maven modules defined in the parent pom.
