### ISSUE TITLE
Is there a way to suppress vulnerability globally

### ISSUE THREAD

**Issue by alfajr** [DependencyTrack/dependency-track#3393]
### Current Behavior

vulnerability can be suppressed per project

### Proposed Behavior

vulnerability can be suppressed globally

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by wurstbrot** [comment]
@alfajr You closed the issue, is the feature already there?

**Comment by wurstbrot** [comment]
https://github.com/DependencyTrack/dependency-track/issues/1495
