### ISSUE TITLE
"Outdated only" and "Direct only" buttons or disabled

### ISSUE THREAD

**Issue by visagansanthanam-unisys** [DependencyTrack/dependency-track#3404]
### Current Behavior

The "Outdated only" & "Direct only" buttons are disabled in some projects and enabled in some other projects in the same instance of the dependency tracker. Below is the screenshot of a project where the buttons are disabled, even though there are outdated components listed

![image](https://github.com/DependencyTrack/dependency-track/assets/100369838/1511d146-dd6f-4531-8630-68636460b204)

The issue is not consistent as some other projects in the same instance has the button working fine
![image](https://github.com/DependencyTrack/dependency-track/assets/100369838/4a3a8e23-94d5-499c-aca4-b33036174da9)

### Steps to Reproduce

1. Navigate to the components tab in the projects
2. Once the components are loaded check for "Outdated only" & "Direct only" toggle buttons.

### Expected Behavior

"Outdated only" & "Direct only" toggle buttons should be enabled to filter the outdated components and also list only the direct dependencies.

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by dade-hms** [comment]
We observe same behavior here. The difference seems to be that the one with deactivated icon. One project was a json sbom uploaded using CURL to api and works properly
![image](https://github.com/DependencyTrack/dependency-track/assets/42467461/5cf103bf-f617-471d-bbed-7d0c70533bd1)
The other one was a xml uploaded using ui
![image](https://github.com/DependencyTrack/dependency-track/assets/42467461/f4e6c508-5c1c-4763-9840-b554e03670df)

**Comment by nscuro** [comment]
The "Direct Only" toggle is only available when the project has a dependency graph, otherwise DT simply can not know which component is brought in directly vs. transitively.

The "Outdated Only" toggle should work even without dependency graph, so that is definitely a defect.
