### ISSUE TITLE
Swagger: Undocumented API response in swagger.json for BomResource

### ISSUE THREAD

**Issue by justin-tay** [DependencyTrack/dependency-track#341]
### Current Behavior:
The swagger.json does not contain documented responses for some apis and hence when using swagger-codegen to generate the api clients the resultant api code ends up with void return results.

This is because the @ApiOperation response is not being set to an appropriate VO hence according to http://docs.swagger.io/swagger-core/apidocs/com/wordnik/swagger/annotations/ApiOperation.html#response() the return type will be void.

- BomResource.uploadBom (POST & PUT)
- BomResource.isTokenBeingProcessed

### Steps to Reproduce:
`java -jar swagger-codegen-cli-3.0.8.jar generate -i swagger.json --api-package org.dependencytrack.client.jersey2.api --model-package org.dependencytrack.client.jersey2.model --invoker-package org.dependencytrack.client.jersey2.invoker --group-id org.dependencytrack --artifact-id jersey-swagger-codegen-api-client --artifact-version 0.0.1-SNAPSHOT -l java --library jersey2 -o jersey-swagger-codegen-api-client`

The BomApi class will contain methods with void parameters.

```
public void uploadBom(String project, Boolean autoCreate, String projectName, String projectVersion) throws ApiException
public void uploadBom1(BomSubmitRequest body) throws ApiException
public void isTokenBeingProcessed(String uuid) throws ApiException
```

### Expected Behavior:
Responses in swagger.json should also have documented 200 responses

```
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/BomSubmitResponse"
            }
          }
```

### Environment:
   - Dependency-Track Version: 3.5.0-SNAPSHOT

### Proposed Solution:
1) Create 2 VOs, eg. BomSubmitResponse and TokenProcessedResponse
2) Modify the @ApiOperation response for the respective methods
3) Return the VOs instead of using the singletonMap

**Comment by stevespringett** [comment]
Closing and incorporating these changes into #840. Please follow that ticket for updates.
