### ISSUE TITLE
Assign projects to teams 

### ISSUE THREAD

**Issue by mathuriga** [DependencyTrack/dependency-track#347]
Requirement : 

Assign projects to teams. Roles of the team can be applied to the projects and allow other teams to view the portfolio of the project (Restrict other teams to audit)

Eg scenario -

Assign Project A to Team A, Team A has audit access to Project A.
Assign Project B to Team B, Team B has audit access to Project B.

Team B can view Project A but restrict audit access to Project A.
Team A can view Project B but restrict audit access to Project B.

**Comment by stevespringett** [comment]
This feature will be included with #140 which is planned for Dependency-Track v3.6.
