### ISSUE TITLE
Windows : Temporary files not deleted

### ISSUE THREAD

**Issue by labrute** [DependencyTrack/dependency-track#349]
Hello,

### Current Behavior:
I'm currently running Dependency-Track on a windows 10 OS, and the disk is full in 1 week.
I think dependency track is not cleanning his updates.

### Steps to Reproduce:
Install windows 10
Download Dependency Track 3.4.1 embedded war
Download JRE-8u201 x64
Create a service with WinSW
Wait few days.
Go to Windows Setting > System > Storage > C: > Temporary Files

### Expected Behavior:
Temp files should be cleanned automaticaly

### Environment:
  
  - Dependency-Track Version : 3.4.1
  - Distribution: Executable WAR
  - BOM Format & Version : Cyclone DX SBOM
  - Database Server : Default
  - Browser: Chrome / IE

### Additional Details:
I m using recommanded configuration "java -Xmx4G -jar dependency-track-embedded.war"

**Comment by stevespringett** [comment]
To my knowledge, there are no temp files created by Dependency-Track. CycloneDX BOMs are processed in-memory, NVD downloads and Lucene index have dedicated directories. The only thing that I can think of that uses temp files is the embedded Dependency-Check scanner which should be disabled anyway if you're using CycloneDX.

Can you describe the contents of the temp files?

**Comment by stevespringett** [comment]
Also, when you say 'disk is full', what size disk are we talking about? Dependency-Track solely relies on textual data, not binaries, and it would take an enormous amount of text to fill a moderately sized disk, especially since the H2 database is not intended for production and an external database is the only supported configuration.

**Comment by labrute** [comment]
Helle @stevespringett ,
I have a disk of  512 Go, and there is 1 temp folder per day.
Each folder is named as : dctemp followed by uuid
And in each folder there is a file named dc.h2.db

So i guess I should switch to an external DB.

**Comment by stevespringett** [comment]
Dependency-Track requires an external database for production use. This database is completely unrelated to the embedded Dependency-Check database. Two different things.

Refer to https://docs.dependencytrack.org/getting-started/database-support/

The embedded Dependency-Check database also cannot be external, it's embedded. But Dependency-Check can be disabled if you don't use or require it. It's actually best practice to disable it if you're importing CycloneDX BoMs. https://docs.dependencytrack.org/best-practices/

The Dependency-Track data directory, as defined here: https://docs.dependencytrack.org/getting-started/data-directory/ contains a `dependency-check` directory where odc stores its database and index. 

I checked in a workaround that **may** clean up the dctemp directory. No guarantees, especially with Windows which is notorious for keeping file locks longer than they need to be. The workaround will be included in v3.5.0. If it doesn't work, you'll need to open an issue with the Dependency-Check project.
