### ISSUE TITLE
API Patch Project endpoint silently ignore purl value in object form

### ISSUE THREAD

**Issue by Maxouwell** [DependencyTrack/dependency-track#3509]
### Current Behavior

When using the PATCH Project endpoint, if the purl is in object format, it ignores the purl value.
If it is in string format, it is processed.
I suspect the object deserialization of PackageURL is failling and just use null instead.

It may affect other API using the PackageURL object.

### Steps to Reproduce

1. Do a curl to /api/v1/project/$UUID with this payload :
```
{
	"uuid": "$UUID",
	"group": "my.group",
	"purl": {
		"scheme": "pkg",
		"type": "npm",
		"namespace": "my.namespace",
		"name": "my-project",
		"version": "VERSION"
	}
}
```
2. Request is accepted, group is updated, purl is not
3. Do a curl to /api/v1/project/$UUID with this payload :
```
{
	"uuid": "$UUID",
	"group": "my.group",
	"purl": "pkg:npm/my.namespace/my-project@VERSION"
}
```
4. Request is accepted, group and purl are updated

### Expected Behavior

Object purl should be accepted, or the swagger should use a string for PackageURL.

### Dependency-Track Version

4.8.x

### Dependency-Track Distribution

Container Image

### Database Server

N/A

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by sebD** [comment]
Other affected API endpoints:
PUT /api/v1/project/
POST /api/v1/project/
PUT /api/v1/component/project/{uuid}
POST /api/v1/component/

**Comment by valentijnscholten** [comment]
I'm interested to know why the json format for purl is useful? It's more common to communicate it in string form?

**Comment by nscuro** [comment]
Yeah, TBH this seems to be more of an issue with Swagger indicating that `purl` is an object when in fact it is not.

I don't think there is value in specifying PURLs as object.

Resolving this merely requires adding a `@ApiModelProperty(dataType = "string")` annotation here:

https://github.com/DependencyTrack/dependency-track/blob/8b23434d34e241a82e95ede34ac5ec14399e786f/src/main/java/org/dependencytrack/model/Project.java#L377-L384

**Comment by sebD** [comment]
Sure no problems.
I was curious to see how it could be implemented, but if it doesn't serve a useful purpose, I'm happy to remove it and make a more useful change instead.

**Comment by sebD** [comment]
Here's the result
![image](https://github.com/DependencyTrack/dependency-track/assets/934062/699a3215-5f90-4056-a3c4-6346d67a4dc3)
