### ISSUE TITLE
Add Packagist (Composer) repository support

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/dependency-track#356]
Add support for the [Packagist](https://packagist.org/) repository, which is used by PHP's [Composer](https://getcomposer.org/).

The public API is [fairly straightforward](https://packagist.org/apidoc#get-package-data), except that there's no easy way to determine the latest version of a package.

**Comment by b2un0** [comment]
Any progress on this?

there is also a `composer.lock` support in [jeremylong/DependencyCheck](https://github.com/jeremylong/DependencyCheckl), but [broken](https://github.com/jeremylong/DependencyCheck/issues/1743).

**Comment by nscuro** [comment]
Dependency-Track already has working vuln detection for Composer components. You'll need this Composer plugin to generate a CycloneDX BOM: https://github.com/CycloneDX/cyclonedx-php-composer. 

This issue addresses the fact that DT can't currently detect the latest version of a Composer component.
