### ISSUE TITLE
VulnDB vulnerabilities are not assigning CVEs as Aliases

### ISSUE THREAD

**Issue by LaVibeX** [DependencyTrack/dependency-track#3580]
### Current Behavior

VulnDB is an important vulnerability database that provides great benefit to Dependency Track. Although we can see the issued CVE ID in the References area, it is not used as an alias. 

We should use this feature to add and pair CVEs as aliases.

By adding those CVEs as aliases, we can considerably minimize duplicate noise in DT while also improving the overall efficiency and accuracy of the vulnerability tracking and reporting functionality.

### Proposed Behavior

Paired CVEs should be assigned as aliases to VulnDB vulnerabilities.

![image](https://github.com/DependencyTrack/dependency-track/assets/52439101/2a8d4248-4284-48a4-8427-052f033c986f)

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Implemented via #3588.
