### ISSUE TITLE
Support Import of CycloneDX 1.6 BOMs

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#3584]
### Current Behavior

Dependency-Track v4.9  implemented support for the import of BOMs that are CycloneDX 1.5 or below.  See #2850 

CycloneDX 1.6 will be released before the end of March 2024, or in the first week of April. We will start to see tooling producing 1.6 BOMs shortly thereafter (most certainly from  the [cdxgen](https://github.com/CycloneDX/cdxgen) project).  An attempt to import any such BOM to DT v4.10.1 would throw an error.

### Proposed Behavior

Dependency-Track must be updated so that CycloneDX v1.6 BOMs can be imported without error.

The implementation of support for new functionality offered by 1.6 (CBOM. etc) is expected to be covered by other issues. This enhancement is to ensure that existing CycloneDX functionality is preserved... no errors and dependency graphs (etc) still work.

Note:  We have a dependency on [cyclonedx-core-java](https://github.com/CycloneDX/cyclonedx-core-java) and so implementation of this enhancement is blocked until `core-java` is updated  to support spec v1.6.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Note that as of v4.11, uploads of BOMs with unsupported spec versions will no longer fail silently in the background. Instead, they will fail schema validation and users will get immediate feedback about it.

**Comment by nscuro** [comment]
Assigning to 4.12 as I am expecting the Java library to be published during the 4.12 release cycle.

**Comment by msymons** [comment]
Block is removed due to release of [cyclonedx-core-java](https://github.com/CycloneDX/cyclonedx-core-java) v9.0.0

**Comment by nscuro** [comment]
Had some code laying around from my initial tests with this library version. So went ahead and committed that. Raised PR #3710.
