### ISSUE TITLE
Add an API endpoint that returns the UUID of the last uploaded BoM for a project

### ISSUE THREAD

**Issue by ddresser** [DependencyTrack/dependency-track#3585]
### Current Behavior

There is no API endpoint that, given a project name, returns the UUID of only the latest uploaded BoM for that project.

### Proposed Behavior

A new API endpoint that takes a project name and will return only the latest uploaded project version, including UUID.

I have a use case that I believe is quite common where I want to analyze the most recently uploaded BoM for a project.  For me, this represents the latest version of the BoM, but I understand that sometimes an older BoM may be re-uploaded.  Even in that case, I believe it is common to want to analyze the most recently uploaded version.  Being able to easily retrieve the UUID of the most recently uploaded version would eliminate the need to parse all the versions and compare dates and would make this type of analysis simpler.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by sebD** [comment]
I'll have a look

**Comment by nscuro** [comment]
@ddresser I just realized this is already possible using the `/api/v1/project` endpoint:

```shell
curl -H 'X-Api-Key: <API_KEY>' \
    'http://localhost:8080/api/v1/project?name=foo&sortName=lastBomImport&sortOrder=desc&offset=0&limit=1'
```

Essentially you limit the list of returned items to projects with name `foo`, then sort by `lastBomImport` in descending order, and ask for at most one item to be returned (`offset=0`, `limit=1`).

Still, thanks @sebD for working on this!
