### ISSUE TITLE
VulnDB Vulnerabilities Always Shown as Unassigned Severity

### ISSUE THREAD

**Issue by LaVibeX** [DependencyTrack/dependency-track#3589]
### Current Behavior

Currently in the **latest master version**, all VulnDB vulnerabilities consistently display an “Unassigned” severity. This can be misleading for users who rely on accurate severity information. This should be addressing promptly to ensure that users receive reliable data regarding vulnerability severity. 

![image](https://github.com/DependencyTrack/dependency-track/assets/52439101/f6ffc8e8-6367-4f13-b85f-ff80a96ba7ee)

Additionally, this issue affects the new Audit Vulnerability counter integrated by PR [#736](https://github.com/DependencyTrack/frontend/pull/736). When all vulnerabilities originate from VulnDB, the severity counters will display 0 in all fields, and the green counter will also be 0.

![image](https://github.com/DependencyTrack/dependency-track/assets/52439101/7987c57e-7dbf-43bc-95e7-18a4bd6019c9)

### Steps to Reproduce

1. Go to the vulnerability section.
2. Examine the severity field for any VulnDB vulnerability.
3. Associate a VulnDB-related CPE with a sample component.
4. Verify the Audit Vulnerability counter after implementing the changes from PR #736.

### Expected Behavior

- The severity field should accurately reflect the severity level of each vulnerability based on available data.
- The Audit Vulnerability counter should correctly account for VulnDB vulnerabilities.

### Dependency-Track Version

4.11.0-SNAPSHOT

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by lukas-braune** [comment]
Just a remark: I cannot confirm this as an issue of DT v4.10.1. It seems to be a regression from a later revision.

**Comment by nscuro** [comment]
Indeed it might be a regression introduced in https://github.com/DependencyTrack/dependency-track/pull/3408

In short: DT before 4.11 did not store the severity in the database, unless explicitly set by the user. Instead, it would compute the severity based on CVSSv2, CVSSv3, and OWASP RR scores whenever the severity was accessed. This made it impossible to reliably query by severity, hence we changed that behavior in the PR mentioned above.

Seems like we missed VulnDB there.
