### ISSUE TITLE
Classifier doesn't change when BOM of existing Project is reuploaded

### ISSUE THREAD

**Issue by Tobsensgit** [DependencyTrack/dependency-track#3598]
### Current Behavior

I am using the cyclonedx-maven-plugin to create the BOM-File of my project. When I upload the project for the first time it sets the Classifier in DT according to my confuguration in the cyclonedx-maven-plugin. However, when i reupload the BOM with a different projectType/Classifier, the upload is successful but the Classifier isn't changing. Is there a way to make this work without deleting the Projects beforehand?
Thanks for the amazing Tool - Best Regards

### Steps to Reproduce

1. Create the BOM-File with a specific projectType/Classifier
2. Upload the File to DT
3. Create the BOM-File of the same project, with a different projectType/Classifier
4. Upload the File to DT
5. Check that the Last BOM Import shows the update, but not the updated Classifier category

### Expected Behavior

Change the Classifier with the current BOM-FIle projectType value

### Dependency-Track Version

4.8.x

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Fixed in v4.12 via the new BOM upload processing logic: https://github.com/DependencyTrack/dependency-track/blob/ab9d19dbce5b752401fc736b64232ab702f12301/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java#L330

In the previous implementation, classifier of the project was not updated.
