### ISSUE TITLE
Search defaulting to username

### ISSUE THREAD

**Issue by dattim** [DependencyTrack/dependency-track#361]
### Current Behavior:
Navigating to the Dependencies tab within any project auto-fills the 'Search' input box with the user name (in my case 'admin').

I turned off all browser auto-fill settings, and cleared my history, it continues to default to the username

### Steps to Reproduce:
Login to dependency tracker, navigate to a project, select the 'Dependencies' tab

### Expected Behavior:
The 'Search' input box should not auto-fill

### Environment:
  - Dependency-Track Version: Dependency-Track v3.4.1
  - Distribution: Docker
  - BOM Format & Version:
  - Database Server: H2
  - Browser: Updating Google Chrome
Version 74.0.3729.169 (Official Build) (64-bit)

### Additional Details:

Perhaps a solution to this would be to give that input box a unique id or name, if the browser is not respecting my auto-fill settings.

**Comment by stevespringett** [comment]
The use of `name="username"` on HTML inputs is limited to the login modal and user management.  The use of `id="username"` is only specified on the login modal.

There are multiple search dialogs (header, components table, projects table, dependencies table, etc) and none of them use 'username'.

The header search field has an `id="smart-search-input"` and does not specify a name attribute.

I'm not sure where how the browser is autofilling a field that is unrelated, but that seems to be the case. Can you provide details on specifically what fields and their values when being autofilled?

**Comment by stevespringett** [comment]
Also, IME, disabling autofill in HTML doesn't actually prevent the browsers from doing so. Most ignore it.
