### ISSUE TITLE
Mysql 8

### ISSUE THREAD

**Issue by feliceg77** [DependencyTrack/dependency-track#362]
Is Dependency track compatible with Mysql 8?

**Comment by feliceg77** [comment]
At url https://docs.dependencytrack.org/getting-started/database-support/ is reported:
"MySQL 5.6 and 5.7"

is true?

**Comment by stevespringett** [comment]
MySQL 8 and MariaDB 10 introduced breaking changes and is not currently supported. The latest versions of PostgreSQL and Microsoft SQL are supported and will yield the best results.

Short-term, it would be useful to have MySQL8/MariaDB10 support, but long-term, the goal is to move away from RDBMS onto graphs.
