### ISSUE TITLE
Automatically convert package-lock.json to CycloneDX and import

### ISSUE THREAD

**Issue by pieterhouwen** [DependencyTrack/dependency-track#3628]
### Current Behavior

When wanting to analyse a package-lock.json file for vulns I have tried to upload the package-lock.json as BOM. The front-end gave me an OK but nothing changed when refreshing the component list. 

I then had to download, install, and use cdxgen to convert the package-lock.json to a compatible format and upload that to my project.

### Proposed Behavior

It would be great if you could just upload the package-lock.json as BOM and DT would convert and analyse the file itself.
AFAIK this is also the case for python's requirements.txt file.

Maybe add an additional modal when clicking on Import to define which type of file it is?

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Dependency-Track is intentionally designed to be technology agnostic. It has no notion of package managers, and has no understanding as to which steps need to be taken to generate a BOM. Only CycloneDX BOMs are accepted at the moment.

The upcoming v4.11 release will validate uploads against the CycloneDX schema, and reject non-conforming files, which will address this part of your report:

> I have tried to upload the package-lock.json as BOM. The front-end gave me an OK but nothing changed when refreshing the component list.

---

> It would be great if you could just upload the package-lock.json as BOM and DT would convert and analyse the file itself.

Relying on the parsing of manifest and / or lock files is doomed to yield sub-optimal results. It's best to use tools that understand the respective ecosystem, such as https://www.npmjs.com/package/@cyclonedx/cyclonedx-npm.
