### ISSUE TITLE
Enhance MS Teams alerts with project name and URL on BOM_PROCESSING_FAILED events

### ISSUE THREAD

**Issue by lukas-braune** [DependencyTrack/dependency-track#3637]
### Current Behavior

Currently, the Microsoft Teams alerts for BOM_PROCESSING_FAILED events do not contain any details about the affected project. For example:

![image](https://github.com/DependencyTrack/dependency-track/assets/9955029/b209195a-e946-4a69-a8ee-7e6709a45ceb)

Without this information, it is challenging to locate and identify the project in question.

### Proposed Behavior

Enhance the Microsoft Teams alert for BOM_PROCESSING_FAILED events to include:
- **Project Name**: The name of the affected project that triggered the BOM_PROCESSING_FAILED event.
- **Project URL**: A link to the specific project in Dependency-Track for quick access and review.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by 2000rosser** [comment]
I'd like to give this issue a try
