### ISSUE TITLE
JSON Schema for NVD Vulnerability Data API version 2.1.0

### ISSUE THREAD

**Issue by Flueckee** [DependencyTrack/dependency-track#3639]
### Current Behavior

The current schema version for the NVD Data API is 2.0. This will be updated in the next few weeks based on news from https://nvd.nist.gov/general/news/api-cves-schema-restriction-update. The schema json should also be updated.

### Proposed Behavior

Updating schema version for NVD Data API to 2.1.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Will need this to be addressed in the `open-vulnerability-clients` library: https://github.com/jeremylong/Open-Vulnerability-Project/issues/154

**Comment by jeremylong** [comment]
Note that while we created https://github.com/jeremylong/Open-Vulnerability-Project/pull/158 - there are no impactful changes due to the schema change.
