### ISSUE TITLE
Deleting SNAPSHOT Components in Bulk

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#364]
It would be very useful to be able to delete (clean-up) components in-bulk using a criteria such as:

* No dependencies
* Matches a pattern such as:
   * Version includes SNAPHOT
   * GroupId = xxx  (ie, specify `my.company.groupid`)

It's already possible to delete components...  but only on a one-by-one basis.  This is really slow.

My Dependency-Track server v3.5.0 now tracks over 10,000 components.  A current analysis of the master branch of a project will include SNAPSHOT versions of the modules of said project.  Project XXXX 1.3.20-SNAPSHOT will thus have:

XXXX-MOD1 1.3.20-SNAPSHOT
XXXX-MOD2 1.3.20-SNAPSHOT
XXXX-MOD3 1.3.20-SNAPSHOT

Until such time as 1.3.20 is released,  all three of these components are also Dependencies.

When a release of XXX is performed, then we now see:

XXXX-MOD1 1.3.21-SNAPSHOT
XXXX-MOD2 1.3.21-SNAPSHOT
XXXX-MOD3 1.3.21-SNAPSHOT

..and the old 1.3.20-SNAPSHOT components are now orphaned, no longer dependencies of any project (unless they are dependencies of a totally different project, something that sometimes happens in testing).

My problem is that I now see hundreds of such SNAPSHOT components, although I am not quite sure how many...  something that would require:

* Implement Search/Filtering on per-Column Basis #313
* Add "Affected Projects" Count to Components and Vulnerabilities Screens #312

In fact, with the implementation of both of these enhancements, one would also be able to see when (say) `XXXX-MOD1 1.3.20` (or earlier version) is no longer used.. and make a decision about cleaning up these components as well.

The use case for all this is pretty easy...  being able to se the wood for the trees.  The continued tracking of so many SNAPHOT (etc) generates a lot of noise.

**Comment by stevespringett** [comment]
In can't find the ticket for this. But recall one where the default view of components would be to display only components that are "in use" (i.e. are a dependency) with an option to prune orphaned components on a regular schedule. 

I can't find the ticket, but that's is the current plan and will likely solve the data view issue you're having.

Bulk operations is much more grand than just delete as none of the REST APIs account for this at this time.

**Comment by msymons** [comment]
Found it!   #197

I am not quite sure that I would want to purge everything that it unused.  If a component that was formerly "in use" **and** had a vulnerability at that time,  would it not be useful to know that if the component gets re-introduced later?

**Comment by msymons** [comment]
I am happy that this issue can be "closed as completed" in v4.0.0. 

SNAPSHOT verions of component now only exist in Dependency-Track within projects built from feature branches, etc  (ie, work in progress).  There is no longer ever the need to clean things up,.
