### ISSUE TITLE
Use cpe and/or purl from cyclonedx metadata.component to set project cpe and/or purl.

### ISSUE THREAD

**Issue by savek-cc** [DependencyTrack/dependency-track#3643]
### Current Behavior

When importing an SBOM that defines a CPE and/or PURL for the metadata.component, these fields are not populated for the project created.
Other properties of the metadata.component have been fixed in the past, see e.g. https://github.com/DependencyTrack/dependency-track/pull/3179

### Steps to Reproduce

1. Import an SBOM with a metadata.component.cpe entry
2. Review the project information - it's missing the data for the CPE field.

### Expected Behavior

Imported project also populates CPE and PURL fields if present in the metadata.component.cpe/purl

### Dependency-Track Version

4.10.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Legacy `BomUploadprocessingTask` was dropped for v4.12. No further change necessary.
