### ISSUE TITLE
Vulnerability Table Error

### ISSUE THREAD

**Issue by gjfvieira** [DependencyTrack/dependency-track#3646]
### Current Behavior

I've enabled Jira notifications for new vulnerabilities a couple days ago and for some reason I'm now facing issues with the vulnerability table (probably not related though). This is the log when I try to get the details of any of the listed vulnerabilities (I'm currently using GHAdvisories only):

<img width="689" alt="image" src="https://github.com/DependencyTrack/dependency-track/assets/47488771/fc10fae0-10bd-43d1-a7b8-a5a862b1dae9">
<img width="477" alt="image" src="https://github.com/DependencyTrack/dependency-track/assets/47488771/e3b6d3c0-3fab-47c5-a57d-a10ac0276293">

(unfortunately I don't have direct access to the database server, so can't exactly see what's going on with the table) 

I've just noticed this, so I'm expecting it to be resolved with the next DB sync (I no longer have access to the latest vulnerability sync log)

### Steps to Reproduce

-

### Expected Behavior

-

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
See #3372, #2061, #2141. It's not an issue in the table or even the data itself, it's an issue with the query compilation performed by the ORM. 

Unfortunately we have not been able to identify how exactly this is triggered, and what the root cause is. A restart of the container resolves the issue.

**Comment by nscuro** [comment]
I'm going to close this as duplicate of the issues I mentioned, since the underlying issue is the same.
