### ISSUE TITLE
Add Support for Snyk

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#365]
Once Package URL is implemented by Snyk, enhance Dependency-Track to be able to support the analysis of SBoMs using Snyk as a source of vulnerability intelligence.

Snyk API access requires a paid plan (standard, pro, or enterprise)

Depends on: https://github.com/snyk/snyk/issues/210

**Comment by sahibamittal** [comment]
@stevespringett I've been working on Snyk vulnerability analysis integration upon bom upload in DT. 
It will act as an analyser similar to OSS index. It'll call Snyk API for every component purl scanned.

<img width="1416" alt="Screenshot 2022-08-02 at 10 31 56 a m" src="https://user-images.githubusercontent.com/5709882/182342567-98a9389f-7296-4098-adb9-8fd714c3744d.png">

Project vulnerabilities in DT will look like: 

<img width="1416" alt="Screenshot 2022-08-02 at 10 35 11 a m" src="https://user-images.githubusercontent.com/5709882/182343179-05d2ab44-8fbb-44ac-8782-f4d14317384e.png">

**Branch with code changes -> https://github.com/sahibamittal/dependency-track/tree/snyk-integration**

**Comment by stevespringett** [comment]
Thats fantastic. Does Snyk have an API that we can use to send multiple components in a request, similar to OSS Index where we sent 100 components at a time?

**Comment by sahibamittal** [comment]
No sadly for now, this is an initial version supporting two packages (maven, npm). It now enables querying the API with purl as url encoded. Currently, there are only two endpoints:

1. List all vulnerabilities of a package by purl specification
GET /packages/{purl_specification}/vulnerabilities

2. List all vulnerabilities of a package
GET /vulns/{package_manager_name}/{package_name}/{package_version} 

https://apidocs.snyk.io/?version=2022-04-04%7Eexperimental#get-/packages/-purl_specification-/vulnerabilities

**Comment by nscuro** [comment]
The initial implementation (#2070) will attempt to work around the missing batching functionality by distributing the analysis requests to a configurable amount of threads (static thread pool, default size of 10). Will need to observe how well this works in production.
