### ISSUE TITLE
About the Restful API error: lookup and search

### ISSUE THREAD

**Issue by xuri422** [DependencyTrack/dependency-track#3660]
### Current Behavior

I use hte Postman for API test, below API interface, like : Login, upload_bom, create project is work well.
but lookup and search project there are abnormal,
when I use: /project/lookup, the body like this:
{
    "name": "test"
    "version": "1.0"
}
the "test"  project name and version "1.0" is exist, but the response is:  The project could not be found.(404)

when I use: /api/v1/search/project,  the body like this:
{
    "name": "test"
}
the response is: 
{
    "results": {
        "project": []
    }
}

So ,I don't know how to fill the body, then can return the right response, thanks.

### Steps to Reproduce

1. use Postman can reproduce it.

### Expected Behavior

I hope this two API can return the right rusult, like uuid etc.

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Both endpoints expect the parameters to be sent as query parameters, not as JSON in the request body.

Try:

```
GET /api/v1/project/lookup?name=test&version=1.0
```
