### ISSUE TITLE
How upload big DC-Scan with a PowerShell Script

### ISSUE THREAD

**Issue by HSSE-Dev** [DependencyTrack/dependency-track#367]
Hello,
I am currently using Dependency Check version 5.0 and Dependency Tracker 3.5 trying to create a script that uploads my scans via the API.
The API says that only XML from version 1.3 is supported for DC scans, but the generated DC-XML file is always version 1.0, is that a problem?
With the PowerShell script below I can successfully upload BOMs from CycloneDX if the url and json are set to bom. When running for scans, $response always remains empty. Does anyone have a solution to the problem?
```
$content = [Convert]::ToBase64String([IO.File]::ReadAllBytes(".\dependency-check-report.xml"))
$url3 = "http://XXXX/api/v1/scan"

$apiKey = "XXXXXXXXXX"

$body = @{
    scan     = $content
    project = 'XXXXX'

}

$json = $body | ConvertTo-Json
$headers3 = @{
    'X-API-Key'      = $apiKey
    'Content-Type'   = 'application/json'
    'Content-Length' = $json.Length.ToString()
};

try {
    $response = Invoke-RestMethod -Method PUT -Uri $url3 -Headers $headers3 -Body $json -TimeoutSec 60
    Write-Host $response.StatusCode
    Write-Host $response.StatusDescription
    Write-Host $response
}
catch {
    Write-Error "FAILED!"
    Write-Warning "StatusCode:" $_.Exception
}
```

**Comment by stevespringett** [comment]
DT 3.5 and lower currently does not support scans created from DC 5.x. A check was added to DT 3.5 to prevent scans from DC 5.x from being uploaded. Users attempting to upload DC 5 scans in DT 3.4.x were seeing stack traces in DT without any indication of what went wrong.

Refer to #354

The actual error message reads:

> The scan uploaded is not in a supported format. Supported formats include Dependency-Check XML schema v1.x produced by Dependency-Check v1.x - v4.x. Refer to https://docs.dependencytrack.org/best-practices/

**Comment by HSSE-Dev** [comment]
@stevespringett Thank you so much for your help. Unfortunately another problem has occurred now. BOM from NPM modules are uploaded without problems but when I create a BOM from Maven I get the token back but it doesn't find any content in the project. Are there any specific settings you need to consider?
The Maven project consists of several modules and the BOM was created with 
`mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom`

A small excerpt of the BOM:

```
<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" serialNumber="urn:uuid:fa140467-1a21-48ee-8014-eb35e7c954a8" version="1" xsi:schemaLocation="http://cyclonedx.org/schema/bom/1.1 http://cyclonedx.org/schema/bom/1.1">
    <components>
        <component type="library">
            <publisher>The Apache Software Foundation</publisher>
            <group>org.apache.geronimo.specs</group>
            <name>geronimo-jpa_2.1_spec</name>
            <version>1.0-alpha-1</version>
            <description>Implementation of JSR-338 JPA 2.1 Spec API</description>
            <scope>required</scope>
            <hashes>
                <hash alg="MD5">77c073f4c23c0c7ae63ec2c1b0d0708c</hash>
                <hash alg="SHA-1">afeedb974e4f35eb3258ff53a9abab1e2ec5ceca</hash>
                <hash alg="SHA-256">1c83ca36f2bbdbfb9ad91281b5b984886cde2e0ac7eb285ce6cacbc84fc6e072</hash>
                <hash alg="SHA-384">dc924978ac19201d7061db1ae5364e00b254ed32352ce5fd88b5dd3407607224b8f462daf0f808bd2a653ea3ccc7507e</hash>
                <hash alg="SHA-512">f18e50441c507a48cab2f8d6accf991781c1403e5ab4cf13d1ae4c030207741157d50d09271fcca0dd4cd10d78ab684f4cb4550598e07763991a913b7abced3a</hash>
            </hashes>
            <licenses>
                <license>
                    <id>Apache-2.0</id>
                </license>
            </licenses>
            <purl>pkg:maven/org.apache.geronimo.specs/geronimo-jpa_2.1_spec@1.0-alpha-1?type=jar</purl>
        </component>
        <component type="library">
            <publisher>FasterXML</publisher>
            <group>com.fasterxml.jackson.jaxrs</group>
            <name>jackson-jaxrs-json-provider</name>
            <version>2.9.8</version>
            <description>Functionality to handle JSON input/output for JAX-RS implementations (like Jersey and RESTeasy) using standard Jackson data binding.</description>
            <scope>required</scope>
            <hashes>
                <hash alg="MD5">88d9332591c5506a442c5209c4a97d43</hash>
                <hash alg="SHA-1">cbfb046b70f764aed65426db19a3b8984482a86e</hash>
                <hash alg="SHA-256">421d7296306c2d6a431fd244ca47f3612a8cc384f0983d3d1199df6594406e94</hash>
                <hash alg="SHA-384">9eba596a080184b9d8039c83cdca75bebb9a234509272635073979a9fa0ba7c0bc7a75d534b7b34c9da608c15494dc95</hash>
                <hash alg="SHA-512">794695b8ac9eb71d50b7324473049e92a0cb4b644da28d4396d6141826f1b758b21b056e642837bc776c4b21547ff40b7fd5705e9359259d044b8067158b21d9</hash>
            </hashes>
            <licenses>
                <license>
                    <id>Apache-2.0</id>
                </license>
            </licenses>
            <purl>pkg:maven/com.fasterxml.jackson.jaxrs/jackson-jaxrs-json-provider@2.9.8?type=jar</purl>
        </component>
```

**Comment by stevespringett** [comment]
The bom looks good. What does the log say?

**Comment by stevespringett** [comment]
Also, note, the endpoing for uploading a scan is different from uploading a bom. 

The bom endpoint has two options, you can either do the base64 encoding json payload thing, or you can use POST with the payload XML payload in the body. your choice

**Comment by HSSE-Dev** [comment]
The BOM cannot be uploaded manually via the UI and the API doesn't work either. For the API I use the JSON & PUT variant, but POST should achieve the same result, right? How can I view the logs from the Dependency Tracker?

**Comment by stevespringett** [comment]
Logs or the Docker container go to stdout like most containers do.

Logs for the embedded or traditional jar go to ~/.dependency-track/dependency-track.log

https://docs.dependencytrack.org/getting-started/data-directory/

**Comment by HSSE-Dev** [comment]
### BOM creation with maven
I did some tests and looked at the logs, for the BOM creation with Maven I created an Issue [https://github.com/CycloneDX/cyclonedx-maven-plugin/issues/15](url)

When I remove the double url, DT throws this exception, and I have added a shortened BOM to it.
So far it was not possible to upload a maven generated BOM.
#### Dependency Track Log
[dependency-track-embedded.out.log](https://github.com/DependencyTrack/dependency-track/files/3296507/dependency-track-embedded.out.log)

#### Cutted BOM
[bom.xml.log](https://github.com/DependencyTrack/dependency-track/files/3296890/bom.xml.log)

### BOM creation for NodeJS (multiple package.json)
Our project has several modules(package.json) so I wrote a PowerShell script to merge the XML files, changing the line endings to Windows format and the encoding to UTF-8-Bom which DT couldn't handle, and by switching to UTF-8 and Unix(LF) everything worked as expected.

**Comment by stevespringett** [comment]
I'm unable to replicate. Using the Maven plugin (either v1.3.1 or 1.4.0), I'm able to generate BOMs which can be uploaded and processed by DT without error. 

If you can provide a BOM that cannot be processed without error, I'll take a look.

Also, the node module has an _append_ feature that lets you merge boms together. The other implementations do not yet have that feature.

**Comment by HSSE-Dev** [comment]
The problem already occurs with the shortened BOM sent above. Is there a way to increase the loglevel of the DT?

**Comment by HSSE-Dev** [comment]
I've raised the LogLevel again but unfortunately that doesn't bring any further information. The problem already occurs with the shortened BOMs sent above. Should I set maven to BOM 1.0 and test it again?

**Comment by stevespringett** [comment]
Just to confirm., you're using Dependency-Track v3.5.0 correct? Previous versions did not support CycloneDX v1.1.

Also, what distribution are you using (docker, executable war, traditional war)?

If traditional war, is this deployed to Tomcat or Jetty or something else.? 

Also, what happens when you change the bom element to look like this?
```xml
<bom xmlns="http://cyclonedx.org/schema/bom/1.1" serialNumber="urn:uuid:cd25cbcf-7fcf-4664-a6b6-ee1dd80632a8" version="1">
```

**Comment by stevespringett** [comment]
Also, v1.4.1 of the Maven plugin was just released which omits the xmlns:xsi and xsi:schemaLocation attributes from the bom. They're not needed and the Maven plugin was the only one generating them.

**Comment by HSSE-Dev** [comment]
I'm sorry for the work I did for you, it was very bad timing. On June 6th we downloaded the current version of the DT, which was 3.4.1 but on June 7th version 3.5 was released. All the time I thought that I was always working with the latest version. I updated immediately and the bug is fixed.  Thank you very much for your help.

**Comment by stevespringett** [comment]
Glad it’s working. Cheers
