### ISSUE TITLE
BOM Validation: Unable to determine schema version from JSON

### ISSUE THREAD

**Issue by eugenhoffmann** [DependencyTrack/dependency-track#3696]
### Current Behavior

When uploading a BOM file with BOM Validation enabled:

- if the "specVersion" field in the JSON is located above the "metadata" section, the upload is successful. 

- However, if the "specVersion" field is located below the "metadata" section, the upload fails with the error message: "The uploaded BOM is invalid - Unable to determine schema version from JSON."

![image](https://github.com/DependencyTrack/dependency-track/assets/142139018/7b26e3d9-9ea9-4558-82bb-fa1f39e148e1)

### Steps to Reproduce

**Valid BOM upload**
1. Upload BOM (Project &#8594; Components &#8594; Upload BOM) [valid_bom.json](https://github.com/DependencyTrack/dependency-track/files/15291705/valid_bom.json)

**Invalid BOM upload**
1. Upload BOM (Project &#8594; Components &#8594; Upload BOM) [invalid_bom.json](https://github.com/DependencyTrack/dependency-track/files/15291709/invalid_bom.json)

### Expected Behavior

The order of the elements, specifically the "specVersion" field, should not influence the success of the BOM upload.

### Dependency-Track Version

4.11.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

15.5

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Thanks for reporting @eugenhoffmann! Was able to reproduce and fix the issue via #3697.
