### ISSUE TITLE
Upgrade REST API Spec from Swagger 2.0.0 to OAS 3.1.x

### ISSUE THREAD

**Issue by setchy** [DependencyTrack/dependency-track#3706]
### Current Behavior

Currently the Dependency Track REST API Specification uses Swagger 2.0.0

### Proposed Behavior

Upgrade to OpenAPI Spec (OAS) 3.1.x

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Duplicate of #840.

**Comment by setchy** [comment]
> Duplicate of #840.

D'oh! I swear I did a search before creating 😅
