### ISSUE TITLE
SBOM validation fails on URL with spaces

### ISSUE THREAD

**Issue by jmezach** [DependencyTrack/dependency-track#3741]
### Current Behavior

After upgrading to DependencyTrack 4.11.0 we started getting validation errors when uploading an SBOM to DependencyTrack. Specifically we're getting the following result back:

```json
{
    "status": 400,
    "title": "The uploaded BOM is invalid",
    "detail": "Schema validation failed",
    "errors": [
        "$.components[191].externalReferences[0].url: does not match the iri-reference pattern must be a valid RFC 3987 IRI-reference",
        "$.components[191].externalReferences[0].url: does not match the iri-reference pattern must be a valid RFC 3987 IRI-reference",
        "$.components[191].externalReferences[0].url: does not match the regex pattern ^urn:cdx:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[1-9][0-9]*$",
        "$.components[191].externalReferences[0].url: does not match the iri-reference pattern must be a valid RFC 3987 IRI-reference",
        "$.components[191].externalReferences[0].url: does not match the regex pattern ^urn:cdx:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[1-9][0-9]*#.+$"
    ]
}
```

After inspecting the SBOM we're trying to upload we noticed that the offending component has an external reference of type VCS, but the associated URL contains spaces which have not been escaped. This particular component is an internally developed component and the URL is automatically filled in by our CI/CD system and apparently not being escaped. Unfortunately this is behaviour we cannot change ourselves. In previous versions of DependencyTrack this does not appear to have been an issue. 

### Steps to Reproduce

1. Attempt to upload the provided [bom.json](https://github.com/DependencyTrack/dependency-track/files/15391194/bom.json) to DependencyTrack
2. Observe a 400 Bad Request being returned

### Expected Behavior

Ideally I would like DependencyTrack to just accept this SBOM as it did previously.

### Dependency-Track Version

4.11.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

16.2

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
You can disable BOM validation in the settings, please take a look at the v4.11.0 [changelog](https://docs.dependencytrack.org/changelog/) and the accompanying upgrade notes:

> Historically, Dependency-Track did not validate uploaded BOMs and VEXs against the CycloneDX schema. While this allowed BOMs to be processed that did not strictly adhere to the schema, it could also lead to confusion when uploaded files were accepted, but then failed to be ingested during asynchronous processing. Starting with this release, uploaded files will be rejected if they fail schema validation. Note that this may reveal issues in BOM generators that currently produce invalid CycloneDX documents. Validation may be turned off in the administration panel under Configuration -> BOM Formats.

I would highly recommend to address this issue at the source, either by fixing the generator, or adding a post-generation step which fixes these issues before uploading the BOM to DT. Disabling validation bypasses the primary way to catch issues early.

Closing because this is not a defect in Dependency-Track, and validation can be disabled.
