### ISSUE TITLE
ranking vulnerabilities by affected projects

### ISSUE THREAD

**Issue by Crox48** [DependencyTrack/dependency-track#3758]
### Current Behavior

![grafik](https://github.com/DependencyTrack/dependency-track/assets/129370281/d18a8f1f-dbfb-453c-a525-a31ab4f414f4)

The current frontend has yet a few columns to rank the values in the tab **vulnerabilities**, but the header for affected projects (*Projects*) and *Serverity* have no arrows on how to rank the entries of the table.

### Proposed Behavior

Add ranking for all headers in the table, which can be ranked (most likely *Projects* and *Serverity*)

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Duplicate of #2190.
