### ISSUE TITLE
Allow authentication in outbound webhook 

### ISSUE THREAD

**Issue by Pabloo-ss** [DependencyTrack/dependency-track#3772]
### Current Behavior

When creating an alert using outbound webhook publisher, only a destination could be set. This could be a problem if the webhook needs to be authenticated via key/token.
<img width="1240" alt="image" src="https://github.com/DependencyTrack/dependency-track/assets/57215349/f773189c-715b-4a7a-b446-97126b4073a1">

### Proposed Behavior

Would be interesting having a way of specifying a token to authenticate to other services (Opsgenie for instance). Maybe through setting headers...

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
What version of Dependency-Track are you on? Support for authentication tokens was added in v4.11: https://github.com/DependencyTrack/frontend/pull/665

**Comment by Pabloo-ss** [comment]
v4.11.1
<img width="1413" alt="image" src="https://github.com/DependencyTrack/dependency-track/assets/57215349/311e10a4-ebe5-44ea-9eaa-b4baeca65819">

**Comment by Pabloo-ss** [comment]
Any idea of why this could be happening?
