### ISSUE TITLE
NEW_VULNERABLE_DEPENDENCY and NEW_VULNERABILITY not being thrown

### ISSUE THREAD

**Issue by Pabloo-ss** [DependencyTrack/dependency-track#3780]
### Current Behavior

When a new SBOM with vulnerabilities is uploaded, BOM conssumed and BOM processed alerts are triggered but nothing else. NEW_VULNERABLE_DEPENDENCY and NEW_VULNERABILITY are not sent.

### Steps to Reproduce

1. Set up an slack alert
2. Upload SBOM with vulns

### Expected Behavior

NEW_VULNERABLE_DEPENDENCY and/or NEW_VULNERABILITY should be triggered and thrown to Slack

### Dependency-Track Version

4.11.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

13

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Duplicate of https://github.com/DependencyTrack/dependency-track/issues/3742.
