### ISSUE TITLE
LogLevel can't be configured for docker deployment

### ISSUE THREAD

**Issue by mbayrak78** [DependencyTrack/dependency-track#379]
### Current Behavior:
As documented, setting LOGGING_LEVEL to DEBUG as environment variable doesn't configure Dependency Tracker correctly.
In "src\main\docker\Dockerfile" at line 43 application is started with 

CMD java $JAVA_OPTIONS -DdependencyTrack.loggingLevel=$LOGGING_LEVEL -jar dependency-track-embedded.war

Typo: correct symbol should be named dependencyTrack.loggin**g.l**evel

### Steps to Reproduce:
Create docker image with a Dockerfile containing 
ENV LOGGING_LEVEL DEBUG

Start docker container and verify that no DEBUG logs are written.

### Expected Behavior:
DEBUG logs should appear.

### Environment:
  
  - Dependency-Track Version: latest
  - Distribution: Docker (embedded war)
  - BOM Format & Version: 
  - Database Server: H2
  - Browser: Chrome

### Additional Details:
Bug fix: change to correct symbol.
Intermeditate solution:
Add following to dockerfile
ENTRYPOINT exec java $JAVA_OPTIONS -DdependencyTrack.logging.level=${LOGGING_LEVEL} -jar dependency-track-embedded.war

**Comment by stevespringett** [comment]
Thanks for discovering the issue. This has been fixed and will be included in v3.6

**Comment by mbayrak78** [comment]
Thanks for including fix in next release.
