### ISSUE TITLE
Inherited Risk Score in Projects List

### ISSUE THREAD

**Issue by feliceg77** [DependencyTrack/dependency-track#380]
### Current Behavior:
Projects List doesn't view Inherited Risk Score in a table column 

### Proposed Behavior:
Visualize Inherited Risk Score in a table column of Projects List
User can order the list based on the score value

**Comment by msymons** [comment]
Requested previously as #127.
Would be very useful.  Having the risk score for each project display in the one view (projects) is something that has been requested by my users.

It would also be useful when used in conjunction with a tag...  where one would thus see (say) just the risk scores for "the 10 projects used by customer X".

Especially useful in this use-case if the screen could also display the total score (but this is something that I requested seperately).
