### ISSUE TITLE
Import Dependency Check v5.0.0 XML into Dependency Track 3.5.0

### ISSUE THREAD

**Issue by RaphaelHerd** [DependencyTrack/dependency-track#381]
I'm using dependency check within my CI/Cd pipeline. After the scan I want to import the resulting report XML into dependency track. 

My first test was to import it manually in the GUI like descibed at (https://docs.dependencytrack.org). It says:

11:58:55.063 WARN [BomUploadProcessingTask] The BOM uploaded is not in a supported format. Supported formats include CycloneDX, SPDX RDF, and SPDX Tag

I googled and it seems that I have to upload it by using the API (https://docs.dependencytrack.org/usage/cicd/). I used the command adjusted to my server details:

curl -v -X "PUT" "http://dtrack.example.com/api/v1/scan" \
     -H 'Content-Type: application/json' \
     -H 'X-API-Key: LPojpCDSsEd4V9Zi6qCWr4KsiF3Konze' \
     -d @payload.json

I received an HTTP 200 status code with the message similar to "all ok". When I'm now looking into the log it says:

12:19:39.022 WARN [ScanUploadProcessingTask] The scan uploaded is not in a supported format. Supported formats include Dependency-Check XML schema v1.x produced by Dependency-Check v1.x - v4.x. Refer to https://docs.dependencytrack.org/best-practices/

I tried to downgrade my dependency-check to 1.4.0 but it seems that there is a broken change in the release.

So my question: Am I doing something wrong or has the XML format changed and cannot be processed by the dependency-check 3.5.0 version?

**Comment by stevespringett** [comment]
DT v3.5 does not support importing of DC v5 scans. It supports importing DC 1.0.0 - 4.0.2.  Refer to #354 for more information.

**Comment by RaphaelHerd** [comment]
Ok, I see. What is the preferred way to import such reports? I read that SPDX is recommended. But how should I generate it with OWASP dependency-check? It's not supported as export format to the best of my knowledge. 

What tool for using in CI/CD you recommend to import the reports in dependency-track smoothly? I'm not bound to dependency-check.

Thanks for helping me out

**Comment by stevespringett** [comment]
DC doesn't produce BOMs, only scan reports. 

As for SPDX, the best practices recommends v2.2. Previous SPDX versions are not adequate. v2.2 is more than a year over due. Not sure when the project will release it.

The best practices state to use CycloneDX for best results. That's what you should run in the CI/CD pipeline to generate the BOM. https://cyclonedx.org/ Once the BOM is generated, import it into Dependency-Track via the Jenkins plugin or via REST.

Refer to https://www.youtube.com/watch?v=nZakPU0wJMo for a simple example and explanation.

**Comment by amandel** [comment]
I did create https://github.com/jeremylong/DependencyCheck/issues/2233 on the ODC side. Since I got no response yet, it looks like it is not so obvious straight forward as I initially thought.

**Comment by stevespringett** [comment]
The actual format is much less important than the fields and consistency of information the format provides.

The official CycloneDX implementations will all consistently produce factual (non-evidence based)
- component identification for every ecosystem and for all direct and transitive dependencies
  - group, name, version, PURL
  - publisher and copyright in some situations as well
- resolved SPDX license identifier (or license names if cannot be resolved) for all direct and transitive dependencies
- hashes for all direct and transitive dependency

Some implementations will also produce:
- external references to the project (github repo, issue tracker, advisories, etc)
- dependency graph

Eventually all implementations will produce this information and DT will make use of all of it. Much of this information is out of scope for the Dependency-Check project and would be difficult to achieve without having native integrations with each ecosystem. This is the reason why CycloneDX doesn't have a single implementation that does everything for all ecosystems, rather, there are ecosystem specific implementations that can use the native libraries for things like dependency resolution, which vary dramatically across different build tools.

So just adding CycloneDX output support for Dependency-Check without addressing the above will likely provide less than ideal results. This is especially true for non-Java components, where Dependency-Check would need to recreate the wheel for each ecosystem in order produce a BOM that was both accurate and consistent.

**Comment by nille** [comment]
Am I wrong in stating that using 4.0.2 of DC to output XML that DT will accept and process is not really a valid option since the NVD database changed from XML to JSON (which DC 4.0.2 does not support)?

**Comment by stevespringett** [comment]
@nille Which is why use of DC has been deprecated and disabled by default in v3.6.0 and will be completely removed in v3.7.0.
