### ISSUE TITLE
World Kinect has adopted Dependency Track

### ISSUE THREAD

**Issue by aravindparappil46** [DependencyTrack/dependency-track#3810]
### Organization Name

World Kinect Corporation

### Organization Website

https://world-kinect.com

### Organization Logo (optional)

https://avatars.githubusercontent.com/u/43382006?s=400&u=c45feb70b5eeb3393b43dd1b73c729815e65b2e8&v=4

### How is your organization using Dependency Track?

World Kinect Corporation (NYSE: WKC) uses Dependency-Track to continuously identify software supply chain risks and to enforce policy compliance across the portfolio.

### Want to link blogs or videos? Share them here.

[Showcase @ Dependency-Track Community Meeting](https://www.youtube.com/watch?v=MS2DlMdUI7Q)

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by aravindparappil46** [comment]
Side quip: Some other `ADOPTERS.md` structures that I've seen in the wild:

https://github.com/dapr/community/blob/master/ADOPTERS.md
https://github.com/backstage/backstage/blob/master/ADOPTERS.md

Table format seems lesser cognitive load (and could sort markdown tables[ online](https://tabletomarkdown.com/format-markdown-table/), if needed)

**Comment by nscuro** [comment]
Good hint @aravindparappil46!

I'm wondering if even keeping this in a structured file format (JSON, YAML) would be beneficial. We could generate an `ADOPTERS.md` file based on its contents, in a consistent format, whenever that structured file is changed.

Not only that, we could also trigger a GitHub Actions workflow in https://github.com/DependencyTrack/dependencytrack.org to update a banner of adopter logos on the website.

Thoughts?
