### ISSUE TITLE
The Audit Vulnerabilities list query is too slow

### ISSUE THREAD

**Issue by x-zim** [DependencyTrack/dependency-track#3811]
### Current Behavior

The number of Audit Vulnerabilities is about 200, and the query is very slow. Is there any solution here

### Steps to Reproduce

1.Click on the Audit Vulnerabilities list, and the above problems appear

### Expected Behavior

Expect a solution here

### Dependency-Track Version

4.11.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
You are definitely right.

The endpoint suffers from the N+1 problem and does not yet support pagination.

There's nothing you can do from your end, this needs a code change.

**Comment by x-zim** [comment]
Is this problem solved with version iteration in mind

**Comment by nscuro** [comment]
I had a look at this today and was able to make some quite substantial improvements: https://github.com/DependencyTrack/dependency-track/pull/3869

There's still plenty of headroom for further optimization, but it's a good start I think.

**Comment by nscuro** [comment]
I'm going to close this issue under the assumption that #3869 resolves it. Please feel free to open a new issue if the v4.12 release does not satisfy your expectation.
