### ISSUE TITLE
Add a warning or an error when the bom version is not supported

### ISSUE THREAD

**Issue by Maxouwell** [DependencyTrack/dependency-track#3815]
### Current Behavior

If the bom version sent is not supported, the project is updated with 0 component and a CycloneDx version "CycloneDx null"

I had the problem when the cycloneDx maven plugin switched to CycloneDx 1.5, on Dtrack 4.8.2

### Proposed Behavior

Reject the bom or add a error/warning in the logs

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
This is fixed in v4.11 (https://github.com/DependencyTrack/dependency-track/pull/3522, https://github.com/DependencyTrack/frontend/pull/762). BOMs are now validated upon upload. If the CycloneDX version is not yet supported, the upload will fail.
