### ISSUE TITLE
Creating a project with a parent?

### ISSUE THREAD

**Issue by Drewster727** [DependencyTrack/dependency-track#382]
Dep Track 3.5.0

@stevespringett I have historically not assigned a version to a project when I have uploaded a bom file. So, I would just get the uuid of the existing project and overwrite the dependencies/components.

I now want to start keeping track of dependencies per version of a project, for obvious reasons. Is the correct procedure to just use the normal /project PUT call with the name + version? When I do that, I see multiple versions of the same project in the "Projects" view of dependency track. 
![image](https://user-images.githubusercontent.com/4528753/60278130-70809e00-98c4-11e9-9640-9b7f45c76dbe.png)

That got me thinking, when I look at swagger for that PUT call, I can see a "parent" property:
![image](https://user-images.githubusercontent.com/4528753/60278175-89894f00-98c4-11e9-9994-8a2bc2594857.png)

- Should I be using that? 
- Is the parent UUID just the latest version I've uploaded? 
- Do you have an example of how to post that in?
- I would think the "Projects" view would just show the projects (and maybe the latest version in the version column) -- why does it shows all versions of all projects?

Just need some clarification of how the project/parent relationship works and what the benefits are.

Additionally -- can we do a diff between versions? Or is that something I need to do via API calls myself.

Thanks for this fantastic application!
-Drew

**Comment by stevespringett** [comment]
@Drewster727 Don't use the parent yet. The data model supports a parent project with children projects, but the UI, metrics, and other things do not yet support that. Just leave the parent null or simply don't set it.

The best way is to simply post the bom using the uuid of the project. As an alternative, use the name/version instead.

The projects view currently displays all projects (including all versions). It would be a nice enhancement to be able to list only one and then select which version.

Another nice enhancement would be doing a diff between two project versions.

I'm not sure if enhancement requests for these two things currently exist, but if they dont, go ahead and create one for each.

**Comment by Drewster727** [comment]
@stevespringett thanks for the quick reply.

I am currently posting the bom using the existing uuid of the project. The problem with that is that I cannot see the dependencies as they were in the version prior to the one I just posted in (it overwrites the entire list). Does that make sense? 

We're basically trying to determine what all of the package changes were prior to deploying applications to do a quick check that we're not going to cause any issues. Therefore, I need the list of dependencies for a given project version 1.0 to compare with the new project version 2.0 I'm pushing in.

**Comment by stevespringett** [comment]
Got it. Understood. Another possible enhancement would be to 'lock' a project to prevent changes. This would be especially useful for ensuring that the data in different versions of a project does not change. For example, if software goes GA and is released to customers, that GA version should likely not change. Changes should be published in subsequent versions.

**Comment by Drewster727** [comment]
For now we'll just have to continue overwriting the project without version. Hoping we can get this functionality in the near future!

One other thing -- is it possible to get release logs posted with new releases? I have no idea what I added upgrading from 3.4.x to 3.5.x

Thanks steve!
-Drew

**Comment by msymons** [comment]
@Drewster727, here you go:

https://docs.dependencytrack.org/changelog/
