### ISSUE TITLE
Dependency tracker not loading

### ISSUE THREAD

**Issue by VikraKrish** [DependencyTrack/dependency-track#3833]
### Current Behavior

![DT1](https://github.com/DependencyTrack/dependency-track/assets/136571368/b9774d61-c066-419e-b985-cd56b4dbda34)
![DT2](https://github.com/DependencyTrack/dependency-track/assets/136571368/695c665e-a3e9-4359-a618-346ed218d861)
![DT3](https://github.com/DependencyTrack/dependency-track/assets/136571368/5327dff2-e2b0-46c0-9222-4505ab64381e)

### Steps to Reproduce

1.I set up the container image with Docker Compose on both an Azure VM and my local machine. 
2.The Docker services are running, but when I try to access them in the browser, the front end is either static or not accessible (see attached screenshots).
 3.I'm not sure if I missed something during the installation.
 4.I am running with default Database (H2) since this is just for testing.

![DT1](https://github.com/DependencyTrack/dependency-track/assets/136571368/5df72eda-ebea-423d-925b-db3ed1da3f4a)
![DT2](https://github.com/DependencyTrack/dependency-track/assets/136571368/ce069e84-9999-4e3b-8e83-3aeeafe8ac1a)
![DT3](https://github.com/DependencyTrack/dependency-track/assets/136571368/ee74591d-2eea-4387-8e03-8ec916f6a97b)
![DT4](https://github.com/DependencyTrack/dependency-track/assets/136571368/e94308b5-b697-43b2-9bfd-6d83952a59bb)

### Expected Behavior

The dependency tracker needs to be accessible

### Dependency-Track Version

4.1.1

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by VikraKrish** [comment]
![Log](https://github.com/DependencyTrack/dependency-track/assets/136571368/2b735200-1cc5-48d5-b4f3-7b4cc7ea1bc0)

Attaching the Docker Error Log Message

**Comment by nscuro** [comment]
See https://github.com/DependencyTrack/dependency-track/issues/3844#issuecomment-2170281070.
