### ISSUE TITLE
Base URL

### ISSUE THREAD

**Issue by Drewster727** [DependencyTrack/dependency-track#385]
Dep Track 3.5.0

![image](https://user-images.githubusercontent.com/4528753/60285084-c0666180-98d2-11e9-9f88-61e16b4bf3c6.png)

I understand the reason for this field. Especially useful if behind a reverse proxy.
However, I do not see anywhere in the configuration to specify this value on start? Either a config setting or an environment setting.
https://docs.dependencytrack.org/getting-started/configuration/
https://docs.dependencytrack.org/getting-started/deploy-docker/

Am I missing something? I won't necessarily have access to the UI in my swarm, so this needs to be applied in the config on start.

Thanks,
Drew

**Comment by stevespringett** [comment]
All of the configuration options in the administrative console are accessible via REST and are not definable on startup.

**Comment by Drewster727** [comment]
Does the base url not warrant a configuration and/or environment variable? For those of us running this behind a reverse proxy.

**Comment by stevespringett** [comment]
What is the use-case that would be solved by having this configurable as an environment variable?

In both cases, the URL would need to be known in advance. In one case, the configuration would be made before launch and in the other case, the configuration would be made after launch. I'm not sure I understand the benefit.

I'm trying to avoid a scenario where every potential option in the admin interface would be an environment variable as it would likely start breaking upgrades if the variables change in-between the last launch of a previous version and the first launch of an upgraded version.

**Comment by stevespringett** [comment]
Closing issue
