### ISSUE TITLE
Permission changes are not reflected to created users.

### ISSUE THREAD

**Issue by mathuriga** [DependencyTrack/dependency-track#390]
**Steps to reproduce -**

01. log in as Admin
02. Create a team 'teamA'
03. Assign the following permissions to the team 'teamA'. 

- VULNERABILITY_ANALYSIS
- VIEW_PORTFOLIO
- SCAN_UPLOAD
- PROJECT_CREATION_UPLOAD
- BOM_UPLOAD

04. Create a user 'abc'
05. Assign a created team 'teamA' to user 'abc'
06. Assign following permissions to user 'abc'

- VULNERABILITY_ANALYSIS
- VIEW_PORTFOLIO
- SCAN_UPLOAD
- PROJECT_CREATION_UPLOAD
- BOM_UPLOAD

07. Log in as user abc.

**Observed Behavior:**

The created user couldn't able to upload BOM and create Project even though the above permissions are assigned. 

**Expected behavior:**

User 'abc' could able to upload BOM and create a project. 

Did I miss any steps? Could you please clarify this?

**Comment by stevespringett** [comment]
Permission are inherited from the team. No need to specify them on a per-user basis. 

If the request to upload a BOM contained autoCreate=true, and values for projectName and projectVersion, then the project will be created and the bom will be processed. If the request does not contain these things, it will not.

Also with these permissions, a project will not be created from the UI. That requires the PORTFOLIO_MANAGEMENT permission.

**Comment by mathuriga** [comment]
@stevespringett ,

Thanks for the prompt response. I have the following use case.

01. Restrict component level auditing to all teams and allow component level auditing to one respective team. In this case, we can give PORTFOLIO_MANAGEMENT access to all teams instead we have to give that access to the respective team. 

02. All other teams could able to audit project-level analysis, create new versions on top of the exisitng project and upload BOM on the created new version. 

Is it possible to achieve the above use case by using available permissions?

Thanks in advance.

**Comment by stevespringett** [comment]
That sounds like a perfectly valid use-case. Unfortunately, the permission model doesn't distinguish between component auditing and project auditing. The VULNERABILITY_ANALYSIS permission covers both component and project auditing. 

If this is important to you, I'd suggest creating an enhancement request.

**Comment by mathuriga** [comment]
Ack.
