### ISSUE TITLE
Dependency Track Maven Plugin

### ISSUE THREAD

**Issue by pmckeown** [DependencyTrack/dependency-track#391]
I was wondering why there is no Maven plugin for uploading BOMs, gathering project metrics and optionally failing builds?

Since I introduced Dependency Track to my developers, they have really taken to seeing the state of their application with regards to vulnerabilities in 3rd party libs they use to build their features.  However the main complaint I get from them is that they want feedback earlier in the dev cycle.  

Currently we upload to our Dependency Track instance on master branch builds from Jenkins only, as there is currently no easy way with maven, and as such the feedback is late in the cycle.  I think there is quite a lot of value in uploading a BOM straight after generation in an early build phase and determining if there are issues in a later phase (verify). 

As such, I have started to put together an open source maven plugin to address some of this functionality.  It is at the very early stages but here is the project link and trello board.  

Please let me know you have any feedback, thoughts or concerns.  

Thanks,
Paul

https://github.com/pmckeown/dependency-track-maven-plugin
https://trello.com/b/7eBRt1Pi/dependency-track-maven-plugin

**Comment by stevespringett** [comment]
Uploading boms is typically just a single curl statement. however, waiting for the analysis to complete and retrieving results is a bit more involved. It's not that it's an oversight, rather, there are a ton of enhancements in the works, so it's simply a matter of capacity. But I'm glad you've identified a need and are working on it. :-)

Cheers

**Comment by pmckeown** [comment]
Yeah, its the results analysis we are after.  Will crack into it.  Thanks :)
