### ISSUE TITLE
Make API more lenient with regards missing Accept-Encoding header

### ISSUE THREAD

**Issue by pmckeown** [DependencyTrack/dependency-track#392]
The Dependency Track jersey server throws exceptions when client's perform GET requests for data but don't supply the "Accept-Encoding" header.

I tried three different open source REST client libraries (Unirest, okhttp, Apache HttpClient) and all behaved in the same way as the server closed the connection because I wasn't supplying the correct Accept-Encoding.  

### Current Behavior:
The following error is printed in the logs and the client connection is closed.  No hint is provided that the content is gzipped.
java.io.IOException: write beyond end of stream
	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:201)

### Proposed Behavior:
A couple of small tweaks would make this more user-friendly:
- Document the behaviour in the swagger spec
- Add the Content-Encoding header to the response

Clients may then be able to see that they need to specify that they accept gzip content and configure themselves accordingly.

**Comment by oxdef** [comment]
Looks like I have similar strange bug with Go and [HTTP client](https://golang.org/pkg/net/http/). By default when try to get response from DTrack API the result is **empty** response. But when Go net/http transport option `DisableCompression` is *true* then everything is ok.

```
        tr := &http.Transport{
		DisableCompression: false,
	}

	client := &http.Client{Transport: tr}
	req, err := http.NewRequest(http.MethodPut, apiUrl + BOM_UPLOAD_URL, bytes.NewBuffer(payloadJson))
	req.Header.Add("X-API-Key", apiKey)
	req.Header.Add("Content-Type", "application/json")
	resp, err := client.Do(req)
	checkError(err)
	defer resp.Body.Close()
	err = json.NewDecoder(resp.Body).Decode(&bomResponse)
	checkError(err)
	fmt.Println(bomResponse.Token)
```

**Comment by stevespringett** [comment]
The fix for #392 and #474 are the same. They just describe two different symptoms of the same underlying problem. I plan on releasing 3.6.2 in the next day or two which will include this important fix. I would have done it today, but Maven Central is having issues and I'm unable to release a related library to fix.

**Comment by pachulo** [comment]
> I plan on releasing 3.6.2 in the next day or two which will include this important fix

Any news on this @stevespringett ? We just were too bitten by this...

**Comment by stevespringett** [comment]
Thanks for the bump. v3.7.0 is going to take a lot longer than anticipated and therefore there's some other defects besides this one, that also need to make their way into 3.6.2. I'll work on doing that tonight and try to get something released tonight or tomorrow morning.

**Comment by stevespringett** [comment]
Update. I'm narrowing the scope of what's going into v3.7.0. There's already some useful stuff in there and important bug fixes. I've moved all remaining tasks to 3.8.0 and will likely release 3.7.0 which includes this fix in the next few days.
