### ISSUE TITLE
Switch to use authors instead of author

### ISSUE THREAD

**Issue by thompson-tomo** [DependencyTrack/dependency-track#3936]
### Current Behavior

The author property is populated under components however this field is deprecated in at least 1.6 possibly prior.

Deprecation is mentioned in: https://github.com/CycloneDX/specification/blob/62a669075f1897193a14060e0784e6a7576b693d/schema/bom-1.6.schema.json#L899 and removal tracked via: https://github.com/CycloneDX/specification/issues/387

### Proposed Behavior

The Authors property is populated rather than author

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Implemented in https://github.com/DependencyTrack/dependency-track/pull/3969
