### ISSUE TITLE
Update the documentation around Docker Compose

### ISSUE THREAD

**Issue by nigellh** [DependencyTrack/dependency-track#3939]
### Current Behavior

Please see https://github.com/DependencyTrack/dependency-track/issues/3938

Followed the instructions for starting a DT instance and it failed. This was due to docker-compose (with the '-') no longer being supported with the version of Docker I was using.

### Proposed Behavior

Update the documentation to include this information and take the guidance from the above issue for installing Docker Compose as a plugin. 

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by we684123** [comment]
I noticed that the [Deploy Docker page](https://docs.dependencytrack.org/getting-started/deploy-docker/) is missing the alpine.oidc.client.id parameter. Could you please address this issue? Thank you!

![2024-08-27 09_23_01-Deploying Docker Container _ Dependency-Track — Mozilla Firefox](https://github.com/user-attachments/assets/5932accd-9e59-4914-bd81-fcc884ea9bb1)
