### ISSUE TITLE
Analyse arbitrary BOM-file

### ISSUE THREAD

**Issue by sga-solita** [DependencyTrack/dependency-track#3952]
### Current Behavior

Currently you need to have a project to upload bom-files.

### Proposed Behavior

As a developer utilizing CI/CD, I use Dependency Track to monitor multiple projects, uploading a BOM only upon production release. It would be beneficial to have the capability to upload a BOM independently of a project, solely to analyze the dependencies and receive a vulnerability report. This feature would be particularly useful during the creation of pull requests, serving as a checkpoint prior to merging.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Duplicate of #1125.
