### ISSUE TITLE
Audit vulnerabilities not showing records of big projects

### ISSUE THREAD

**Issue by Pabloo-ss** [DependencyTrack/dependency-track#3970]
### Current Behavior

When uploading large SBOMs and accessing audit vulnerabilities inside the project, "No matching records found" is displayed although project has many vulns.
<img width="1719" alt="image" src="https://github.com/user-attachments/assets/92af1029-9817-48fb-b579-38fea65e87c9">

### Steps to Reproduce

1. Upload large SBOM
2. Go to audit vulnerabilities inside the project
3. "No matching records found" is displayed
[go_sbom.json](https://github.com/user-attachments/files/16190138/go_sbom.json)

### Expected Behavior

Display all vulns.
The rest of the projects, which are quite smaller display vulns correctly, except another project which is also quite large and undergo the same problem (both projects are SBOM of root level manifests in monorepo: pnpm-lock.yaml and go.mod)

### Dependency-Track Version

4.11.5

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Can you please check the *Console* and *Network* tabs in your browser's developer tools? Any errors or failing / slow requests when you click *Refresh* on the findings table?

Based on your screenshot I'm inclined to say the request for fetching findings is timing out.

There are some quite significant performance improvements coming for this in v4.12: https://github.com/DependencyTrack/dependency-track/pull/3869

**Comment by Pabloo-ss** [comment]
You are right, Im getting a 504. I suppose Ill have to wait until v4.12 is released... Thank you!!

**Comment by nscuro** [comment]
Thanks, I'll close this as duplicate of #3811 then.
