### ISSUE TITLE
DT project-urls in notification mails for 'new vulnerable dependency' don't work

### ISSUE THREAD

**Issue by malice00** [DependencyTrack/dependency-track#3979]
### Current Behavior

In the notification mail for 'new vulnerable dependency', DT generates a url that ends in `/projects/?uuid=<uuid>`, which does not work when clicking on it. The url for the component, which looks similar, does work.
I do find it strange though, that in the mail for 'new vulnerability' the url is generated differently and ends in `/projects/<uuid>`.

### Steps to Reproduce

1. Create a project
2. Setup mail notification for 'NEW_VULNERABLE_DEPENDENCY'
3. Upload SBOM
4. Wait for mail
5. Click project-link

### Expected Behavior

We expect to either see the url similar as in the 'new vulnerability' mail or for DT to correctly handle the currently generated url.

### Dependency-Track Version

4.11.5

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

14.9

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by malice00** [comment]
OK, so it seems this is a very easy fix. If you want to use the `?uuid=<uuid>`-Variant, the corrent url is `/project`-- so without the 's'! Nothing a cloned template can't fix, but would be nice to have the default templates work out of the box. ;-)

**Comment by nscuro** [comment]
Fixed in https://github.com/DependencyTrack/dependency-track/pull/4026.
