### ISSUE TITLE
Dependency graph of BOMs generated with Syft is incomplete due to missing root node

### ISSUE THREAD

**Issue by kruegera-hub** [DependencyTrack/dependency-track#3989]
### Current Behavior

Our Dependency track instance cant create a dependecy graph for any uploaded SBOMS created by syft.
We are running DT version  v4.11.5

As an example i pulled the latest alpine version and created the SBOM for it. 
<img width="398" alt="2024-07-19 15_26_28-" src="https://github.com/user-attachments/assets/50134a8d-00d3-4851-819f-7368e8a5c7f0">

I added the SBOM file: 
[sbom_diy.json](https://github.com/user-attachments/files/16312537/sbom_diy.json)

The logs look like that:
<img width="1258" alt="2024-07-19 15_07_42-" src="https://github.com/user-attachments/assets/8bb94041-9707-4331-96ee-beed93689748">

### Steps to Reproduce

1)Create SBOM   - run: docker pull alpine:latest

    - name: Generate SBOM
      run: |
          ${{ runner.temp }}/syft/syft alpine:latest -o cyclonedx-json=sbom_diy.json
          
      env:
          PATH: ${{ runner.temp }}/syft:$PATH

2) Upload SBOM to DT using 
    - name: Upload SBOM to Dependency Track using curl 
      run: |
        curl -X "POST" "DTINSTANCELINK/api/v1/bom" \
         -H "Content-Type: multipart/form-data" \
         -H "X-Api-Key: working API KEY" \
         -F "autoCreate=true" \
         -F "projectName=DIY_test_image_alpine" \
         -F "projectVersion=1" \
         -F "bom=@sbom_diy.json"

### Expected Behavior

A complete Dependency Graph

### Dependency-Track Version

4.11.5

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
The problem is that the project itself (`metadata.component` in the BOM) does not appear in the `dependencies`:

```shell
$ jq '.metadata.component."bom-ref"' sbom_diy.json
"2dd8ebdb45d1dbf3"

$ jq '[.dependencies[] | select(.ref == "2dd8ebdb45d1dbf3")] | length' sbom_diy.json
0
```

Compare this to the other components in the BOM:

```shell
$ jq '.components[0]."bom-ref"' sbom_diy.json
"pkg:apk/alpine/alpine-baselayout@3.6.5-r0?arch=x86_64&distro=alpine-3.20.1&package-id=08c208ae832e3bf1"

$ jq '[.dependencies[] | select(.ref == "pkg:apk/alpine/alpine-baselayout@3.6.5-r0?arch=x86_64&distro=alpine-3.20.1&package-id=08c208ae832e3bf1")]' sbom_diy.json
[
  {
    "ref": "pkg:apk/alpine/alpine-baselayout@3.6.5-r0?arch=x86_64&distro=alpine-3.20.1&package-id=08c208ae832e3bf1",
    "dependsOn": [
      "pkg:apk/alpine/alpine-baselayout-data@3.6.5-r0?arch=x86_64&upstream=alpine-baselayout&distro=alpine-3.20.1&package-id=eb22ad614104fc6e",
      "pkg:apk/alpine/busybox-binsh@1.36.1-r29?arch=x86_64&upstream=busybox&distro=alpine-3.20.1&package-id=935ad6397e8681a6"
    ]
  }
]
```

DT thus can't know what components the project directly depends on, meaning the graph is missing it's root.

I added a warning log in #3990 to make this more obvious in the future.

**Comment by kruegera-hub** [comment]
Thank you for your answer! That means it's rather a syft issue than a DT issue and syft would have to create the sboms differently?

**Comment by nscuro** [comment]
> That means it's rather a syft issue than a DT issue and syft would have to create the sboms differently?

Correct.
