### ISSUE TITLE
Add 'active' bit to project

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#399]
Displaying projects will result in all project being display, even multiple versions of the same project. To help diminish the effect of this and to focus attention on active projects, the data model should introduce an 'active' bit, which will be configurable.

Inactive projects will be hidden by default but should be able to be retrieved.

**Comment by stevespringett** [comment]
The configuration is complete. Hiding inactive projects by default and optionally displaying them still needs to be done.

**Comment by stevespringett** [comment]
<img width="601" alt="working-prototype" src="https://user-images.githubusercontent.com/3878933/61684342-d3f0c680-acde-11e9-9786-109fc95a4d2b.png">

**Comment by msymons** [comment]
The concept of an "active" bit is something that should meet our needs...  my boss was asking just last week about how DT server could handle a collection of projects that we are not currently developing (but where we still want to be able to inspect metrics).

Will the active bit be used to adjust the dashboard view and the projects view (portfolio vulnerabilities, etc)?  Would/Should there be an impact on notifications?  ie, should alerts be configurable with a checkbox "include inactive projects"?

In your original description you refer to "...even multiple versions of the same project."  Is this not something that perhaps might benefit from a "temporary" bit?  This would allow for development branches.   Maybe even allow for implementation of automatic deletion of a version after (say) 30 days of no BOM upload  (similar to short-lived branches in SonarQube).  If you like the idea I will log a separate enhancement and flesh it out a bit more...

**Comment by stevespringett** [comment]
> Will the active bit be used to adjust the dashboard view and the projects view (portfolio vulnerabilities, etc)? 

The initial idea for v3.6 is to just be able to remove (from view) the inactive projects by default. 

>Would/Should there be an impact on notifications? ie, should alerts be configurable with a checkbox "include inactive projects"?

> Maybe. I'll need to give this some thought as I don't want to NOT notify on something when the user expects to be notified. The bit is in the project config, completely disconnected from notifications. The impact of flipping a bit would have an impact on notifications and it wouldn't be obvious. So I would rather error on the side of providing the notifications regardless of active status.

**Comment by msymons** [comment]
Based on your thinking for notifications, things could perhaps be made more obvious by modification to the "Add project" dialog that is displayed for "Limit to Projects"  (rather than for the alert as a whole, which was my original suggestion).

* Display an extra column to indicate active/inactive for each project
* Provide a toggle all/active-only/inactive-only

This would give the user total control on what gets alerted (or not alerted).

One use case for this...  I would create a new alert for NEW_VULNERABLE_DEPENDENCY in inactive projects.  The hope would be to identify when a supposedly inactive project is actually getting worked on....

Separately,  thoughts on  "temporary" bit?

**Comment by msymons** [comment]
@stevespringett, is the projects tab on the components screen covered by this work?

Here's our use case:  

* 120  projects.  60 use  component XXX  and 60 use component YYYY
* It is trivial to filter (and count) projects using XXX and YYY in in Dependency Track 3.5.1
* We need to update projects to migrate XXX to YYY
* However, some of the projects are not deployed (ie, are inactive) and do not need to be counted.
* Hence, with the active bit, the count of 60 might drop to (say) 40.
* A project might (or might not) be deployed later...  so toggle is important (making it easier to spot projects that need their confiigurations tweaked).

Separately, I see that you have made a commit "Hiding inactive projects from project version drop down".   Would it not be better to display **all** versions (including inactive) but visually distinguish between them using bold or italics or different font.  ie, whatever is best visually *and* meets accessibility needs (which might rule out using colour).  Maybe just indicate inactive projects by appending "(inactive)" to what the drop-down displays.  This latter would also cater for handling display of "temporary" versions (see comment above from 23 July).
