### ISSUE TITLE
Test Error: multiple SLF4J bindings

### ISSUE THREAD

**Issue by timmeinerzhagen** [DependencyTrack/dependency-track#402]
### Current Behavior:
When building the Project using "mvn clean package -P embedded-jetty" the Test "ConsolePublisherTest" fails with the Error Message below.
(As a result I'm just skipping the test stage until it's fixed)

### Steps to Reproduce:
Project was copied from Github.
"mvn clean package -P embedded-jetty" was run

### Expected Behavior:
Ignoring of the multiple bindings of slf4j as noted in the slf4j docs. Finish with build successful.

### Environment:
  - OS: Ubuntu 18.10 desktop amd64
  - Java: 1.8.0_212
  - Maven: 4.18.0-25-generic
  - Dependency-Track Version: tested with master (29.07.19) and 3.5.X 
  - Distribution: Compile from Code
  - BOM Format & Version: /
  - Database Server: /
  - Browser: /

### Additional Details:

[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.914 s <<< FAILURE! - in org.dependencytrack.notification.publisher.ConsolePublisherTest
[ERROR] testErrorStream(org.dependencytrack.notification.publisher.ConsolePublisherTest)  Time elapsed: 0.787 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<[]--------------------...> but was:<[SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.m2/repository/us/springett/alpine-executable-war/1.2.0/alpine-executable-war-1.2.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
]--------------------...>
        at org.dependencytrack.notification.publisher.ConsolePublisherTest.testErrorStream(ConsolePublisherTest.java:74)

**Comment by stevespringett** [comment]
Confirmed to be a defect. The build script actually runs twice, once normally, and once with the embedded jetty profile. During the second run, tests are disabled because the assumption was they were already successful. But I was able to reproduce this issue locally.

**Comment by javabeanz** [comment]
Does the logging library need fixing here too ?

**Comment by stevespringett** [comment]
Ideally yes. There is some optimizations that still need to take place.
