### ISSUE TITLE
`TrivyAnalysisTaskIntegrationTest` is failing for Trivy v0.54.0

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/dependency-track#4021]
### Current Behavior

Trivy [`v0.54.0`](https://github.com/aquasecurity/trivy/discussions/7268) just got released, and all test cases in `TrivyAnalysisTaskIntegrationTest` running against `latest` broke:

```
Error:    TrivyAnalysisTaskIntegrationTest.testWithPackageWithTrivyPropertiesWithDistroWithoutOS:392 
Expecting any element of:
  []
to satisfy the given assertions requirements but none did:


Error:    TrivyAnalysisTaskIntegrationTest.testWithPackageWithTrivyProperties:301 
Expecting any element of:
  []
to satisfy the given assertions requirements but none did:


Error:    TrivyAnalysisTaskIntegrationTest.test:131 
Expecting any element of:
  []
to satisfy the given assertions requirements but none did:

```

### Steps to Reproduce

1. Run `TrivyAnalysisTaskIntegrationTest`
2. Observe test failures when running against `latest`

### Expected Behavior

The tests should not fail.

### Dependency-Track Version

4.12.0-SNAPSHOT

### Dependency-Track Distribution

Container Image, Executable WAR

### Database Server

N/A

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Caused by https://github.com/aquasecurity/trivy/commit/7cbdb0a0b5dff33e506e1c1f3119951fa241b432

`vuln_type` is now `pkg_type`: https://github.com/DependencyTrack/dependency-track/blob/e3b856fc294feb91af2103551ed84354b0a71160/src/main/java/org/dependencytrack/parser/trivy/model/Options.java#L24-L25

Fun... Because we don't know the Trivy version at runtime, and Trivy's API doesn't have a version indicator, we'll need to send the same data for both `vuln_type` and `pkg_type`, similar to https://github.com/DependencyTrack/dependency-track/commit/08dfb0a3a57d21b7b65478834b1cab2b7d4609dd

**Comment by msonnlei** [comment]
@nscuro thanks for the fix. Are you planning to backport it?

**Comment by nscuro** [comment]
@msonnlei Yes, there are a few other fixes that should be backported. So another bugfix release is justified I think.
