### ISSUE TITLE
Oracle RDBMS support

### ISSUE THREAD

**Issue by pachulo** [DependencyTrack/dependency-track#403]
### Current Behavior:
As I understand from reading:

- https://docs.dependencytrack.org/getting-started/database-support/

Dependency-track does not seem to support using an Oracle RDBMS. Am I wrong?

### Proposed Behavior:
Suport Oracle RDBMS, and if it's supported, document it.

Thanks!

**Comment by stevespringett** [comment]
Oracle is supported by the persistence layer (http://www.datanucleus.org/), however, I do not have plans on supporting Oracle with upgrades, etc. That said, it might work. I don't know.

It's also highly probable that support for RDBMS will be removed in a future version as the platform's architecture gets refactored in v4 (likely two years away), which will likely depend on a GraphDB of some kind (Neo4j perhaps - still undecided).

**Comment by pachulo** [comment]
OK, I guess we will go the PostgreSQL road then. Thanks for the support!
