### ISSUE TITLE
Search Filter does not work when viewing projects using tag

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#405]
### Current Behavior:
When using a tag to view a subset of projects then the search filter does not work.  ie  when (say) 40 projects use the tag, one cannot use the search filter to cut the display down further.  Nothing at all happens.

### Steps to Reproduce:
Whilst defect was seen in DT with about 180 projects total and tags that applied to 25 or so projects, this should be possible to reproduce with just a few projects...

- Create 4 projects:  AAA, XXY, XXZ, YYY
- Add tag  ZZZ to all projects except AAA
- View any one of the projects except AAA and click on the tag
- This will load `/projects/?tag=ZZZ` and display XXY, XXZ, YYY
- Now try and use search filter field.  Type XX.  All 3 projects are still displayed... YYY has not been filtered.
 
### Expected Behavior:
Search filter should still work when in "tag view".

### Environment:
  
  - Dependency-Track Version: 3.5.1
  - Distribution: [ Executable WAR ]
  - BOM Format & Version: Cyclone DX v1.1
  - Database Server: [ PostgreSQL ]
  - Browser: Firefox 66.0.1  (Chrome 76 also tested).

**Comment by msymons** [comment]
Tested that the issue does still exist with Dependency-Track 3.8.0

**Comment by s-spindler** [comment]
Continues to be an issue in 4.5.0.

@stevespringett Why did you label this as an enhancement and not a defect?

As it is the search box is not functioning. I suppose it could be hidden for the tags view but as long as it is there a user could expect it to take effect when used.

I tried to find the relevant code parts for this but couldn't find the `searchText` parameter anywhere. Any hints would be greatly appreciated.
