### ISSUE TITLE
Dependency Graphs & External References Not Displayed After Upgrade to 4.1.1.6

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#4074]
### Current Behavior

After upgrade to Dependency-Track v4.1.1.6,  projects that were correctly displaying dependency graphs before upgrade are no longer displaying them

![image](https://github.com/user-attachments/assets/c5ed48db-2962-4b93-bac3-ba54e86ec69f)

In addition, External References are empty  (View Details -> External References)

Uploading a BOM to a "broken project" will fix both the graph and the external references....

![image](https://github.com/user-attachments/assets/431dbc74-6fee-4525-b485-0deaf2b4e42c)

This all looks like a frontend problem but it is caused by underlying problem in api-server,

### Steps to Reproduce

* Upgrade to 4.1.1.6  (or note the timestamp X for when you upgraded)
* Examine a project that has had a BOM uploaded after time X.  The dependency graph and external references should be displayed.
* Examine a project Y that has NOT had a BOM uploaded since time X.   The dependency graph and external references are missing.

### Expected Behavior

All projects should display dependency graphs and external references if such are present in the BOM.

### Dependency-Track Version

4.11.6

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

14.12

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Fixed via #4071
