### ISSUE TITLE
Problem with NVD mirror: 404 Not Found

### ISSUE THREAD

**Issue by pachulo** [DependencyTrack/dependency-track#408]
We are using the Docker container and the NVD mirror seems to be not available:

```
$ wget http://172.17.0.3:8080/mirror/nvd/nvdcve-modified.xml.gz
--2019-08-02 14:26:23--  http://172.17.0.3:8080/mirror/nvd/nvdcve-modified.xml.gz
Connecting to 172.17.0.3:8080... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-08-02 14:26:23 ERROR 404: Not Found.
```

Is there any additional configuration that needs to be done?

Thanks!

**Comment by stevespringett** [comment]
Just ensure that Dependency-Track has access to the NVD without requiring authentication and that its not being blocked. Other than that, there's no specific configuration that needs to be done. The mirror generally becomes available in about 10 minutes after initial startup.

**Comment by pachulo** [comment]
I'm testing this on my local machine with the Docker container.
I think that everything is fine with the access to NVD:

...

09:19:05.085 INFO [ProcessTask] Processing Complete for NVD CVE - 2015  (262326 ms)
09:19:36.658 INFO [ProcessTask] Processing Complete for NVD CVE - 2019  (244755 ms)
09:20:24.703 INFO [ProcessTask] Processing Complete for NVD CVE - 2016  (253154 ms)
09:21:08.495 INFO [ProcessTask] Processing Complete for NVD CVE - 2017  (273502 ms)
09:21:59.499 INFO [ProcessTask] Processing Complete for NVD CVE - 2018  (318082 ms)
09:21:59.499 INFO [NvdCveUpdater] Begin database maintenance.
09:22:01.020 INFO [NvdCveUpdater] End database maintenance.
09:22:01.632 INFO [Engine] Check for updates complete (850330 ms)
09:22:01.647 INFO [DependencyCheckTask] Dependency-Check update-only complete
```


Buy yet I cannot access the mirror at:
http://localhost:8080/mirror/nvd/nvdcve-modified.xml.gz

**Comment by stevespringett** [comment]
Did you ever resolve this?

Also FYI, in v3.6, mirroring of the XML files has been removed since they're no longer supported by the NVD.

**Comment by pachulo** [comment]
> Did you ever resolve this?

No, not really.

> Also FYI, in v3.6, mirroring of the XML files has been removed since they're no longer supported by the NVD.

OK, good to know.

**Comment by pachulo** [comment]
Well, I would say this doesn't apply anymore.
