### ISSUE TITLE
Server failed with “javax.servlet.ServletException: javax.jdo.JDODataStoreException: Iteration request failed“

### ISSUE THREAD

**Issue by pachulo** [DependencyTrack/dependency-track#409]
### Current Behavior:
After the weekend, the server was giving us 500.

After a restart everything is fine again.

### Steps to Reproduce:
We don't really know how to reproduce it; all we did was:
1. Create a project.
2. Manually upload a BOM file.
3. Configure the Sonatype OSS Index correctly.

### Expected Behavior:
The application should not fail.

### Environment:
  
  - Dependency-Track Version: 3.5.1
  - Distribution: Docker
  - BOM Format & Version: `<bom xmlns="http://cyclonedx.org/schema/bom/1.1" serialNumber="urn:uuid:91faa83d-0b2f-4dc9-9084-c3789813e67a" version="1">`
  - Database Server: PostgreSQL
  - Browser: Google Chrome 76

### Additional Details:
In the logs we saw this exception:

`javax.servlet.ServletException: javax.jdo.JDODataStoreException: Iteration request failed : SELECT 'alpine.model.Permission''alpine.model.Permission' AS "DN_TYPE" AS "DN_TYPE""A1"."DESCRIPTION",,"A1"."ID","A1"."NAME" AS "NUCORDER0","A0"."MANAGEDUSER_ID","A1"."NAME" AS "NUCORDER0","A0"."MANAGEDUSER_ID","A1"."NAME" AS "NUCORDER0" FROM "MANAGEDUSERS_PERMISSIONS" "A0""MANAGEDUSERS_PERMISSIONS" "A0" INNER JOIN "PERMISSION" "A1" ON "A0"."PERMISSION_ID" = "A1"."ID" WHERE  INNER JOIN "PERMISSION" "A1" ON "A0"."PERMISSION_ID" = "A1"."ID" WHERE EXISTS (SELECT 'alpine.model.ManagedUser' AS "DN_TYPE", AS "DN_TYPE","A0_SUB"."ID" AS "DN_APPID" FROM "MANAGEDUSER" "A0_SUB"null WHERE "A0_SUB"."USERNAME" = ? AND "A0"."MANAGEDUSER_ID" = "A0_SUB"."ID""A0_SUB"."USERNAME" = ? AND "A0"."MANAGEDUSER_ID" = "A0_SUB"."ID") ORDER BY "NUCORDER0"EXISTS (SELECT 'alpine.model.ManagedUser' AS "DN_TYPE", AS "DN_TYPE","A0_SUB"."ID" AS "DN_APPID" FROM "MANAGEDUSER" "A0_SUB"null WHERE "A0_SUB"."USERNAME" = ? AND "A0"."MANAGEDUSER_ID" = "A0_SUB"."ID""A0_SUB"."USERNAME" = ? AND "A0"."MANAGEDUSER_ID" = "A0_SUB"."ID") ORDER BY "NUCORDER0"EXISTS (SELECT 'alpine.model.ManagedUser' AS "DN_TYPE", AS "DN_TYPE","A0_SUB"."ID" AS "DN_APPID" FROM "MANAGEDUSER" "A0_SUB"null WHERE "A0_SUB"."USERNAME" = ? AND "A0"."MANAGEDUSER_ID" = "A0_SUB"."ID""A0_SUB"."USERNAME" = ? AND "A0"."MANAGEDUSER_ID" = "A0_SUB"."ID") ORDER BY "NUCORDER0"`

**Comment by stevespringett** [comment]
Exceptions like this that are likely due to connectivity issues with Postgres. I've seen this multiple times, and 99% of the time the org is using postgres.

DT maintains a connection pool to the database (defaults to 10 connections). The connections have a max life of 600000ms (10 minutes). If postgres is configured with a lower value (ie. 5 minutes), then these type of issues will occur.

Try experimenting with:
`ALPINE_DATABASE_POOL_IDLE_TIMEOUT`
`ALPINE_DATABASE_POOL_MAX_LIFETIME`
as defined in https://docs.dependencytrack.org/getting-started/deploy-docker/

**Comment by pachulo** [comment]
OK, we will try to modify those and will report here any issues. Thanks!

**Comment by pachulo** [comment]
We tried setting **idle_in_transaction_session_timeout** to **600000** on PostgreSQL, let's see if it works OK.

From https://www.postgresql.org/docs/11/runtime-config-client.html:

> idle_in_transaction_session_timeout (integer)
> Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds. This allows any locks held by that session to be released and the connection slot to be reused; it also allows tuples visible only to this transaction to be vacuumed. See Section 24.1 for more details about this.
> 
> The default value of 0 disables this feature.
