### ISSUE TITLE
Deleting project properties over the REST API does not work

### ISSUE THREAD

**Issue by Mtothexmax** [DependencyTrack/dependency-track#4095]
### Current Behavior
```
curl -X DELETE \
-H "X-Api-Key: $DEPENDENCY_TRACK_API_TOKEN" \
-H "Content-Type: application/json" \
-d '{"groupName": "group123", "propertyName": "property123"}' \
"$DEPENDENCY_TRACK_URL/v1/project/$UUID/property"
```

returns error 405 although the GET and PUT REST API calls work.

### Steps to Reproduce

1. create a project and add a project property with the group name and property name as in the curl above
2. run the curl command from above and the project uuid from your project
3. error 405 appears

### Expected Behavior

the project property is deleted.

(please do not confuse this with component properties or config properties)

### Dependency-Track Version

4.11.5

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Does it work via UI? Since the UI is merely calling the REST API, too.

**Comment by Mtothexmax** [comment]
sorry, my bad, I forgot the /api in the url
