### ISSUE TITLE
Add a DefectDojo integration

### ISSUE THREAD

**Issue by rback123** [DependencyTrack/dependency-track#410]
### Current Behavior:

There is no DefectDojo integration.

### Proposed Behavior:

Please add a DefectDojo integration for vulnerability aggregation. I believe this would be very similar with the existing Kenna or Fortify integrations. I would like to surface all the audit findings of known component vulnerabilities as issues in DefectDojo. Dependency-Track could push this information to a CI/CD Engagement in DefectDojo increasing automation in our AppSec Pipelines.

DefectDojo is another OWASP flagship product, but incase others aren't familiar with it here are some URLs that may be beneficial. 
* Homepage - https://www.defectdojo.org
* Code - https://github.com/DefectDojo/django-DefectDojo
* Docs - https://defectdojo.readthedocs.io/en/latest/

Thank you!

**Comment by stevespringett** [comment]
ThreadFix has native support for Dependency-Track. It pulls in vulnerability information from Dependency-Track and handles all the project mappings. There's nothing Dependency-Track needed to do. To my understanding Orchestron (we45) will be doing the same thing - or maybe already has.

Integration should likely be handled by DD as the tool configuration in DD has the ability to enter the Dependency-Track URL and API key. The only piece missing a parser in DD to handle the response sent from Dependency-Track.

ThreadFix utilizes the /vulnerability api. Kenna Security and Fortify SSC both utilize the /findings API, which is a bit newer and more suitable for integration with external systems.

There are two options for the findings API, a typical JSON response, or a forced download response resulting in a slightly different JSON. Both are nearly identical. The only difference is that the forced download one (binary-octetstream) contains a fileformat version and meta info, whereas the normal JSON response does not. DD would likely be able to use the normal JSON response quite easily.

https://docs.dependencytrack.org/integrations/file-formats/

**Comment by stevespringett** [comment]
If/when a DefectDojo ticket is created to add support for Dependency-Track, please reference this ticket.
