### ISSUE TITLE
Massive log monitoring from database

### ISSUE THREAD

**Issue by sga-solita** [DependencyTrack/dependency-track#4101]
### Current Behavior

We have been running Dependency Track for about a month and just now I can see that there are a LOT of log entries in Application Insights from the database queries
![image](https://github.com/user-attachments/assets/a7db093f-805a-452e-b248-36df11716071)

This is causing our Log Analytics Workspace to be responsible for most of our costs:
![image](https://github.com/user-attachments/assets/fbf5470b-8171-4603-aa4a-a699b4c6222d)

How do I reduce or disable database query output? I did search through the documentation, but was unable to find something specifically for this problem.

### Steps to Reproduce

1. Use Dependency Track
2. Check logs

### Expected Behavior

Possibility to reduce or disable log output from database queries.

### Dependency-Track Version

4.11.7

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
DT doesn't log any queries by default. This looks like you configured Postgres to log queries in Azure, and you're using Azure's log analytics service on top of that.

You'll need to check your Azure config to disable that.

**Comment by sga-solita** [comment]
I did think of that possibility, but the cloud_RoleName is DT backend (redacted here, but screenshot for clarity)
![image](https://github.com/user-attachments/assets/e7db3a58-9053-4f28-b036-ccda209bd02b)

**Comment by nscuro** [comment]
DT doesn't know about any cloud and roles within it. Your Postgres database has verbose query logging enabled, but that configuration is entirely on your side and nothing DT can change or even see.
