### ISSUE TITLE
500 error when trying to remove dependencies from projects in bulk

### ISSUE THREAD

**Issue by pachulo** [DependencyTrack/dependency-track#411]
### Current Behavior:
When working on a project, selecting Dependencies and then trying to remove them returns a 500 error:

> An unexpected error occurred. Please contact the Dependency-Track administrator for assistance (500).

### Steps to Reproduce:

1. Create a project.
2. Upload a BOM
3. Try to delete some dependencies by selecting them and clicking on "Remove Dependency"

### Expected Behavior:
The dependencies should be deleted.

### Environment:
  
  - Dependency-Track Version: 3.5.1
  - Distribution: Docker
  - BOM Format & Version: 1.1
  - Database Server: PostgreSQL
  - Browser: Chrome 76

### Additional Details:

For what I understand, the UUIDS of the components are not populated:
![image](https://user-images.githubusercontent.com/3256953/62628380-79d14180-b92b-11e9-919c-7dc906906e50.png)

**Comment by stevespringett** [comment]
This issue was resolved in #400 and affects only the UI. As a workaround, use the API to remove dependencies until v3.6.0 is released.

**Comment by pachulo** [comment]
Ups, I did check the issues but not the PRs, sorry for the noise!

**Comment by stevespringett** [comment]
Closing, as 3.6.0 will be released this weekend.
