### ISSUE TITLE
New active project filter doesn't work as expected

### ISSUE THREAD

**Issue by patros** [DependencyTrack/dependency-track#412]
This appears to be a schema/data migration issue.

With the latest snapshot build I was initially presented with an empty project list. I checked a few projects and they all showed as being active. But they only displayed if I select to show inactive projects.

After a bit of digging the active flag defaults to null in the database. This only happens with existing projects, not newly created ones. When viewing the project details for a project with a null active flag the interface displays the project as being active.

Once the active flag is correctly set in the database to true it works as expected.

### Current Behavior:
NA

### Steps to Reproduce:
Upgrade existing installation with existing projects to latest snapshot.

### Expected Behavior:
Existing projects should be set to active in the database.

### Environment:
  
  - Dependency-Track Version: snapshot
  - Distribution: Docker
  - BOM Format & Version: NA
  - Database Server: MSSQL
  - Browser: NA

**Comment by stevespringett** [comment]
While I haven’t tested the upgrade yet, it should work.

https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/upgrade/v360/v360Updater.java

Note that upgrades are only supported between GA releases. If updating from one snapshot to another (ie 3.6.0 snapshot and another 3.6.0 snapshot), upgrade classes will not be triggered.

When you tested this, did you upgrade from 3.5.0/3.5.1 or did you update from a previous 3.6.0 snapshot?

**Comment by patros** [comment]
Ah, that will be it. Straight from the latest 3.5.1 image. Thanks @stevespringett
