### ISSUE TITLE
Upload dependency scan XML report to Dependency Track

### ISSUE THREAD

**Issue by ManeShrushti** [DependencyTrack/dependency-track#413]
I am trying to upload the dependency check scan report which is in XML format to the Dependency track v3.5.1. It shows a warning "Supported formats include Dependency-Check XML schema v1.x produced by Dependency-Check v1.x - v4.x." But I have generated the report using the dependency-check v3.3.0 and I am still not able to upload the file via the following command

cat > payload.json <<HERE
	{
	"project": "...",
	"scan": "$(cat dependency-check-report.xml |base64 -w 0 -)"
	}
HERE
curl -X "PUT" "http://localhost:8080/api/v1/scan" \
-H 'Content-Type: application/json' \
-H 'X-API-Key: .....' \
-d @payload.json
Can you please also specify where exactly can I find the API-key and the Project ID to apply in these commands.

**Comment by stevespringett** [comment]
The API is defined on a per-team basis in the admin console. There is an automation team that is created by default that already has the necessary permissions to upload scans and boms. The project uuid is retrieved from the URL when viewing a specific project. Use that UUID for API requests
