### ISSUE TITLE
Vulnerability analysis cannot be performed, if the component contains “purchaser” property in SBOM file

### ISSUE THREAD

**Issue by buke-narlitepe-itk** [DependencyTrack/dependency-track#4144]
### Current Behavior

When we upload **SBOM** file in **CycloneDX ( 1.5 version)** format to the tool, we do not get any results. Instead, we receive a parse error from your API. 
Once we examine further:
if any component contains the following section, API throws an error:
```
  "purchaser": {
    "organization": {
      "contact": [
        {
          "name": ""
        }
      ]
    }
```
When we remove the above part from the component section, the analysis can be completed as expected.
Additionally, there is another component in SBOM file that has already vulnerabilities. Due to this error, its analysis is also skipped.
 
![image](https://github.com/user-attachments/assets/4629ee2b-d05d-4010-babf-27b9b6be2ff9)
![image](https://github.com/user-attachments/assets/2bd12e20-0ce9-48f8-b899-c2090fd77c32)

### Proposed Behavior

If there is an error or omission in SBOM file that could disrupt the analysis, it would be better, that the error message was more descriptive. 
At least the analysis results of the other component can be given, and the error of the faulty component can be thrown as a response in more descriptive way.
We would also like to know why such an error occurred.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
> we receive a parse error from your API.

Can you share the exact error you'e getting?

**Comment by nscuro** [comment]
It's a parsing bug in the CycloneDX library: https://github.com/CycloneDX/cyclonedx-core-java/issues/507
