### ISSUE TITLE
Supress Vulnerability on System Level

### ISSUE THREAD

**Issue by algol68** [DependencyTrack/dependency-track#4155]
### Current Behavior

In order to suppress vulnerability, one has to go into each affected project and individually suppress vulnerability in question. 

### Proposed Behavior

Have system-level configuration to allow vulnerability to be suppressed across all projects..would be a great timesaver.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Duplicate of #1495
