### ISSUE TITLE
Cannot import GitHub's dependency graph SBOM

### ISSUE THREAD

**Issue by madchap** [DependencyTrack/dependency-track#4168]
### Current Behavior

Trying to import an SPDX file from GitHub's dependency graph SBOM fails with a 400 error.

![image](https://github.com/user-attachments/assets/b01d1c0c-018a-4d76-910a-71ab32063e6f)

![image](https://github.com/user-attachments/assets/571f5a60-f6a2-45a1-ba69-bd46d3c1ad46)

### Steps to Reproduce

1. "Export SBOM" from a public GitHub's repository. I took DefectDojo's at https://github.com/DefectDojo/django-DefectDojo/network/dependencies
2. Try to upload into DTrack. Experience a 400 error.

### Expected Behavior

Upload of the SBOM succeeds.

### Dependency-Track Version

4.11.7

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Database Server Version

N/A

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
SPDX is not supported at the moment, see #1746
