### ISSUE TITLE
Metadata component CPE not recognized in BOM upload

### ISSUE THREAD

**Issue by eugenhoffmann** [DependencyTrack/dependency-track#4173]
### Current Behavior

The CPE value defined in metadata component not being recognized when uploading a BOM file.
However, the defined PURL address is recognized and set correctly in the project

### Steps to Reproduce

1. Upload the [BOM file](https://github.com/user-attachments/files/17129884/cdx.json) via "Upload BOM" button.
2. Click on "View Details"
3. Navigate to "Identity"

### Expected Behavior

The CPE should be set in the project, just like the PURL address is correctly set when used in the metadata component

### Dependency-Track Version

4.11.7

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

15.5

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Good catch, CPE is not being set here: https://github.com/DependencyTrack/dependency-track/blob/16ef23646011cba2796a979a114cb90e7317d125/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java#L324-L340
