### ISSUE TITLE
Api cal to get all the Audited components in a particular project

### ISSUE THREAD

**Issue by itmanju** [DependencyTrack/dependency-track#4197]
### Current Behavior

Not able to get only audited components in a particular project using API call

### Proposed Behavior

Api cal to get all the Audited components in a particular project

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by dipeshsingh253** [comment]
Hi 👋, I would like to work on this issue. Can you please assign it to me...? @itmanju

**Comment by itmanju** [comment]
I am fine for you to look into this

**Comment by itmanju** [comment]
> Hi 👋, I would like to work on this issue. Can you please assign it to me...? [@itmanju](https://github.com/itmanju)
