### ISSUE TITLE
JIRA Integration doesn't work and it's not clear what values to enter

### ISSUE THREAD

**Issue by DanOrsborne** [DependencyTrack/dependency-track#4237]
### Current Behavior

The integration doesn't work at all using username and password or API key or user and api key 
Consider also making the instructions clearer and having a 'Test connection' button on the setup page to confirm the details are correct.

### Steps to Reproduce

1.Open JIRA page 
2. Add credentials and URL for JIRA
3. Go to the Alerts page and enter the key and ticket type
4. Press Test

Expected 
Issue is created in JIRA

Actual
Nothing created and no feedback on the screen about the issue

### Expected Behavior

Expected 
Issue is created in JIRA

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by DanOrsborne** [comment]
Looking through the logs the error is:

2024-10-10 07:58:36,395 WARN [JiraPublisher] No JIRA ticket type configured; Skipping notification (PublishContext{notificationGroup=POLICY_VIOLATION, notificationLevel=INFORMATIONAL, notificationScope=PORTFOLIO, notificationTimestamp=2024-10-10T07:58:36.39549595Z, notificationSubjects={component=Component[uuid=94f87321-a5d1-4c2f-b2fe-95165debebc6, group=null, name=componentName, version=componentVersion], project=Project[uuid=c9c9539a-e381-4b36-ac52-6a7ab83b2c95, name=projectName, version=projectVersion]}}) [requestId=435c2ee7-9820-4bff-9334-43f99bd35fd6]

But the value is set in the Notification settings to BUG

**Comment by dan-caprioara** [comment]
Same for me: "[JiraPublisher] No JIRA ticket type configured; Skipping notification..."

**Comment by Kringe07** [comment]
I also have the same issue

**Comment by dan-caprioara** [comment]
Neither the MS Teams integration. Maybe is a bug in the common code?

**Comment by valamiyanew** [comment]
I am having same issue. Has anyone got solution for this? Any new patch is coming to fix this?
