### ISSUE TITLE
502 Bad Gateway when trying to send dependency results with curl

### ISSUE THREAD

**Issue by elfcan** [DependencyTrack/dependency-track#428]
Hello,

I installed Dependency Track with docker and am trying to send dependency result via curl as described on this page: https://docs.dependencytrack.org/usage/cicd/
 
I'm running it behind proxy with Apache with Letsencrypt certificates. When I try this curl:

`curl -o -X "PUT" "https://dtrack.kodgemisi.com/api/v1/scan"      -H 'Content-Type: application/json'      -H 'X-API-Key: kiX2Znz...'      -d @payload.json
`
I get 502 Bad Gateway response. 

![Selection_399](https://user-images.githubusercontent.com/2270993/64188205-9e610080-ce7a-11e9-9cb8-6f87bad1b951.png)

What am I missing? Please help.

Best,
Elifcan

**Comment by stevespringett** [comment]
The request looks right. Likely something outside of Dependency-Track. Does the proxy support PUT?

**Comment by elfcan** [comment]
Hello, thank you for the quick response. I removed the proxy and tried like this:

`curl -o -X "PUT" "http://dtrack.kodgemisi.com:8777/api/v1/scan"      -H 'Content-Type: application/json'      -H 'X-API-Key: kiX2Znz...'      -d @payload.json`

Even like this:

`curl -o -X "PUT" "http://144.76.5.198:8777/api/v1/scan"      -H 'Content-Type: application/json'      -H 'X-API-Key: kiX2ZnzEVl8BILpvA6UPgYaJWs0HxwZ1'      -d @payload.json`

This is what I get:

![Selection_400](https://user-images.githubusercontent.com/2270993/64237003-2808e080-cf04-11e9-9b1c-ed931bd6234b.png)

I don't understant why I am getting "could not resolve host" error. I can access the dashboard, add projects, etc. But I had no luck with the API.

Best,
Elifcan

**Comment by elfcan** [comment]
Hello, thank you for the quick response. My curl command was wrong, now it works. Thanks for your time!
