### ISSUE TITLE
Rohde & Schwarz has adopted Dependency-Track

### ISSUE THREAD

**Issue by lukas-braune** [DependencyTrack/dependency-track#4295]
### Organization Name

Rohde & Schwarz

### Organization Website

https://www.rohde-schwarz.com/

### Organization Logo (optional)

https://avatars.githubusercontent.com/u/39411067?s=200&v=4

### How is your organization using Dependency Track?

At Rohde & Schwarz, we are deeply committed to ensuring the cybersecurity of our products, systems, and solutions. As part of our comprehensive security strategy, we utilize a diverse set of tools to safeguard our technology. We value Dependency-Track for its scalability, adherence to open standards, and active community. Additionally, we actively contribute to the development of Dependency-Track by adding features, improving its usability for large organizations, and strengthening its security posture.

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by nscuro** [comment]
Thanks so much @lukas-braune and team for the kind words, and of course the many contributions!
