### ISSUE TITLE
Dependency-Check v5.x Scan PUT Fails

### ISSUE THREAD

**Issue by IndifferentDisdain** [DependencyTrack/dependency-track#430]
### Current Behavior:
When using Dependency Check v5.x to generate an XML report and PUT to Dependency-Track v3.5.1, 200 is returned but no data is processed by Dependency Track. Downgrading Dependency Check to v4.0.2 resolves the issue.

### Steps to Reproduce:

1. Windows 10, Install Dependency Check v5.2.1, add to path, restart
2. Pull Dependency Track Docker image owasp/dependency-track and run locally
3. At root of any code repo, run `dependency-check.bat project "ProjectName" --scan . -f XML`
4. Run `base64 dependency-check-report.xml > dependency-check-report-encoded.txt -w 0`
5. Create payload.json as `{"project": "{ProjectGUID}", "scan": "{copy .txt contents above}"}`
6. run `curl -X "PUT" "http://localhost:8080/api/v1/scan" -k -H "Content-Type: application/json" -H "X-API-Key: "{APIKEY}" -d @payload.json`, and you should get a 200
7. Check in Dependency Track, and no results
8. Downgrade Dependency Check to v4.0.2, restart, repeat, and results will appear.

### Environment:
  
  - Dependency-Track Version: 3.5.1
  - Distribution: Docker
  - BOM Format & Version: Dependency Check scan XML v5.2.1

**Comment by stevespringett** [comment]
Refer to #381 and #354. Dependency-Check v5 and higher is not supported. The log file states this fact when importing.

Also note, that Dependency-Check reports will be disabled by default in v3.6 (#397) and removed in v3.7 (#396)

**Comment by IndifferentDisdain** [comment]
Apologies for missing that, thanks for the reply and confirmation.
