### ISSUE TITLE
Excel input of dependencies / components

### ISSUE THREAD

**Issue by preethamnagesh8** [DependencyTrack/dependency-track#441]
**Current**: This scenario is mainly for asset vulnerability discovery in Dependency Track. Current scenario: we need to upload an SBoM file or manually enter the product details one by one.

**Proposed**: Upload an excel file with details of vendor, product and the version as 3 columns. The dependency track tool should make a check against the data repositories and provide the following outputs:

1. In case the product is found in CPE, should give the number of vulnerabilities.
2. In case the product is not found(product details entered is wrong) should give a not found alert / notification to user.

**Comment by stevespringett** [comment]
Importing arbitrary Excel files is not in scope of this project. This project works on SBOMs. As an alternative, a REST API exists containing much more functionality than the UI exposes. Importing components via REST may be an option.

When adding components, you may add the group (vendor), name (product), and version, but without a valid CPE or PURL, no analysis will be performed. So when importing, ensure each component has a valid CPE or PURL.

**Comment by preethamnagesh8** [comment]
Ok right. Thanks for the suggestion. Will try that out
