### ISSUE TITLE
Unable to upload dependency-check-report.xml via API

### ISSUE THREAD

**Issue by shakthi-n** [DependencyTrack/dependency-track#442]
Am running a dependency-check-report for a .NET 4.7 framework application. The output is generated in both HTML and XML. I can see the vulnerabilities fine in the report. When i try to upload the base64 of xml via scan endpoint, i get 200 OK status in Postman but nothing happens on dependency tracker server. I even tried to upload as payload.json using Crul with no luck. Any help is appreicated.

**Comment by stevespringett** [comment]
What does the dependency-track.log say?

**Comment by shakthi-n** [comment]
Where can i find the log file? I don't have access to dependency track server but i can request for the file.

**Comment by stevespringett** [comment]
Its in the data directory
https://docs.dependencytrack.org/getting-started/data-directory/

Also note that Dependency-Check v5 and higher are not supported. The log file will state this if that's what's being imported.

Importing Dependency-Check reports will be disabled by default in v3.6 (#397) and removed in v3.7 (#396)

**Comment by shakthi-n** [comment]
Looks like am using higher version as you mentioned. here is the message from log "The scan uploaded is not in a supported format. Supported formats include Dependency-Check XML schema v1.x produced by Dependency-Check v1.x - v4.x. Refer to https://docs.dependencytrack.org/best-practices/"

**Comment by shakthi-n** [comment]
I was able to upload xml file generated using version 4.2.0. Thanks.
