### ISSUE TITLE
SBOM Upload along with Child Project failing UUID too long for Parent Project

### ISSUE THREAD

**Issue by Kalyan-Alamuru** [DependencyTrack/dependency-track#4424]
### Discussed in https://github.com/DependencyTrack/dependency-track/discussions/4422

<div type='discussions-op-text'>

<sup>Originally posted by **Kalyan-Alamuru** November 30, 2024</sup>
I have requirement to create Multiple Child Projects in Parent Project which are passed as Map of List.  It is bit weird to understand what's happening as when I create a New Parent and Child along with it, The Set Creates without any issues. But when I try to second child under Existting Parent with a Child it fails with following Error :
Uncaught internal server error [requestId=e56c80b1-374c-4ae0-a3ea-161faabde9a1]
java.lang.IllegalArgumentException: UUID string too large
	at java.base/java.util.UUID.fromString1(Unknown Source)
	at java.base/java.util.UUID.fromString(Unknown Source)

I checked both my Parent UUID and Child UUID that is going to be created and I can't see an issue with it as they both agree to format of 
// Validate the parent UUID format
        if (!parentUuid.matches("[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")) {
            println "Invalid UUID format for parent: ${parentUuid}"
            failedToCreateParentProjectList.add(parentChildMap)
            projectsNotCreated.add(parentChildMap)
            return
        }
My Parent UUD is : 38b62b24-f823-4fa7-9a1e-e51a1569f6a1
I'm running Dependency Track as local deployment in docker container in Ubuntu 20.04 LTS and My D Track version is : v4.12.1 </div>

**Comment by valentijnscholten** [comment]
Can you provide the exact request + body you're sending as well as the Stracktrace.

**Comment by Kalyan-Alamuru** [comment]
Hi @valentijnscholten  - thanks for the reply. I managed to sort it. As It is to do with formatting of UUID which is causing this error i.e. added additional [] while doing get API Calls for projects which already created.
