### ISSUE TITLE
Infinite loop when synchronisizing npm-Advisories.

### ISSUE THREAD

**Issue by deluxe2** [DependencyTrack/dependency-track#447]
### Current Behavior:
When mirroring the npm-Advisories, there are only checks for a 200-HTTP-Status and for broken HTTP-Requests. If a requests succeeds with a non 200 status, the program stucks in a infinite loop.

### Expected Behavior:
The unexpected status should be logged and the synchronisation stopped.

### Additional Details:
The referenced call is in this [sourcefile](https://github.com/DependencyTrack/dependency-track/blob/bea61fd6330facd2fd22299342f948b72907124f/src/main/java/org/dependencytrack/tasks/NpmAdvisoryMirrorTask.java#L101).

**Comment by stevespringett** [comment]
Thanks for reporting. The issue has been resolved and will be included in v3.6
