### ISSUE TITLE
Generation & Publishing SBOM for Dependency-Track Itself

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#452]
### Current Behavior:
There is no published BOM for Dependency-Track that could be uploaded into Dependency-Track itself.  ie, to see that DT 3.5.1 is built using a vulnerable version of `jackson-databind` (or whatever) or includes an out-of-date component or one with a license problem.

### Proposed Behavior:
Publish a CycloneDX BOM as part of the release process for Dependency-Track,

What I hope to see here is something that is a demonstration of process that is an illustration for  [OWASP Component Analysis](https://www.owasp.org/index.php/Component_Analysis) best practice, or for the upcoming [OWASP Software Component Verification Standard](https://www.owasp.org/index.php/OWASP_Software_Component_Verification_Standard)

One thing that I am not sure about is the best way to make such BOM available, ie, with versioning, etc.  ie, would a Maven project just publish the BOM to Maven as a normal artefact?

This enhancement is also valid for cyclonedx-maven-plugin and all other projects.  Logged here because "you have to start somewhere".

If successful, it would be great to then be able to spread the message and be able to see BOMs published for Jenkins, SonarQube, etc, and be able to really get a better of risk in your whole environment...

**Comment by stevespringett** [comment]
Producing a BOM for Dependency-Track during build is simple, as Alpine (what DT is built on) contains a Maven profile that does it. However, DT also includes unmanaged Javascript dependencies which would not be included in it, so it's a bit of a manual effort there. Once the new front-end project is complete, DT will consist of Maven and NPM builds, so it would be much simpler. I'll see what I can do in the interim.

As far as best practices, a lot of that work is still be flushed out independent of DT. The OWASP things you mention are examples, but also NTIA and their four working groups. NTIA is getting really close to publishing our first set of docs on software transparency and one of those groups is now moving towards investigating tooling and putting SBOMs into practice. That work will likely result in follow-up documentation, all of which will be published by NTIA.

https://www.ntia.doc.gov/SoftwareTransparency

**Comment by stevespringett** [comment]
The work being done on the new frontend produces SBOMs during build. Once complete, a complete bill of material will be easily producible.
