### ISSUE TITLE
When i initialize Dependency Track, it gives error 

### ISSUE THREAD

**Issue by aykutaricioglu** [DependencyTrack/dependency-track#455]
Hi,

When i start DependencyTrack with embedded war, it gives following error. How can i fix this?

![image001 (5)](https://user-images.githubusercontent.com/9120266/65448540-b7d5e680-de41-11e9-898d-c26463d1056d.png)

Kind Regards,

**Comment by stevespringett** [comment]
Not sure. Dependency-Track v3.6 (releasing later this week) will no longer bundle the Dependency-Check ScanAgent. So whatever the problem is will not be an issue with v3.6.

**Comment by aykutaricioglu** [comment]
Thank you for your reply.

I need to define proxy permission for accessed URL's. Can you tell me the URLs I should allow?

**Comment by stevespringett** [comment]
A definite list does not exist, but may include the NVD, OSS Index, NPM, VulnDB, Kenna Security, and all the supported repository URLs. Each new version adds more.

**Comment by aykutaricioglu** [comment]
Thank you for your quick response.
