### ISSUE TITLE
Failing to download from nvd.nist.gov due to certificate error

### ISSUE THREAD

**Issue by relnah** [DependencyTrack/dependency-track#457]
### Current Behavior:
Running 3.6.0 Docker container there are errors on all dwnloads from nvd.nist.gov due to certificate error.
Example of log entries:
09:06:47.577 ERROR [NistMirrorTask] Download failed : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
09:06:47.578 INFO [NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
09:06:47.777 ERROR [NistMirrorTask] Download failed : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
09:06:47.371 INFO [NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz

### Steps to Reproduce:
Pull and run latest from docker hub.

### Expected Behavior:
Downloads should work

### Environment:
  
  - Dependency-Track Version:
3.6.0
  - Distribution: [ Docker | Executable WAR | Traditional WAR ]
Docker
  - BOM Format & Version: N/A
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]
PostgreSQL
  - Browser: 
N/A

**Comment by stevespringett** [comment]
Thanks for reporting however this is an issue with the NVD. They will need to correct. I just checked and do not see any certificate issues so they may have corrected already.

**Comment by relnah** [comment]
Hi! I'm still having the same issue, but you are probably correct. I'm having the same issue when pulling the 3.5.1 image to roll back. Also when just running a wget from a newly updated rpi I get cert error. Though no issue with cert in browser, which was what led to me reporting it here.

**Comment by mterron** [comment]
Browsers deal with broken chain where wget, curl, etc don't. Has anyone got in touch with NIST?

**Comment by stevespringett** [comment]
I have contract them to let them know.

**Comment by duttonw** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=nvd.nist.gov 

yep ```This server's certificate chain is incomplete.```


```

Java
--

Path #1: Trusted
--
1 | Sent by server | nvd.nist.govFingerprint SHA256: 4a0f1bcc9693dc156ff41085002a79ac79f76c1552dca18b2ebf415413195c71Pin SHA256: 2Iswi79cJgROkDh5TDGSejbO8aZGBF6Ircl/ZHt88jk=RSA 2048 bits (e 65537) / SHA256withRSA
2 | Extra download | DigiCert SHA2 Secure Server CAFingerprint SHA256: 154c433c491929c5ef686e838e323664a00e6a0d822ccc958fb4dab03e49a08fPin SHA256: 5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=RSA 2048 bits (e 65537) / SHA256withRSA
3 | In trust store | DigiCert Global Root CA   Self-signedFingerprint SHA256: 4348a0e9444c78cb265e058d5e8944b4d84f9662bd26db257f8934a443c70161Pin SHA256: r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E=RSA 2048 bits (e 65537) / SHA1withRSAWeak or insecure signature, but no impact on root certificate
```

**Comment by itajun** [comment]
Not recommended :), but this is a possible workaround until the certificate gets fixed: 
`java -Dcom.sun.security.enableAIAcaIssuers=true -jar nist-data-mirror-1.3.0.jar ./test`

**Comment by timja** [comment]
> Not recommended :), but this is a possible workaround until the certificate gets fixed:
> `java -Dcom.sun.security.enableAIAcaIssuers=true -jar nist-data-mirror-1.3.0.jar ./test`

Why not recommended, it's just disabled for compat reasons, not because it's not recommended?
> Support for the caIssuers access method of the Authority Information Access extension is available. It is disabled by default for compatibility and can be enabled by setting the system property com.sun.security.enableAIAcaIssuers to the value true.
If set to true, Sun's PKIX implementation of CertPathBuilder uses the information in a certificate's AIA extension (in addition to CertStores that are specified) to find the issuing CA certificate, provided it is a URI of type ldap, http, or ftp.

https://docs.oracle.com/javase/8/docs/technotes/guides/security/certpath/CertPathProgGuide.html#AIA

**Comment by itajun** [comment]
You are right. I thought it wasn't supported by other jdks, but it seems to be. Working well for me so far.

**Comment by timja** [comment]
It didn't work for me with the gradle plugin, although it did work with the mirror tool.
Anyway this is now fixed for us, the chain must be supplied correctly now

**Comment by stevespringett** [comment]
Response from NVD:

Good morning,

Thank you for reporting this to the NVD, we are aware of the problem and are currently working on a resolution. We apologize for the inconvenience.

V/r,
National Vulnerability Database Team
mailto:nvd@nist.gov

**Comment by mterron** [comment]
Update:

Good morning,



We believe we have resolved the issue you reported. Please let us know if
you are still experiencing problems.

V/r,
National Vulnerability Database Team
nvd@nist.gov

**Comment by relnah** [comment]
The site that @duttonw linked to says they are all good now. https://www.ssllabs.com/ssltest/analyze.html?d=nvd.nist.gov

Won't be able to test my case until tomorow morning.

**Comment by stevespringett** [comment]
Closing as the issue has been resolved.
