### ISSUE TITLE
Severity Colours

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#461]
### Current Behavior:
Dependency-Track is representing "no vulnerabllity" using the colour blue and low severity vulnerability using the colour green.

When implementing the new SVG badge functionality in v3.6.0, the very first feedback received was a comment on this...  that green (normally associated with "go" or "no problem") should not be used to communicate that there IS a problem (albeit of low severity).

### Proposed Behavior:
* Use blue for low severity
* Use green for no vulnerabiility  (zero threat).
* ...or allow colours to be configured (so that they are independent of any cultural association of meaning...  that "red is always bad", etc).

**Comment by stevespringett** [comment]
The severity colors in the SVG badge match the severity colors in the UI. The colors are in-line with other risk management and threat warning color schemes.

https://www.gov.scot/binaries/content/gallery/publications/guidance/2008/11/risk-management-hai-methodology-nhsscotland/0072146.gif

http://help.newzie.com/PriorityColorSchema.png

https://upload.wikimedia.org/wikipedia/commons/3/30/Triagemexico.jpg

https://www.tenable.com/products/tenable-sc

The assumption that green implies everything is good, is incorrect in risk management frameworks. Blue is the lowest, often times simply informational in severity.

There are no plans on allowing users to modify colors. The CSS for the UI can be modified and that will be persisted between restarts (not upgrades) and the SVG uses templates. These templates will eventually be modifyable via the UI (alerts use the same template engine). Once template editing is available, you'll be able to modify the SVG colors if you choose.

**Comment by msymons** [comment]
Thanks for the informative links and the explanation.  I think that that will suffice for my audience....  although I may still play with template editing when it is released.
