### ISSUE TITLE
The /api/v1/project endpoint returns 500 when the name query string parameter is provided without excludeInactive

### ISSUE THREAD

**Issue by dc-re** [DependencyTrack/dependency-track#462]
### Current Behavior:
When the `/api/v1/project` endpoint is called passing the `name` parameter and omitting the `excludeInactive` parameter, the server returns 500

### Steps to Reproduce:
Using curl:
curl -X GET "https://DTRACK_HOST/api/v1/project?name=asd" -H  "accept: application/json" -H  "X-Api-Key:  XXXXXXXXXXX"

### Expected Behavior:
The server returns the project or 404, if the project is not found.
Alternatively, if since 3.6.0 `excludeInactive` is mandatory, the server should return 400.

### Environment:
  
  - Dependency-Track Version: 3.6.0
  - Distribution: Docker
  - BOM Format & Version: 1.0
  - Database Server: PostgreSQL
  - Browser: N/A

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by aleproscia** [comment]
I've the same problem, but only if excludeInactive equals false: if true, it works.
[server.log](https://github.com/DependencyTrack/dependency-track/files/3681591/server.log)
