### ISSUE TITLE
Missing java parameters in docker file

### ISSUE THREAD

**Issue by aykutaricioglu** [DependencyTrack/dependency-track#465]
I get an error because there are missing java parameters. I checked from the previous version. I think you should add the following parameters.

ENV JAVA_OPTIONS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xmx4G"

![Screen Shot 2019-10-02 at 16 48 52](https://user-images.githubusercontent.com/9120266/66050158-58f52900-e535-11e9-9752-b04737456f38.png)

**Comment by stevespringett** [comment]
`UseCGroupMemoryLimitForHeap` is deprecated and no longer relevant in newer versions of Java 8. It was an experimental option so `UnlockExperimentalVMOptions` is also no longer required.

Ensure your JVM has a minimum of 4GB. `Xmx4G` will force the JVM to _think_ it has that much, but if the Docker container isn't allocating it, you'll get OutOfMemory exceptions. At a minimum, Docker should be allocating 4.5GB. Dependency-Track is configured to use 90% of the available RAM of the container.

Keep in mind, that DT will use up to 13GB, so 4GB is the bare minimum necessary. If you need to, modify the run command to include the memory limit.

To allocate 8G for example:
```bash
docker run -d -m 8192m -p 8080:8080 --name dependency-track -v dependency-track:/data owasp/dependency-track
```

**Comment by stevespringett** [comment]
https://docs.dependencytrack.org/getting-started/deploy-docker/
