### ISSUE TITLE
What about exposing "context" in the Dockerfile

### ISSUE THREAD

**Issue by amandel** [DependencyTrack/dependency-track#467]
### Current Behavior:
To change the web root context using the docker container I have to ovvride the command:

`command: java -XX:MaxRAMPercentage=90.0 -DdependencyTrack.logging.level=INFO -jar dependency-track-embedded.war -context /dtrack`

### Proposed Behavior:
Using a environment variable that is the picked up in would be more convenient:
`context: /dtrack`
Or to make it simple in the Dockerfile sth like a environment variable  `DEPENDENCY_TRACK_OPTIONS` where one could set `-context /dtrack`

**Comment by stevespringett** [comment]
Fair enough - thanks for the suggestion.

**Comment by amandel** [comment]
Thanks for the quick feedback! I just realize the health check defined in the Dockerfile also needs to be adjusted if the context is moved.
