### ISSUE TITLE
Project with name containing # breaks Dtrack with 500 error code

### ISSUE THREAD

**Issue by oxdef** [DependencyTrack/dependency-track#469]
### Current Behavior:
```
An unexpected error occurred. Please contact the Dependency-Track administrator for assistance (500).
``` 
alert for project with name containing `#` character.

### Steps to Reproduce:

1. Navigate to Projects
2. Create project with name `C#`

### Expected Behavior:
Correct processing of project names with any characters

### Environment:
  - Dependency-Track Version: v3.6.0 (Build ID: 80f6955a-3c69-435f-8cce-9b8fa104fe73)
  - Distribution: Docker
  - BOM Format & Version:-
  - Database Server: PostgreSQL
  - Browser: Firefox 69.0.1 / Linux

### Additional details 
500 is generated by request and response to
```
GET https://dtrackhost/api/v1/project?name=C HTTP/1.1
...
HTTP/1.1 500 Server Error
Server: nginx
Date: Fri, 04 Oct 2019 15:34:37 GMT
Content-Length: 0
Connection: keep-alive
```
It may be because of absence of correct encoding somewhere in UI/JS + API should correctly process invalid params.

**Comment by stevespringett** [comment]
Thanks for the report. Confirmed this is an issue.
