### ISSUE TITLE
About Ios Support 

### ISSUE THREAD

**Issue by aykutaricioglu** [DependencyTrack/dependency-track#471]
Hello,

Will you provide Ios scan?

**Comment by stevespringett** [comment]
Dependency-Track is ecosystem agnostic, so yes it supports iOS.

**Comment by aykutaricioglu** [comment]
Which tool can scan ios projects? I can not see in the "CycloneDx" repositories.

**Comment by stevespringett** [comment]
And official iOS implementation does not currently exist. For non-official implementations, the OSS review toolkit has a backlog item to support cocoapods.

**Comment by aykutaricioglu** [comment]
Will "CycloneDx" get this feature? 

You talk about this app right? "https://github.com/heremaps/oss-review-toolkit"

**Comment by stevespringett** [comment]
Closing
