### ISSUE TITLE
Invalid compressed (gzip) body in response from DTrack API

### ISSUE THREAD

**Issue by oxdef** [DependencyTrack/dependency-track#474]
### Current Behavior:
Get response like
```
HTTP/1.1 200 OK
Date: Wed, 09 Oct 2019 12:32:44 GMT
Content-Type: application/json
X-Powered-By: Dependency-Track v3.6.0
Cache-Control: private, max-age=0, must-revalidate, no-cache
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET POST PUT DELETE OPTIONS
Access-Control-Allow-Headers: Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *
Access-Control-Expose-Headers: Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 3600
Content-Encoding: gzip
Content-Length: 20

�
```
Pay attention to the value of `Content-Length` header. Compressed value of e.g.`{"token":"f02451d3-e774-402a-a1ef-da61da7686ae"}` can't be so small
```python
>>> import gzip
>>> s_in = b'{"token":"f02451d3-e774-402a-a1ef-da61da7686ae"}'
>>> len(s_in)
48
>>> len(gzip.compress(s_in))
68
```

### Steps to Reproduce:
Send correct HTTP request for BOM uploading to API `/api/v1/bom` with header `Accept-Encoding: gzip`

### Expected Behavior:
Correct value for compressed response body

### Environment:
  - Dependency-Track Version: 3.6.0

### Additional information:
 - Could be connected with https://github.com/DependencyTrack/dependency-track/issues/392
 - Such behaviour is default for HTTP client in Go. See https://golang.org/pkg/net/http/#Transport (`DisableCompression`)

>  // DisableCompression, if true, prevents the Transport from
>  // requesting compression with an "Accept-Encoding: gzip"
>  // request header when the Request contains no existing
>  // Accept-Encoding value. If the Transport requests gzip on
>  // its own and gets a gzipped response, it's transparently
>  // decoded in the Response.Body. However, if the user
>  // explicitly requested gzip it is not automatically
>  // uncompressed.

**Comment by stevespringett** [comment]
Is the content length accurate if accept-encoding is not specified?

**Comment by oxdef** [comment]
> Is the content length accurate if accept-encoding is not specified?
Yes. Also important that this bug is exactly about `Accept-Encoding: gzip` (*only `gzip` is specified*)
