### ISSUE TITLE
Vulnerable .NET Project Suggestion

### ISSUE THREAD

**Issue by mehmetka** [DependencyTrack/dependency-track#479]
Hello,

When i upload bom.xml output of a maven project to Dependency Track, i can see audits but i can't get audits for .NET projects. I've tried for lots of .NET projects but i couldn't get any results.

Could you suggest me to scan a vulnerable .NET project?

Best regards.

**Comment by stevespringett** [comment]
Do any of the .NET components contain known vulnerabilities that OSS Index has identified? If so, then you will see findings in the Audit tab and will be able to audit them. If OSS Index did not find any known vulnerabilities in the components, then you will not see any findings in the Audit tab.

**Comment by fatihersinadim** [comment]
Hi @stevespringett 

https://github.com/rxtur/BlogEngine.NET

https://app.snyk.io/vuln/SNYK-DOTNET-BOOTSTRAP-450234
https://app.snyk.io/vuln/SNYK-DOTNET-JQUERY-60118

I know that the Jquery and Bootstrap versions used in the project are vulnerable. However, after create bom.xml with CycloneDX and uploading it to the Dependency-Track, I see that no issue has been detected. 

Can you check it out if you can?

If I did everything right, we must have a problem on the ASP.NET side. I tested about 15-20 projects, but not one finding was detected.

Kind Regards,

**Comment by stevespringett** [comment]
Can you publish the BOM (or just part of it) that contains the above components?

**Comment by stevespringett** [comment]
Also just for clarification, you’ve enabled OSS Index correct?

https://docs.dependencytrack.org/datasources/ossindex/

**Comment by fatihersinadim** [comment]
I've attached bom.xml file.

[bom.xml.txt](https://github.com/DependencyTrack/dependency-track/files/3733038/bom.xml.txt)

And yes, I configured OSS Index correctly.

Regards,

**Comment by mehmetka** [comment]
Hello again,

I tried 3.6.1 version and activated OSS Index as you mentioned above, apparently problem solved.

Thank you.
