### ISSUE TITLE
Licenses and publisher templates are not properly read on a standalone installation (in tomcat)

### ISSUE THREAD

**Issue by tnm-l** [DependencyTrack/dependency-track#482]
Hi,

I have encountered the following issue with Dependency track:

### Current Behavior:
When running Dependency track in a servlet container such as Tomcat that has been installed in the default location on Windows (C:\Program Files\Apache Software Foundation\Tomcat 9.0) the licenses are not loaded into the database and the logs display an error message about missing publishers templates.

### Steps to Reproduce:
On a Windows machine.
Install Apache tomcat in the default location
Deploy dependency track
Log in and go to the licenses tab: No licenses are displayed.

### Expected Behavior:
On a Windows machine.
Install Apache tomcat in the default location
Deploy dependency track
Log in and go to the licenses tab: Licenses are actually displayed.

### Environment:
  
  - Dependency-Track Version: **3.6.1**
  - Distribution: Traditional WAR
  - BOM Format & Version: Not BOM related
  - Database Server:MSSQL 
  - Browser:  All

### Additional Details:

The issue is caused by the way the path is calculated to the JSON files that contain information about the licenses and to the publisher templates. The path is indeed calculated as an URL encoded one, so Dependency Track tries to find files located under C:\Program%20Files\Apache%20Software%20Foundation\Tomcat%209.0, a location which is reported as not existing by the system.
URL decoding the path solves the issue. I will attach a pull request with the associated changes. I haven't been able to test it in another environment though.

Thanks for your work on this tool in any case.

**Comment by stevespringett** [comment]
Thanks for the PR. This will be included in the next major release.
