### ISSUE TITLE
Dependency Track 3.6.1 is not reporting vulnerabilities in the component

### ISSUE THREAD

**Issue by karunyaj29** [DependencyTrack/dependency-track#487]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
m using latest version of dependency track 3.6.1 embedded war file with postgres as datastore. I have not observed any issues in the log, NVD data feed from 2002 till 2019 got downloaded successfully and even the database seems to be updated with all the CVE Ids.
However when any component or BOM is uploaded with vulnerable components, vulnerabilities are not reported, everytime it shows zero vulnerabilities. Could you please help what might have gone wrong.
I have just changed application.properties file in WEB-INF/classes with database and proxy changes.

### Environment:
  
  - Dependency-Track Version:3.6.1
  - Distribution: Executable WAR 
  - BOM Format & Version: CycloneDx1.1
  - Database Server:  PostgreSQL 
  - Browser: 

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
Dependency-Track no longer performs fuzzy matching against the NVD. So false positive rates are dramatically improved - almost non-existent.

Is OSS Index enabled? If not, enable it. This is required.

Is there a vulnerable component that you know of what isn't being reported? If so, what is the Package URL for the component?

**Comment by karunyaj29** [comment]
I have enabled OSS Index and did the configuration in Analyzers, however i see 
Received unexpected HTTP response 401 Unauthorized 
error and it stopped.
We are running everything behind proxy, is there anything that i need to enable from proxy perspective?

And other than the component vulnerabilities, when i want to check the vulnerabilities against postgresql 9.5.8, it is not reporting any vulnerabilities. Does this also depend on OSS Index?
![image](https://user-images.githubusercontent.com/56876615/67393928-fb4a7e80-f5c0-11e9-8821-e481287f91f2.png)

**Comment by stevespringett** [comment]
Of course, you have to configure proxy settings. DT needs access to a dozen resources on the web.

https://docs.dependencytrack.org/getting-started/configuration/

or if Docker:
https://docs.dependencytrack.org/getting-started/deploy-docker/

**Comment by karunyaj29** [comment]
I have configured proxy details in application.propeties file, my question
is whether we need to whitelist anything for ossindex?

**Comment by stevespringett** [comment]
That would be a question for your IT folks.

**Comment by karunyaj29** [comment]
True. Thank you.

**Comment by karunyaj29** [comment]
Finally i could see the vulnerabilities reported for the 3rd party components used in my project. Thanks for the help.
However to detect the vulnerabilities in Tech stack like postgresql or wildfly, i'm finding that it still shows zero vulnerabilities. In earlier versions i.e., 3.4.1 /3.5.0 i used to just provide component name, version and group vendor and it used to list the vulnerabilties against that version of software..for eg for postgresql 9.5.8 version i have provided these
![image](https://user-images.githubusercontent.com/56876615/67480397-6f4a5c80-f67d-11e9-821a-5775eec0db86.png)
In the latest version of dependency-track do we need to provide any additional details for tech stack components to identify the vulnerabilities?

**Comment by stevespringett** [comment]
Library/frameworks need to use Package URL - which is what you did earlier with the OSS Index integration. 

Assets (operating systems, applications, hardware) need to use CPE. So Postgres needs to have a valid CPE 2.2 or CPE 2.3.

For example:
```
cpe:2.3:a:postgresql:postgresql:9.5.8:*:*:*:*:*:*:*
```

See also: https://docs.dependencytrack.org/datasources/routing/
