### ISSUE TITLE
Executable WAR doesn't work... Embedded WAR works but NVD error is observed

### ISSUE THREAD

**Issue by ParthibanSG** [DependencyTrack/dependency-track#488]
I have an existing tomcat running in my linux box and I copied over dependency-track.war to my webapps folder and WAR exploded. However, when I try to access the dependency track via URL, it doesn't work

http://<server>:8080/dependency-track

I tried the same scenario with embedded war file but executed it under different port. I can login into the dependency track portal however when the database mirroring occurs, i get below error for NVD's

12:26:52.920 ERROR [NistMirrorTask] An error occurred uncompressing NVD payload
java.util.zip.ZipException: Not in GZIP format

Is there any fix or resolution to this or going to be a hotfix

**Comment by stevespringett** [comment]
What version of Dependency-Track are you using?

Does Dependency-Track have access to the Internet?

**Comment by ParthibanSG** [comment]
I tried with both 3.5 as well as 3.6.1 version. Both versions has executable WAR exploded but the webpage is not working

In case of embedded WAR, I deploy it with different port and able to access the webpage

Our server doesn't have access to internet and it goes via proxy and I have set the proxy as well in our server. After proxy set also, executable WAR doesn't give webpage however embedded WAR provides the webpage but with error for NVD alone where it is unable to extract and throws error as "Not a valid GZIP format"

**Comment by stevespringett** [comment]
v3.5.x and previous will no longer work due to changes in the NVD. v3.6.0 or v3.6.1 are required as of October 16th. See https://nvd.nist.gov/general/news/XML-Vulnerability-Feed-Retirement.

If you started with v3.5.x, you may want to delete the ~/.dependency-track/nist directory.

**Comment by ParthibanSG** [comment]
Thanks Steve, I get it to work with 3.6.1 however I get below error during the NVD update

2019-10-29 04:55:04,650 [] ERROR [org.dependencytrack.parser.nvd.NvdParser] An error occurred while parsing: cpe:2.3:a:disney:where\'s_my_water?_free:1.9.1:*:*:*:*:android:*:*
us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid product component: CPE Strings may not contain unquoted question marks except at the beginning or end of the string

Additionally, our artifactory server has all the NVD data, NPM advisories as well. Is there a way where I can configure to retrieve advisories and NVD updates from our own Artifactory server rather than connecting to external links?

**Comment by stevespringett** [comment]
Refer to #468 for the exception. It’s an NVD issue.

There’s about a dozen external services that DT relies on. NVD and NPM are two of them. This cannot be configured. DT cannot run in a closed environment.

**Comment by ParthibanSG** [comment]
Thanks Steve for the assitance... I am all set now
