### ISSUE TITLE
why the docker can't run

### ISSUE THREAD

**Issue by JcQSteven** [DependencyTrack/dependency-track#493]
I tap the commands according to READ.me 

docker pull owasp/dependency-track
docker volume create --name dependency-track
docker run -d -p 8080:8080 --name dependency-track -v dependency-track:/data owasp/dependency-track

but it can't  access to http://my_vurtual_pc_ip:8080
the status code is 503
HOW CAN I RUN THE PROJECT?
This is my docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:27:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:25:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by stevespringett** [comment]
And what is the error message you're receiving? 

https://docs.dependencytrack.org/getting-started/deploy-docker/

Most common issues that I've seen is lack of resources (cpu or ram) or no access to the Internet.

**Comment by JcQSteven** [comment]
I‘ve solved this problem when I changed my virtual machine RAM from 2GB to 4.5 GB. It works .
 i advice that you can notice The Minimum environment in READ.me file . 
Thx
