### ISSUE TITLE
Auto-Create Projects doesn't work - 3.6.1 Version

### ISSUE THREAD

**Issue by ParthibanSG** [DependencyTrack/dependency-track#499]
I am using Dependency Track 3.6.1 and has integrated Jenkins to it as well. I am using API key of Administrator team and has all the permissions. I have enabled "Auto-Create Projects" in Jenkins configuration for dependency track

I initiate a run without specifying project version in the jenkins step dropdown (expecting it to auto-create project automatically) but Jenkins throws error as Project needs to be specified

[DependencyTrack] Publishing artifact to Dependency-Track - http://localhost:8080/dependency-track
[DependencyTrack] Either the projectId or the projectName and projectVersion have to be specified

**Comment by ParthibanSG** [comment]
Is this an issue or I need to specify projectName and version explicitly everytime?

**Comment by stevespringett** [comment]
you have two options:
- specify the uuid of project (will not auto create obviously)
- specify the name and version of the project (it will automatically be created if it doesn't exist)

## Sample pipeline
```groovy
node {
    stage "Publish Dependency-Track results"
    
    dependencyTrackPublisher artifact: 'bom.xml', artifactType: 'bom', projectName: 'Acme Example', projectVersion: '1.0', synchronous: true
    
    //dependencyTrackPublisher artifact: 'bom.xml', artifactType: 'bom', projectId: '3a38aedf-e9e9-4e0a-8913-2d99951aa76d', synchronous: true
}
```

## Console output
```
Entering stage Publish Dependency-Track results
Proceeding
[Pipeline] dependencyTrackPublisher
[DependencyTrack] Publishing artifact to Dependency-Track - http://192.168.1.16:8080
[DependencyTrack] The artifact was successfully published
[DependencyTrack] Polling Dependency-Track for BOM processing status
[DependencyTrack] Looking up id of newly created project
[DependencyTrack] Processing findings
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

The projectName and projectVersion can obviously be variables injected from your build as well.

**Comment by ParthibanSG** [comment]
Thanks @stevespringett this looks fine for me
