### ISSUE TITLE
Vulnerable .Net components missing in DT

### ISSUE THREAD

**Issue by shounakitraj** [DependencyTrack/dependency-track#501]
Hi Steve,

As a part of SCA we are using DT for tracking the vulnerabilities. We have application written in .Net.

I have created BOM file using **cyclonedx-dotnet** by providing sample .sln to it. Now when I uploaded the bom file to DT I thought DT will list down all the known vulnerabilities of the components those are part of bom.xml file.

But somehow it is missing few libraries (Which atleast I know are vulnerable versions, not sure if there any other these). For example bootstrap or JQuery.

I have Enabled OSS Index also and using DT version v3.6.1 as mentioned in #479 
Following is part of bom.xml file for bootstrap 3.3.5 component (https://snyk.io/test/npm/bootstrap/3.3.5).

```
     <component type="library">
      <name>Bootstrap</name>
      <version>3.3.5</version>
      <description><![CDATA[Bootstrap framework in CSS. Includes fonts and JavaScript]]></description>
      <licenses>
        <license>
          <url>https://github.com/twbs/bootstrap/blob/master/LICENSE</url>
        </license>
      </licenses>
      <copyright>Copyright 2015</copyright>
      <purl>pkg:nuget/Bootstrap@3.3.5</purl>
      <externalReferences>
        <reference type="website">
          <url>http://getbootstrap.com</url>
        </reference>
      </externalReferences>
    </component>
```

Also the DT log shows where I have put the correct API username and API key.

`17:16:50.078 WARN [OssIndexAnalysisTask] Received unexpected HTTP response 400 Bad Request`

Let me know if you require any more information from my side

**Comment by stevespringett** [comment]
False negatives from OSS Index should be reported here: 
https://ossindex.sonatype.org/doc/report-vulnerability

For reference, OSS Index is reporting vulnerabilities in:
`pkg:npm/bootstrap@3.3.5`

but not:
`pkg:nuget/Bootstrap@3.3.5`

**Comment by shounakitraj** [comment]
Interestingly OSS is not reporting vulnerablities in
`<purl>pkg:nuget/bootstrap@3.3.5</purl>`

I have tried this as well.

**Comment by msymons** [comment]
@shounakitraj, the direct link for reporting false negatives is here:

https://github.com/OSSIndex/vulns

Issue reporting is based on simple templates and is easy to use.

The response is normally pretty quick and Dependency-Track then starts reporting the 
threats as it ingests the newely changed  data... although there can be a delay whilst changes are propagated "through the pipeline".  Bottom line... once OSS Index make their change you won't have to do a thing in DT.

**Comment by shounakitraj** [comment]
Thank you @msymons and @stevespringett . I will report in OSSIndex.

But can you please also help me on the log message I can see in DT logs:

`17:16:50.078 WARN [OssIndexAnalysisTask] Received unexpected HTTP response 400 Bad Request`

Let me know if I am missing something.

**Comment by msymons** [comment]
Not sure about the HTTP 400.  But for bootstrap vulnerabilities, I think that the problem may be one of case-sensitivity.

OSS Index gives vulnerabilities for:

[pkg:nuget/bootstrap@3.3.5](https://ossindex.sonatype.org/component/pkg:nuget/bootstrap@3.3.5) (although you said in a comment that you tried this without success).

...but not for:

[pkg:nuget/Bootstrap@3.3.5](https://ossindex.sonatype.org/component/pkg:nuget/Bootstrap@3.3.5)

...and it's the latter purl that appears in the BOM quoted above.

**Comment by shounakitraj** [comment]
Yes, that is strange that I am not able to get expected results even with pkg:nuget/bootstrap@3.3.5

**Comment by stevespringett** [comment]
Links to issues:
https://github.com/OSSIndex/vulns/issues/49
https://github.com/OSSIndex/vulns/issues/48
