### ISSUE TITLE
How to get NVD vulnerabilities in 3.6.1?

### ISSUE THREAD

**Issue by Zamlox** [DependencyTrack/dependency-track#505]
I have installed dependency-track 3.6.1 using docker container and although internal analyzer is enabled, I don't get NVD vulnerabilities. Only NPM vulnerabilities.
In log file I can see entries like:
```
17:21:36.633 INFO [NistMirrorTask] Using cached version of nvdcve-1.0-2018.json.gz
17:21:36.753 INFO [NistMirrorTask] Using cached version of nvdcve-1.0-2018.meta
17:21:36.873 INFO [NistMirrorTask] Using cached version of nvdcve-1.1-2018.json.gz
17:21:36.996 INFO [NistMirrorTask] Using cached version of nvdcve-1.1-2018.meta
17:21:37.117 INFO [NistMirrorTask] Using cached version of nvdcve-1.0-2019.json.gz
17:21:37.238 INFO [NistMirrorTask] Using cached version of nvdcve-1.0-2019.meta
17:21:37.357 INFO [NistMirrorTask] Using cached version of nvdcve-1.1-2019.json.gz
17:21:37.485 INFO [NistMirrorTask] Using cached version of nvdcve-1.1-2019.meta
17:21:37.609 INFO [NistMirrorTask] Using cached version of nvdcve-1.0-modified.json.gz
17:21:37.734 INFO [NistMirrorTask] Using cached version of nvdcve-1.0-modified.meta
17:21:37.854 INFO [NistMirrorTask] Using cached version of nvdcve-1.1-modified.json.gz
17:21:37.974 INFO [NistMirrorTask] Using cached version of nvdcve-1.1-modified.meta
```
I checked also VULENRABILITY table in database and no records with source NVD.
How can I fix that ?
Thanks.

**Comment by stevespringett** [comment]
Enable OSS Index. 

See also https://docs.dependencytrack.org/analysis-types/known-vulnerabilities/

**Comment by RaphC** [comment]
Is this a change between 3.5.1 and 3.6.1 ?

**Comment by stevespringett** [comment]
OSS Index was always disabled by default. However, the embedded Dependency-Check instance which used fuzzy matching which resulted in a lot of false positives, was removed. All components now need a valid Package URL and/or CPE in order to be analyzed. 

https://docs.dependencytrack.org/changelog/

**Comment by RaphC** [comment]
thank you

**Comment by Zamlox** [comment]
I have added CPE for some components and now I have also NVD vulnerabilities.
Thank you for your help.
