### ISSUE TITLE
DTrack not displaying vulnerable components

### ISSUE THREAD

**Issue by nhtones** [DependencyTrack/dependency-track#506]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
After submitting a CycloneDX 1.1 BOM to DTrack, via Jenkins plugin,  no vulnerable components are reported.  Dependency check analysis carried out during maven build for the same project identifies 18 vulnerable components.

### Steps to Reproduce:
Configured jenkins build to publish BOM to dtrack.
Maven build using cyclonedx-maven-plugin:1.4.1:makeAggregateBom creates bom.xml
bom.xml transferred to DTrack for analysis

### Expected Behavior:
DTrack analysis returns same findings as dependency check task.

### Environment:
  
  - Dependency-Track Version: 3.6.1
  - Distribution:Executable WAR 
  - BOM Format & Version: Cyclone DX 1.1
  - Database Server: Postgres
  - Browser: Chrome

### Additional Details:
No errors are reported in dtrack logs

2019-11-08 09:40:31,546 [] INFO [org.dependencytrack.tasks.BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: c86550e2-fef7-48df-8c32-311b1bc900e5
2019-11-08 09:40:35,779 [] INFO [org.dependencytrack.tasks.BomUploadProcessingTask] Processed 168 components uploaded to project c86550e2-fef7-48df-8c32-311b1bc900e5
2019-11-08 09:40:35,985 [] INFO [org.dependencytrack.tasks.scanners.InternalAnalysisTask] Starting internal analysis task
2019-11-08 09:40:35,991 [] INFO [org.dependencytrack.tasks.scanners.InternalAnalysisTask] Internal analysis complete
2019-11-08 09:40:35,994 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update for project: c86550e2-fef7-48df-8c32-311b1bc900e5

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by nhtones** [comment]
To add a further example dependency check:
![image](https://user-images.githubusercontent.com/14176078/68467851-da179e00-020e-11ea-8f3b-882fd7811745.png)

DTrack vulnerability database:
![image](https://user-images.githubusercontent.com/14176078/68467903-f0255e80-020e-11ea-8ace-e346fd569e85.png)

DTrack project dependency:
![image](https://user-images.githubusercontent.com/14176078/68467988-12b77780-020f-11ea-80cb-e6bbbdd88a60.png)

**Comment by nhtones** [comment]
Analysing the bom.xml the boostrap component has the following entry:

 <component type="library">
            <group>org.webjars</group>
            <name>bootstrap</name>
            <version>3.3.7-1</version>
            <description>WebJar for Bootstrap</description>
            <scope>required</scope>
            <hashes>
                <hash alg="MD5">2985df3d6a406b16d5119e584ab03257</hash>
                <hash alg="SHA-1">990657dc94f7921d46aae4e54d46ab76a4d1c3b0</hash>
                <hash alg="SHA-256">4d6718bf7cbcb1c827b68dd2b7bc38fa5344fa2e1611d7701e09f4f38f4d72f0</hash>
                <hash alg="SHA-384">a2c78849583adf892134c9c3192cecef35509a94bf89ec676f69453658dfafce6fedbb6b2a832e86f21fdb6b633ddbdf</hash>
                <hash alg="SHA-512">f3888f6a633f32fc2c70ed995391abc012b9b9d88b48537c54ed309abf04a1d1709ec13ea61638b27c4077cf4f9aaaffd0704c68712483517b36f5d88be6922f</hash>
            </hashes>
            <licenses>
                <license>
                    <id>Apache-2.0</id>
                </license>
            </licenses>
            <purl>pkg:maven/org.webjars/bootstrap@3.3.7-1?type=jar</purl>
        </component>

The hashes reported here are different to the dependency-check hashes for the bootstrap JS files.

**Comment by stevespringett** [comment]
Ensure that OSS Index is enabled. If it’s enabled and working correctly, report false negatives to https://github.com/OSSIndex/vulns

**Comment by nhtones** [comment]
Hi.  Thanks @stevespringett it looks like enabling OSS Index has resolved this.

**Comment by nhtones** [comment]
Apologies this is now reporting some vulnerabilities but not any related to jquery and bootstrap webjars.  Other jar files such as jackson-databind are being reported on.

**Comment by stevespringett** [comment]
webjars, while a good idea, are poorly implemented as they unnecessarily alter the identifiers of packages from other ecosystems. Thus you loose the ability to inherit risk when analyzing them.

Repackaging packages from other ecosystems, Javascript being the most common, will have this issue. It's also common in NuGet with repackaged Javascript packages for .NET.

To report false negatives in OSS Index, open an issue at https://github.com/OSSIndex/vulns

Once resolved, the jQuery vulns from webjars will show up in Dependency-Track.

**Comment by nhtones** [comment]
@stevespringett thanks again for the advice.

I think I see now what you are saying.  The webjar provided version of jquery (org.webjars-jquery-3.4.1.jar) will have a different hash to that noted in the vulnerability database for jquery.min.js.  As such, it will not be detected as being present in the application.  Is that correct?

Raising a false negative with OSSIndex I would provide them with the hashes necessary to identify org.webjars-jquery-3.4.1.jar?  Do you know if the hashes created by CycloneDX for org.webjars-jquery-3.4.1.jar would be unique for my installation?

**Comment by stevespringett** [comment]
Actually, its a bit simplier than that. OSS Index uses Package URL.

In the case of jQuery, version 3.4.1 currently doesn't have any known vulnerabilities, but Bootstrap 3.3.7 does. The false negatives in the webjars distribution of bootstrap should be reported to OSS Index.

## jQuery 3.4.1
NPM identifier:
```
pkg:npm/jquery@3.4.1
```

Webjars (Maven) identifier:
```
pkg:maven/org.webjars/jquery@3.4.1
```

OSS Index URLs
- https://ossindex.sonatype.org/component/pkg:npm/jquery@3.4.1
- https://ossindex.sonatype.org/component/pkg:maven/org.webjars/jquery@3.4.1


## Bootstrap 3.3.7
NPM identifier:
```
pkg:npm/bootstrap@3.3.7
```

Webjars (Maven) identifier:
```
pkg:maven/org.webjars/bootstrap@3.3.7-1
```
and
```
pkg:maven/org.webjars/bootstrap@3.3.7
```

OSS Index URLs
- https://ossindex.sonatype.org/component/pkg:npm/bootstrap@3.3.7
- https://ossindex.sonatype.org/component/pkg:maven/org.webjars/bootstrap@3.3.7-1
- https://ossindex.sonatype.org/component/pkg:maven/org.webjars/bootstrap@3.3.7

**Comment by nhtones** [comment]
@stevespringett thanks - I've raised false negatives with OSS Index
