### ISSUE TITLE
I would like to give a folder a path of third party libraries to DT 

### ISSUE THREAD

**Issue by RavindraAnnam** [DependencyTrack/dependency-track#509]
Hi,
I would like to give a folder a path of third party libraries to DT .

I am not able to find any feature in DT and related to BOM  i could not find any utility to create BOM file easily .Please help me .

Regards,
Ravindra.

Groups.io (mailing list)
  - https://dependencytrack.org/discussion

Slack channel
  - https://dependencytrack.org/slack

Slack invite
  - https://dependencytrack.org/slack/invite

Providing as much detail as possible, what is your question?

**Comment by stevespringett** [comment]
If you're looking to scan managed dependencies, it's a simple matter of using the native build plugins that already exist. Refer to https://cyclonedx.org/

For unmanaged dependencies (random files of unknown origin), there isn't a tool out there that I know of that will analyze the files, accurately identify them, and create a resulting BOM. You'll likely need to create this or use a commercial SCA tool capable of binary analysis.

You also might want to look at the Dependency-Check project, as the command line interface utility does some of this. It's evidence-based and will not accurately identify components, but does do a decent job and provides confidence for each piece of evidence. You won't be able to import it into Dependency-Track however.

**Comment by RavindraAnnam** [comment]
Thanks Steve for your reply .I am kind of new to this plugins  and having some knowledge of eclipse .
Can you please give me any manual having steps to use the Maven plugin .

Regards,
Ravindra.

**Comment by stevespringett** [comment]
Instructions for using build plugins, such as Maven, can be on https://cyclonedx.org/

## Creating a BOM
```
mvn org.cyclonedx:cyclonedx-maven-plugin:makeBom
```

## Creating an Aggregate BOM
```
mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
```

**Comment by RavindraAnnam** [comment]
Thanks Steve .
 I am getting below 

error while running the dependency tracker .And how can we check the Scan status like actually started/how much % completed etc..Attaching the error.
[Error.docx](https://github.com/DependencyTrack/dependency-track/files/3844934/Error.docx)

**Comment by stevespringett** [comment]
It appears you're using Tomcat, which works fine, I use it during testing, but I cannot support manual deployments to a servlet container. There are too many runtime/environment variables which can affect performance and stability. So I have no idea why you're getting those error messages. You'll likely have to look at the Tomcat, Windows, and application logs to determine that.

https://docs.dependencytrack.org/getting-started/deploy-war/

Most orgs use the Docker container. It's the simplest to deploy, works consistently regardless of where it's deployed, and is easily supportable.
