### ISSUE TITLE
No licenses detected for dotnet project?

### ISSUE THREAD

**Issue by SS-TT** [DependencyTrack/dependency-track#510]
I'm sorry for posting it here but I don't have access to Slack.
I've ran `CycloneDX` on my solution, and it correctly generated the BOM file.
Here's a sample entry for the generated BOM:

```xml
<component type="library">
  <name>AutoMapper</name>
  <version>8.0.0</version>
  <description><![CDATA[A convention-based object-object mapper.]]></description>
  <licenses>
    <license>
      <url>https://github.com/AutoMapper/AutoMapper/blob/master/LICENSE.txt</url>
    </license>
  </licenses>
  <purl>pkg:nuget/AutoMapper@8.0.0</purl>
  <externalReferences>
    <reference type="website">
      <url>http://automapper.org/</url>
    </reference>
  </externalReferences>
</component>
```

As you can see, license is set for the component, so I'd expect it to be seen on the GUI as well.
This is what I actually see:
![immagine](https://user-images.githubusercontent.com/39333824/68684998-b2f00200-0569-11ea-9edb-82b779f0c55b.png)

The very same situation is for **all** the components that Cyclone detected in my dotnet project.
To double-check I scanned a maven project, and in that case most of the components have their license set (with some exceptions).

I don't think it's an issue on the cyclonedx plugin, because the BOM contains a reference to the license file, so I'd like to understand what's going on.

**Comment by stevespringett** [comment]
The SPDX ID or license name was not included in the BOM. Dependency-Track does not download content from arbitrary URLs in an attempt to identify licenses. That data is expected to be in the BOM.

As noted in https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl,  `licenseUrl` is deprecated. Those packages should be using the `license` element instead. 

The CycloneDX .NET implementation does not download the license file and attempt to identify it. It relies solely on data from the .nuget package.

 Issues with the .NET version should be posted https://github.com/CycloneDX/cyclonedx-dotnet

**Comment by SS-TT** [comment]
Ok, I misunderstood how Dependency-Track works then.
I thought that the link to the license file would be enough.
I'll link this issue on cyclonedx-dotnet, thanks.
