### ISSUE TITLE
Fortify Connection Issue

### ISSUE THREAD

**Issue by ParthibanSG** [DependencyTrack/dependency-track#515]
I have enabled Dependency Track in Fortify portal and configured dependency track as well for fortify integration. Analysis results is not getting uploaded and while parsing the log, I am observing below error. However, with the same user in Fortify portal, I am able to generate the file token but not sure why I am seeing FORBIDDEN in dependency track

WARN [org.dependencytrack.integrations.fortifyssc.FortifySscClient] Fortify SSC Client did not receive expected response while attempting to generate a one-time-use fileupload token. HTTP response code: 403 - Forbidden
ERROR [org.dependencytrack.integrations.fortifyssc.FortifySscClient] An error occurred while communicating with the Fortify SSC integration point
ERROR [org.dependencytrack.integrations.fortifyssc.FortifySscClient] HTTP Status : 403 Forbidden
ERROR [org.dependencytrack.integrations.fortifyssc.FortifySscClient] Request URL : https://<fortifyserver>/ssc/api/v1/fileTokens

Thanks

**Comment by stevespringett** [comment]
So the DT log says that its a permission issue on SSC. What does the SSC log say?

**Comment by ParthibanSG** [comment]
I don't see any log logged in SSC though... It's just DT reporting this issue

**Comment by ParthibanSG** [comment]
I was able to resolve this from Fortify end and now payload is accepted in SSC
