### ISSUE TITLE
dependency check json report

### ISSUE THREAD

**Issue by javixeneize** [DependencyTrack/dependency-track#533]
Hi

Quick question, instead of sending the dependency check xml report, would it work with the json generated by dependency check?

Thanks

**Comment by stevespringett** [comment]
Reports generated from DC 4.x are currently supported, deprecated, and disabled by default in DT 3.6.0. There is no support for reports generated from DC 5.x. Support for importing DC reports will be removed in DT 3.7. There are no plans on supporting the JSON format.

See: #397 and #396
