### ISSUE TITLE
use your own instance of NVD

### ISSUE THREAD

**Issue by javixeneize** [DependencyTrack/dependency-track#534]
Hi

Is there any way of changing the source for the NVD data? In dependency check there are two options, data, to specify the path of the h2 file, and cveUrlBase/cveUrlModified to specify the path to download the database itself

If not, it would be a good addition to the config file

Thanks

**Comment by stevespringett** [comment]
Specifying alternative URLs to the dozen or so external services DT relies on is not currently possible.
