### ISSUE TITLE
Using MySQL throws Exception Creating 'SCAN' Table

### ISSUE THREAD

**Issue by andysenn** [DependencyTrack/dependency-track#539]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
When setting up a new Dependency Track installation and using MySQL, database creation yields an SQLSyntaxErrorException. See full log (attached).

### Steps to Reproduce:
Create an empty MySQL database for Dependency Track
Configure Dependency Track to use the MySQL database
Configure Dependency Track to use the MySQL Connector/J driver
Start Dependency Track

### Expected Behavior:
The database is created without error

### Environment:
  
  - Dependency-Track Version: 3.6.1
  - Distribution: Executable WAR
  - BOM Format & Version: N/A
  - Database Server: MySQL 5.7
  - Browser: N/A

### Additional Details:

I found Issue #111, which seems very similar, but did not find any other useful results. I also reviewed the commit history since the release of 3.6.1 and did not see any changes that looked like they were intended to address this issue.

[dtrack.log](https://github.com/DependencyTrack/dependency-track/files/3929249/dtrack.log)

**Comment by stevespringett** [comment]
Refer to https://docs.dependencytrack.org/getting-started/database-support/

MySQL support is less than ideal as it does non-standard things by default. If the sql_mode isn't correct, it will not work.

**Comment by andysenn** [comment]
@stevespringett,

Thank you for the quick response! I configured MySQL following the instructions on the linked page. Running `SHOW VARIABLES;`, `sql_mode` reports the following:

```
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

All other options are left to their default values.

MySQL version is `5.7.28-0ubuntu0.18.04.4`.

Please let me know if there's any other information that I can provide and I'd be more than happy to do so.

Thank you!

**Comment by andysenn** [comment]
I apologize. I just realized that doesn't match the configuration I specified. I'll follow up on that and get back to you shortly.

**Comment by andysenn** [comment]
@stevespringett,

Alright, truth time. After banging my head against the wall over this for a while now, I just realized that I forgot to restart the mysql service after making the configuration change. I sincerely apologize for wasting your time. It's working now. Thank you for your prompt response and for providing such a valuable tool. Keep up the good work.

Thank you!

**Comment by stevespringett** [comment]
Fantastic. Glad you got it working.
