### ISSUE TITLE
Trigger scan once the CycloneDX BoM is ingested for a project

### ISSUE THREAD

**Issue by pealtrufo** [DependencyTrack/dependency-track#540]
I have Dependency Track running. Internal and NPM analysers are enabled. 

I have ingested a CycloneDX BoM for a demo project and I can see the components loaded. That project uses a vulnerable version of Jackson-databind (2.8.11.1). Now if I search by Jackson, I see the components and the CVEs associated with Jackson, but still 0 vulnerabilities are reported for that project. See screenshot
![Screen Shot 2019-12-06 at 09 12 24](https://user-images.githubusercontent.com/32867433/70313144-f22e0d80-180c-11ea-9150-0554e4058e43.png)

![Screen Shot 2019-12-06 at 09 46 57](https://user-images.githubusercontent.com/32867433/70313403-77b1bd80-180d-11ea-8bce-78389ec99def.png)

I can see in the logs that last night the task to analyse the portfolio was triggered:
> _03:27:50.936 INFO [InternalAnalysisTask] Starting internal analysis task
> 03:27:50.936 INFO [InternalAnalysisTask] Analyzing portfolio
> 03:27:50.937 INFO [NpmAuditAnalysisTask] Starting Node Audit analysis task
> 03:27:50.937 INFO [NpmAuditAnalysisTask] Analyzing portfolio
> 03:27:50.948 INFO [NpmAuditAnalysisTask] Portfolio analysis complete
> 03:27:50.948 INFO [NpmAuditAnalysisTask] Node Audit analysis complete
> 03:27:50.950 INFO [InternalAnalysisTask] Portfolio analysis complete
> 03:27:50.950 INFO [InternalAnalysisTask] Internal analysis complete_

But the time it took to complete suggest me that something is wrong, but not sure where to look. Configuration seems ok. 

Also, I have been trying to use the REST API to trigger a scan for a project where the BOM has been ingested already, but I am not sure what the endpoint is expecting and am receiving this error:
> 09:28:35.677 WARN [ScanUploadProcessingTask] The scan uploaded is not in a supported format. Supported formats include Dependency-Check XML schema v1.x produced by Dependency-Check v1.x - v4.x. Refer to https://docs.dependencytrack.org/best-practices/

Is there anyway that I can trigger an analysis for a project where the BoM has been ingested already?

Thanks

**Comment by stevespringett** [comment]
Ensure that OSS Index is enabled. Use the email address as the api username and specify the token.

https://docs.dependencytrack.org/datasources/ossindex/

There isn't a way to trigger a scan manually. Components are analyzed when BOMs are uploaded and every 24 hours (regardless of whether BOMs are uploaded).

**Comment by pealtrufo** [comment]
Thanks Steve. Is this then the expected behaviour when OSS index is not enabled? Cannot you just use the internal and NPM analysers if you don't have a Sonatype account? 

Thanks

**Comment by stevespringett** [comment]
Yes, expected behavior. The internal analyzer is for performing exact matches for components with valid CPEs.

https://docs.dependencytrack.org/analysis-types/known-vulnerabilities/

It's most useful for assets (applications, operating systems, and hardware components). When dealing with frameworks and libraries, NPM Audit and OSS Index are required.

**Comment by pealtrufo** [comment]
Thanks for confirming Steve. So I understand that when using CycloneDX BoM as the feed for DepTrack, OSS Index has to be enabled and Sonatype account created to support anything different than NodeJS. 

Do you know what project info is shared with Sonatype when performing a scan wit OSS index enabled?

**Comment by stevespringett** [comment]
The only thing that's shared is the group, name, and version of components. It's essentially the exact same information as the NPM Audit analyzer, just in a different format (Package URL).
