### ISSUE TITLE
Prometheus Metrics

### ISSUE THREAD

**Issue by sergioasantiago** [DependencyTrack/dependency-track#553]
Is there any plan to support process/resources usage metrics exported via e.g: Prometheus?

**Comment by stevespringett** [comment]
Dependency-Track is built on https://github.com/stevespringett/Alpine. Support for metrics are on the roadmap for Alpine and are being tracked here: https://github.com/stevespringett/Alpine/issues/22

I do not use Prometheus, but if there's anything special to support it, pull requests are accepted.

**Comment by sergioasantiago** [comment]
I got it.

**Comment by Pamir** [comment]
Prometheus jmx exporter can be used. Does this solve your problem?

**Comment by sergioasantiago** [comment]
Yes indeed it can help. I was just think whether it makes sense to have dedicated implementation embedded in DT service. But for sure jmx exporter makes sense as well.
