### ISSUE TITLE
Project Findings Audited %: Incorrect values (revisited)

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#561]
### Current Behavior:
Project Overview pages display a "Findings Audited %" metric.  This metric seems to be calculated incorrectly.

I have not tested whether the same metric is correct at the portfolio level.

#### Example:

* Audit tab displays 13 vulnerabilities, of which 3 are audited.
* Overview reports count of 10 vulnerabilities (correct)
* Overview reports count of 3 for "Findings Audited" (correct)
* Overview reports that "Findings Audited %"  = 30%  (incorrect).

The actual percentage is 23.07%  ( ((13 - 3)/13)) * 100)

This was previously reported as item 3 in #377 

### Steps to Reproduce:

* Inspect a project that has a number of vulnerabilities.  Audit and supress 1 vulnerability and check that audit % is displayed correctly.
* Repeat for audit of 2 vulnerabilities, etc.
 

### Expected Behavior:
Findings Audited % should display correct metric.

### Environment:
  
  - Dependency-Track Version: 3.7.1
  - Distribution: [ Executable WAR ]
  - BOM Format & Version: CycloneDX 1.1
  - Database Server: [ PostgreSQL ]
  - Browser: Firefox 71.0

**Comment by stevespringett** [comment]
This is fixed in the new frontend
