### ISSUE TITLE
Generated BOM is not showing dependencies as potentially vulnerable 

### ISSUE THREAD

**Issue by MMirabito** [DependencyTrack/dependency-track#565]
Dear all, 

I just started playing around with Dependency-Track. But I believe I may have missed some configuration because it's not behaving as I was expecting it. So I am hoping someone can point out what I am doing wrong. This is what I have done so far: 

- Installed  **Dependency-Track Version  3.7.1**  on my machine as self-contained app I took the defaults 
- Run it and made sure that I can access it:
`java -Xmx8G -jar dependency-track-embedded.war -context /DEPENDECY-TRACK`
- All vulnerability DBs are mirrored and updated
- In my sample Maven project I included:
   - The [cyclonedx-maven-plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin) to generate the BOM.xml 
   - The  [dependency-track-maven-plugin](https://github.com/pmckeown/dependency-track-maven-plugin) to upload the bom.xml directly to the  DependencyTrack server

When I run Maven the BOM.xml is getting generated and is being uploaded to Dependency-Track. See various screenshots below: 
![image](https://user-images.githubusercontent.com/23298288/72211114-addcff80-3493-11ea-855c-d5b911b443c9.png)

I purposely placed a vulnerable jar file as the dependency in order to see if  the would get flagged but it does not appear to. 

`<dependency>
    <groupId>org.apache.struts</groupId>
    <artifactId>struts-core</artifactId>
    <version>1.3.10</version>
</dependency>

`

However, that same dependency appears to be getting flagged with dependency-check see image below of the HTML report:
![image](https://user-images.githubusercontent.com/23298288/72211148-483d4300-3494-11ea-8b50-f3f8e907ffd7.png)

Am I missing something, is the analysis and/or risk flagging delayed ?

Thanks in advance for any guidance,
max

**Comment by stevespringett** [comment]
Enable OSS Index. Refer to https://docs.dependencytrack.org/datasources/ossindex/

**Comment by MMirabito** [comment]
Hi @stevespringett ,

Thanks for pointing out what I neglected to configure 👍 

Thanks,
max

Once configured this what I getting 

![image](https://user-images.githubusercontent.com/23298288/72211467-d667f800-3499-11ea-984f-4cebe90d2440.png)

**Comment by stevespringett** [comment]
Fantastic. Glad it's working.
