### ISSUE TITLE
Multiple BOM into one project

### ISSUE THREAD

**Issue by siewer** [DependencyTrack/dependency-track#571]
Is it somehow possible to upload multiple BOMs into one Dependency Track project? We have multiple projects which are not put as modules in any parent projects but they are logically connected into one application.

I would be great to browse through alert in one namespace.

**Comment by stevespringett** [comment]
Refer to #130 

Uploading multiple BOMs at a single time is currently not supported but is on the roadmap. The more people upvote tickets, the more likely they are to get worked on. PRs also help a lot.
