### ISSUE TITLE
Annotation of latest version is off

### ISSUE THREAD

**Issue by davidkarlsen** [DependencyTrack/dependency-track#576]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:

Shows old version as current when already on newer version

### Steps to Reproduce:
See attachment

### Expected Behavior:
Should be green as current version is latest

### Environment:
  
  - Dependency-Track Version: 3.7.1
  - Distribution: Docker
  - BOM Format & Version: cyclonedx maven plugin, latest
  - Database Server: PostgreSQL
  - Browser: any browser

### Additional Details:
<img width="1635" alt="Screenshot 2020-01-30 at 11 03 07" src="https://user-images.githubusercontent.com/18299/73439870-a309e200-4350-11ea-9445-6dc22961b74d.png">

**Comment by stevespringett** [comment]
Execute https://github.com/DependencyTrack/dependency-track/blob/master/upgrade/3.7.1_and_previous_maven_central_fix.sql against your database to fix.

A minor 3.7.x version will not be released for this, but it has been fixed in master.
