### ISSUE TITLE
Dependency track vs dependency scan reports

### ISSUE THREAD

**Issue by MarkSkillen** [DependencyTrack/dependency-track#604]
Hi, 
I’m noticing a difference between what the OWASP dependency scan reports as vulnerabilities versus what dependency track reports, for the same code base. 
For a particular springboot app using gradle dependency scan reports over 20 vulnerabilities whereas dependency track reports 0 (after uploading the bom).
Would this be expected behaviour and if so how come?
Thanks in advance

**Comment by nhtones** [comment]
Hi @MarkSkillen this may be similar to what I encountered in #506

**Comment by stevespringett** [comment]
Yes that’s expected but also a potential config issue. DC uses fuzzy matching and will generate false positives. DT will not.

Refer to https://docs.dependencytrack.org/odt-odc-comparison/

Also ensure OSS Index is enabled in DT. Refer to https://docs.dependencytrack.org/datasources/ossindex/

**Comment by MarkSkillen** [comment]
Thanks for the input
