### ISSUE TITLE
Dependency Track embedded with embedded H2 db is not finding any vulnarabilities

### ISSUE THREAD

**Issue by RaooIni** [DependencyTrack/dependency-track#606]
Hi,
I downloaded snapshot version and started server  using command  java  -jar dependency-track-embedded.war -port 9090.  I've uploaded bom file created by maven plugin but I do not see any vulnerabilities in the dashboard/project level  but I do see dependencies loaded..

If I use older version I can't even upload bom file because I get  unknown host exception. I see there is an issue already there for this.

Can you provide end to end steps with sample bom file  using embedded war and embedded h2 db?

Thanks
Rao

**Comment by stevespringett** [comment]
Enable OSS Index and reupload bom. 

Refer to the docs: https://docs.dependencytrack.org/analysis-types/known-vulnerabilities/
