### ISSUE TITLE
How modify the time interval for each portfolio scan ? (each hour by default)

### ISSUE THREAD

**Issue by technoo10201** [DependencyTrack/dependency-track#608]
Hello everyone,

I would like to know if there is any way to configure via the UI the time interval for each portfolio scan. I checked in the code and it seems to be hardcoded and not modifiable. 

I see in TaskScheduler.java : 

`
// Creates a new event that executes every 1 hour (3600000) after an initial 10 second (10000) delay
        scheduleEvent(new MetricsUpdateEvent(MetricsUpdateEvent.Type.PORTFOLIO), 10000, 3600000);
`

`
        // Creates a new event that executes every 1 hour (3600000) after an initial 10 second (10000) delay
        scheduleEvent(new MetricsUpdateEvent(MetricsUpdateEvent.Type.VULNERABILITY), 10000, 3600000);
`

Thanks in advance for any help !
Technoo'

**Comment by stevespringett** [comment]
Adjusting the schedule is not currently configurable.
