### ISSUE TITLE
Limit PORTFOLIO alert to project does not work

### ISSUE THREAD

**Issue by NoExitTV** [DependencyTrack/dependency-track#616]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
Have two PORTFOLIO alerts, each limited to a separate project, p1 & p2.
Portfolio alert for p1 is set to NOT notify on BOM_CONSUMED/BOM_PROCESSED. Portfolio alert for p2 is set to alert on everything.

Upload a BoM to p1, and a notification for BOM_CONSUMED & BOM_PROCESSED is sent.
Same behavior on both email & microsoft teams alerts.

### Steps to Reproduce:
Create two projects, p1 and p2.
Create a email/microsoft teams portfolio alert limited to project p1, and select all "Notify On" except BOM_CONSUMED & BOM_PROCESSED.
Create a email/microsoft teams portfolio alert limited to project p2, and select all "Notify On".
Upload a BoM to p1 and notify the alert about BOM_CONSUMED & BOM_PROCESSED still sent out.

### Expected Behavior:
No alert about BOM_CONSUMED & BOM_PROCESSED should be sent out when uploading BoM to p1.

### Environment:
  
  - Dependency-Track Version: 3.7.1
  - Distribution: Docker
  - BOM Format & Version: CycloneDX 1.1
  - Database Server: MSSQL
  - Browser: Edge Chromium

### Additional Details:

Hosted on azure using azure container instances. The DT-container has 2 cores and 8 GB ram.
The database is an Azure SQL database using pricing tier "Standard S1: 20 DTUs"

**Comment by stevespringett** [comment]
Thanks for the report.

**Comment by stevespringett** [comment]
Closing. Fixed in v4.0 - to be released soon.
