### ISSUE TITLE
dependency-track stops with exit status 137

### ISSUE THREAD

**Issue by marioja** [DependencyTrack/dependency-track#618]
Started new dependency-track using documented docker run command.  After a number of minutes (more than 30), it crashed and stopped.

### Current Behavior:
Started new dependency-track using documented docker run command.  After a number of minutes (more than 30), it crashed and stopped.
### Steps to Reproduce:
docker run -d -m 8192m -p 8080:8080 --name dependency-track -v dependency-track:/data owasp/dependency-track

### Expected Behavior:
load the NVD

### Environment:
  
  - Dependency-Track Version:v3.7.1
  - Distribution: Docker
  - BOM Format & Version:
  - Database Server: H2
  - Browser: Edge

### Additional Details:

Dependency-track logfile during run
[dependency-track.log](https://github.com/DependencyTrack/dependency-track/files/4333172/dependency-track.log)

**Comment by stevespringett** [comment]
There are no errors in the dependency-track log. This is likely an environment issue. Was the Docker host able to allocate the full 8G to the container? If not, containers will crash - it;'s expected behavior.

**Comment by marioja** [comment]
There is no memory problem on the host.  It may be that 8192m is now borderline.  The CPE uncompressed dictionary is over 183MB.  I deleted the container, the data/nist folder content and restarted the container with -m 16000m.  Let's see if it works.  How long is the CpeDictionaryParser?

**Comment by marioja** [comment]
This is what I got this time:
```
19:23:21.430 INFO [CpeDictionaryParser] Parsing official-cpe-dictionary_v2.3.xml

19:23:21.431 INFO [CpeDictionaryParser] This may take several minutes

19:36:04.091 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread

javax.jdo.JDODataStoreException: HikariPool-4 - Connection is not available, request timed out after 68117ms.

at org.dependencytrack.parser.nvd.CpeDictionaryParser.parse(CpeDictionaryParser.java:110)

at org.dependencytrack.tasks.NistMirrorTask.uncompress(NistMirrorTask.java:267)

at org.dependencytrack.tasks.NistMirrorTask.doDownload(NistMirrorTask.java:203)

at org.dependencytrack.tasks.NistMirrorTask.getAllFiles(NistMirrorTask.java:112)

at org.dependencytrack.tasks.NistMirrorTask.inform(NistMirrorTask.java:96)

at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

Caused by: java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out after 68117ms.

at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)

at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)

at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)

at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)

at org.datanucleus.store.rdbms.ConnectionFactoryImpl$ManagedConnectionImpl.getConnection(ConnectionFactoryImpl.java:418)

... 11 common frames omitted
```

**Comment by marioja** [comment]
I found out what is happening.  I was actually using a volume mount from the windows host (-v c:/dtrack) and if you look at [Getting started](https://docs.docker.com/docker-for-windows/) under File sharing (about 45% down the page) you will find out that database do not work on volume mounts.  There is possibly a [workaround](which I am going to try).

**Comment by marioja** [comment]
Workaround does not work because the newer versions of Docker for Windows do not provide any way to change how the file systems are mounted.

**Comment by marioja** [comment]
I tried the following command (using docker volumes instead of bind mounts on the host):
```docker run -d -m 16000m -p 8080:8080 --name dtrack -v dtrack:/data owasp/dependency-track```
and it exist with status 137 and these are the last 3 lines from the log:
```
01:03:52.936 INFO [NistMirrorTask] Uncompressing official-cpe-dictionary_v2.3.xml.gz
01:03:53.995 INFO [CpeDictionaryParser] Parsing official-cpe-dictionary_v2.3.xml
01:03:53.995 INFO [CpeDictionaryParser] This may take several minutes
```
Can anyone get this working on Windows 10 1903 in Docker for Windows 2.2.0.4(43472) lastest version?  The only way I can get dependency-track to work is using the dependency-track-embedded.war directly in windows 10 using java -jar.

**Comment by stevespringett** [comment]
Just to verify, you've modified the default value of 2GB that Docker for Windows defaults to, correct?

![settings-resources](https://user-images.githubusercontent.com/3878933/76715896-35492800-66fc-11ea-883c-a5e340d93562.png)

If you don't get an answer here, you might want to check out the Slack channel.
https://dependencytrack.org/slack/invite

**Comment by marioja** [comment]
Doh, no.  This is not obvious.  Did not realize there were such limits.  I had change the number of CPUs.

**Comment by marioja** [comment]
It works.  It may prove useful to put it in the deploy-docker doc page.  Thanks Steve
