### ISSUE TITLE
Executable WAR: Reverse proxy support

### ISSUE THREAD

**Issue by hostalp** [DependencyTrack/dependency-track#620]
Please add a reverse proxy support so that proxied requests can be seen correctly (hosts, port, protocol, secure).
This would be useful for example when the access has to be TLS encrypted and thus some reverse proxy such as Apache or Nginx is added to the front of the application.

In the case of Jetty it's about the [ForwardedRequestCustomizer](https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/server/ForwardedRequestCustomizer.html)
https://www.eclipse.org/jetty/documentation/9.4.x/configuring-connectors.html#_x_forward_for_configuration
This would make use of X-Forwarded request headers that can be then added at the reverse proxy.

### Current Behavior:
Requests are seen as coming from the reverse proxy. This is seen in the audit log for example where it would be particularly useful to have the correct information.
Hosts, port, protocol and possibly isSecure flag (if used) are incorrect (they match how the reverse proxy makes requests towards the application).

### Proposed Behavior:
Requests would be seeen as they appear when reaching the reverse proxy.

**Comment by stevespringett** [comment]
For clarification are you referring to inbound requests from browsers or APIs to the Dependency-Track server, correct?

**Comment by hostalp** [comment]
> For clarification are you referring to inbound requests from browsers or APIs to the Dependency-Track server, correct?

Exactly

**Comment by stevespringett** [comment]
Closing. Implemented in v4.0 - to be released soon.
