### ISSUE TITLE
Upgrade java

### ISSUE THREAD

**Issue by davidkarlsen** [DependencyTrack/dependency-track#627]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
Runs on java8

### Proposed Behavior:
Upgrade to java 11. Java 11 typically runs faster: https://www.optaplanner.org/blog/2019/01/17/HowMuchFasterIsJava11.html

**Comment by stevespringett** [comment]
FYI, in my tests using AdoptOpenJDK 8 vs AdoptOpenJDK 11, 8 is noticeably faster when there's a large amount of tracked objects (GC). This is visible when performing a full mirror of the NVD.

I have not tested 14. It's likely that DT may skip 11 and go directly to 14 if performance has been improved.

**Comment by davidkarlsen** [comment]
I guess that depends on the GC in use - but newer is better :)

**Comment by hostalp** [comment]
I just want to add a note that I performed some brief tests of the curent DT release (3.7.1, executable WAR) with Java 11 (AdoptOpenJDK HotSpot 11.0.6_10) using the PostgreSQL database and it just doesn't even start, it gets blocked somewhere. I didn't explore it in much detail, so don't know where exactly. With the embedded H2 database it starts fine though.

One thing I remember was that it threw a warning:
> WARNING: An illegal reflective access operation has occurred" "java.net.URLClassLoader.addURL(java.net.URL)

On attempt to load the JDBC driver and then made no further (visible) progress. But even if I allowed this (something like `--add-opens=java.base/java.net=ALL-UNNAMED` if I remember that right), though it didn't threw that warning any longer, it still didn't start. Would be worth further investigations.

**Comment by stevespringett** [comment]
@hostalp Please do not use the Alpine property that specifies the location of the database driver. Rather, include the database driver in the classpath when launching Dependency-Track. This is one of the many breaking changes in Java 11.

I believe I have solved the other breaking changes in Alpine already. But a lot of testing is needed.

**Comment by hostalp** [comment]
> @hostalp Please do not use the Alpine property that specifies the location of the database driver. Rather, include the database driver in the classpath when launching Dependency-Track. This is one of the many breaking changes in Java 11.
> 
> I believe I have solved the other breaking changes in Alpine already. But a lot of testing is needed.

Will try. Perhaps You might add an example into the docs, since using the obligate -cp (or -classpath) with -jar doesn't work (with -jar, other classpath settings are ignored). I can rewrite it to `java -cp /opt/dependency-track-embedded.war:/opt/lib/postgresql/postgresql-42.2.11.jar ... alpine.embedded.EmbeddedJettyServer ...` but perhaps You meant another approach.

**Comment by scolytus** [comment]
Please don't skip Java 11 as it's the current LTS release.
Support for Java 14, also with AdoptOpenJDK, ends September 2020.
