### ISSUE TITLE
LDAP configuration and admin access

### ISSUE THREAD

**Issue by jotka** [DependencyTrack/dependency-track#630]
Hi
I've turned on the LDAP integration and I am able to login with my company credentials (with no permissions).

It seems that the LDAP integrations turns off the managed 'admin' account (when I try to login as admin, I'm getting the 'invalid password' message.

Having the LDAP integration off, I can login using the 'admin' password sucessfully, but then I cannot manage LDAP user permissions :)

What are my options now?

**Comment by stevespringett** [comment]
Managed users are always enabled for local authentication fallback. However, if there is a user in the LDAP directory with the name of 'admin', that may cause some issues. If that's the case, create a new managed user with all permissions that is named something that does not conflict with anything in the LDAP directory.

**Comment by jotka** [comment]
actually, I've tried that by creating new administrative user with a login name that's for sure not in LDAP. The fallback doesn't work. All I got is 'invalid password' when I turn on the LDAP integration...

**Comment by jotka** [comment]
Ok solved now.  It seems that when using the embedded db there is no fallback to the managed accounts. All works with remote Postgres.
