### ISSUE TITLE
Lastest docker image produces an empty dark screen at the DT url

### ISSUE THREAD

**Issue by marioja** [DependencyTrack/dependency-track#631]
The defect may already be reported! Please search for the defect before creating one.
I took the lastest image for owasp/dependency-track:latest and when restarted the container which used to work with the previous image (3.7.1) I get an empty dark screen.

### Current Behavior:
I get an empty dark screen.

### Steps to Reproduce:
docker-compose up -d

### Expected Behavior:
See the login screen

### Environment:

  - Dependency-Track Version: ? presumably 3.8.0
  - Distribution: docker
  - BOM Format & Version:
  - Database Server: H2
  - Browser: Edge or IE

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
No idea. There have been a number of beta testers using 3.8 snapshots for several months now. I've personally upgraded a few instances from 3.7.x to 3.8 without any issues.

You might want to check the DT logs and see if there are issues during the upgrade. You also may want to clear your browsers cache or try using FireFox or Chrome. No testing has been performed with Microsoft rendering engines, as both Trident and EdgeHTML are deprecated and not supported by DT. Modern Edge uses Chromium which is known to work.

**Comment by marioja** [comment]
Well I think this is exactly it:

We are using this version of Edge:

Microsoft Edge 42.17134.1098.0
Microsoft EdgeHTML 17.17134
