### ISSUE TITLE
Not seeing .dll vulnerabilities in dependency-track

### ISSUE THREAD

**Issue by AidanVincent** [DependencyTrack/dependency-track#638]
Hi Steve 

I have a Jenkins instance with both Dependency Check and Track integrated into my build pipeline.
In my build steps, I create the cyclonedx BOM for the .NET framework projects.
Upload the BOM to Track, it get's injested and analysed - yet it shows no vulnerabilies (but Check does).

Examples of .dlls which show as vulnerable in Check but not Track are:
Microsoft.AspNet.Razor (v1.0.21015.408)
Microsoft.Web.Infrastructure (1.0.0.0)

I have the OSS Index analyzer enabled with a valid API key - which is working.
I am running Track in Docker, same results using docker-compose.
I should point out that I do see some vulnerabilities in projects, from the analyzers NPM and OSSINDEX but nothing for NuGet.

Am I missing something?

**Comment by stevespringett** [comment]
Comparisons between Dependency-Check and Dependency-Track should not be performed. DC uses fuzzy matching which produces false positives by design, DT does not. The results are expected to be different.

Refer to https://docs.dependencytrack.org/FAQ/

**Comment by AidanVincent** [comment]
Thanks for the reply. So if I have the ability to create BOMs for each of my applications - I should use Dependency-Track as the source of truth instead of using Check at all in my pipeline?

**Comment by stevespringett** [comment]
Correct.

**Comment by AidanVincent** [comment]
Perfect. And using CycloneDX's dotnet tool - it shouldn't negatively impact scan results whether the BOMs were created from .NET framework projects instead of Core, correct?

**Comment by stevespringett** [comment]
Correct. Doesn't matter from a Dependency-Track perspective.
