### ISSUE TITLE
Add support for CPAN

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#639]
CPAN doesn't have a direct API, but metacpan provides versioned API access to CPAN data.

Three potential endpoint to integrate with are distribution, release, and modeule.

https://fastapi.metacpan.org/v1/distribution/Moose
https://fastapi.metacpan.org/v1/release/Moose
https://fastapi.metacpan.org/v1/module/Moose

Refer to https://github.com/metacpan/metacpan-api/blob/master/docs/API-docs.md

**Comment by nscuro** [comment]
Removing the milestone for now. Unlikely we can tackle this in 4.6.
