### ISSUE TITLE
LDAP User Provisioning - does not assign user to teams when user added to LDAP group

### ISSUE THREAD

**Issue by fireflycons** [DependencyTrack/dependency-track#643]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:

When a user who has no membership of any LDAP group mapped to teams and then is later added to one of these groups, and the user logs in (after enough time for any directory replication), user's team membership is not updated.

### Steps to Reproduce:

* User who is not a member of any bound LDAP group logs in for the first time
* User is authenticated but sees nothing (expected)
* User is later added to LDAP group
* User logs in again, still sees nothing

A restart of the system was required to get it to rescan group membership and assign user to teams

### Expected Behavior:

At user login, LDAP group membership should be re-evaluated and team membership updated.

### Environment:
  
  - Dependency-Track Version: Latest (as of date of this ticket)
  - Distribution: Docker
  - BOM Format & Version: n/a
  - Database Server: PostgreSQL
  - Browser: Chrome

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
LDAP synchronization occurs every 6 hours. It's not performed on-demand.

https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/tasks/TaskScheduler.java#L57

There is currently no way to manually trigger an LDAP refresh. For large directories, it can be a time-intensive task, which is why its not performed on-demand.

**Comment by fireflycons** [comment]
Thanks for the quick response Steve! I'll accept that as answered and close.

I must point out however that actually setting up LDAP and understanding how it works from the context of the UI was more than somewhat difficult, as documentation is thin on the ground - e.g. the relationship between LDAP users and groups with DT teams, and also which LDAP filters are used when. I resorted to examining DT logs with DEBUG enabled to understand what was going on!

A suggestion. It might be useful to have two base search scopes - one for users and one for groups. The way our directory is configured, and possibly many others is that the users OU and groups OU are both off the root, each having many levels of sub-OUs, therefore all searches have to search the _entire_ directory - and ours is pretty big as I work for a large organisation.
