### ISSUE TITLE
No Proxy Support

### ISSUE THREAD

**Issue by mehmetka** [DependencyTrack/dependency-track#655]
Hi,

When we set https_proxy as environment variable, Dependency-Track uses proxy for both (http and https). How can we split this usage? Or is it possible to split?

We use https_proxy to get updates but when we set proxy then Dependency-Track tries to go to Fortify SSC via proxy, but because of proxy it can't. 

Even if we set no_proxy variable, appearantly Dependency-Track doesn't use it. Is it possible to set no_proxy?

Best regards.

**Comment by stevespringett** [comment]
Proxy support is either enabled or disabled. Dependency-Track does not currently support exclusions for hosts to not use the proxy. Ideally, there would be a configurable option to specify a list of zero or more hosts to exclude from proxy. Support for this does not currently exist

Pull requests are appreciated.
