### ISSUE TITLE
Dependency Track 3.8 - default login admin/admin not working

### ISSUE THREAD

**Issue by kiranabt** [DependencyTrack/dependency-track#656]
Hi,

I have hosted Dependency Tract 3.8 war file on tomcat 8.5. I'm able to get the login page but default credentials admin/admin is not working.

When I look at the login API call it's giving 404 error.

Error :
Message /api/v1/user/login
Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

**[13/Apr/2020:19:09:18 +0530] "POST /api/v1/user/login HTTP/1.1" 404 738**

Thanks,
Kirana

**Comment by stevespringett** [comment]
Upon first login, the admin is required to change the password. If the password has already been changed, there is no way to reset it.

If the server is in production, you'll likely need to run the symetric key through bcrypt to generate a new password and manually modify the database in order to update it. That would likely be the only way to recover an admin password.

If the server is being evaluated (non-prod) and you're using the embedded H2 database (the default), then simply remove the DT data directory. Refer to https://docs.dependencytrack.org/getting-started/data-directory/ for what it contains.

**Comment by stevespringett** [comment]
Also note, it's not possible to support traditional WAR deployments as there are too many environment variables that affect runtime behavior. Docker is highly favored over traditional deployments as the majority of the environment issues are removed from the equation.

**Comment by julienbouchet** [comment]
Hi,

I have the same error using the Docker deployment mode. In fact, the redirection to the login page seems to break the main URL by removing the context. In my case, the URL http://mydomain/dependencytrack moves to http://mydomain/login in the browser which leads to an 404 error for the authentication request.

I notice a browser request to http://mydomain/dependencytrack/static/config.json. The response is a JSON object with the empty attribute API_BASE_URL. I don't know if there is a relation with our problem and how to set a custom value ?

Regards,
Julien.

**Comment by stevespringett** [comment]
@julienbouchet The request to /static/config.json is only used when the frontend is deployed independently from the server. It allows you to specify the URL to the Dependency-Track server if it is deployed elsewhere. The issue of context is documented in #665 

Its unclear why the default credentials are not working as specified in this ticket. I'm not able to reproduce this, and I think it's the first time it's ever been reported.

**Comment by jrobertsz366** [comment]
It also does not work for me.  Why is it so hard to get this tool to work?

**Comment by stevespringett** [comment]
If you deploy the Docker container per the instructions, it will work out-of-the-box. Super simple, works in just a few minutes.

For anything else, you'll likely have environmental issues that need to be met first. One known problem is that Dependency-Track cannot currently be deployed to a non-root context. So deploying the war to /dtrack for example, will not work. This is a known issue #665.

Also note that Trident and EdgeHTML are not supported. Both rendering engines (IE and original Edge) are deprecated and are not tested. They may or may not work. Chromium Edge, Chrome, FireFox, and Safari are all supported.

**Comment by thinksabin** [comment]
Im having the same issue deployed in the tomcat 8.5. 

> the URL http://mydomain/dependencytrack moves to http://mydomain/login in the browser which leads to an 404
i guess it should retain the parent url.

the war is placed in normal standard:
/opt/tomcat/apache-tomcat-8.5.55/webapps/

**Comment by stevespringett** [comment]
@thinksabin as stated previously, this is a known issue. If you deploy manually to Tomcat, then you'll need to deploy to the ROOT context. Simply dropping the war into /webapps/ will not work. Also, consider Docker since all of the environment issues are removed. Future versions of DT will only be available via Docker at some point.

**Comment by jrobertsz366** [comment]
Hi Steve - how do I deploy to ROOT - not sure how to do that.  I am now running in Prod with a new server provided via IT and I need to deploy to Tomcat instead of running the embedded version with Jetty and I am running into the previous error.  Please point me in the correct direction.

**Comment by jrobertsz366** [comment]
I figured this out.  I had to rename ROOT under webapps, restart tomcat,  and then rename the war file as ROOT.war and redeploy it

**Comment by jrobertsz366** [comment]
DT starts on tomcat but there are errors in the logs and importing a bom file never yields any findings even though I know there are some as the same steps via the executable WAR yield findings.  I have tried this on 3 servers and get the same following errors;

catalina.2020-09-15.log:15-Sep-2020 08:06:11.895 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [MVStore background writer nio:C:/Users/SVC-pspccybsec/.dependency-track/db.mv.db] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:


 sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
 sun.nio.ch.FileDispatcherImpl.pread(Unknown Source)
 sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
 sun.nio.ch.IOUtil.read(Unknown Source)
 sun.nio.ch.FileChannelImpl.readInternal(Unknown Source)
 sun.nio.ch.FileChannelImpl.read(Unknown Source)
 org.h2.store.fs.FileNio.read(FilePathNio.java:74)
 org.h2.mvstore.DataUtils.readFully(DataUtils.java:442)
 org.h2.mvstore.FileStore.readFully(FileStore.java:98)
 org.h2.mvstore.Chunk.readBufferForPage(Chunk.java:361)
 org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1214)
 org.h2.mvstore.MVStore.readPage(MVStore.java:2209)
 org.h2.mvstore.MVMap.readPage(MVMap.java:672)
 org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
 org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
 org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
 org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
 org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
 org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
 org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
 org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2802)
 org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3290)

5-Sep-2020 18:30:50.050 WARNING [http-nio-8080-exec-8] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
15-Sep-2020 18:30:50.065 WARNING [http-nio-8080-exec-8] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Thread-24] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 java.util.concurrent.ArrayBlockingQueue.poll(Unknown Source)
 org.dependencytrack.common.HttpClientPool$IdleConnectionMonitor.run(HttpClientPool.java:90)
 java.lang.Thread.run(Unknown Source)
15-Sep-2020 18:30:53.066 INFO [http-nio-8080-exec-8] org.apache.catalina.startup.HostConfig.undeploy Undeploying context []
