### ISSUE TITLE
Triggering Fortify Upload After BOM Uploaded to a project and its analyzing finished

### ISSUE THREAD

**Issue by eyups** [DependencyTrack/dependency-track#671]
Hello,

I know there is Fortify cadence for this in the settings but when I set it to lower values like 1 hour then I see too many artifacts in the Fortify like 24 artifacts in a day. Currently it is set to 3 hours for us and this makes developers wait sometimes 3 hours to see the results.

That's the reason why I am looking for a workaround like triggering fortify upload manually for a project or something else. Do you have any opinions for this situation ?

Thanks.

**Comment by stevespringett** [comment]
There isn't a way in DT to trigger an upload to SSC other than the schedule. As a workaround, you can easily integrate with the DT and SSC API and build your own trigger.

The Dependency-Track findings API is used to generate the file (finding packaging format) which is used to upload to SSC. Both the DT findings API and the SSC artifact upload API are both documented in their respective platforms. You can disable the Fortify SSC integration in DT and still use the findings API and upload the artifact to SSC whenever you want.

**Comment by eyups** [comment]
Hello Steve,

I wasn't aware of Findings API. Thank you very much for your suggestion. I think I will use this way.
