### ISSUE TITLE
Scoped npm packages in purl and NpmAuditAnalysisTask

### ISSUE THREAD

**Issue by scolytus** [DependencyTrack/dependency-track#672]
### Current Behavior:

* scoped packages in npm are defined in purl spec to be represented like this: `pkg:npm/%40angular/animation@12.3.1`
* however, cyclonedx-node-module produced a purl like this: `pkg:npm/angular/%40angular%2Fanimations@9.1.4`
  * see https://github.com/CycloneDX/cyclonedx-node-module/issues/56
* thus dependency track was designed to handle these purls

### Expected Behavior:

* Dependency Track can handle correct npm purls according to purl specification

Up for debate:

* Dependency Track has a strategy to handle already stored purls
* Dependency Track can still ingest SBOMs using the old purls

### Additional Details:

* In [NpmAuditAnalysisTask.java:115](https://github.com/DependencyTrack/dependency-track/blob/158f00a5f3ea37a7486e227d1a4e5f8abdb663ba/src/main/java/org/dependencytrack/tasks/scanners/NpmAuditAnalysisTask.java#L115) only `purl.getName()` is used. This used to work because the scope was included in the name.
* Minor performance thing, just because I've noticed: In [NpmAuditAnalysisTask.java:113](https://github.com/DependencyTrack/dependency-track/blob/158f00a5f3ea37a7486e227d1a4e5f8abdb663ba/src/main/java/org/dependencytrack/tasks/scanners/NpmAuditAnalysisTask.java#L113) only `component.getName()` is used to check if the same package is to be scanned in this iteration. Two packages with the same name from a different scope would lead to an extra request. No need to fix this.

**Comment by stevespringett** [comment]
Closing. Fixed in v4.0 - to be released soon.
