### ISSUE TITLE
Conflicting results of ODT and ODC scan 

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [DependencyTrack/dependency-track#674]
I have a project scanned using both _ODC_ and _ODT_. As you can see in the screenshot below, ODC scan finds 5 vulnerable dependencies.

![image](https://user-images.githubusercontent.com/13638976/81649497-0e2b8000-9439-11ea-8bfb-5380b3045ac5.png)

ODT scan on the other hand, says that 0 vulnerablities where found. 

I understand that ODC and ODT use different ways to generate their BoMs so their results might differ a bit, but I am not sure if finding 0 vulns is correct. Which report is the **valid** one?

(p.s. I also have other projects on ODT that have vulnerable dependencies, and NPM Audit/OSS Index enabled, so finding 0 vulnerabilities is not an analyzers' issue)

**Comment by stevespringett** [comment]
Please refer to https://docs.dependencytrack.org/FAQ/
