### ISSUE TITLE
How to use DependencyTrack with multiple development teams

### ISSUE THREAD

**Issue by chrissike** [DependencyTrack/dependency-track#679]
Dear dependency-track team,
I've already posted this question to the OWASP slack channel but would like to try it here as well.

We're thinking of using DependencyTrack in a large scale enterprise. We would have quite a number of teams working with the tool. As we consider the findings sensitive information we wouldn't want the teams to see each others findings. So far we couldn't find a way of granting permissions on a project/development team level. Now I'm asking myself if it's just some configuration option that I'm missing or if it's a wrong concept to not share this information in between development teams.

Thank you for any hints on this topic!
Best regards
Christina

**Comment by msymons** [comment]
This requirement would be covered by #140, which is assigned to the 3.9 milestone.  ie, not long now, hopefully!
