### ISSUE TITLE
Unit and API Resource Testing

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#68]
The project needs to build up its unit testing and the API testing of its resources.

UI testing will eventually need to be done as well.

All server-side tests should extend BaseTest.

**Comment by adunkey** [comment]
Hi,

Would gladly help on any testing needed.

Thanks,

AD

**Comment by stevespringett** [comment]
Fantastic. Automated unit and integration (API) testing is very much needed.
