### ISSUE TITLE
Internal Validation for external components

### ISSUE THREAD

**Issue by stefanogreg** [DependencyTrack/dependency-track#680]
Hello,
In my project each of the used external dependencies, other than a Vulnerability/Security Assessment shall also go through an "Internal Validation" process which basically states that the given component can be used in the company/project (taking under consideration e.g. known bugs of the component, and other aspects).
Would be possible to implement in some way such additional Validation workflow or "Tag" modules as "Validated" in some way?

I was thinking as a workaround to create an internal Vulnerability e.g. "Internal Verification" and apply by default to all scanned packages so that there will not be the need for an additional workflow but will show up in the currently available reports, is there a way to easily do that?

Thank you very much for your effort in such a great tool!

**Comment by stevespringett** [comment]
There are no plans on creating an approval workflow. Every attempt at creating a 'golden repository' use of components that I've ever seen, has introduced more risk than it solves. 

However, DT will have policy framework in the next release. In v3.9 I think it will likely be scoped to license use, however, component age, known vulnerabilities, purl, etc will all be possible inputs to automated policy evaluation. Multiple policies can exist and different projects can have different policies. See #249 for policy 

Once the project health information in #650 is complete, this could also be incorporated into the policy engine in the future as well. In fact, Microsoft and GitHub are doing some experimental work in this area already - all open source of course, so DT will likely leverage some of the things they're working on. SAP also has some interesting OSS project health risk evaluators on GH.
