### ISSUE TITLE
How to setup LDAP Properly? Getting 401 with no logs to troubleshoot

### ISSUE THREAD

**Issue by mkkeffeler** [DependencyTrack/dependency-track#681]
I am setting dependency track up brand new, have an external microsoft sql database. 

Setup ldap as per https://docs.dependencytrack.org/getting-started/ldap-configuration/ (we are running Red hat directory server, which is just a red hat supported version of 389. 

I can't get the login with ldap to work, and I don't see outbound connections in our firewall to troubleshoot (I know it has access, another app on the same server talks to ldap) and also don
't have connection attempts in the ldap logs showing any failures, additionally the only thing related to ldap that I can get dependency track to log is 

May 20 17:58:53 <server> java[51590]: 17:58:53.603 INFO [LdapSyncTask] Starting LDAP synchronization task
May 20 17:58:53 <server> java[51590]: 17:58:53.604 INFO [UserResource] LDAP user created: <username> by: admin / IP Address: <server ip> / User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KH
May 20 17:58:53 <server> java[51590]: 17:58:53.676 INFO [LdapSyncTask] LDAP synchronization complete

What am I missing here? currently using the executable war file

**Comment by stevespringett** [comment]
When executing DT, enable debug logging. That should provide some good info on what its failing on.

Example:
```sh
java -Xmx8G -DdependencyTrack.logging.level=DEBUG -jar dependency-track-embedded.war
```

**Comment by mkkeffeler** [comment]
That did fix my issue, but have a question about anonymous binding to ldap, in that case, do we need to remove the lines for user name and password or simply leave them empty? pretty sure ive tried both but no luck.

**Comment by stevespringett** [comment]
Not specifying username/password should work.

I honestly haven't tested anonymous binds in a long time. So if it doesn't work, feel free to create a ticket.
