### ISSUE TITLE
No Vulnerabilities found for Jar files or OpenSSL 1.0.2

### ISSUE THREAD

**Issue by jrobertsz366** [DependencyTrack/dependency-track#683]
Hi,

I've installed Dependency Tracker today and I've spent about 5 hours trying to get it to show me the vulnerabilities.  

I have a project with maven dependencies that where imported via an sbom that was generated via the maven plugin.

I also added the openssl 1.0.2 component with the cpe value from NVD.  I know that hast vulnerabilities.

I also enabled SonaType OSS Index with my email address and token.

I can see the vulnerabilities from NPM, NIST, etc, when I click on vulnerabilities. 

When I click on the project I don't see any vulnerabilities.

When I click on the openssl component I also don't see any vulnerabilities.

I know opensl 1.0.2 has vulnerabilities listed in the NVD and I am also surprised that 50+ Jar files don't have a single vulnerability reported.  What gives?

BTW, I also disconnected from my VPN to ensure I had internet access without a proxy.

Attached is the log output.  I am running the tool as embedded.
[dependency-track.log](https://github.com/DependencyTrack/dependency-track/files/4665210/dependency-track.log)

**Comment by jrobertsz366** [comment]
Also, just in case, here is the sbom file I imported.

[bom.zip](https://github.com/DependencyTrack/dependency-track/files/4665213/bom.zip)

**Comment by jrobertsz366** [comment]
Using 3.8 embedded downloaded today.

**Comment by thinksabin** [comment]
did you try uploading the bom.xml file again in the same project?
there is an issue where sometimes vulnerabilities are not being detected in the first project creation.

**Comment by stevespringett** [comment]
According to the log file posted, OSS Index was not enabled at the time the bom was uploaded. If OSS Index is enabled now, try reuploading the bom. If you don't reupload the bom, the entire inventory will be checked every 24 hours. You should see an entry for OssIndexAnalysisTask being executed in the log.

Also, I could not reproduce the OpenSSL 1.0.2 not being flagged for vulns. I used `cpe:2.3:a:openssl:openssl:1.0.2:*:*:*:*:*:*:*` and DT discovered over a hundred vulns.

**Comment by jrobertsz366** [comment]
Thanks Steve.   You are awesome!

**Comment by jrobertsz366** [comment]
Thank you thinksabin.  yes - I tried reuploading the bom.xml file and it worked the second time.  I can see the findings now.

Follow up question:  Does DT need an outbound connection to the internet only to update the KB or does it also need it when I upload a new bom file?

**Comment by thinksabin** [comment]
DT needs some level of internet access to download feeds from nvd, sonatype oss, and even other repository like npm, pypi, etc. the integration to slack and email notification is another stuffs that need internet. You can whitelist those links in the firewall if your environment demands such.

I'm also wondering what would be list of url by defaults to get whitelisted in the tight security environment that might be enough for the proper working of the dt. I guess @stevespringett can point us into the right direction.

**Comment by jrobertsz366** [comment]
Thanks thinksabin!  But do you know, if at the time the bom is imported if dt needs and internet connection?  Technically, it has a current set of local KBs from the analyzers, so I would expect the answer to be no.  I am trying to determine if I need to disconnect my laptop from the VPN every time I import a bom file (temporary workaround until we host DT on a server with the appropriate FW rules).

**Comment by stevespringett** [comment]
### Vulnerability Intelligence
https://nvd.nist.gov
https://registry.npmjs.org
https://ossindex.sonatype.org
https://vulndb.cyberriskanalytics.com

### Repositories
See: https://docs.dependencytrack.org/datasources/repositories/

### Notes
The DT project does not keep a default list of hosts it needs to connect to since the list is dynamic based on the types of services DT requires for individual organizations. Additionally, repositories are added all the time and are customizable by organizations. Several repositories and additional sources of vulnerability intelligence are planned for future releases, so you'll need to pay attention to the change logs and determine if you'll need to update whitelists.

**Comment by stevespringett** [comment]
The only service that has a 'feed' is NVD and npmjs. However, the npmjs feed is not used for vulnerability intelligence. OSS Index, NPM, and VulnDB are all backed by APIs. So the checking is performed via REST. So outbound initiated connections are used throughout the lifecycle of DT. Same for repositories when DT is identifying the latest version of components and other metadata about them. In the future, DT will be adopting NVD APIs as well.

**Comment by jrobertsz366** [comment]
Thanks Steve.

**Comment by thinksabin** [comment]
> Thanks thinksabin! But do you know, if at the time the bom is imported if dt needs an internet connection? Technically, it has a current set of local KBs from the analyzers, so I would expect the answer to be no. I am trying to determine if I need to disconnect my laptop from the VPN every time I import a bom file (temporary workaround until we host DT on a server with the appropriate FW rules).

I dont think you need internet everytime bom is imported. If you know the dt update time then once you have updated db in dt, it should work fine.

**Comment by PenelopeFudd** [comment]
It might be beneficial to pop up a warning if OSS index isn't set up yet, otherwise a person might have a false sense of security.  

Maybe something like [Windows does](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/windows-defender-security-center) when you haven't got a virus scanner set up?
