### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by meetgyn** [DependencyTrack/dependency-track#684]
Good Morning.
I installed Dependency-Track, everything was working, but I couldn't understand its real functionality. For example, do I want to take the xml from openvas and import it, or from nmap does it? I have many customers and would like to create a base of vulnerabilities

**Comment by stevespringett** [comment]
I think the animation on the website describes what DT does best.
https://dependencytrack.org/

DT only accepts software bill of materials documents in CycloneDX or SPDX format.

It is not a vulnerability aggregation platform. It does not have capabilities of ThreadFix, Defect Dojo, Orchestron, or Zero North.
