### ISSUE TITLE
How to Query Dependency Tracker to Extract a Report

### ISSUE THREAD

**Issue by jrobertsz366** [DependencyTrack/dependency-track#685]
GM - Could you please provide me some guidance on how to extract a Dependency Track report for a project? I would like to query the findings via REST or some other API and generate a spread sheet that I can provide to the teams for their projects.

**Comment by stevespringett** [comment]
Depends on what you want in the report. If you only want content from the findings api, then do something like this:

```bash
curl "http://[dtrackserver]:[port]/api/v1/finding/project/[project uuid]" -H 'X-Api-Key: [apikey]'
```

**Comment by jrobertsz366** [comment]
Thanks Steve.  Is project uuid just the name?  If not, how do I retrieve it?

**Comment by jrobertsz366** [comment]
OK - I am using this, but I am getting no response from server.  BTW, when I try any request via the Swagger extension for chrome I get the same response for them:  "no response from server"

**Comment by jrobertsz366** [comment]
Forgot to past the invocation for reference:

C:\Users\crober25>curl "http://localhost:8080/api/v1/finding/project/8e2b19e1-1694-4e99-b603-f71b46a8a1a9" -H "X-Api-Key: nJJ9Sfc5uI4D0Z4OBcTx8j99t557AHuj"

**Comment by stevespringett** [comment]
Firewall perhaps? Not sure how/if Windows blocks localhost. Also, the Swagger extension for Chrome works great. use it all the time with DT, so I know that works as well. Sounds like there are some networking or environmental issues preventing you from connecting.

**Comment by jrobertsz366** [comment]
Well, actually, I just changed the key to a new one, here is the new request:

C:\Users\crober25>curl "http://localhost:8080/api/v1/finding/project/8e2b19e1-1694-4e99-b603-f71b46a8a1a9" -H "X-Api-Key: lA2cQPaYBZqmhq1liOtMAC4d5AqMsp7U"

And I am seeing this on the server side log:

12:22:38.058 INFO [AuthorizationFilter] Unauthorized access attempt made by API Key lA2cQPaYBZqmhq1liOtMAC4d5AqMsp7U to http://localhost:8080/api/v1/finding/project/8e2b19e1-1694-4e99-b603-f71b46a8a1a9

So I think the server is not accepting the key even though the UI is showing that is the new key.

**Comment by jrobertsz366** [comment]
<img width="1031" alt="Capture" src="https://user-images.githubusercontent.com/50830420/82688884-a4c12380-9c27-11ea-8792-67ab41a79e1d.PNG">

**Comment by jrobertsz366** [comment]
![image](https://user-images.githubusercontent.com/50830420/82688919-b3a7d600-9c27-11ea-9699-72b75487068e.png)

**Comment by jrobertsz366** [comment]
Duh!  I needed to add the permissions.  Once I did that it worked.  lol.

![image](https://user-images.githubusercontent.com/50830420/82689585-b7882800-9c28-11ea-8c4a-d7b7f2212fd3.png)
