### ISSUE TITLE
InternalAnalysisTask fails to report any new vulnerability to an existing component

### ISSUE THREAD

**Issue by guidola** [DependencyTrack/dependency-track#691]
### Current Behavior:
When using **CPE** as component identifier and when a new vulnerability appears for an already registered component (always by **CPE**) the system fails to report through any of the configured notification actions the **NEW_VULNERABILITY** notification that one would assume would be triggered by the prior event.

### Steps to Reproduce:
Not manually reproducible. Configure a component based on **CPE** and hope for it to get a new vulnerability reported.

### Expected Behavior:
A notification should be sent for any of the configured methods when the prior behavior is met.

### Environment:
  
  - Dependency-Track Version: 1.38
  - Distribution: Docker
  - BOM Format & Version: Not used for the scope of the defect
  - Database Server: PostgreSQL
  - Browser: Chrome v 81

### Additional Details:

As per [discussion](https://groups.io/g/dependency-track/topic/74456114#122) **a defect has been detected by @stevespringett in the InternalAnalysisTask where that task had not implemented the notification part of the analysis process** and consequently any new vulnerability added to a CPE tracked component would fail to be reported through any of the configured channels.

**Comment by stevespringett** [comment]
Closing. Fixed in v4.0 - to be released soon.
