### ISSUE TITLE
Support for CVE identification of GO lang dependencies 

### ISSUE THREAD

**Issue by mathuriga** [DependencyTrack/dependency-track#694]
Does Dependency Track supportsCVE identification of GO lang dependencies?

I could able to generate BOM file for a dependencies used in a GO lang based project. Once I uploaded this BOM file to DT, will DT perform CVE identification for those dependencies?

**Comment by stevespringett** [comment]
The BOM will contain PURLs for all the components, just like any other language. Assuming OSS Index is enabled, then yes, DT will use OSS Index to identify vulnerabilities in Go modules.

**Comment by mathuriga** [comment]
@stevespringett ,

Thank you for the prompt reply. Now I have enabled the OSS Index with the created free account. When I checked the dependency-track.log file to check whether OSS Index analysis is started or not (To make sure configurations are correct), I couldn't able to find any logs related to this task.

How can I verify this? Please note that I'm using DT V3.7.1

**Comment by stevespringett** [comment]
Sure, just upload a BOM again and that may trigger an analysis. Otherwise, you'll have to wait 24 hours for DT to do its daily analysis of all components.

**Comment by mathuriga** [comment]
@stevespringett,

Thanks for the information and I'm closing this issue.
