### ISSUE TITLE
How to use projects and versions

### ISSUE THREAD

**Issue by gdub** [DependencyTrack/dependency-track#695]
I'm trying to better understand how to make proper use of projects and versions.

Currently, when using the `/api/v1/bom` endpoint to upload new BOMs, I'm supplying `projectName`, `projectVersion`, and `autoCreate: true`.  This results in a new project object created for each version uploaded.

However, my own mental model is similar to the comment at: https://github.com/DependencyTrack/dependency-track/issues/383#issuecomment-554313382, i.e. a project that can have multiple versions, each version having its set of dependencies.  I wouldn't expect every new version to create a new project.

For context, I'm in a development situation where:
* There are multiple deployment environments, e.g. dev, stage, prod
* Every commit to master auto-deploys to dev environment.
* Release/version tags (semver) deploy to stage, then prod.

From what I've gathered reading through documentation and other issues, it seems that it's not recommended to create a project for every build/commit as would be happening in a CD pipeline.  It would be great to have some examples or best practices on how projects/versions are intended to be used (apologies if I've missed this somewhere).

What would be suggested for development environment like the one described above?  For example:
* Should I be using the autocreate to have a new project/version created each commit to master?  E.g. using build ID or commit hash as version.
* Should I only create a project/version for releases?  E.g. `1.2.3`, `1.2.4`.  Seems that here I'd want to cleanup/deactive old versions after a deploy of a new version to production (since I'd only care to see vulnerability information for versions that are actually deployed somewhere).
* Should I create a project/version for each environment (`dev`, `stage`, `prod`) and push BOM updates to the specific project UUIDs when the project is deployed to each environment?  Seems like this would reduce project/version churn, would give you history of the environment, but perhaps would lose the association to version numbers (though, perhaps could use metadata/tagging on the project/version?).

Thank you for your time.

**Comment by stevespringett** [comment]
>Should I be using the autocreate to have a new project/version created each commit to master? E.g. using build ID or commit hash as version.

No. Project versions are intended to keep track of software that represent risk to an organization. If you have multiple versions of something in production or support multiple versions of software, then you should have separate versions for them as they do represent risk to the org. However, in a CI environment, your previous build and the one before that is likely not in production, does not represent risk to the org, yet Dependency-Track is having to calculate metrics for all of these project versions and roll them up to the portfolio level, which consumes a lot of unnecessary resources and makes the portfolio metrics meaningless.

> Should I only create a project/version for releases? E.g. 1.2.3, 1.2.4. Seems that here I'd want to cleanup/deactive old versions after a deploy of a new version to production (since I'd only care to see vulnerability information for versions that are actually deployed somewhere).

Yes, anything that is in production or is supported in any way. Any software (first party or COTS), which represent risk to an org should have its own project version.

> Should I create a project/version for each environment (dev, stage, prod) and push BOM updates to the specific project UUIDs when the project is deployed to each environment? 

Seems unnecessary and prevents you from tracking progress over time. The timeseries metrics are intended to be useful during the lifecycle of the SDLC. If you have separate projects for each phase of the lifecycle, you'll need to string together the metrics and related graphs to make sense of them. I wouldn't advise this approach.

Eventually, each project version will also have tags associated to timestamps. So at any point in time, you'll be able to tag a point in time as build 12345 or dev/stage/prod whatever. The idea is that the tags would appear on the charts when you hover over them. That will be coming in a future release.

**Comment by stevespringett** [comment]
If you have sequential development where you'r constantly releasing but not necessarily deploying, and you only have one version of software in prod at any given time, use a single project version for that. That way you can track a teams progress over time and across multiple releases.

If you need to support multiple versions of the same software, then you'll need to keep individual project versions for them. I recommend using the clone functionality for that and not the autocreate. If you do have multiple versions, then its important to clean up old versions when they no longer represent risk to the org. So when something is no longer supported or is no longer in production, then remove the old projects. This will help keep your portfolio metrics more representative of reality.

**Comment by gdub** [comment]
Thanks for the response, @stevespringett, very helpful.

To solidify my understanding...

So if I only care to track the version in production (only ever a single version in my scenario), then I would have a single project UUID.  Upon a production deployment, say going from current version `1.0` to new version `2.0`, I would use API to:

1. Find project UUID for `name=myapp` and `version=1.0`.
1. Upload new BOM for project UUID.
1. Update project object, change version value from `1.0` to `2.0`.

On the other hand, if the org wanted to track both stage and production environments (again, only one version deployed to each environment), then seems I'd have to use the strategy of creating/maintaining separate project objects for each version (since it's possible that the same version is deployed to both stage and production at the same time).

Do I have that right?

> Eventually, each project version will also have tags associated to timestamps. So at any point in time, you'll be able to tag a point in time as build 12345 or dev/stage/prod whatever. The idea is that the tags would appear on the charts when you hover over them. That will be coming in a future release.

I do like this suggestion of being able to tag project version objects, e.g. with environment=dev/stage/prod.  It would be beneficial to see on the charts, agreed, and I think it would help with project version maintenance. E.g. deploying to prod could do something like:

1. Find any project versions tagged with the target environment, e.g. `prod`, and remove their `prod` tag.
1. Find project version for the version being deployed and tag it with `prod`.
1. Find any project versions not tagged with `dev`, `stage`, `prod`, etc. and mark them inactive.

Actually, looking at the API docs, I guess this sort of tagging is already possible, just not timestamped?

**Comment by stevespringett** [comment]
Correct. Tags are already supported. Multiple tags can be applied to a project version and they are clickable within the UI so you can search for all projects with a specific tag: java, or prod for example.

<img width="661" alt="Screen Shot 2020-06-04 at 6 32 41 PM" src="https://user-images.githubusercontent.com/3878933/83820313-fa6ae680-a691-11ea-8795-34474d81df21.png">

Tagging a point in time however, is not yet supported but will be in the future.
