### ISSUE TITLE
"Warning: An illegal reflective access operation has occurred"

### ISSUE THREAD

**Issue by PenelopeFudd** [DependencyTrack/dependency-track#699]
### Current Behavior:
Jun 09 23:34:18 ip-172-16-197-216 dependency-track[13914]: 06:34:18.259 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: b09d5690-06c9-460f-9794-166b6c3d2b26
Jun 09 23:34:18 ip-172-16-197-216 dependency-track[13914]: WARNING: An illegal reflective access operation has occurred
Jun 09 23:34:18 ip-172-16-197-216 dependency-track[13914]: WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/tmp/jetty-0_0_0_0-8080-dependency-track-embedded_war-_-any-8879153553537000918.dir/webapp/WEB-INF/lib/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
Jun 09 23:34:18 ip-172-16-197-216 dependency-track[13914]: WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
Jun 09 23:34:18 ip-172-16-197-216 dependency-track[13914]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Jun 09 23:34:18 ip-172-16-197-216 dependency-track[13914]: WARNING: All illegal access operations will be denied in a future release

### Steps to Reproduce:
curl  'https://dependency-track.example.com/api/v1/bom' \
    --header 'Content-Type: multipart/form-data' \
    --header 'Accept: application/json' \
    --header 'X-Api-Key: supersecret' \
    -F bom=@bom.xml  \
    -F autoCreate=true \
    -F projectName=foobar \
    -F projectVersion=1

### Expected Behavior:
No warnings

### Environment:
  
  - Dependency-Track Version: 3.8.0
  - Distribution: Executable WAR 
  - BOM Format & Version: CycloneDX 1.0
  - Database Server: H2
  - Browser: curl

### Additional Details:

I'm just learning how to use DT, trying to upload bom.xml files via the API.

**Comment by stevespringett** [comment]
What version of Java is it running with?  Anything higher than 9 isn’t supported.

**Comment by PenelopeFudd** [comment]
Trying it with Java 11, as we're upgrading all our software to latest versions: that's the whole reason we're downloading DT!  :-)

As far as I can tell, the app looks perfect on Java 11: only noticed that warning by accident and thought to help by forwarding it on.  Using openjdk-11-jre-headless:amd64-11.0.7+10-2ubuntu2~18.04.deb on Ubuntu 18.04 on an EC2 instance.

The requirements verifier complained about the memory being too low.  If Java 11 is a problem, maybe add a version check to the verifier?

Thanks!

**Comment by stevespringett** [comment]
Related to #376

**Comment by stevespringett** [comment]
The overwhelming majority of users rely on a Docker which includes the latest Java 8 release with all recent backports and security fixes. Java 11 has not been extensively tested. There are known issues and likely some unknown issues as well as 11 has many breaking changes.

**Comment by PenelopeFudd** [comment]
Ok, thanks for clarifying.
