### ISSUE TITLE
3.8.0 Cannot customize add vulnerability。

### ISSUE THREAD

**Issue by lihaoran93** [DependencyTrack/dependency-track#706]
Version：3.8.0 exevuter War.

Home --> Vulnerabilities ,  The interface has no add button。

![图片](https://user-images.githubusercontent.com/26021760/85101815-daacf400-b235-11ea-864b-7fcd29fd2be6.png)

**Comment by stevespringett** [comment]
The previous jquery based UI had an experimental notice in the upper right of the add vulnerability dialog.

It’s still an experimental and unfinished feature and will change slightly. Progress of the feature can be tracked here https://github.com/DependencyTrack/dependency-track/issues/96

**Comment by lihaoran93** [comment]
This is a nice feature, some popular component's Vulnerabilities not included in these well-known vulnerability libraries
