### ISSUE TITLE
Components - Sort Vulnerabilities by Severity

### ISSUE THREAD

**Issue by ThunderSon** [DependencyTrack/dependency-track#708]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
No sorting behavior exists in the Components' Vulnerability tab on the Severity, like in the Projects tab.

### Proposed Behavior:
Implementation of the severity sorting mechanism as seen in other parts of the project.

**Comment by nscuro** [comment]
Pre v4.11, this was not possible to do since the severity was not stored in the database (https://github.com/DependencyTrack/dependency-track/issues/2474). This has changed as of v4.11, so the enhancement is now unblocked.

**Comment by fupgang** [comment]
This seems to be a simple change in the [frontend](https://github.com/DependencyTrack/frontend), that is toggle the `sortable` field to `true`:
https://github.com/DependencyTrack/frontend/blob/af17196c0144258ceba99b7325a50c91b99fecc7/src/views/portfolio/projects/ComponentVulnerabilities.vue#L102

This can probably be done for other columns, too, e.g. "CWE".

I could create a PR.
Which tests are to be implemented for this change? Frontend and / or API server?
