### ISSUE TITLE
Identify dependency source

### ISSUE THREAD

**Issue by y4ppieflu** [DependencyTrack/dependency-track#709]
Hello! 

I am using Dependency Track v3.8.0 to analyse third-party components, referenced in a large dotnet solution (using cyclonedx-dotnet module). 
Everything works perfectly, except the fact that from Dependency Track interface I cannot find a way to track down a particular .csproj file, in which dependency was introduced. My understanding is that cyclonedx module is handling all .csproj files recursively in a specified directory and it shouldn't be too tricky to enrich bom with a reference to the source file, from which dependency originates.

Is it something that can be achieved?

**Comment by stevespringett** [comment]
Eventually, DT will be able to support all of the 'External References' supported in CycloneDX. CycloneDX support a 'vcs' external reference type which is intended to refer to the location where the source code lives. If the CycloneDX .NET implementation supports this (I don't know if it does or not), then a future version of DT will be able to provide references back to the vcs for each component.

**Comment by y4ppieflu** [comment]
Ok, got it. Thanks for clarifications @stevespringett
