### ISSUE TITLE
MySQL 5.6 is not supported anymore? 

### ISSUE THREAD

**Issue by vsoloviov** [DependencyTrack/dependency-track#710]
Questions may be asked directly on GitHub, but may have a better chance of being discussed by the larger community by posting questions to the official discussion list or Slack channel.

Groups.io (mailing list)
  - https://dependencytrack.org/discussion

Slack channel
  - https://dependencytrack.org/slack

Slack invite
  - https://dependencytrack.org/slack/invite

Providing as much detail as possible, what is your question?
-----

Hello, I'm trying to configure dependency-track (3.8.0) to work with mysql database. 

https://docs.dependencytrack.org/getting-started/database-support/ says mysql 5.6 is supported, but using default settings I can't get it work:
```
09:05:39.073 ERROR [Datastore] An exception was thrown while adding/validating class(es) : Specified key was too long; max key length is 767 bytes
```
What am I doing wrong?
Charset is `latin1` , collation is `latin1_swedish_ci` .

Btw it works on mysql 5.7, but unfortunately it is not an option for me.
I assume default key length in mysql 5.7 is larger, does it mean 5.6 is not supported anymore?
Thank you!

**Comment by vsoloviov** [comment]
I tried to set `set global innodb_large_prefix = 1;` , but started receiving a new error
```
15:39:55.909 ERROR [Datastore] An exception was thrown while adding/validating class(es) : Index column size too large. The maximum column size is 767 bytes.
```

**Comment by vsoloviov** [comment]
If anyone faces same issue, i.e. limited to mysql 5.6 only, I was able to install by creating tables manually before starting DT:

1. You need to run `set global innodb_large_prefix = 1;`
2. Create tables with DYNAMIC row type
```
drop database `dtrack`;
create database `dtrack` character set latin1;
set global innodb_large_prefix = ON;
use `dtrack`
CREATE TABLE `TEAM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `UUID` varchar(36) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TEAM_UUID_IDX` (`UUID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

CREATE TABLE `MAPPEDLDAPGROUP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DN` varchar(1024) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `TEAM_ID` bigint(20) NOT NULL,
  `UUID` varchar(36) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `MAPPEDLDAPGROUP_U1` (`TEAM_ID`,`DN`),
  UNIQUE KEY `MAPPEDLDAPGROUP_UUID_IDX` (`UUID`),
  KEY `MAPPEDLDAPGROUP_N49` (`TEAM_ID`),
  CONSTRAINT `MAPPEDLDAPGROUP_FK1` FOREIGN KEY (`TEAM_ID`) REFERENCES `TEAM` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;
```
3. Start DT.

(That's a reason why it works in mysql 5.7 and doesn't work in mysql 5.6: by defaul, in 5.6 ROW_FORMAT is COMPACT, in 5.7 - DYNAMIC).

**Comment by stevespringett** [comment]
Is there a way to change the default row format to dynamic in 5.6?

DT will perform automatic upgrades including changes to the underlying schema, so you'll likely run into issues with the next version of DT which will include lots of underlying database changes.

**Comment by vsoloviov** [comment]
> Is there a way to change the default row format to dynamic in 5.6?

Nope, this option is available from 5.7

**Comment by vsoloviov** [comment]
> DT will perform automatic upgrades 

We run DT 3.8.0 in docker, I believe it is not automatic, right?

**Comment by stevespringett** [comment]
When a new version of DT is ran against an older DT database schema, it will automatically upgrade the schema. 

You'll still have to `docker pull` the image however. That's not automatic.

**Comment by vsoloviov** [comment]
👍 nice, I misunderstood the context of "automatic", thanks!
