### ISSUE TITLE
How to configure the Dependency-Track behind firewall & keep NVD updated?

### ISSUE THREAD

**Issue by Hsiang-Chih** [DependencyTrack/dependency-track#717]
How to configure the Dependency-Track behind firewall (without direct internet access) & keep the following vulnerabilities updated?

I'm installing the Dependency in a local network which doesn't have internet access. In this scenario, how can I keep the following CVE database updated for the Dependency-Track to scan? Thanks 

- National Vulnerability Database (NVD)
- VulnDB
- Sonatype OSS Index 

https://docs.dependencytrack.org/datasources/nvd/

**Comment by stevespringett** [comment]
You can't. Dependency-Track requires access to the public Internet.

* NVD needs to be mirrored and in the near future, NVD APIs will be used instead
* VulnDB leverages either a bulk download or an API.
* OSS Index uses only an API
* NPM Advisories uses only an API
* All of the configured repositories only use an API

A comprehensive list of URLs does not exist. But you should allow access to the NVD, VulnDB, OSS Index, NPM and all of the repos listed here https://docs.dependencytrack.org/datasources/repositories/

**Comment by Hsiang-Chih** [comment]
Appreciated. Is it possible that I may use another PC with internet access to download those NVD and then import those NVD into the local PC where the Dependency Track installed?

**Comment by stevespringett** [comment]
The NVD is only used for components with CP

**Comment by rajesh2887** [comment]
Hi
i have used this command-line utility to mirror the NVD (CPE/CVE JSON) data from NIST.
https://github.com/stevespringett/nist-data-mirror/.

After mirrored the NVD.. how to connect this with my dependency-track to start scan the vulnerability.

**Comment by stevespringett** [comment]
NVD
