### ISSUE TITLE
Can`t create private Vulnerability

### ISSUE THREAD

**Issue by asking-for-a-friend** [DependencyTrack/dependency-track#720]
Hi All, 
I run dependency-track v3.8. on a Tomcat 9 with a postgres 12 database. 
I try to create a private Vulnerability - but I dont have the "Add Vulnerability" Button. 
Do i have to use a specific version to use private Vulnerability?

**Comment by stevespringett** [comment]
The UI in 3.7.1 and previous states that it's a preview feature and subject to change, which it will.

I've received feedback on the feature and it's planned to be complete in 3.10. 
https://github.com/DependencyTrack/dependency-track/issues/96
