### ISSUE TITLE
DT does not show license version even if bom.xml contains it

### ISSUE THREAD

**Issue by shounakitraj** [DependencyTrack/dependency-track#723]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
DT does not show license information in Project even if the bom.xml contains the license information. Please check following screenshot of DT and entries from bom.xml

![image](https://user-images.githubusercontent.com/25792555/87042208-faba4c80-c210-11ea-8572-d51a10ab23d8.png)

`<?xml version="1.0" encoding="utf-8"?>
<bom version="1" serialNumber="urn:uuid:c7750b1e-ee00-470d-b9fe-e8f17557e402" xmlns="http://cyclonedx.org/schema/bom/1.1">
  <components>
    <component type="library">
      <name>AWSSDK.S3</name>
      <version>3.3.7</version>
      <description><![CDATA[Amazon Simple Storage Service (Amazon S3), provides developers and IT teams with secure, durable, highly-scalable object storage.]]></description>
      <licenses>
        <license>
          <url>http://aws.amazon.com/apache2.0/</url>
        </license>
      </licenses>
      <purl>pkg:nuget/AWSSDK.S3@3.3.7</purl>
      <externalReferences>
        <reference type="website">
          <url>https://github.com/aws/aws-sdk-net/</url>
        </reference>
      </externalReferences>
    </component>
    <component type="library">
      <name>AngleSharp</name>
      <version>0.9.4</version>
      <description><![CDATA[AngleSharp is the ultimate angle brackets parser library. It parses HTML5, CSS3, and XML to construct a DOM based on the official W3C specification.]]></description>
      <licenses>
        <license>
          <url>https://github.com/AngleSharp/AngleSharp/blob/master/LICENSE</url>
        </license>
      </licenses>
      <copyright>Copyright 2015, AngleSharp.</copyright>
      <purl>pkg:nuget/AngleSharp@0.9.4</purl>
      <externalReferences>
        <reference type="website">
          <url>https://anglesharp.github.io</url>
        </reference>
      </externalReferences>
    </component>
    <component type="library">
      <name>Apache.NMS.ActiveMQ</name>
      <version>1.7.2</version>
      <description><![CDATA[The ActiveMQ NMS client is a .NET client that communicates with the ActiveMQ broker.]]></description>
      <licenses>
        <license>
          <url>http://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
      </licenses>
      <purl>pkg:nuget/Apache.NMS.ActiveMQ@1.7.2</purl>
      <externalReferences>
        <reference type="website">
          <url>http://activemq.apache.org/</url>
        </reference>
      </externalReferences>
    </component>
    <component type="library">
      <name>Appium.WebDriver</name>
      <version>3.0.0.2</version>
      <description><![CDATA[Selenium Webdriver extension for Appium.]]></description>
      <licenses>
        <license>
          <url>https://raw.githubusercontent.com/appium/appium-dotnet-driver/master/LICENSE</url>
        </license>
      </licenses>
      <copyright>Copyright 2017</copyright>
      <purl>pkg:nuget/Appium.WebDriver@3.0.0.2</purl>
      <externalReferences>
        <reference type="website">
          <url>https://github.com/appium/appium-dotnet-driver</url>
        </reference>
      </externalReferences>
    </component>
  </components>
</bom>`

### Steps to Reproduce:
Upload above bom file to DT in project, it will get uploaded without license information

### Environment:
  
  - Dependency-Track Version: 3.8.0
  - Distribution: [ Docker | Executable WAR | Traditional WAR ]: Embedded War
  - BOM Format & Version: dotnet-CycloneDX 0.9.0
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]
  - Browser: Google Chrome

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
The BOM does not contain a valid SPDX license ID, only a url to the license file. This is expected behavior. Resolved SPDX licenses will be displayed (with a link to detailed license info) as well as unresolved licenses which have a name. Licenses which only have a URL are unknown and DT does not have logic to remotely fetch the license and attempt to use fuzzy matching to determine what type of license it is. This capability is not in scope for DT and will not be added.

Note that the nuget spec for defining licenseUrl is deprecated and should no longer be used by publishers. Rather, nuget recommends that valid SPDX license IDs or license expressions are used instead. Once publishers adopt these practices, DT will properly display the license information.
https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl

**Comment by shounakitraj** [comment]
Thanks Steve for quick response.

I created this BOM using dotnet-CycloneDX. Do you recommend using any other tool to create BOM. I can also share the the sample .csproj file I am using for creating BOM file.

**Comment by stevespringett** [comment]
If we look at https://www.nuget.org/packages/AngleSharp/0.9.4 as an example, this is a rather old component and uses Nugets legacy licenseUrl property. This component has not been updated to use Nugets new license property, which would solve the problem.

I'd highly recommend using the official .NET implementation that you're already using. I believe this version has been updated to include support for using the GitHub API to help in resolving licenses. 
https://github.com/CycloneDX/cyclonedx-dotnet/pull/39

I'd recommend ensuring you're using the latest version of it and if it's still not resolving licenses, create an issue for the project and see if there's room for improvement.

**Comment by shounakitraj** [comment]
Thanks Steve. When I am trying to use latest dotnet-CycloneDX (0.11.0) version for creating BOM file I am getting following message, so I am using dotnet-CycloneDX (0.9.0) is using:

```
¯ Analyzing: C:\Users\admin\file.csproj
  Getting project references
  No project references found
  1 project(s) found
```
My file.csproj contains following contents:

```
<Project>
  <ItemGroup>
    <!--Set Third party nuget versions-->	
    <PackageReference Include="AngleSharp" Version="0.9.4" />
	<PackageReference Include="Apache.NMS.ActiveMQ" Version="1.7.2" />
    <PackageReference Include="Aspose.BarCode" Version="19.4.0" />
    <PackageReference Include="Aspose.Cells" Version="19.8.0" />
    <PackageReference Include="Aspose.Pdf" Version="19.8.0" />
    <PackageReference Include="Aspose.Words" Version="20.1.0" />
  </ItemGroup>
</Project>
```

**Comment by stevespringett** [comment]
You might want to open an issue with the CycloneDX project. Nothing I can do here.

**Comment by shounakitraj** [comment]
Thanks Steve. I have opened issue in CycloneDX project. https://github.com/CycloneDX/cyclonedx-dotnet/issues/183
