### ISSUE TITLE
How do I upload a set of BOM files via the REST API?

### ISSUE THREAD

**Issue by jrobertsz366** [DependencyTrack/dependency-track#724]
Hi, 

How do I upload a set of BOM files to Dependency Track via the REST API?

Regards,

Joe

**Comment by stevespringett** [comment]
https://docs.dependencytrack.org/usage/cicd/

See also /api/swagger.json on your DT instance.

**Comment by jrobertsz366** [comment]
Hmm...this is not working for me.  I am testing with postman and a PUT via base64 and this is the error I receive:

Illegal unquoted character ((CTRL-CHAR, code 13)): has to be escaped using backslash to be included in string value
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 3, column: 78] (through reference chain: org.dependencytrack.resources.v1.vo.BomSubmitRequest["bom"])

**Comment by jrobertsz366** [comment]
when I base64 encode the file it get broken down into multiple lines at 78 chars each.  Is that a problem?

**Comment by jrobertsz366** [comment]
For this example from the CI/CD page, does the file need to be json?  The bom file is XML.

curl -X "PUT" "http://dtrack.example.com/api/v1/bom" \
     -H 'Content-Type: application/json' \
     -H 'X-API-Key: LPojpCDSsEd4V9Zi6qCWr4KsiF3Konze' \
     -d @payload.json

**Comment by jrobertsz366** [comment]
Not sure how to pass in the base64 content to json

**Comment by stevespringett** [comment]
DT 3.8 and previous only support CycloneDX 1.1 BOMs in XML format.

**Comment by jrobertsz366** [comment]
Ok - so which option should I use via CI/CD to upload the BOM files?

**Comment by jrobertsz366** [comment]
I figure this out and I can upload the JSON via the PUT example if I just keep the base64 string as one long string without CRLF

**Comment by anuragpathak2608** [comment]
I'm using below curl to upload a file to DT

**curl -X "PUT" "http://serveraddress/api/v1/bom" -H 'Content-Type:application/json' -H 'X-API-Key:API_KEY' -d @payload.json**

payload.json data looks like
{

  "project": "ce197a41------",

  "scan": "PD94bWwgdmVyc2lvbj0i---"

}
When I run this curl command executes successfully(no output is shown by the command) but I don't see any data is reflecting in the project.

Am I missing something?
