### ISSUE TITLE
Does DT come preloaded with NVD vulnerabilities or does it have to load them during the first start?

### ISSUE THREAD

**Issue by jrobertsz366** [DependencyTrack/dependency-track#725]
Hi, Does DT come preloaded with NVD vulnerabilities or does it have to load them during the first start?

I just installed it and all I am seeing is the NPM vulnerabilties

**Comment by stevespringett** [comment]
https://docs.dependencytrack.org/getting-started/initial-startup/

**Comment by jrobertsz366** [comment]
Thanks Steve
