### ISSUE TITLE
How do I upload multiple BOM files to a Project?

### ISSUE THREAD

**Issue by jrobertsz366** [DependencyTrack/dependency-track#727]
Hi,

How do I upload multiple BOM.xml files to a project.  I uploaded the first file via the REST API and I end up with 266 dependencies and 13 findings.  I then uploaded a 2nd BOM.xml file and I ended up with 221 dependencies and 0 findings.  If I then upload the first BOM.xml file I am back to 266 dependencies and 13 findings.

I have 4 separate sets of BOM.xml files for the same project (multiple code base builds).  Is it possible to upload all 4 to the same project and aggregate the findings or do I need to create 4 projects?

**Comment by stevespringett** [comment]
You cant. You'll need to merge the BOMs prior to upload and do so in a way that doesn't compromise the bom-ref or the dependency-graph (if they have one). Merging is complicated.

**Comment by stevespringett** [comment]
If you want DT to support merging, please create an enhancement request, get it upvoted, or submit a PR.

**Comment by jrobertsz366** [comment]
Thank you Steve.  How do I submit a ER?  Can the reporting REST API be used to pull the metrics from all 4 projects for all 4 BOMs to generate and aggregate list of TPCs with their licenses and vulnerabilities?

**Comment by stevespringett** [comment]
Eventually, projects aggregation (projects included in other projects) will be possible. But that's likely a few years off. ERs can be created using GitHub issues

**Comment by jrobertsz366** [comment]
Super.  See EH #728.
