### ISSUE TITLE
Using MSSQL overloads SQL server

### ISSUE THREAD

**Issue by gmeks** [DependencyTrack/dependency-track#730]
When i started up Dependacytrack container i noticed that the MSSQL server was using 100% CPU.

### Current Behavior:
Dependacytracker seems to be locked in a loop running the following query:
`(@P0 nvarchar(4000))SELECT 'org.dependencytrack.model.VulnerableSoftware' AS DN_TYPE,A0.CPE22,A0.CPE23,A0.EDITION,A0.ID,A0."LANGUAGE",A0.OTHER,A0.PART,A0.PRODUCT,A0.PURL,A0.PURL_NAME,A0.PURL_NAMESPACE,A0.PURL_QUALIFIERS,A0.PURL_SUBPATH,A0.PURL_TYPE,A0.PURL_VERSION,A0.SWEDITION,A0.TARGETHW,A0.TARGETSW,A0."UPDATE",A0.UUID,A0.VENDOR,A0.VERSION,A0.VERSIONENDEXCLUDING,A0.VERSIONENDINCLUDING,A0.VERSIONSTARTEXCLUDING,A0.VERSIONSTARTINCLUDING,A0.VULNERABLE FROM VULNERABLESOFTWARE A0 WHERE A0.CPE23 = @P0 AND A0.VERSIONENDEXCLUDING IS NULL AND A0.VERSIONENDINCLUDING IS NULL AND A0.VERSIONSTARTEXCLUDING IS NULL AND A0.VERSIONSTARTINCLUDING IS NULL        `

### Steps to Reproduce:
Start a clean install of dependecytrack against mssql

### Environment:
  
  - Dependency-Track Version: 3.8.0
  - Distribution:  Docker
  - BOM Format & Version:
  - Database Server:MSSQL Azure
  - Browser: 

### Additional Details:
This is a clean install from docker.
I also see that it redownloads all external advisories every time i reboot the container, that might be related or a seperate issue.

My suspesion is that this is some sort of background job, it happens with no users active. 

Screenshot of CPU usage:
https://imgur.com/a/JnZC9Iq

Only warning in error log:
2:45:41.421 WARN [Datastore] Default type for java type of java.lang.Float was previously jdbc-type=FLOAT but this is not provided by the JDBC driver! Please report this to the DataNucleus developers
db_1  | 12:45:41.422 WARN [Datastore] Default type for java type of java.lang.Double was previously jdbc-type=FLOAT but this is not provided by the JDBC driver! Please report this to the DataNucleus developers

**Comment by stevespringett** [comment]
Ensure that a persistent data volume is being used. Refer to https://docs.dependencytrack.org/getting-started/deploy-docker/

As stated in the docs, initial startup takes 10-30 minutes so that the contents of the NVD can be properly seeded. So you'll see the same (or similar) queries potentially millions of times. https://docs.dependencytrack.org/getting-started/initial-startup/

**Comment by gmeks** [comment]
Il gladly rerun a test, the longest i left it on was  4-5 hours. It was constantly in 100% load.
Im using docker compose, so it should have a presistent storage.

But i take from your reply that i likly have a issue in my setup around presistent volumes.

**Comment by stevespringett** [comment]
The container could be under resourced as well. The more CPU and RAM you can through at it, the better. Also, performance may be constrained by the host the container is running on.

You might want to check the Slack channel as I know there are others using MSSQL on Azure. They might have some pointers.

**Comment by gmeks** [comment]
I think your suspection that there was something wrong the docker volume is correct. Checking inside the volume it does not contain any files.

It got it working as expected when i defined  ALPINE_DATA_DIRECTORY . Its still using 100% CPU on the SQL server, but its not done with all the  nvdcve data.

But that might be that a 50 DTU on the SQL might be low. Il leave it running for while and see :)

**Comment by sennerholm** [comment]
we had similar problems and first tried to increased the DTU to 800 but then we find out that if we rebuild the index we could lower the DTU usage. We did:
 ```
ALTER INDEX ALL ON BOMS_COMPONENTS REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON COMPONENT REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON COMPONENTANALYSISCACHE REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON COMPONENTMETRICS REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON COMPONENTS_VULNERABILITIES REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON CWE REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON DEPENDENCY REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON DEPENDENCYMETRICS REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON EVENTSERVICELOG REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON LICENSE REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON REPOSITORY_META_COMPONENT REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON VULNERABILITY REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON VULNERABILITYMETRICS REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON VULNERABLESOFTWARE REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
ALTER INDEX ALL ON VULNERABLESOFTWARE_VULNERABILITIES REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
GO
 ```

And after that the DTU usage drop. It seems like the _NistMirrorTask_ is stressing the database, anyone who knows how often it's triggered and if it's possible to trigger in any way?

**Comment by gmeks** [comment]
Since Azure SQL is annoying pain to use, i was unable to check what was going on. 

But my suspesion is that for whatever reason the SQL being generated is not good, when inserting alot of rows usage of bulkinsert with Merge would make this close to instant. 

Hopefully i have chance to look at this later in the authom. And provide more valuable feedback, i will then try @sennerholm  suggestion.

**Comment by SheaFixstars** [comment]
Has there been any update on this. We are seeing the exact same issue as the initially posted SELECT. It is maxing out the MSSQL server calling that SELECT statement about ~15k - 16k times an hour. We are running it though Azure App Services and I have confirmed that the storage is working properly on the docker container. We are running this with a 100 DTU server and it has persisted in this state for a few weeks at minimum.

As this Dependency Track instance only has about 17 projects I am not expecting to see this type of SQL usage. Please let me know what I can provide to help with this issue.

![Screenshot from 2021-11-18 11-35-08](https://user-images.githubusercontent.com/66436076/142508003-1d148a36-7deb-474b-ae8e-e596983349ce.png)
.

**Comment by stevespringett** [comment]
@SheaFixstars are you running v4.3.0 or higher?

**Comment by SheaFixstars** [comment]
@stevespringett I am running v4.3.6

**Comment by stevespringett** [comment]
@SheaFixstars How many total components do you have? And how many of those components have a CPE?

**Comment by sduquette-devolutions** [comment]
We have run into the same high cpu usage issue on an Azure SQL instance and it was also caused by the query identified by @SheaFixstars. One of my colleagues figured out that @P0 in the query is declared as an NVARCHAR and CPE23 is a VARCHAR, a conversion is applied to all the values in the table. By modifying the query you can see that the execution cost is orders of magnitude lower.

![query1](https://user-images.githubusercontent.com/70600710/154129165-08a267a6-15ef-4430-b10f-9b4a1345dc43.png)

As a temporary workaround we converted the field CPE23 in the table to a NVARCHAR, the CPU utilization dropped by about 80%. There appears to be other fields in the table with the same issue so there is likely more performance to be reclaimed.

```
DROP INDEX [VULNERABLESOFTWARE_CPE23_VERSION_RANGE_IDX] ON [dbo].[VULNERABLESOFTWARE];
GO

ALTER TABLE VULNERABLESOFTWARE ALTER COLUMN CPE23 nvarchar(255) NULL;
GO

CREATE NONCLUSTERED INDEX [VULNERABLESOFTWARE_CPE23_VERSION_RANGE_IDX] ON [dbo].[VULNERABLESOFTWARE]
(
	[CPE23] ASC,
	[VERSIONENDEXCLUDING] ASC,
	[VERSIONENDINCLUDING] ASC,
	[VERSIONSTARTEXCLUDING] ASC,
	[VERSIONSTARTINCLUDING] ASC
)
GO
```


![query](https://user-images.githubusercontent.com/70600710/154129216-d12ca1c9-e68e-4bac-9114-1855abcab3f3.png)


![query2](https://user-images.githubusercontent.com/70600710/154129226-e1794a7e-dd89-43ba-ba88-8b64fa429d97.png)

**Comment by stevespringett** [comment]
@sduquette-devolutions Thank you for sharing this research. Those are some incredible numbers.

Dependency-Track does not have direct control over the statements that are executed when the database is created, nor when queries are executed. The column in question is defined by DT to be a VARCHAR. I'm not sure why the query is trying to convert it. All the Datanucleus code for relational databases is located here: https://github.com/datanucleus/datanucleus-rdbms. I'll try to locate a property that controls this.

There are 95 other fields that are defined the same way, including all of the other fields in the VulnerableSoftware class. So there's likely a lot of performance optimizations that can be made.

The question is:
* How do we  optimize performance in a way that is compatible with Datanucleus?
  * That takes into consideration support for multiple database platforms and versions.
  * That does not introduce breaking changes that would affect upgrades.

**Comment by stevespringett** [comment]
This code from the Microsoft JDBC driver looks interesting.
https://github.com/microsoft/mssql-jdbc/blob/03e27bb7fe3edb3ca16f334bc4fe828214e83af3/src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java#L84
https://docs.microsoft.com/en-us/sql/connect/jdbc/reference/setsendstringparametersasunicode-method-sqlserverdatasource?view=sql-server-ver15

So for all JDBC VARCHAR types, the Microsoft JDBC Driver will return an NVARCHAR type by default.

Per https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15, try adding  `sendStringParametersAsUnicode=false` to the JDBC connection string.

**Comment by slavergne-devolutions** [comment]
@stevespringett I think you got it. Talking it over with @sduquette-devolutions and we [found this article](https://vladmihalcea.com/sql-server-jdbc-sendstringparametersasunicode/) which describes this scenario exactly.

Microsoft also recommends the following:
> When working with CHAR, VARCHAR, and LONGVARCHAR data, users can set the connection property sendStringParametersAsUnicode to false for optimal performance gain.
https://docs.microsoft.com/en-us/sql/connect/jdbc/improving-performance-and-reliability-with-the-jdbc-driver?view=sql-server-ver15

We will add `sendStringParametersAsUnicode=false` to the connection string via the `alpine.database.url` of the `application.properties` tomorrow and report back any and all findings.

Before the initial "quick fix/hack" above, the database usage was running at 35-45% CPU on a `General Purpose: Provisioned, Gen5, 2 vCores` ($500 CAD/month).

With the "quick fix/hack" we are now running on 20-25% DTU of a `Standard S1: 20 DTUs` ($39 CAD/month).

If `sendStringParametersAsUnicode=false` works, we will most likely be able to scale down to a `Standard S0: 10 DTUs` ($19 CAD/month).

**Comment by slavergne-devolutions** [comment]
It works across all queries being sent to the SQL Server database. What a difference.

All parameters received from the application are now `varchar`
![image](https://user-images.githubusercontent.com/67292147/154291888-a5a171e2-579d-458c-af80-0ceb3b5effd3.png)

Query plan before/after the change (WOW)
![image](https://user-images.githubusercontent.com/67292147/154292257-cfd1eb60-4d78-4bda-9939-a548d4439ab7.png)

Thank you for the help.

**Comment by stevespringett** [comment]
Thats fantastic. I'm going to add this to the documentation. Thanks for reporting back.

**Comment by DrakezulsMinimalism** [comment]
@sduquette-devolutions @stevespringett Would it be enough to simply update the DB URI in the configuration, or do we have to manipulate the existing SQL tables in some way?

Also, thanks for sharing those improvements!

**Comment by sduquette-devolutions** [comment]
@DrakezulsMinimalism Just changing the connection string is sufficient, no need to modify the tables. You're welcome, glad it helps!

**Comment by stevespringett** [comment]
@DrakezulsMinimalism yes. Updated JDBC connection string is included in the documentation. Simply add `;sendStringParametersAsUnicode=false`.

https://docs.dependencytrack.org/getting-started/database-support/

Closing issue as resolved.

**Comment by DrakezulsMinimalism** [comment]
Thanks both!

I saw the doc, but was not sure if this is something that needs "transitioning" ... not sure how that would be indicated in an "necessary upgrade steps" sections or something.
