### ISSUE TITLE
How can I get a list of components & licenses by project?

### ISSUE THREAD

**Issue by jrobertsz366** [DependencyTrack/dependency-track#732]
Hi,

How can I retrieve a list of components & licenses by project?  I can retrieve a list of components via a /v1/component API call and I can retrieve a list of projects via a /v1/project API call, but how can I get a list of components with their licenses that also includes the project name, project version, and project UUID for each component?

Regards,

Joe

**Comment by stevespringett** [comment]
Refer to `/v1/dependency/project/{uuid}`
