### ISSUE TITLE
Can /v1/component return the full list of components?

### ISSUE THREAD

**Issue by jrobertsz366** [DependencyTrack/dependency-track#733]
Hi,

Can /v1/component return the full list of components?  When I invoke the API call it only returns the components that start with the letter a.

Regards,

Joe

**Comment by stevespringett** [comment]
Results are paginated and limited to 100. Use ?page=x to paginate through results.

Also. Questions should be asked on Slack. Thank you.

**Comment by jrobertsz366** [comment]
Thanks Steve.  Unfortunately, my work place is blocking the use of Slack
