### ISSUE TITLE
Auto-Create from jenkins plugin stopped working

### ISSUE THREAD

**Issue by savek-cc** [DependencyTrack/dependency-track#738]
We've been using the Jenkins integration to auto-create projects (+version) from Jenkins using the format specified in https://github.com/DependencyTrack/dependency-track/issues/499.
This example used to work before upgrading to the current development version (master). Now we get

```
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.DependencyTrack.DependencyTrackPublisher': artifactType
[DependencyTrack] Publishing artifact to Dependency-Track - https://eng-deptrack.intranet.escrypt.com
[DependencyTrack] The specified project could not be found
```
And the project is not created any more for new versions. Using a manual API call with same name, version and bom as well as   "autoCreate": "true" - deptrack accepts the new project (so auto-creation still works when not using the jenkins plugin.

The exact call for the Jenkins plugin currently is 
`dependencyTrackPublisher artifact: 'target/bom.xml', artifactType: 'bom', projectName: 'test-autocreate', projectVersion: 'testing', synchronous: true`

**Comment by stevespringett** [comment]
Jenkins issues need to be created on https://issues.jenkins-ci.org

Additionally, I am personally no longer supporting Jenkins and looking for a new maintainer of the plugin. This was announced multiple times on social media as well as the Dependency-Track Slack channel.

**Comment by savek-cc** [comment]
Thanks for the non answer (as the plugin wasn't changed but apparently the DT-rest-API behaviour did) - maybe also indicate this status on the DP homepage - https://docs.dependencytrack.org/integrations/jenkins/.

**Comment by savek-cc** [comment]
Managed to catch the actual request from Jenkins to DT. The Jenkins Plugin sends a payload with "autoCreate":false explicitly set. So behaviour of DT is fine and probably expected. Will update here if I find a resolution with Jenkins-CI.
