### ISSUE TITLE
Cyclonedx BOMs with the 1.2 schema show BOM format as CycloneDX null

### ISSUE THREAD

**Issue by Ashenmaster** [DependencyTrack/dependency-track#755]
### Current Behavior:
I'm generating a CycloneDX BOM on a JS project using the @cyclonedx/bom npm package, the BOM uses the 1.2 schema, if I then upload it to dependency track it shows the BOM format as `CycloneDX null` on the projects page. Checked the changelog for the most recent release and it doesn't look like this issue has been solved (guessing because the schema was released in May I believe)

### Steps to Reproduce:
1. Generate a 1.2 schema BOM using @cyclonedx/bom npm package
2. Upload this into dependency track (API or UI both have the same result)
3. Wait for the BOM to be processed and refresh the screen

### Expected Behavior:
BOM format to display as CycloneDX 1.2

### Environment:
  
  - Dependency-Track Version: v3.6.1
  - Distribution: Docker
  - BOM Format & Version: CycloneDX 1.2
  - Database Server: PostgreSQL
  - Browser: Chrome

**Comment by stevespringett** [comment]
CycloneDX v1.2 (and the implementations that support it) came out after the release of DT 3.8. As such, CDX v1.2 is not currently supported.

Support for v1.2 has been added to the next release of DT, version 4.0.
https://github.com/DependencyTrack/dependency-track/commit/e2deacd6d57f1a1195ff4acf591becc54b0ef5bd

**Comment by stevespringett** [comment]
Closing. CycloneDX v1.2 support implemented in v4.0 - to be released soon.

**Comment by mhanci92** [comment]
The same issue seems currently to exist/appear with CycloneDX v1.3 and DT's latest version (4.2.2).
