### ISSUE TITLE
Policy: Add support for component age in policy conditions

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#772]
Extend functionality implemented in #83 to support component age in policy conditions.

**Comment by msymons** [comment]
This will be very useful.  Some use cases:

A component can be years old and yet still display the green triangle in DT, indicating the latest version is being used.  Which is correct... but hides the underlying problem, which is that the component is not being maintained or has (say) changed groupId.   A component age policy would catch this.

Latest version of [Apache Commons IO](https://commons.apache.org/proper/commons-io/changes-report.html) is 2.8.0 and DT reports usage is 2.4.  That does not look so bad at first glance.  But 2.4 is coming up for 9 years old.  And that is something that you want to be caught by a policy condition.
