### ISSUE TITLE
Docker Container:Admin Password Not Working

### ISSUE THREAD

**Issue by rc-flexm** [DependencyTrack/dependency-track#819]
There seems to be an issue with the latest docker container, I recently pulled a container and while it allowed a login the first time around and I changed the password- it stopped accepting the password on my subsequent attempts.
So far, I have removed and pulled the container again a couple of times and also have run a system prune for docker and gotten the container back- nothing seems to work and it shows invalid password even on fresh builds.

Was hoping you could help me address this or see what I may have overlooked.

**Comment by stevespringett** [comment]
There are known issues with older versions of FireFox and Edge.
See https://github.com/DependencyTrack/frontend/issues/34

No other known issues exist.

**Comment by rc-flexm** [comment]
Hey Steve,
I've not had any luck with deleting the volume and redeploying it as well. May I request you to take a quick glance through the docker logs I've attached and see if there is something Im missing? Cause to me the logs dont seem to indicate anything wrong other than the fact that the login isnt going through.

[dependency-track-dockerlogs.txt](https://github.com/DependencyTrack/dependency-track/files/5473032/dependency-track-dockerlogs.txt)


![image](https://user-images.githubusercontent.com/73706003/97834499-05d44380-1cfe-11eb-8de1-f4fb74e349a6.png)

**Comment by stevespringett** [comment]
The logs look good to me.

Can you delete the docker volume the container is using please?

Once deleted, start the container again and attach the logs. you should see some entries in the log about keys being generated. If you're using an external database, you'll need to drop all tables from it as well. If using the default H2 database, then deleting the volume will take care of it.

**Comment by rc-flexm** [comment]
I guess something on my system was causing the issue- I restored my system and now it works like a charm!

Thank you for your help! :)
