### ISSUE TITLE
Basic Auth for API

### ISSUE THREAD

**Issue by luhahn** [DependencyTrack/dependency-track#831]
Currently the API requires an generated API key from a team.

Since we want to use Dependency-Track in our Kubernetes cluster and configure it mostly automated, we would need a way to authenticate via basic auth with the default admin user. So the REST API can change the default password, set teams and ldap team mappings.

Would that be possible?

Another option would be setting an environment variable or enable application.properties to set the default admin password. But also then basic auth would be required.

**Comment by nscuro** [comment]
Is keeping state between the requests an issue for your use case? If not, you can do the following:

* Force a password change for `admin`:

```
$ curl \
    -d "username=admin" \
    -d "password=admin" \
    -d "newPassword=admin123" \
    -d "confirmPassword=admin123" \ 
    "$DTRACK_URL/api/v1/user/forceChangePassword"
```

* Login with new creds, acquiring an access token:

```
$ token=$(curl \
    -d "username=admin" \
    -d "password=admin123" \
    "$DTRACK_URL/api/v1/user/login")
```

* Perform your configuration requests using the access token:

```
$ curl -X PUT \
    -H "Authorization: Bearer $token" \
    -H "Content-Type: application/json" \
    -d '{"name":"myNewTeam"}' \
    "$DTRACK_URL/api/v1/team"
```

**Comment by luhahn** [comment]
mh, that looks like a solution. I will check if i can integrate this approach into our framework. Thanks!

**Comment by luhahn** [comment]
Works great, thanks i totally missed this option!
