### ISSUE TITLE
Using the auto-generated API token, but getting "Token has not been specified for use with OSS Index"

### ISSUE THREAD

**Issue by uboznikov** [DependencyTrack/dependency-track#833]
I'm trying to manually trigger the Sonatype OSS Index Analyzer via BOM upload.

I set my `Registered email address` for Sonatype in the `Sonatype OSS Index` settings page in admin; I noticed the field `API token` gets automatically filled up.

But when I upload the BOM, I get the following:

```
WARN [OssIndexAnalysisTask] An API Token has not been specified for use with OSS Index. Skipping
```

Also a follow-up question, where can we change the default schedule time of every 6 hours for Sonatype OSS Index?

Thanks.

PS: I'm using v3.8.0 executable WAR.

**Comment by uboznikov** [comment]
I also tried looking to create an API token directly from Sonatype OSS Index but it seems it is composed of pair of  a `userCode` and a `passCode`, but in the admin page the field is only `API token`.

https://help.sonatype.com/iqserver/automating/rest-apis/user-token-rest-api---v2

**Comment by uboznikov** [comment]
I have located my API token from the page:

https://ossindex.sonatype.org/doc/api-token

My only remaining question is:

> where can we change the default schedule time of every 6 hours for Sonatype OSS Index?

**Comment by stevespringett** [comment]
> where can we change the default schedule time of every 6 hours for Sonatype OSS Index?

This is not currently configurable. In DT 3.x it is set for every 6 hours. Starting with DT 4.0, it will be set for every 24 hours. This is in line with how often OSS Index updates their dataset, which is daily. Checking more often than 24 hours is not beneficial as the results will always be the same.
