### ISSUE TITLE
Api documentation v1/team is faulty

### ISSUE THREAD

**Issue by luhahn** [DependencyTrack/dependency-track#838]
The api documentation states that the following is supported:

```

uuid: string
name: string
apiKeys: [ {key: string}, .... ]
ldapUsers: [...]
managedUsers: [...]
mappedLdapGroups: [{dn: string, team: string}, ...]
permissions | [{ permission: string, description: string}, ...]
```

The uuid is marked with mandatory.

1. The uuid is not needed on team creation and will be ignored without an error.
2. apiKeys: ignored completly
3. mappedLdapGroups: ignored completly
4. permissions: ignored completly

What actually works is creating the team without uuid and just a name.
Adding permissions, mappings and apiKeys after that with the corresponding api. 

The current way v1/team put and post is documented is a little bit confusing.

**Comment by stevespringett** [comment]
API docs are a known problem.
Closing and incorporating these changes into #840. Please follow that ticket for updates.
