### ISSUE TITLE
API endpoint similar to user/self but for teams

### ISSUE THREAD

**Issue by sephiroth-j** [DependencyTrack/dependency-track#861]
There are features for uploading a SBOM which require special permissions, such as PROJECT_CREATION_UPLOAD. The Jenkins plugin cannot check if this requirement is met because there is no API endpoint that could be used by non-administrative API keys.

I request a "/team/self" endpoint that provides the following subset from "/team" but is restricted to the team to which the provided API key belongs.

- name
- permissions
- uuid?

**Things to consider about this**
Such an endpoint could raise a security finding because it could be used to enumerate valid API keys using brute force. On the other hand, such possibility already exists but is limited to administrative accounts.

**Comment by msymons** [comment]
I think that the "wizard" functionality that has (just) been implemented in SonarQube illustrates that it is possible to use the idea suggested in this enhancement in a way that **hardens** security.

**Comment by sephiroth-j** [comment]
@stevespringett , this feature could be another candidate for the next minor release v4.4.

**Comment by stevespringett** [comment]
Indeed. I'll target for 4.4

**Comment by sephiroth-j** [comment]
Great, PR #1334 is ready and waiting for your review.

Will version 4.4 be the next version or will there be a 4.3.7?

**Comment by stevespringett** [comment]
There are no plans to release a 4.3.7. The backlog of items in 4.4 will be trimmed down so that 4.4 can be made available sooner.
