### ISSUE TITLE
Docker RUN ERROR

### ISSUE THREAD

**Issue by w2n1ck** [DependencyTrack/dependency-track#867]
use：
docker pull owasp/dependency-track
docker volume create --name dependency-track
docker run -d -p 8080:8080 --name dependency-track -v dependency-track:/data owasp/dependency-track

but have error：

b15b380a1578        owasp/dependency-track   "/bin/sh -c 'java $J…"   23 minutes ago      Up 23 minutes (unhealthy)   0.0.0.0:8080->8080/tcp   dependency-track

i do nothing

env：
centos7、JDK8

help me！please！

**Comment by w2n1ck** [comment]
and I can't get into docker either

**Comment by w2n1ck** [comment]
and 6 GB of memory to the docker

**Comment by nscuro** [comment]
Try starting the container without the `-d` flag and obsere the logs. If you see errors, post the logs here, so we can investigate the cause.

**Comment by w2n1ck** [comment]
Amazing!!! I applied for a new machine, use -m 8192m, to docker 8G, it works!!!  why? 4G is ok on the document.

btw, can the DT check gradle?
