### ISSUE TITLE
OIDC does not work with standard OOB docker-compose deployment

### ISSUE THREAD

**Issue by pklotz-jdisc** [DependencyTrack/dependency-track#887]
### Current Behavior:
Default deployment with docker-compose on *remote* VM with docker.
Problem is that browser reports red error box in the upper right-hand corner that OIDC authentication could not be identified.
Login button does not show any reaction.

This should be a common problem for a lot of people to run into, therefore it should make sense to find out what the reason is and make e.g. a FAQ
When installing on the local machine e.g. Windows docker it works as expected.

### Steps to Reproduce:
docker-compose up -d
in browser goto e.g. http://192.168.185.54:8080/ (Intranet IP)

### Expected Behavior:
Authentication works like it does when installing locally by asking to change the password.

### Environment:
  
  - Dependency-Track Version: 3.0.0
  - Distribution: Docker
  - BOM Format & Version:
  - Database Server:  PostgreSQL
  - Browser:  Chrome, Edge, Firefox doesn't matter

### Additional Details:

When looking in the developer tools, one sees that he tries to contact localhost for the API
this of course does not work as the dependency-track docker is running on a remote VM.
Suspect that the 
      - API_BASE_URL=http://localhost:8081
in the docker-compose.yml is the cause

But chaning to the IP address of the VM
      - API_BASE_URL=http://192.168.185.54:8081
and the frontend docker does not start anymore
---
ERROR: for e545f51dc1a0_root_dtrack-frontend_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for dtrack-frontend  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
---

Also tried to use 
container_name: dtrack-api
and then use 
      - API_BASE_URL=http://dtrack-api:8081

Also tried to use external default network
but in bose cases the docker container does not start because he tries to use localhost as one can see in the error message above. But documentation of configuration is not clear as to where this comes from.

My suspicion is that the URL is used both for accessing the API server internally in the docker-compose network
but at the same time it is used in the browser, which of course needs the external VM hostname/IP address and cannot use a container_name or localhost.

**Comment by nscuro** [comment]
Hi @pklotz-jdisc,

the provided `docker-compose.yml` is intended for local testing, hence the usage of localhost. 

The frontend is a client-side application, which means that your browser performs all the requests.
This implicates that the URL provided in `API_BASE_URL` needs to be reachable from your machine.
Nothing inside the frontend container will ever attempt to connect to the API server.

That said, setting `API_BASE_URL` to `http://192.168.185.54:8081` *should* work in your case.
The `UnixHTTPConnectionPool` error you're seeing is probably related to Docker itself, see: https://github.com/docker/compose/issues/3927

**Comment by pklotz-jdisc** [comment]
Hi Niklas, 
thanks you were right, the link to the docker issue, which means a simple restart of the docker deamon solved the problem. Why ever. 
We should maybe mention somewhere more prominent, that you need to change the API_BASE_URL in all other cases than local installation. But otherwise, thanks and I close this issue then.
