### ISSUE TITLE
Unable to parse PackageURL: pkg:pypi

### ISSUE THREAD

**Issue by giulio1979** [DependencyTrack/dependency-track#900]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
Unable to parse PackageURL: pkg:pypi

### Steps to Reproduce:
While trying to import a BOM produced by cdxgen for a python package I am getting a number of warnings and exceptions:

12:39:50.119 WARN [ModelConverter] Unable to parse PackageURL: pkg:pypi/openshift ; python_version@'2.7'
12:39:50.126 WARN [ModelConverter] Unable to parse PackageURL: pkg:pypi/python-gitlab < 2.3.0
12:39:50.128 WARN [ModelConverter] Unable to parse PackageURL: pkg:pypi/ipaddress ; python_version < '3.3'
12:39:50.133 WARN [ModelConverter] Unable to parse PackageURL: pkg:pypi/unittest2 ; python_version@'2.6'
12:39:50.133 WARN [ModelConverter] Unable to parse PackageURL: pkg:pypi/firepower-kickstart ; python_version@'3.6'
12:39:50.134 WARN [ModelConverter] Unable to parse PackageURL: pkg:pypi/librouteros ; python_version@'3.6'
12:39:50.135 WARN [ModelConverter] Unable to parse PackageURL: pkg:pypi/git+https://github.com/vmware/vsphere-automation-sdk-python.git ; python_version@'2.7'
12:39:50.218 WARN [ModelConverter] Unable to parse PackageURL: pkg:pypi/ipaddress; python_version < '3.3'
12:39:50.255 ERROR [BomUploadProcessingTask] Error while processing bom
javax.jdo.JDOFatalUserException: Attempt to store value "d78efbe7c778d5a7bbdb8d1d73df3d7f4d37f5fdbb75af1c6b4779dfbdf86ded1e6fcebd79fd7a7b769d71f6b8eb67bc" in column ""SHA_256"" that has maximum length of 64. Please correct your data!
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:615)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:717)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:738)
	at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:398)

### Expected Behavior:
Bom imported

### Environment:
  
  - Dependency-Track Version: 3.8
  - Distribution: Docker
  - BOM Format & Version: http://cyclonedx.org/schema/bom/1.2
  - Database Server: PostgreSQL 
  - Browser: 

### Additional Details:

Please advise

**Comment by stevespringett** [comment]
Looks like these are invalid PURLs. For example: `pkg:pypi/openshift ; python_version@'2.7'` is not valid and violates the spec. Therefore when parsing the PURL with the official Package URL Java implementation that DT embeds, it fails to properly parse. 

I'd recommend reporting the issue to the cdxgen project.

**Comment by giulio1979** [comment]
Will do, thank you
