### ISSUE TITLE
Basic startup scenario fails

### ISSUE THREAD

**Issue by przemos** [DependencyTrack/dependency-track#906]
Hi, 

I am running a very simple scenario:

docker run  -m 8192m -p 8080:8080 --name dependency-track -v dependency-track:/data dependencytrack/bundled:latest

14:37:39.186 INFO [Config] --------------------------------------------------------------------------------
14:37:39.194 INFO [Config] OS Name:      Linux
14:37:39.194 INFO [Config] OS Version:   4.19.121-linuxkit
14:37:39.194 INFO [Config] OS Arch:      amd64
14:37:39.195 INFO [Config] CPU Cores:    2
14:37:39.196 INFO [Config] Java Vendor:  AdoptOpenJDK
14:37:39.196 INFO [Config] Java Version: 8.0.222
14:37:39.197 INFO [Config] Java Home:    /opt/java/openjdk
14:37:39.197 INFO [Config] Java Temp:    /tmp
14:37:39.197 INFO [Config] User:         dtrack
14:37:39.198 INFO [Config] User Home:    /data/
14:37:39.198 INFO [Config] --------------------------------------------------------------------------------
14:37:39.199 INFO [Config] Initializing Configuration
14:37:39.200 INFO [Config] System property alpine.application.properties not specified
14:37:39.201 INFO [Config] Loading application.properties from classpath
14:37:39.205 INFO [Config] --------------------------------------------------------------------------------
14:37:39.206 INFO [Config] Application:  Dependency-Track
14:37:39.207 INFO [Config] Version:      4.0.1
14:37:39.209 INFO [Config] Built-on:     2021-01-13T03:30:31Z
14:37:39.210 INFO [Config] --------------------------------------------------------------------------------
14:37:39.211 INFO [Config] Framework:    Alpine
14:37:39.212 INFO [Config] Version :     1.8.0
14:37:39.213 INFO [Config] Built-on:     2020-12-27T22:46:29Z
14:37:39.214 INFO [Config] --------------------------------------------------------------------------------
14:37:39.231 INFO [RequirementsVerifier] Initializing requirements verifier
14:37:39.233 INFO [UpgradeInitializer] Initializing upgrade framework
14:37:40.511 ERROR [UpgradeInitializer] Unable to upgrade Dependency-Track versions prior to v4.0.0. Please refer to documentation for migration details. Halting.

and get an error straight away. 
I have no idea how to recover from that.

**Comment by przemos** [comment]
Recreated docker volume

**Comment by stevespringett** [comment]
Dependency-Track thinks this is an upgrade based on the database its connected to. Upgrades from 3.x are not supported.Z there is a separate migration utility that is being worked on my the community to migrate databases form 3.8 to 4.0.

**Comment by stevespringett** [comment]
Glad it's working. Closing.
