### ISSUE TITLE
NGinx Error 413 on API Call with Large BOM upload.

### ISSUE THREAD

**Issue by Corjaantje** [DependencyTrack/dependency-track#916]
After generating a rather heavy BOM out of a NodeJS project, which ended up containing +- 850 packages after including all DevDependencies, the POST API Endpoint for uploading a BOM threw an 413 Request Entity Too Large error.
Is there any way to either increase the limit on the NGinx endpoint on the docker environment myself?

### Environment:
  
  - Dependency-Track Version: 4.0.0
  - Distribution: Docker
  - BOM Format & Version: CycloneDX 1.2, XML

### Additional Details:
413 Request Entity Too Large
nginx

**Comment by nscuro** [comment]
Hi, I'm assuming you're using NGINX as reverse proxy in front of DT? 

NGINX has a [maximum body size for requests that defaults to 1MB](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size). To completely remove that restriction, use `client_max_body_size 0;`, so for example:

```
location /api {
    proxy_pass http://dtrack-apiserver:8080;
    client_max_body_size 0;
    // ...
}
```

**Comment by Corjaantje** [comment]
Thank you kindly, that'll do the trick!

**Comment by Jaff** [comment]
Any suggestions for applying this to frontend running in docker? We just encountered the issue ourselves.

**Comment by nscuro** [comment]
@Jaff You shouldn't need this for the frontend, as nothing is uploaded to it. The container just serves static files (HTML, CSS, JavaScript) that your browser executes. Files are uploaded from your browser directly to the API server. 

Are you running a reverse proxy or load balancer in front of your API server container?
