### ISSUE TITLE
SWID tagID not added to components from imported bom

### ISSUE THREAD

**Issue by Otyg** [DependencyTrack/dependency-track#921]
### Current Behavior:
When a CycloneDX 1.2 BOM containing swid tagID is uploaded to DependencyTrack via the GUI the swid tag ids is not added to the created components.

### Steps to Reproduce:
1. Generate a CycloneDX 1.2 bom and add swid tagID to the components
2. Upload the BOM to a project in DependencyTrack by using the GUI
3. View Details for the component

### Expected Behavior:
SWID Tag ID should have the value set in the BOM.

### Environment:
  
  - Dependency-Track Version: 4.0.1
  - Distribution: Docker
  - BOM Format & Version: CycloneDX 1.2
  - Database Server: PostgreSQL
  - Browser: Chrome

### Additional Details:
Example BOM-file used:
`<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.2" version="1">
    <components>
        <component bom-ref="pkg:rpm/python3-rhn-check@2.8.16-13.module%2Bel8.1.0%2B3455%2B3ddf2832.x86_64" type="application">
            <name>python3-rhn-check</name>
            <version>2.8.16-13.module+el8.1.0+3455+3ddf2832.x86_64</version>
            <scope>required</scope>
            <purl>pkg:rpm/python3-rhn-check@2.8.16-13.module%2Bel8.1.0%2B3455%2B3ddf2832.x86_64</purl>
            <swid tagId="Rhel_8.3-x86_64-python3-rhn-check-2.8.16-13.module~el8.1.0~3455~3ddf2832.x86_64"/>
        </component>
    </components>
    <dependencies>
        <dependency ref="pkg:rpm/python3-rhn-check@2.8.16-13.module%2Bel8.1.0%2B3455%2B3ddf2832.x86_64"/>
    </dependencies>
</bom>`

**Comment by stevespringett** [comment]
Thank you for reporting. I will try to reproduce and get this into the next release if found to be defective.

**Comment by stevespringett** [comment]
Reproduced. Working on fix.
