### ISSUE TITLE
has a problem use the docker desktop in window to start the image dependence-track 4.0.1

### ISSUE THREAD

**Issue by liuxihua** [DependencyTrack/dependency-track#923]
i use these commends:
# Pull the image from the Docker Hub OWASP repo
docker pull dependencytrack/bundled

# Creates a dedicated volume where data can be stored outside the container
docker volume create --name dependency-track

# Run the bundled container with 8GB RAM on port 8080
docker run -d -m 8192m -p 8080:8080 --name dependency-track -v dependency-track:/data dependencytrack/bundled

when i run the container,

it got a error like :

11:06:10.480 INFO [Config] --------------------------------------------------------------------------------

11:06:10.484 INFO [Config] OS Name: Linux

11:06:10.484 INFO [Config] OS Version: 4.19.121-linuxkit

11:06:10.484 INFO [Config] OS Arch: amd64

11:06:10.485 INFO [Config] CPU Cores: 2

11:06:10.485 INFO [Config] Java Vendor: AdoptOpenJDK

11:06:10.485 INFO [Config] Java Version: 8.0.222

11:06:10.486 INFO [Config] Java Home: /opt/java/openjdk

11:06:10.486 INFO [Config] Java Temp: /tmp

11:06:10.486 INFO [Config] User: dtrack

11:06:10.486 INFO [Config] User Home: /data/

11:06:10.486 INFO [Config] --------------------------------------------------------------------------------

11:06:10.486 INFO [Config] Initializing Configuration

11:06:10.487 INFO [Config] System property alpine.application.properties not specified

11:06:10.487 INFO [Config] Loading application.properties from classpath

11:06:10.490 INFO [Config] --------------------------------------------------------------------------------

11:06:10.491 INFO [Config] Application: Dependency-Track

11:06:10.491 INFO [Config] Version: 4.0.0

11:06:10.491 INFO [Config] Built-on: 2021-01-03T07:21:39Z

11:06:10.491 INFO [Config] --------------------------------------------------------------------------------

11:06:10.491 INFO [Config] Framework: Alpine

11:06:10.492 INFO [Config] Version : 1.8.0

11:06:10.492 INFO [Config] Built-on: 2020-12-27T22:46:29Z

11:06:10.492 INFO [Config] --------------------------------------------------------------------------------

11:06:10.505 INFO [RequirementsVerifier] Initializing requirements verifier

11:06:10.506 INFO [UpgradeInitializer] Initializing upgrade framework

11:06:10.857 ERROR [UpgradeInitializer] Unable to upgrade Dependency-Track versions prior to v4.0.0. Please refer to documentation for migration details. Halting.

and I behind the proxy.

pls give me some help , thanks

**Comment by nscuro** [comment]
Hi @liuxihua, it seems like you used the `dependency-track` volume with version <= 3.8.0 of Dependency-Track before. Docker won't show errors when creating volumes that already exist. In fact, the documentation [states](https://docs.docker.com/engine/reference/commandline/volume_create/#examples):

> If you specify a volume name already in use [...], Docker assumes you want to re-use the existing volume and does not return an error.

Please remove your volume and retry again:

```bash
$ docker volume rm dependency-track
$ docker volume create --name dependency-track
```

Be aware that all your previous data will be lost. For production deployments, please use an external database.

**Comment by liuxihua** [comment]
Thank you very much，@nscuro 
It works.
