### ISSUE TITLE
JDBC Driver for Postgresql - update

### ISSUE THREAD

**Issue by pawelwalaszek** [DependencyTrack/dependency-track#924]
The defect may already be reported! Please search for the defect before creating one.

Please update docker-compose.yml to postgresql-42.2.18.jar in:

[curl -LO https://dependencytrack.org/docker-compose.yml](curl -LO https://dependencytrack.org/docker-compose.yml)

### Environment:
  
  - Dependency-Track Version: 4.0.0
  - Distribution: [ Docker ]
  - BOM Format & Version:
  - Database Server: [ PostgreSQL ]
  - Browser:

**Comment by stevespringett** [comment]
JDBC drivers are bundled with v4.1.

v4.1 is already pinned to driver version 42.2.18

See: https://github.com/DependencyTrack/dependency-track/blob/master/pom.xml#L99
