### ISSUE TITLE
UI links are redirected to the login page even for logged in users.

### ISSUE THREAD

**Issue by shayrybak** [DependencyTrack/dependency-track#925]
Hi, first, thank you for this project, it is very useful. I've encountered this behavior and I realize this might be designed functionality for security, but it seems weird to me not being able to share links in our team.

### Current Behavior:
When copying a link in the UI to a certain location, such as a project page, browsing directly to that link will redirect to the login page, and after login, it's redirected to the dashboard page.

### Steps to Reproduce:
copy a link to a specific project.
open the link directly in the browser

### Expected Behavior:
If logged in, go directly to the requested page,
If not logged in, redirect to login saving the requested page, redirecting to it after a successful login.

### Environment:
  
  - Dependency-Track Version: v4.0.0
  - Distribution: Docker
  - BOM Format & Version: not relevant 
  - Database Server: PostgreSQL
  - Browser: Chrome

### Additional Details:
response code is 307 with the following headers:
```
Location: https://{{host}}/dashboardhttps://{{host}}/projects/{{project-id}}
Non-Authoritative-Reason: HSTSz
```

**Comment by msymons** [comment]
Redirect after login will be of even greater importantance when Dependency-Track implements support for deep links.

**Comment by stevespringett** [comment]
See https://github.com/DependencyTrack/frontend/pull/47

**Comment by stevespringett** [comment]
Closing as duplicate
