### ISSUE TITLE
unable to stop container

### ISSUE THREAD

**Issue by Rando783** [DependencyTrack/dependency-track#928]
I### Current Behavior:
![image](https://user-images.githubusercontent.com/59581699/107537805-49f2a200-6b91-11eb-9a57-f8f67a100489.png)
 if I try to stop the containers and remove them to start fresh a new instance just appears on its own.

### Steps to Reproduce:
followed download instructions..
curl -LO https://dependencytrack.org/docker-compose.yml
docker-compose up -d

I can't remove the container now
used docker ps to get the container
used docker container stop <container ID>
it stops for a second and then another instance appears so I am unable to remove it

Looking to start fresh but am unable to get rid of that container because it constantly runs

### Expected Behavior:
 stop container and remove it

### Environment:
  
  - Dependency-Track Version:
  - Distribution: [ Docker | Executable WAR | Traditional WAR ]
  - BOM Format & Version:
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]
  - Browser: 

### Additional Details:

looking to start fresh but unable to remove dtrack container from docker

**Comment by ecabrerar** [comment]
Hi, 
Maybe you don't have an issue with dependency-track.
To stop the container if you are using docker-compose, you have to use :

docker-compose stop ( Stop running containers without removing them)
docker-compose stop CONTAINER_ID (Stop an specific running container)

**Comment by Rando783** [comment]
Hi Eudris,
       You are correct! I tried to stop the container but it would just restart. I ended up just uninstalling all or docker and then re-installing. That seemed to do the trick.

Thanks!
