### ISSUE TITLE
Support for Google OSV database

### ISSUE THREAD

**Issue by sameer1046** [DependencyTrack/dependency-track#931]
### Current Behavior:
The tool doesn't have support for Google open source vulnerability database 
https://osv.dev/list

### Proposed Behavior:
The tool should be able to get data from Google osv database.

**Comment by stevespringett** [comment]
Good suggestion. It's unfortunate osv doesn't support [Package URL](https://github.com/package-url/purl-spec). I'd recommend creating a ticket for them to support it. Relying on 'name' and 'ecosystem' is fragile and going to be unpredictable. Once osv supports Package URL, I'd be happy to add support for it.

**Comment by VinodAnandan** [comment]
https://github.com/google/osv/issues/64

**Comment by VinodAnandan** [comment]
@stevespringett OSV now supports PURL. Please find the below links for more details 

https://security.googleblog.com/2021/06/announcing-unified-vulnerability-schema.html
https://tinyurl.com/vuln-json
https://osv.dev/docs/#operation/OSV_QueryAffected

**Comment by VinodAnandan** [comment]
`curl -X POST -d '{"package": {"purl": "pkg:maven/org.apache.struts:struts2-core"}, "version": "2.0.14"}' https://api.osv.dev/v1/query`

**Comment by pombredanne** [comment]
@VinodAnandan FWIW, `pkg:maven/org.apache.struts:struts2-core` may not be the proper purl for this package, but rather `pkg:maven/org.apache.struts/struts2-core`

**Comment by VinodAnandan** [comment]
Thanks @pombredanne

**Comment by pombredanne** [comment]
@VinodAnandan sure thing! ... note that when VulnerableCode will be ready for usage, it will also have OSV content and everything is keyed by Package URL there... so this could be come a natural additional data source for DT

**Comment by VinodAnandan** [comment]
The purl issue has been fixed. Thanks to @oliverchang

"` curl -X POST -d '{"package": {"purl": "pkg:maven/org.apache.struts/struts2-core@2.0.14"}}' https://api.osv.dev/v1/query `"

**Comment by sahibamittal** [comment]
OSV maintains GCS bucket with all aggregated vulnerabilities which can be scheduled and mirrored in dependency-track database https://github.com/google/osv/blob/master/README.md#data-dumps
I'd like to work on it.

**Comment by sahibamittal** [comment]
Draft PR for discussion -> https://github.com/DependencyTrack/dependency-track/pull/1703

**Comment by nscuro** [comment]
Implemented in #1703. Thanks @sahibamittal! 🥳
