### ISSUE TITLE
NullPointerException when trying to clone a project version

### ISSUE THREAD

**Issue by smallvm** [DependencyTrack/dependency-track#934]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
Cloned project using includeTags, includeProperties, includeDependencies, includeAuditHistory creates a new version containing all that information from the original project version.

### Steps to Reproduce:

Create a new project "TEST" with version number "1" and upload attached sample BOM.

DT should come up with a bunch of vulnerabilities for the included component.

Do any audit action like adding comments.

Either use the UI to add a new version (check all 4 checkboxes) or use the REST project/clone endpoint.

This behaviour can be observed from dependency track version 4 onwards.

### Expected Behavior:

Cloned project version contains tags, properties, dependencies, audit history from the original project version.

### Environment:
  
  - Dependency-Track Version: Server: 4.1.0, UI: 1.2.0
  - Distribution: Docker
  - BOM Format & Version: CyclloneDX 1.2
  - Database Server: Docker default, I guess it's H2
  - Browser: Firefox 78.7.0esr

### Additional Details:

BOM (HTML encoded):
&lt;&quest;xml version&equals;&quot;1&period;0&quot; encoding&equals;&quot;UTF-8&quot;&quest;&gt;&NewLine;&lt;bom xmlns&equals;&quot;http&colon;&sol;&sol;cyclonedx&period;org&sol;schema&sol;bom&sol;1&period;2&quot; version&equals;&quot;1&quot;&gt;&NewLine;  &lt;components&gt;&NewLine;    &lt;component type&equals;&quot;library&quot;&gt;&NewLine;      &lt;publisher&gt;Apache&lt;&sol;publisher&gt;&NewLine;      &lt;group&gt;openssl&lt;&sol;group&gt;&NewLine;      &lt;name&gt;openssl&lt;&sol;name&gt;&NewLine;      &lt;version&gt;1&period;0&period;2g&lt;&sol;version&gt;&NewLine;      &lt;cpe&gt;cpe&colon;&sol;a&colon;openssl&colon;openssl&colon;1&period;0&period;2g&lt;&sol;cpe&gt;&NewLine;    &lt;&sol;component&gt;&NewLine;  &lt;&sol;components&gt;&NewLine;&lt;&sol;bom&gt;&NewLine;

Stack trace:
dtrack-apiserver_1  | 11:43:43.191 INFO [CloneProjectTask] Cloning project: 8a9f17bd-9558-4f10-9a7e-b5c45c7c46a9
dtrack-apiserver_1  | 11:43:43.233 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
dtrack-apiserver_1  | java.lang.NullPointerException: null
dtrack-apiserver_1  | 	at org.dependencytrack.model.Component.setPurlCoordinates(Component.java:520)
dtrack-apiserver_1  | 	at org.dependencytrack.persistence.QueryManager.cloneComponent(QueryManager.java:759)
dtrack-apiserver_1  | 	at org.dependencytrack.persistence.QueryManager.clone(QueryManager.java:441)
dtrack-apiserver_1  | 	at org.dependencytrack.tasks.CloneProjectTask.inform(CloneProjectTask.java:43)
dtrack-apiserver_1  | 	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
dtrack-apiserver_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
dtrack-apiserver_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
dtrack-apiserver_1  | 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by stevespringett** [comment]
Thanks for reporting. Confirmed this is a regression in 4.0/4.1. I'm targeting to fix this in v4.2
