### ISSUE TITLE
An Idle transaction are not getting timeout.

### ISSUE THREAD

**Issue by rvsoni** [DependencyTrack/dependency-track#941]
### Current Behavior:
The current behavior is that sometimes Transaction is stuck and becomes idle, Datanucleus component does not kill the pending idle pending transaction to free up the connection to make it available to use. 

The issue is between the somewhere Datanucleus and the HikariCP setting, 

As per HikariCP setting, **idletimeout** properties
Official documents HikariCP **(https://github.com/brettwooldridge/HikariCP)**

```
idleTimeout
This property controls the maximum amount of time that a connection is allowed to sit idle in the pool. This setting only applies when minimumIdle is defined to be less than maximumPoolSize.

```

Dependency track application set the **idleTimeout** via Datanucleus but Datanucleus does not have any way to set **minimumIdle** properties

Datanucleus component does not support properties "**minimumIdle**"

https://www.datanucleus.org/products/accessplatform/jdo/persistence.html#connection_pooling_rdbms_hikaricp

So the connection stuck as idle in the transaction are not timed out and eventually run out of all connections from the poll.

The restart of the application or killing the stuck connection only the option as of now. 

### Steps to Reproduce:

Run Dependency application with lots of projects and set connection pool around 30 see eventually all connection from the poll will be stuck on the transaction and remain idle. 

### Expected Behavior:
an idle transaction should be timed out after some time. 
HikariCP support that by setting the properties, "idleTimeout", "minimumIdle", 

### Environment:
  
  - Dependency-Track Version: 4.1.0
  - Distribution: Docker 
  - BOM Format & Version: 
  - Database Server: PostgreSQL 
  - Browser: FF

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
Thanks for reporting. This may explain some gradual performance degradation that some users are experiencing. I think there's an opportunity to potentially use a hikari configuration file. This would be in addition to what DataNucleus supports. Looking at the code, it appears that all HikariConfig constructs all call the default constructor, which in turn loads a hikari configuration file based on a system property. This is just a though, but it might provide a way to work around the fact that Datanucleus does not support the properties we need.

https://github.com/brettwooldridge/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/HikariConfig.java#L131

**Comment by rvsoni** [comment]
@stevespringett  you are correct on this, 

The issue is that now, the app has to provide a way to set poprties in env for the Docker setup. 
We need to find a way to persist the properties on file on startup and also set the env variable "hikaricp.configurationFile" to point that file, so hikaricp can load it and set the additional properties on the connection pool.

Like, on docker startup save the env variable into the properties file using some bash script and then start the java process.

Ravi

**Comment by stevespringett** [comment]
I'm revisiting this again due to #1026. 

According to https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/connectionpool/HikariCPConnectionPoolFactory.java

`minimumIdle` is actually supported via the `PROPERTY_CONNECTION_POOL_MIN_IDLE` property defined in https://github.com/datanucleus/datanucleus-rdbms/blob/5.2/src/main/java/org/datanucleus/store/rdbms/RDBMSPropertyNames.java.

So simply setting the value of `datanucleus.connectionPool.minIdle` would set the HikariCP `minimumIdle` property. This doesn't appear to be documented, but it should work.

Question...

I will be implementing `ALPINE_DATABASE_POOL_MIN_IDLE` in a few minutes, which will allow Dependency-Track to have control over the HikariCP `minimumIdle` property. What are your thoughts on proposed values for idletimeout and minimumIdle?

**Comment by rvsoni** [comment]
Hi @stevespringett 

We are monitoring around 300 projects/library using Dependency track applicaton, it takes around a couple of minutes to complete background job to find new Security issues, update matrix, We are using 1 CPU and 4G RAM t2.2xlarge (AWS Ec2) with shared with other dockers on the same box,  

You can set around 10 minutes as the default value for minimumIdle property is fine, 
Ravi
