### ISSUE TITLE
hub.docker.com/r/dependencytrack/frontend quick start command is not correct

### ISSUE THREAD

**Issue by nibiwodong** [DependencyTrack/dependency-track#953]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
docker inner port is 80, but not 8080
https://hub.docker.com/r/dependencytrack/frontend
![image](https://user-images.githubusercontent.com/17465789/109602537-3d8fb280-7b5b-11eb-8030-99f0e962a8f8.png)
docker pull dependencytrack/frontend
docker run -d -p 8080:8080 --name dtrack-frontend dependencytrack/frontend

### Steps to Reproduce:
change port mapping from  8080:8080 to 8080:80

### Expected Behavior:

docker pull dependencytrack/frontend
docker run -d -p 8080:80 --name dtrack-frontend dependencytrack/frontend

### Environment:
  
  - Dependency-Track Version:
  - Distribution: [ Docker | Executable WAR | Traditional WAR ]
  - BOM Format & Version:
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]
  - Browser: 

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
Thanks for identifying this issue. Resolved.
