### ISSUE TITLE
Dependency version conflict，The packaged JAR should have only one of these versions？

### ISSUE THREAD

**Issue by lihaoran93** [DependencyTrack/dependency-track#959]
Whether need to exclude one of the versions？
<img width="1545" alt="图片" src="https://user-images.githubusercontent.com/26021760/109937744-2e029c00-7d0a-11eb-98b4-d55c3983ea7b.png">

**Comment by stevespringett** [comment]
It appears the BOM actually includes both versions. Check your BOM to verify. Then check the artifacts created from the build to verify whether or not both versions are included or not. Maven sometimes does this.
