### ISSUE TITLE
Provide editing support of INTERNAL vulnerabilities

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#96]
A 'Preview Feature' that implements #21 is included in v3.0. 

This enhancement request is to address the need to edit vulnerabilities that have a source of INTERNAL.

From the 'vulnerability' page, include logic that determine if the source is INTERNAL. If so, then provide buttons/inputs to provide editing capabilities directly from the vulnerability page.

**Comment by pachulo** [comment]
Is this still in the roadmap?

**Comment by stevespringett** [comment]
Yes, It's a preview feature currently. Not feature complete. I may wait until the new front-end is complete before starting on this. I'm trying to avoid any new UI components at the moment.

**Comment by pachulo** [comment]
OK, thanks for the update! Did not know about the new front-end effort!

I guess then that, right now, there is no way to delete a manually created vuln, even though the API...doesn't it?

**Comment by stevespringett** [comment]
The API has endpoints for creating and updating internal vulns, but I do not believe an endpoint for deleting internal vulns is in place yet. You may have to wait until the this feature is fully complete in order to delete internal vulns.
