### ISSUE TITLE
Active projects visible as inactive

### ISSUE THREAD

**Issue by siewer** [DependencyTrack/dependency-track#963]
### Current Behavior:
Project created via API, BOM uploaded via API. When entering the GUI i see
![obraz](https://user-images.githubusercontent.com/10408473/110474469-fddb4480-80df-11eb-8e3f-2d18cb69b0fa.png)

When i select "show inactive project" slider i can see:
![obraz](https://user-images.githubusercontent.com/10408473/110474588-24997b00-80e0-11eb-8d75-1378e2381683.png)

Projects are "active" but not visible on main page. Also widgets about risk are empty.

### Steps to Reproduce:
run docker compose:
https://dependencytrack.org/docker-compose.yml
create project via API
upload BOM via API

### Expected Behavior:
project would be visible without selecting slider "show incative project" and widgets about risk should be populated

### Environment:
  
  - Dependency-Track Version: 4.1.0
  - Distribution: docker
  - BOM Format & Version: CycloneDX 1.2
  - Database Server:  PostgreSQL
  - Browser: Firefox

**Comment by stevespringett** [comment]
What does the body of the API request look like?

The UI also leverages the API and does not have this issue.

**Comment by siewer** [comment]
going without "Show inactive projects"
I got request for `/api/v1/project?excludeInactive=true&searchText=&sortOrder=asc&pageSize=10&pageNumber=1`
with response body `[]`

going with "Show inactive projects"
I got request for `/api/v1/project?excludeInactive=false&searchText=&sortOrder=asc&pageSize=10&pageNumber=1`
with response body of proper project list

**Comment by stevespringett** [comment]
I have tried to reproduce on two different instances, but I'm not able to reproduce. The UI displays active projects all the time and displays inactive projects only when the checkbox is enabled.

**Comment by siewer** [comment]
I have now tested some stuff and when I edit project and even change nothing but still click on update project it is then visible at project page.

(in my context projects are created via REST API)

**Comment by stevespringett** [comment]
Was your instance of DT an upgrade from 3.x?

**Comment by stevespringett** [comment]
Can you run the following SQL query for me:

```sql
SELECT * FROM \"PROJECT\" WHERE \"ACTIVE\" IS NULL;
```

If you get 1 or more results back, then execute:

```sql
UPDATE \"PROJECT\" SET \"ACTIVE\" = true WHERE \"ACTIVE\" IS NULL;
```

I think I might have found one possibility why this is occurring - again - not able to reproduce so its theoretical.

**Comment by stevespringett** [comment]
If this is infact the issue, https://github.com/DependencyTrack/dependency-track/commit/42b6be93dd333c7922fe884ff188cf6c53fcdf7c should resolve it.
