### ISSUE TITLE
OIDC doesn't work

### ISSUE THREAD

**Issue by smercier74** [DependencyTrack/dependency-track#964]
Hello, 
    I'm using dependency track 4.1.0 with the frontend 1.2.0 on an EKS environment with an Postgresql RDS DB. The api server and the frontend are configured to use an external Keycloak with OIDC.   
The environment has been configured with the documentation ﻿﻿﻿﻿﻿﻿﻿﻿https://docs.dependencytrack.org/getting-started/openidconnect-configuration/#example-setup-with-keycloak

API server | Frontend
-- | --
alpine.oidc.enabled=true | OIDC_CLIENT_ID=dependency-track
alpine.oidc.issuer=https://auth.example.com/auth/realms/example | OIDC_ISSUER=https://auth.example.com/auth/realms/example
alpine.oidc.username.claim=preferred_username |  
alpine.oidc.user.provisioning=true |  
alpine.oidc.teams.claim=groups |  
alpine.oidc.team.synchronization=true

The button OpenID is not available on the login page. No error are visible in the logs of the pods even with log in level DEBUG.

Another test has been done with the latest snapshot for apiserver and frontend and the OpenID button is always unavailable.

Did you encountered the same problem ?

**Comment by nscuro** [comment]
Hi @smercier74, are there any errors in your browser's developer console when opening the login page? What does the API server respond with when the frontend requests `/api/v1/oidc/available`? Does the normal login work?

**Comment by smercier74** [comment]
There is no error in the developer console when the login appears.  
The api ...api/v1/oidc/available returns false   
The others requests static/config.json and version have a code 200 .

The login with the admin user is working fine. The base url is defined and also OIDC groups with same names than in the Keycloak realm.

In the pods the OIDC config is set with environment variables and it is visible when we connect to the pod.  
For the frontend the config is present in the file /app/static/config.json  
```
{
  "API_BASE_URL": "https://<dependency_track_url>",
  "OIDC_ISSUER": "https://<keycloack_host>/auth/realms/<realm>",
  "OIDC_CLIENT_ID": "<openid_client>",
  "OIDC_SCOPE": "openid groups profile email",
  "OIDC_FLOW": ""
}
```

**Comment by smercier74** [comment]
Thanks for your feedback,   
The certificate of our Keycloak is issued by Let's Encrpyt.   
The OIDC config for the api-server use the syntax "_"  
```
env | grep ALPINE_OIDC
ALPINE_OIDC_ENABLE=true
ALPINE_OIDC_TEAM_SYNCHRONIZATION=true
ALPINE_OIDC_ISSUER=https://<keycloak_host>/auth/realms/<realm>
ALPINE_OIDC_USERNAME_CLAIM=preferred_username
ALPINE_OIDC_TEAMS_CLAIM=groups
ALPINE_OIDC_USER_PROVISIONING=true
```

I redo some tests and in the logs of the api-server I see the logs below each time when the login page appears:
```
 08:21:09.672 DEBUG [OidcConfigurationResolver] Will not resolve OIDC configuration: OIDC is disabled
```

I don't see other errors in the logs

**Comment by nscuro** [comment]
Ah, you have `ALPINE_OIDC_ENABLE` in your config, but it has to be `ALPINE_OIDC_ENABLED` with a `D` at the end.

**Comment by smercier74** [comment]
I updated the config with ALPINE_OIDC_ENABLED and it is working fine. Thanks a lot for your help.

**Comment by nscuro** [comment]
Glad I could help. Would you mind closing this issue then?

**Comment by smercier74** [comment]
Of course
