### ISSUE TITLE
Limit PORTFOLIO alert to project does not work for audit changes

### ISSUE THREAD

**Issue by dfn-certling** [DependencyTrack/dependency-track#975]
### Current Behavior:
This is similar to #616. Limiting PORTFOLIO alerts to projects does not work for PROJECT_AUDIT_CHANGE notifications like suppressing findings and setting their analysis state. Changing a finding status for a project sends the notification via all alerts that include PROJECT_AUDIT_CHANGE not depending on the configured project limits.

### Steps to Reproduce:
Define two projects and respective PORTFOLIO alerts limited to the projects with PROJECT_AUDIT_CHANGE selected. Changing a finding status for one of the projects results in a notification sent for both projects.

### Expected Behavior:
The notification should not be sent to alerts that limit their scope to other projects.

### Environment:
  
  - Dependency-Track Version: 4.1.0
  - Distribution: Executable WAR
  - Database Server: PostgreSQL
  - Browser:  Firefox

### Additional Details:

Seems like the same handling that was changed in 286e2f29417f9e84162392263ec218cd7532eaab should be applied to PROJECT_AUDIT_CHANGE notifications.

**Comment by ridaeh** [comment]
We have the same issue , we are **spammed** by other projects alerts

**Comment by nscuro** [comment]
Did not have this on the radar, thanks for bringing it up.

Just raised a PR that should address it. @stevespringett I don't think this justifies a bugfix release, so I'd schedule this for 4.7. Or would you prefer this to be released sooner?

**Comment by stevespringett** [comment]
Thanks all. @nscuro lets target 4.7
