### ISSUE TITLE
4.2.0: incorrect Permissions Descriptions

### ISSUE THREAD

**Issue by hostalp** [DependencyTrack/dependency-track#977]
### Current Behavior:
Administration / Access Management / Permissions
Most Descriptions show only numeric values - possibly string IDs?
![Screenshot_2021-03-20 Dependency-Track - Administration](https://user-images.githubusercontent.com/47250981/111884034-2d7f2c00-89bf-11eb-87a0-a1984d99c42f.png)

### Environment:
  
  - Dependency-Track Version: 4.2.0
  - Distribution: Docker
  - BOM Format & Version:
  - Database Server: PostgreSQL
  - Browser: Firefox 86

### Additional Details:
This is after the migration from 3.7.1 as follows:
1. 3.7.1
2. 3.8.0
3. https://github.com/DependencyTrack/v3.8.0-v4.0.0-migration/blob/main/3.8.0_to_4.0.0_postgres.sql
4. 4.2.0 @ Docker containers, with newly created filesystem content, only keys migrated from the old one

I'm not sure if I've done something wrong there. The migration was successful though, no errors during the process.

**Comment by stevespringett** [comment]
Duplicate and related to #951
