### ISSUE TITLE
Map users to a default group

### ISSUE THREAD

**Issue by davidkarlsen** [DependencyTrack/dependency-track#979]
### Current Behavior:
To map OIDC based users to a group a group claim is required. However since DT uses the UserInfo endpoint rather than claims in the id/accesstokens these claims will not appear (see: https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo).

If an authenticated user could be given a default-group, then we could give authenticated users a portifolio access by default, and handle the few administrators manually in DT.

### Proposed Behavior:
Add support for a default group.

**Comment by nscuro** [comment]
@stevespringett I believe this one can be closed, as it was supposed to be a workaround until #1008 would land.
