### ISSUE TITLE
An unexpected error occurred while updating portfolio metrics and iterating through projects. The error occurred while updating metrics for project

### ISSUE THREAD

**Issue by patbaumgartner** [DependencyTrack/dependency-track#995]
Hi, when I download the latest version from dockerhub (bundled), snapshot, latest but also 4.2.1 and 4.1.0 i face now some issues during the restart of the app.

### Current Behavior:

dtrack4_1         | 13:42:00.048 INFO [NpmAdvisoryMirrorTask] Updating datasource with NPM advisories
dtrack4_1         | 13:42:00.208 INFO [NpmAdvisoryMirrorTask] Retrieving NPM advisories from https://registry.npmjs.org/-/npm/v1/security/advisories?perPage=20&page=20
dtrack4_1         | 13:42:00.454 ERROR [MetricsUpdateTask] An unexpected error occurred while updating portfolio metrics and iterating through projects. The error occurred while updating metrics for project: c350c844-bc6f-4102-8958-62549d5dfefd
dtrack4_1         | java.lang.NullPointerException: null
dtrack4_1         |     at org.dependencytrack.model.ProjectMetrics.getPolicyViolationsFail(ProjectMetrics.java:300)
dtrack4_1         |     at org.dependencytrack.tasks.MetricsUpdateTask.updateProjectMetrics(MetricsUpdateTask.java:338)
dtrack4_1         |     at org.dependencytrack.tasks.MetricsUpdateTask.updatePortfolioMetrics(MetricsUpdateTask.java:102)
dtrack4_1         |     at org.dependencytrack.tasks.MetricsUpdateTask.inform(MetricsUpdateTask.java:66)
dtrack4_1         |     at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
dtrack4_1         |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
dtrack4_1         |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
dtrack4_1         |     at java.base/java.lang.Thread.run(Unknown Source)
dtrack4_1         | 13:42:00.456 INFO [MetricsUpdateTask] Executing metrics 

When calling /projects in the ui, the rest-service vall on /project fails with 

(was java.lang.NullPointerException) (through reference chain: org.datanucleus.store.rdbms.query.ForwardQueryResult[0]->org.dependencytrack.model.Project["metrics"]->org.dependencytrack.model.ProjectMetrics["policyViolationsFail"])

which is visible in the response.

### Expected Behavior:

Projects and components are not visible in the UI at all.
Licenses and vulnerabilites and the charts on the dashboard are working.

### Environment:
  
  - Dependency-Track Version: 4.2.1
  - Distribution: Docker Bundeled
  - BOM Format & Version: latest
  - Database Server: PostgreSQL

**Comment by stevespringett** [comment]
The `snapshot` tag is from continuous integration. Running it against an existing database generated from a released version, is almost guaranteed to mess it up.

This project follows Trunk Based Development (TBD), so therefore, every change to master branch (trunk) will result in a new snapshot image being created.

Going backwards (4.2.1 to 4.1.0) also is not supported. 

Are you able to reproduce the above exception on a fresh install of DT 4.2.1 on a fresh database?

**Comment by patbaumgartner** [comment]
thanks a lot for the fast feedback. actually, I can reproduce the case with a fresh installation. (docker, no data folders, starting from scratch). Not sure if the error could be related to a network issue?

I checked the code mentioning the NPE but I see there only an int ... 

Best,
Patrick

**Comment by patbaumgartner** [comment]
i

**Comment by JonathanMeer** [comment]
I have the same issue. The old Docker container with version 3.8.0 was started by mistake. Now the database is broken. Is there a way I can still save the data?
